### ISSUE TITLE
Avatar user image is not display

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1000]
Tested on Staging iOS version 1.10.3(6-295)
Tested on Staging Android version v1.0 (324)

Steps to reproduce:
1. Navigate to common first page that contain members
2. Navigate to common members/pending / history
3. Navigate to profile page

Actual results:
Avatar user image is not display - see examples
![image](https://user-images.githubusercontent.com/69141571/148692143-1b307696-81ad-492f-a817-30d6cda04da7.png)
![image](https://user-images.githubusercontent.com/69141571/148692162-94e66d04-17f4-4288-8f44-be2dcc850e03.png)

Expected results:
Avatar images must be display.

**Comment by IvanSantiagoUk** [comment]
This is a bug on the firebase storage with testing data

For example in your profile the image is -> https://firebasestorage.googleapis.com/v0/b/common-staging-50741.appspot.com/o/public_img%2Fimg_1635139293706.jpg?alt=media&token=d05024a8-5d1b-48d6-93c7-b90c3d1a28a6

But this image Url doesnt exist actually. So when we try to show it on the app is not appearing

Can you try to reupload a new image and check if that works for your user?

**Comment by watchtower314** [comment]
@IvanSantiagoUk we should get the images from the google account, no? Perhaps there's something wrong with the Google SignIn flow?

**Comment by IvanSantiagoUk** [comment]
I created new account and it worked

**Comment by IvanSantiagoUk** [comment]
SO my thinking is no related with google and we lost hat data in some point of the migration

**Comment by yanivi71** [comment]
closing this issue. on production it works fine
