### ISSUE TITLE
Request to join - User skip credit card page and become a member

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1001]
Tested on Staging iOS version 1.10.3(6-295)
Tested on Staging Android version v1.0 (324)

Steps to reproduce:
1. Join to a common 
2. in contribution page click on amount
3. click on continue

Actual results:
user skip credit card page and become a member - see attached video
it seems that it happens on old commons. when new common is created then user is navigate to the credit card details
https://user-images.githubusercontent.com/69141571/148693493-91470d71-c473-4a45-b245-ce990375711d.mp4

Expected results:
user must be navigate to credit card details

**Comment by watchtower314** [comment]
@yanivi71 @HannaMaklakova @kazaryan-t  this is not a bug, this is intentional, when a user has a card in the database already, we don't want to let the user create another card

**Comment by yanivi71** [comment]
@watchtower314 thanks for the clarification. I will close this issue
