### ISSUE TITLE
UI bugs in notification screen

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1005]
Tested on Staging iOS version 1.10.3(6-295)
Tested on Staging Android version v1.0 (324)
Designs - https://zpl.io/blBLD0z

1. There is no date and time on notifications.
2. On Android - set the border-radius 4pt for the background of notifications titles.
3. For New Proposal and New Featured common notification remove quotation marks.
4. Remove the second name (near the date and time) of common for New Featured common notification.

![IMG_0359](https://user-images.githubusercontent.com/68247034/148741911-655fc7f2-aa8d-4752-a86d-6ce93b15615e.PNG)
![Screenshot_20220110-115250_common-stg](https://user-images.githubusercontent.com/68247034/148741915-c3eac1fe-370f-461b-97d1-356ef3f4af5e.jpg)

![14 01 03 Notification Screen - Common MVP 1 1 - Ze](https://user-images.githubusercontent.com/68247034/148739666-377d93f9-40f7-4236-be31-0bf1ec8fe8fa.png)

**Comment by IvanSantiagoUk** [comment]
I completed all the points apart of "1"

Not sure why that is happening. the issue is than on the notification item the createdAt property is undefined this is causing that problem and as well a reordering issue.

The data seems to be fine on firebase so the problem is how we fecth it and store on mobx. But i really struggle with lyubo implementation and I dont get it.

Can @watchtower314 or @MeyerPVKernelics have a quick look on that point?

**Comment by watchtower314** [comment]
Fixed it

<img width="292" alt="Screen Shot 2022-01-13 at 13 11 44" src="https://user-images.githubusercontent.com/30501647/149319893-ffb5bbc9-aaec-4f7b-8b2e-871f9c843a01.png">

**Comment by kazaryan-t** [comment]
Remove quotes from the user's name in the new proposal notification.

![photo_2022-01-17_18-23-05](https://user-images.githubusercontent.com/68247034/149797167-e52372dd-e38d-4069-819f-a3da9cf1ea23.jpg)

**Comment by kazaryan-t** [comment]
1. I think there is no space between "by" and the user's name on New Proposal notifications. Please, add the space.
2. Also there is no space between New post and post title.

![photo_2022-02-02_11-45-22](https://user-images.githubusercontent.com/68247034/152121025-ecb7a235-03d6-4b5d-ae4c-cd1495ec459d.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.7 (10-307)
Tested on Staging Android version v1.0 (391)
Found OK
