### ISSUE TITLE
Needless step appears during membership request

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1006]
Please, remove the unnecessary step from the membership request process.

After selecting the amount for contribution, the Payme screen appears immediately since the screen Billing details (https://zpl.io/VKdlqjE) was removed.

![IMG_0364](https://user-images.githubusercontent.com/68247034/148743529-3fdf783e-f977-416d-8230-71b936f842ae.PNG)
![IMG_0365](https://user-images.githubusercontent.com/68247034/148743534-1d35d185-7026-4273-bf70-a3d0df5d7db7.PNG)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.5 (8-300)
Tested on Staging Android version v1.0 (358)
unnecessary steps were removed
