### ISSUE TITLE
Notification - no push notification for iOS devices on staging

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1009]
Tested on Staging iOS version 1.10.3(6-295)
Tested on Staging Android version v1.0 (324)

Steps to reproduce:
1. create a common, join a common, create proposal/ discussion

Actual results:
no push notification for iOS devices on staging. only android get notification

Expected results:
push notification must be activate on iOS device

**Comment by MeyerPVKernelics** [comment]
![image](https://user-images.githubusercontent.com/92447173/149509149-f8981194-cf42-40fd-8037-210208177422.png)
We need update APNs certificate

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.4 (7-298)
push notifications is activate on iOS device
