### ISSUE TITLE
Emails - Funding proposal was approved - common balance display in $

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1011]
Tested on Staging iOS version 1.10.3(6-295)
Tested on Staging Android version v1.0 (324)

Steps to reproduce:
1. go to a common you are a member
2. create a proposal
3. accept the proposal

Actual results:
mails is send but common balance display in $

Notice to Admin
The following proposal was approved and is awaiting payment.

Common name: test_common_notifications
Common id: 04ec0e52-a594-4206-b791-256d2f5841c4
**Common balance: ‏935.00 $**
Proposal ID: 990f4fdd-c7b4-4978-be28-3e915d4c7564
User Full Name: user usersky
User ID: user
User Email: arielllllllll@daostack.io
Payment amount: ‏65.00 ₪
Submitted on: Tue Jan 11 2022 16:28:10 GMT+0000 (Coordinated Universal Time)
Passed on: Tue Jan 11 2022 16:28:38 GMT+0000 (Coordinated Universal Time)

Expected results:
Common balance must be convert and display as ILS

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.4 (7)
Tested on Staging Android version v1.0 (324)

@watchtower314 this issue is not fixed

**Comment by watchtower314** [comment]
@yanivi71 this was fixed but not yet deployed

**Comment by yanivi71** [comment]
Ok. Thanks.

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.4 (7-298)
Tested on Staging Android version v1.0 (330)
found OK
