### ISSUE TITLE
New user is stuck on Personal contribution page

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1014]
New user is stuck on Personal contribution page during membership request if his card details are not saved in DB.

Steps to reproduce:
1. Crete a new user
2. Join a Common
3. Go to Personal contribution screen
4. Select an amount

Actual result:
The user is stuck on the Personal contribution screen with endless loading "One moment please"

Expected result:
User should be redirected to PayME screen to insert card details.

![Screenshot_20220112-115514_common-stg](https://user-images.githubusercontent.com/68247034/149113924-96b6b699-0929-47f1-a87d-269a4d5a65a2.jpg)

![Screenshot_20220112-115559_common-stg](https://user-images.githubusercontent.com/68247034/149113939-959cd5c7-aa67-43fa-8f69-ddf669eeccf4.jpg)

https://user-images.githubusercontent.com/68247034/149115970-b6a6dd41-96cf-407c-bd87-47e8ac1cfb91.mp4

**Comment by yanivi71** [comment]
tested on staging Ios ver 1.10.4 (7-297)
@watchtower314 This issue is not fixed. The user is stuck on the Personal contribution screen with endless loading "One moment please"

**Comment by MeyerPVKernelics** [comment]
Will be fixed in https://github.com/daostack/common-monorepo/issues/1029

**Comment by kazaryan-t** [comment]
Verified
