### ISSUE TITLE
Request to join - Change filling address field 

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#1018]
Please change address field (add fields for: address, building number, city, postal code, country)
https://zpl.io/2Zeeprl 
<img width="250" src="https://user-images.githubusercontent.com/87295860/149206379-d51e382d-dbae-47f5-a63d-a2d7eb9ffecf.jpeg">

**Comment by HannaMaklakova** [comment]
Task on hold

**Comment by yanivi71** [comment]
@watchtower314 @HannaMaklakova  this screen is no longer exists in the app. 
i am closing this issue
