### ISSUE TITLE
Common - members - Pending - Circle does not respond when  User has status "pending payment"

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#102]
Tested also on production

Steps to reproduce:
1. Go to Production
2. Go to common "ערבית באהבה"
3. Click on members - > Pending
4. Scroll down to the end of the page (proposal id - 4c51ffbc-cb63-40ca-b9f3-049c64453030)

Actual results:
there is a request to join witn status "pending payment" - see attached image
this status does not changes
Circle returns error "1006" - see error attached

Expected results:
If user stay in this status we need to get from circle response.

![image](https://user-images.githubusercontent.com/69141571/108324547-b80e1900-71d0-11eb-9608-220482b1623f.png)
![image (16)](https://user-images.githubusercontent.com/69141571/108324569-bf352700-71d0-11eb-8cf5-268151cf2545.png)

```
Unable to update payment from circle because error occurred trying to do so {"context":{"error":{"data":{"userMessage":"Request to external service failed. Please try again later","response":"[\"error code: 1006\"]","data":{"message":"Circle call to GET payment with id fc9fe5a9-a212-422a-a6fc-1c26bacf870f failed","errorCode":"External.CirclePayError"}},"name":"Common Error","statusCode":500,"errorId":"2405e83a-01f8-4d64-bf01-4272ca5fb402","userMessage":"Request to external service failed. Please try again later","errorCode":"GenericError"},"payment":{"type":"one-time","createdAt":{"_nanoseconds":408000000,"_seconds":1613554205},"updatedAt":{"_nanoseconds":408000000,"_seconds":1613554205},"fees":{"currency":"USD","amount":0},"id":"29349104-34f5-46b0-85e6-2ab5d5f390ad","status":"pending","amount":{"currency":"USD","amount":2500},"proposalId":"4c51ffbc-cb63-40ca-b9f3-049c64453030","userId":"DollGSAUeDPy5el9nmBSoJ92xxp1","circlePaymentId":"fc9fe5a9-a212-422a-a6fc-1c26bacf870f","source":{"id":"570d9a5b-8fac-4655-b9f2-a00de85c6897","type":"card"}}}}
```

**Comment by alexander2001i** [comment]
> Tested on Staging iOS version 1.9.5 (4978-216)
> Tested on Staging Android version 1.9.5 (4978-177)
> Tested also on production

@yanivi71 about that what do you mean tested on staging and tested on production. As far as I can see that only happens for one except proposal in the production environment?

**Comment by yanivi71** [comment]
@alexander2001i i change it. thanks
