### ISSUE TITLE
Monthly contribution - Error message appears and the monthly contribution does not cancelled

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1023]
Tested on Staging iOS version 1.10.4 (7)
Tested on Staging Android version v1.0 (324)

Steps to reproduce:
1. Go user profile 
2. choose monthly contribution
3. Select a common that is active 
4. Click on Cancel monthly contribution
5. Click on cancel anyway

Actual results:
error message appears and the monthly contribution does not cancelled
see attached video

https://user-images.githubusercontent.com/69141571/149652233-31b8dee0-c267-450c-a0bf-64c6cf077417.mp4

Expected results:
user must able to cancel monthly contribution

**Comment by watchtower314** [comment]
backend: deployed
frontend: ---

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.5 (8-300)
Tested on Staging Android version v1.0 (358)
Found ok 
@watchtower314 i m closing this issue but i will open another issue on the monthly contribution/ the process is not good
