### ISSUE TITLE
Join a common - personal contribution - conflict amount numbers

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1037]
Tested on Staging iOS version 1.10.4 (7)
Tested on Staging Android version v1.0 (324)

Steps to reproduce:
1. join a common that has minimum 1K contribution e.g. common name : "Avvadia"
2. navigate to personal contribution 
3. See contribution amount 1009, 2522.5, 5045, other
4. Click on other
5. enter amount of 5000 ils

Actual results:
Error message appears that the amount must be between 1009 - 2500
even though that the user can choose 5045 from the contribution list - see video

https://user-images.githubusercontent.com/69141571/149885623-33882ab8-6231-454d-947f-a070a967d5b7.mp4

Expected results:
The list o the contribution amount should be limited between 1k - 2500 ils max

**Comment by yanivi71** [comment]
@IlyaDylko @watchtower314 this issue is not fixed. i do not see any changes

**Comment by IlyaDylko** [comment]
@yanivi71 "Since we changed $ to ₪, max min contribution amount changed from 500$ to 2500₪. That caused conflict with the contribution amount options on membership request flow. Now it's decided to make it 500₪ again."
https://github.com/daostack/common/pull/1196

**Comment by watchtower314** [comment]
@HannaMaklakova can you please confirm with Shai what is the maximum amount for joining a common?
we know that minimum is 10 shekels,
max is:

**Comment by HannaMaklakova** [comment]
> @HannaMaklakova can you please confirm with Shai what is the maximum amount for joining a common? we know that minimum is 10 shekels, max is:

Already asked him. Will update here

**Comment by HannaMaklakova** [comment]
> @HannaMaklakova can you please confirm with Shai what is the maximum amount for joining a common? we know that minimum is 10 shekels, max is:

The maximum amount is 5000 shekels
