### ISSUE TITLE
Change Media format of funds

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#1038]
Make the media format to only show 2 decimal places:
https://zpl.io/bzKpDX3
![Screenshot 2022-01-18 at 15 22 45](https://user-images.githubusercontent.com/87295860/149989649-487845f7-ff58-4413-855c-04c29071378b.png)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.5 (8-300)
Tested on Staging Android version v1.0 (358)
format is only show 2 decimal
