### ISSUE TITLE
Membership request - Delete message of the non-supporting MC

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#1039]
delete the message about the non-support of the MasterCard:
https://zpl.io/2Zeeprl
![Screenshot 2022-01-18 at 16 36 25](https://user-images.githubusercontent.com/87295860/149990635-9bce78d5-1bda-43a1-acb0-dd9b2dccbcfd.png)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.5 (8-300)
Tested on Staging Android version v1.0 (358)
message about the non-support of the MasterCard is not display
