### ISSUE TITLE
Optimize messages loading on the common screen

### ISSUE THREAD

**Issue by IlyaDylko** [daostack/common-backend#1046]
I’ve found out that every time we are opening the common screen, all the messages from all of the discussions start fetching at the same time and that creates some lag. It’s not so much noticeable on the new and fast devices though. We can change that by fetching messages only when we open the specific discussion. But in that case we won’t see the number of messages on the discussion cards, cuz that number we get after the fetch, by counting length.
We can create a counter for every discussion and update it with the new messages though. But for that I need some help from the backend team.

**Comment by yanivi71** [comment]
@IlyaDylko as we discussed in the chat . the numbers of the comment is not equal to the numbers in to comment within the discussion.
please check
