### ISSUE TITLE
Funding proposal - create funding proposal - Redesign Address details

### ISSUE THREAD

**Issue by MeyerPVKernelics** [daostack/common-backend#1049]
https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/61acf0df4a06e69e6042062a

Redesign Personal Address details block

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.5 (8-300)
Tested on Staging Android version v1.0 (358)
Address details appears according to the design
