### ISSUE TITLE
Header buttons and discussion cards style on android

### ISSUE THREAD

**Issue by IlyaDylko** [daostack/common-backend#1052]
On android header button do not work on some screens. And discussion cards style is a little bit broken.
![2022-01-27 14 30 06](https://user-images.githubusercontent.com/9967079/151368590-42330a15-b426-4450-896e-00e04faf5abd.jpg)

**Comment by yanivi71** [comment]
Tested on Staging Android version v1.0 (389)
seems the performance is ok.
discussion cards looks ok
