### ISSUE TITLE
Fix the element about hidden content

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1053]
Need to fix the element with a message about hidden content (post and proposal)
Design - https://zpl.io/bzQ614X

![photo_2022-01-27_19-12-46](https://user-images.githubusercontent.com/68247034/151402842-d95b3824-6355-4887-a889-072512db1421.jpg)
![10 03 03 01 Proposals - after copy link - Common M](https://user-images.githubusercontent.com/68247034/151402975-95f9fda4-c45d-4dc4-aab4-bd30e8704233.png)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.7 (10-307)
Tested on Staging Android version v1.0 (391)
Found ok
