### ISSUE TITLE
Proposal -Add bank account - when user does not add "Add photo" or  "Add bank account confirmation letter" no error message appears

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1065]
Steps to reproduce:
1. create a new proposal 
2. click on "Add bank account" button
3. fill all the fields except "Add photo" or  "Add bank account confirmation letter"
4. Click on save

Actual results:
Nothing happens. user stay in the same screen 
![image](https://user-images.githubusercontent.com/69141571/151790331-d563b47a-633f-422a-8042-179b6ff4e162.png)

Expected results:
if user does not fill Add photo" or  "Add bank account confirmation letter" there must be an error message and instruct the user to add these docs

**Comment by MeyerPVKernelics** [comment]
![Screenshot 2022-01-31 at 15 09 12](https://user-images.githubusercontent.com/92447173/151791441-1f0c7dfb-203d-4222-9674-cb09fb2fb380.png)
We don't have an error message for these fields, they just need to change the background color

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.6 (9-306)
The background of the field is changed when user does not add documents
@MeyerPVKernelics @watchtower314 is this the solution? the background color?

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.6 (9-306)
Tested on Staging Android version v1.0 (389)
 there is no error message on background changes
