### ISSUE TITLE
UI fixes in Proposal and Membership request chats

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1067]
iPhone 7 - iOS version 15.3.1
Samsung S10e - Android version 12

https://github.com/daostack/common-monorepo/issues/839#issuecomment-979835462

1. Fix the background of the proposal chat. There is a section at the top of the page that is not painted in the background color.

![photo_2022-01-31_16-17-08](https://user-images.githubusercontent.com/68247034/151800181-cc7944eb-4e46-4069-b86a-ce8fc279f462.jpg)
![photo_2022-01-31_16-17-06](https://user-images.githubusercontent.com/68247034/151800185-f384c67a-60e6-4120-ac45-b2698d609116.jpg)

2. On Android put the Proposal or Common name in the center

![143560675-b4a0a66f-af50-48e2-acef-cc661cfd473c](https://user-images.githubusercontent.com/68247034/151800503-9b19dcd1-2705-4b5c-b4cc-945206edfe40.jpg)

**Comment by watchtower314** [comment]
@kazaryan-t what device is this? I cannot reproduce this on both iOS and android devices

**Comment by kazaryan-t** [comment]
iPhone 7 - iOS version 15.3.1
Samsung S10e - Android version 12

@watchtower314

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.7 (10-307)
Tested on Staging Android version v1.0 (391)
found OK
