### ISSUE TITLE
moderation - post comment - regular user - the report is display 

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1087]
Tested on Staging iOS version 1.10.5 (8-300)
Tested on Staging Android version v1.0 (358)

Steps to reproduce:
1. as a user/moderator report on the post comment
2. as a user enter the post and view the reported comment

Actual results:
regular use see the report display and who wrote it. see attached image
![image](https://user-images.githubusercontent.com/69141571/152341556-a1729d90-120a-47df-ab14-1507aeea782a.png)

Expected results:
The report should not display for regular user

**Comment by watchtower314** [comment]
@yanivi71 marking reported content for regular users was required by Apple, this was added during the development of report button on sprint 8

**Comment by yanivi71** [comment]
closing this issue according to @watchtower314 comment above
