### ISSUE TITLE
Chat - UI fixes for non members

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1089]
1. Discussions - Fix the field **Only members can send messages** according to the design. 
Design - https://zpl.io/VOQpBDX

![photo_2022-02-05_11-07-47](https://user-images.githubusercontent.com/68247034/152633991-05b1b4f4-4adc-4a62-892c-64abf4a2ddfe.jpg)
![10 10 5 Common page_ discussion page NON MEMBER - ](https://user-images.githubusercontent.com/68247034/152633997-0fd62dbd-b5f1-43df-9b12-fb54f326e4a3.png)

2. Proposals - Fix the field **Only members can send messages** according to the design. 

![photo_2022-02-05_15-21-26](https://user-images.githubusercontent.com/68247034/152641869-27b555fa-b416-482e-832a-1b7819802ca2.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.7 (10-307)
Tested on Staging Android version v1.0 (391)
found ok
