### ISSUE TITLE
Membership request - UI fixes on membership request tabs

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1090]
1. There is a blank space between the countdown field and the user's name on the membership request tabs. Fix it according to the design.
Design - https://zpl.io/bzg94yA

![08 03 3 my account_ Membership requests - pending ](https://user-images.githubusercontent.com/68247034/152634145-674c50d9-7477-4175-baf3-f2b120840034.png)
![photo_2022-02-05_11-09-59](https://user-images.githubusercontent.com/68247034/152634149-cd91ceb9-8ceb-42c9-9b5f-97fdc5d2b008.jpg)

2. On the pending tab in the membership request put the three dots (moderator tools) near the contribution amount and remove a blank space between the countdown field and the user's name.
Design - https://zpl.io/2p6PWyQ

![photo_2022-02-05_11-10-05](https://user-images.githubusercontent.com/68247034/152634296-0156933e-e433-4522-9036-a0a73eecfb1e.jpg)
![10 07 1 members pending - Common MVP 1 1 - Zeplin ](https://user-images.githubusercontent.com/68247034/152634298-e07a18d2-cde1-4dfb-a0ea-9b078fba6db2.png)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.8 (11-308)
Tested on Staging Android version v1.0 (392)

Found OK
UI issues fixed
