### ISSUE TITLE
Create Proposal - Add a screen after creating a funding proposal

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1091]
There is no screen **Your proposal is live!** after creating a funding proposal. 
(probably we removed this screen)

Design - https://zpl.io/2GKRzGm

https://user-images.githubusercontent.com/68247034/152635003-a42a59c6-f1c4-40e6-b5f5-cb3a472b4c8b.mp4

**Comment by watchtower314** [comment]
@yanivi71  @kazaryan-t  This is not what we have in the new design (in zeplin, *new design, `Funding proposal - create funding proposal` section)
