### ISSUE TITLE
Incorrect behavior while editing user's profile

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1095]
**Steps to reproduce:**
1. Go to the user's profile
2. Click on Edit button
3. Delete First or/and Last names
4. Click on Cancel or Back buttons

**Actual:**
Nothing happens when clicking on Cancel or Back buttons.

**Expected:**
A pop-up should appear with 2 options: 1. Leave without saving 2. Continue editing

https://user-images.githubusercontent.com/68247034/152640890-a79f546d-4137-4f8d-8d6f-97b3d353da4b.mp4

**Comment by yanivi71** [comment]
@IlyaDylko @watchtower314 basically it works ok new, but on android device we have the device back button and when user click on back the pop up does not appear

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.8 (11-308)
Tested on Staging Android version v1.0 (392)
@IlyaDylko @watchtower314 
Something wrong here. now on android the save button is activate as cancel button and data is not save
and on both platform the information of the the fields is in gray (why?)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.11.0 (13-312)
Tested on Staging Android version v1.0 (396)
found ok
