### ISSUE TITLE
Be a Part of Common pop-up

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1096]
Remove the blank space on **Be a Part of Common** pop-up.

![photo_2022-02-05_15-11-49](https://user-images.githubusercontent.com/68247034/152641511-4c439d05-d443-47b0-a728-acf8045d5cd3.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.7 (10-307)
Tested on Staging Android version v1.0 (391)
Found ok
