### ISSUE TITLE
Incorrect order of Commons

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1097]
All commons should be sorted by latest activity (comment in any post/proposal, new post, new proposal).

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.7 (10-307)
Tested on Staging Android version v1.0 (391)
@IlyaDylko @watchtower314 
When user add chat to proposal the common order does not changes

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.8 (11-308)
Tested on Staging Android version v1.0 (392)
@IlyaDylko i do not see any change here.
When user add chat to proposal the common order does not changes

**Comment by ariel-dao** [comment]
@IlyaDylko why is this tagged as high priority?

**Comment by noamso1** [comment]
I'm pretty sure Ilya fixed this when he added try-catch to "countDiscussionMessages".
Because it exited the function before "forceCommonUpdatedAt".
Now it should work properly. Please recheck.

**Comment by noamso1** [comment]
@ariel-dao can we close this ticket ?

**Comment by ariel-dao** [comment]
@yanivi71 can we?

**Comment by yanivi71** [comment]
Not yet. I need to test it. Once the staging version will be ready

**Comment by IlyaDylko** [comment]
If it's still not fixed, the problem is on the backend side.

**Comment by ariel-dao** [comment]
we are waiting for Yaniv to test it... so it should be assigned to him. please let's avoid re-assigning people unless there is a documented reason

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.11.2 (15-316)
Tested on Staging Android version v1.0 (401)
found ok
