### ISSUE TITLE
Endless white screen while scrolling on My Proposals screen

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1098]
Endless white screen while scrolling on My Proposals screen.

https://user-images.githubusercontent.com/68247034/152642327-ee95758b-a68e-407c-9d7a-8f0bc63b3f7a.mp4

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.7 (10-307)
Tested on Staging Android version v1.0 (391)
Not fixed.
@MeyerPVKernelics @watchtower314 still happens. see proposal page in common "Email Common abc"

**Comment by kazaryan-t** [comment]
Irrelevant, can't reproduce.
