### ISSUE TITLE
moderation - request to join - moderator cannot report on request to join 

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1102]
Tested on Staging iOS version 1.10.5 (8-300)

Steps to reproduce:
1. as a regular user request to join a common
2. as a moderator go to members -> pending
3. click on the 3 dots and click on report  

Actual results:
nothing happened user return back to the pending panel  

Note : regular user cannot report also 

Expected results:
report screen should appears
moderator must have the report rights

**Comment by kazaryan-t** [comment]
1. Endless loading when reporting the membership request
2. User can't close the window "Report" except by clicking on the "Close" button. I guess it should close by swiping down.


https://user-images.githubusercontent.com/68247034/162803030-4be173d0-6912-4488-805f-98c614068838.mov

**Comment by IlyaDylko** [comment]
<img width="462" alt="image" src="https://user-images.githubusercontent.com/9967079/163190841-aa7fa97a-a0b5-4606-b371-3af235df8014.png">

**Comment by noamso1** [comment]
@IlyaDylko I've tested the payload you gave me, and it works fine.

REQUEST:
```
{
  "moderationData": {
    "itemId": "dd3a1f4f-9f17-4ce4-9f6b-4d993c75250d",
    "reasons": "Nudity",
    "moderatorNote": "Test"
  },
  "type": "discussionMessage"
}
```
RESPONSE:
```
{
    "message": "Your report was accepted"
}
```
I tried both with authenticated user and with anonymous user.

**Comment by IlyaDylko** [comment]
The backend fix wasn't deployed on staging. Works fine now.
