### ISSUE TITLE
Emails - approved proposal - Your funding proposal was approved  - email not send

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1103]
Tested on Staging iOS version 1.10.5 (8-300)
Tested on Staging Android version v1.0 (358)

Steps to reproduce:
1. create a new proposal
2. approve the proposal

Actual results:
user does not get mail foe approval proposal.
Note: since we merge the payout the mail does not send

Expected results:
when proposal is approved user should get mail see below.

Subject: Your funding proposal was approved
Hello <User first name>,

Congratulations!
Your proposal: <proposal title> has been approved. To receive the funds you will need to provide your bank account details, as well as some identification information.

Please fill all the required information on the attached form and send it back to us at: payout@common.io

For more information you can contact us any time using our <link>support chat</link>

Common,
Collaborative Social Action.

**Comment by watchtower314** [comment]
@yanivi71 I cannot reproduce this, can you provide more details, or check again?
![IMG_1948](https://user-images.githubusercontent.com/30501647/153175832-d2c01a61-1d2e-4285-980f-d7203833033f.PNG)

**Comment by yanivi71** [comment]
@watchtower314 thanks. seems to be my mistake. i also got approval mail
i m closing this issue
