### ISSUE TITLE
Performance issue with SectionList

### ISSUE THREAD

**Issue by MeyerPV** [daostack/common-backend#111]
![Screenshot 2021-02-22 at 13 59 10](https://user-images.githubusercontent.com/35873164/108699339-25de7b80-7516-11eb-8d93-ba87294fd459.png)

initialNumToRender should be enough to fill the screen but **not much more**.

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-225)
Tested on Staging Android version 1.9.5 (4978-186)

Verified by @MeyerPV on staging
