### ISSUE TITLE
Proposal emails - indicate proposal emails are tests

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#1112]
For emails about funding proposal approved, we need to indicate whether the proposal is a test or not

**Comment by ariel-dao** [comment]
@watchtower314 @yanivi71 pushed a hotfix, please test

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.6 (9-306)
Tested on Staging Android version v1.0 (389)
found ok {test} string appears
