### ISSUE TITLE
Production - create proposal - add bank account - Bank name is a free text.

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1115]
Tested on production with iOS device version 1.9.9(3-56)
reported by @arava

Steps to reproduce:
1. create a proposal 
2. Click on add bank account
3. fill Bank name

Actual results:
Bank name is a free text. 

Expected results:
should be a dropdown with the list of banks so user cannot type bank name with typo

**Comment by watchtower314** [comment]
@HannaMaklakova can you please get from Shai/Arava the lists of banks we need to show in the drop down menu?

**Comment by HannaMaklakova** [comment]
@yanivi71 
We already have the issue here: https://github.com/daostack/common-monorepo/issues/1054

**Comment by yanivi71** [comment]
@HannaMaklakova thank I will close it

**Comment by yanivi71** [comment]
duplicate with https://github.com/daostack/common-monorepo/issues/1054
