### ISSUE TITLE
Deep linking after cold starting the app not working

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#112]
`DeepLinking` is clicking on a link of a common that was creating by sharing the common.

We handle DeepLinks in App.js, and it is **unrelated** to `pushNotification` redirection

<img width="446" alt="Screen Shot 2021-04-08 at 5 56 09" src="https://user-images.githubusercontent.com/30501647/114008053-e0f57680-982f-11eb-9d1f-cef8c633e703.png">

DeepLinks only work on production, here's 2 example links:
https://app.common.io/common/50b389d5-5045-4180-8e95-f38ce4d99871
https://app.common.io/common/b7f21f90-f5ce-4ab1-b9c1-265ccd4b2721

Steps to reproduce:
1. when app is closed, click on a common link

Expected result:
- users should be redirected to the common profile

Actual result:
- user is being redirected to common list

**Comment by yanivi71** [comment]
tested on production
@IvanSantiagoUk the fix works for android, but does not for ios.

when app is closed and you click on the shared link it open the common list page

**Comment by BigRomanov** [comment]
@watchtower314 please add description and reproduction scenario.
