### ISSUE TITLE
Create a "deactivate common" endpoint

### ISSUE THREAD

**Issue by ariel-dao** [daostack/common-backend#1122]
We want to give users to delete their commons, but we don't want to actually delete from the database, so instead we'll use an already existing property in the common entity called "active".

Create an endpoint `/commons/decativate` that will set that property to false. (in the common by id)

**Comment by noamso1** [comment]
@ariel-dao  do we now also need to add checks everywhere to determine if the common is active? for example when creating a proposal or submitting a discussion message?

**Comment by ariel-dao** [comment]
@noamso1 not at the moment
