### ISSUE TITLE
production - invoices - user must be logged in to the web site in order add invoices

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1125]
Tested on production with iOS device version 1.9.9(3-56)

Steps to reproduce:
verify you are logged out from the common web site

1. created a proposal ( i used amount of 50 ILS)
2. add bank account
3. add all other details
3. Click on Create proposal
4. approved the proposal
5. when email is received "Funding proposal was approved" click on the invoice links

Actual results:
user is redirect to the web site and when the user is logged in he sees the common web site page instead of the load invoice  page .
e.g for the link - https://common.io/invoices/submission/de1c6f68-1dc0-4cec-a71a-8118e5cf33e5

Expected results:
user should be redirect to add invoice when he click on the link even if he does not logged in the the web

**Comment by MeyerPVKernelics** [comment]
@yanivi71 @roienatan @HannaMaklakova 
It is necessary to add the ability to log in on the web if the user follows the link and is not logged in

**Comment by HannaMaklakova** [comment]
> It is necessary to add the ability to log in on the web if the user follows the link and is not logged in

Do you mean automatically logged in after following the link?

**Comment by watchtower314** [comment]
@Shaidao 

Perhaps if the user is not logged in, we can
1. redirect the user to login screen, and then redirect to the invoice screen (in web)
2. have a modal pop up for login, and then do the redirection


I'm still confused as to why we have this complex flow of using deeplinks and not just ask the user to go to the proposal screen and have him upload the invoice there, as @yanivi71 said, it's an exhausting flow for users, and we may want to consider simplifying it for them

something like in the attached pic (obviously, the add invoice button will only be visible for approved proposals, in a third tab)
![Screen Shot 2022-02-17 at 14 31 03](https://user-images.githubusercontent.com/30501647/154484581-399fa189-606a-421a-a618-ceb549c9bd66.jpg)

**Comment by Shaidao** [comment]
Currently we don’t have the “link” between the proposal approval and the invoice upload screen. This is a feature we introduced in sprint 10 (design is at work)
Until we have it we need a flow that uses a deeplink to the upload screen and request login if the user is not logged in yet. Let me know if it’s clear
