### ISSUE TITLE
Production - email to user - Funding proposal was approved - has incorrect format

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1126]
Tested on production with iOS device version 1.9.9(3-56)

Steps to reproduce:

1. created a proposal 
2. approved the proposal
3. Get email for approval proposal

Actual results:
The email template  "Funding proposal was approved" is incorrect
this is what the user gets
![image](https://user-images.githubusercontent.com/69141571/153407787-5abc7ee8-4693-42f9-9105-6a13f6000adf.png)

Expected results:
should be verify with the design team what is the correct format. this is an example of the email template before payme
![image](https://user-images.githubusercontent.com/69141571/153408113-ee704877-ea7b-4abc-9217-588718ca9802.png)

**Comment by ariel-dao** [comment]
changed format, further bugs about format should be under shai/arava
