### ISSUE TITLE
Production - common - app crashes when opening common with many members

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1127]
Tested on production with 
Android version v1.0 (377)

Steps to reproduce:
1. open the app on common list
2. choose a common with many members (e.g common X has 126 members)

Actual results:
the common page is open but after several seconds the app crash see attached video 
https://user-images.githubusercontent.com/69141571/153723697-9c6328b7-0cd2-44d4-a5f6-ce5cfe0e0c5e.mp4
and see also log from server
![image](https://user-images.githubusercontent.com/69141571/153723774-94bbe5f9-19e3-4bf8-9fe7-0c31aca481ba.png)

Expected results:
common page should be open with common details

**Comment by watchtower314** [comment]
@yanivi71 could not reproduce this, can you please provide more details?

https://user-images.githubusercontent.com/30501647/153767084-a885b60d-07f7-4675-8a37-1b3a00615458.mov

**Comment by yanivi71** [comment]
@watchtower314 it happens on my Xiaomi device. Both of them
