### ISSUE TITLE
Production - pay out - proposal - when proposal is approved Common owner does not get mail 

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1128]
Tested on production with 
iOS device version 1.9.9(3-56)
Android version v1.0 (377)

Steps to reproduce:
1. Go to a common that you are a member, but  not the common creator
2. Create a proposal
2. approve the proposal

Actual results:
Email is sent to support and to proposal owner, but not to Common owner

Expected results:
email should be sent to 3 addresses 
Common support
Common owner
Proposal owner

**Comment by ariel-dao** [comment]
@Shaidao there is no template for this so at the moment should I CC the common owner?
@HannaMaklakova fyi

**Comment by Shaidao** [comment]
feel free to generate any email needed to throw there some text, we will
handle the content later

**Comment by ariel-dao** [comment]
@yanivi71 can we close this?

**Comment by yanivi71** [comment]
@ariel-dao not yet. i still need to test it on production

**Comment by watchtower314** [comment]
@yanivi71 Where is the specs for this? Proposal approval was always sent only to proposer and admin

**Comment by yanivi71** [comment]
@watchtower314 i took it form here https://daostack.notion.site/Payout-full-flow-ce3e51cbe47c43edb1cfdad2dabc0163
issue no. 2
