### ISSUE TITLE
Fix hidden comments

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1135]
Checked on iOS and Android

Steps to recheck:
1. Open the app on prod
2. Go to the common "common-dev"
3. Join the discussion "Welcome everyone"
4. Check the hidden content

![photo_2022-02-15_10-05-41](https://user-images.githubusercontent.com/68247034/154010037-eeccc961-eb1c-4fdb-9827-c2a32a8995bf.jpg)

![photo_2022-02-15_10-05-48](https://user-images.githubusercontent.com/68247034/154010030-13bcc1a3-d55f-4b3c-a549-e1fbc4dfb3be.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.8 (11-308)
Tested on Staging Android version v1.0 (392)
Found OK
UI for hidden comment is fixed
