### ISSUE TITLE
Production - payout - proposal - add invoices - trustee - when invoices are declined the in process value disappear

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1141]
Tested on production

Steps to reproduce:
1. Create proposal and approved it - see that there is a value of the proposal amount under "in process"
2. add invoices
3. as a trustee decline the invoices

Actual results:
when invoices are declined the in process value disappear

Expected results:
the in process value should be display 
![image](https://user-images.githubusercontent.com/69141571/154124135-86456ece-9a8f-47c3-9aa5-581e321de520.png)

**Comment by IlyaDylko** [comment]
I can't reproduce it on staging. Everything works ok there.

**Comment by yanivi71** [comment]
@IlyaDylko @HannaMaklakova tested agin on staging and not reproduced. i am closing this issue
