### ISSUE TITLE
Production - Create common - Onboarding screens 

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1142]
Need to fix the swipe on the onboarding screens during the common creation.

**Actual:** When swiping left the onboarding screens during the common creation, users are able to swipe them again and again.
**Expected:** The swipe should stop on the last onboarding screen and the user should be able to swipe only right to see the previous screen.

https://user-images.githubusercontent.com/68247034/154221116-7bf90b21-50dd-4241-9197-10a88de69000.mp4

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.7 (10-307)
Tested on Staging Android version v1.0 (391)
Found OK
