### ISSUE TITLE
Production - History tab - UI fixes on proposals with long names

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1143]
Please, fix the position of 'kebab' menu button for proposals with (relatively) long names.
Design - https://zpl.io/V045ZE9.

![photo_2022-02-16_11-10-36](https://user-images.githubusercontent.com/68247034/154222994-dbc4784f-0584-436e-be01-2bf1edc5308d.jpg)

![photo_2022-02-16_11-12-53](https://user-images.githubusercontent.com/68247034/154222990-e31b094b-c726-4ba7-88ad-9ef9daba9a8d.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.11.1 (14-315)
Tested on Staging Android version v1.0 (396)
Found ok
