### ISSUE TITLE
Production - common - members - history - the contribution amount is not convert to ILS

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1144]
tested on production

Steps to reproduce:

1 . go to a common with members 
2. click on members
3. Click on history
4. observe the amount numbers

Actual results:
the membership sums are in usd. In the app the sums are presented in ILS but the numbers weren’t converted.

Expected results:
sum should be convert to ILS

**Comment by yanivi71** [comment]
[@Roie](https://daostack.slack.com/team/U015K4A0SAY) [@Moore](https://daostack.slack.com/team/U019MBKEHMW) previous payments that were done in usd will remain in usd, only new payments will be in ils

**Comment by ariel-dao** [comment]
@yanivi71 can we close this?
