### ISSUE TITLE
Edit info and cover photo page fixes

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1152]
1. When editing common info the **'Save'** button is inactive and the user is not able to edit common info before inserting the tagline.

2. When the user deletes the common name and tagline, the errors _"The first name is a required field"_ and _"The last name is a required field"_ appear.

3. Remove _'Required'_ text from Tagline and About.

![photo_2022-02-21_10-35-34](https://user-images.githubusercontent.com/68247034/154909097-57fc6589-adf7-49b9-aa9b-cdca3e5fb998.jpg)
 
![photo_2022-02-21_10-38-07](https://user-images.githubusercontent.com/68247034/154909363-7f614327-b736-4191-b6b5-7e6c1c621931.jpg)

![photo_2022-02-21_10-42-55](https://user-images.githubusercontent.com/68247034/154909935-01c6c5bd-1dd1-42cc-a21a-8acfe6692088.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.7 (10-307)
Tested on Staging Android version v1.0 (391)
Found OK

**Comment by kazaryan-t** [comment]
1. Remove 'Required' text from Tagline.
2. When the user deletes the tagline, the errors "Tagline is a required field" appears.
P.S. Tagline is not requiered while creating a common, it shouldn't be required while editing.

![photo_2022-03-12_07-55-20](https://user-images.githubusercontent.com/68247034/158004322-b5f16d7c-1e64-42f3-afad-d606b2d379b0.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.11.0 (13-312)
Tested on Staging Android version v1.0 (396)
Found OK
