### ISSUE TITLE
Investigate and implement email statistics tracking statistics 

### ISSUE THREAD

**Issue by ariel-dao** [daostack/common-backend#1155]

**Comment by ariel-dao** [comment]
@noamso1 any updates?

**Comment by ariel-dao** [comment]
![CleanShot 2022-03-09 at 14 20 00](https://user-images.githubusercontent.com/89919079/157457800-58ca9db6-fabb-4e7b-92d4-5594ac8779c5.png)

Since Sendgrid can't seem to support our needs, we will investigate other options like mailchimp

**Comment by ariel-dao** [comment]
![image](https://user-images.githubusercontent.com/89919079/157638591-eac85232-5dd5-484d-958e-d13c2857d3be.png)

@Shaidao we have these email stats in sendgrid, if we want to track (we probably do) for more than 7 days as the message from sendgrid says, we'll need to either buy or implement our own storage. I suggest to check the pricing and avoid more dev work in this area if possible.

**Comment by Shaidao** [comment]
This is not good enough.. a marketing person cannot work in this method, it
should be crystal clear and easy

**Comment by ariel-dao** [comment]
@Shaidao when marketing finds work for dev to help with the analytics it will be implemented
