### ISSUE TITLE
Notification - Update app notification

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#1157]
After released new features users should get the pop-up notification to update their application: https://zpl.io/EmkBWB8

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.8 (11-308)
Tested on Staging Android version v1.0 (392)
@IlyaDylko the pop up appears only on iOS and i can see it after the installation of the new version.
please advice

**Comment by yanivi71** [comment]
@IlyaDylko i get this message each time i install the ios app. i do not think it suppose to act like this. furthermore it does not appear in android
![File (77)](https://user-images.githubusercontent.com/69141571/159471080-c32bb432-f8cb-4eed-88bf-1f87c5099f37.jpg)
