### ISSUE TITLE
Notification - Update payment method notification for circle users

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#1158]
* Notification to update payment methods for users who still have circle payment method: https://zpl.io/ag79LoR

**Comment by watchtower314** [comment]
@HannaMaklakova do we have screens for update payment method?

**Comment by HannaMaklakova** [comment]
> @HannaMaklakova do we have screens for update payment method?

We have but I'm not sure it's right

**Comment by watchtower314** [comment]
@HannaMaklakova Ok, so can you please make sure brio provides us with the correct screens, I cannot work on this ticket without the update payment method flow:

1. User see notification
2. If user clicks `edit details` -> we need to redirect the user to the edit details screen
3. If the user clicks `remind me later` -> we need to have a button or something in user profile that redirects user to the `edit details` screen

**Comment by HannaMaklakova** [comment]
@watchtower314 
Please find screens for the update payment method [here](https://github.com/daostack/common-backend/issues/716)

**Comment by HannaMaklakova** [comment]
add it to https://github.com/daostack/common-backend/issues/716

**Comment by ariel-dao** [comment]
@watchtower314 I think on BE we need to filter out specific users by cards and initiate some notification, we should talk a few min to plan it out

**Comment by watchtower314** [comment]
> add it to #716

@HannaMaklakova  Why was this reopened? We have discussed that the notification cannot be a ticket on its own without the update payment process existing, which is whew moved it to #716

**Comment by HannaMaklakova** [comment]
> > add it to #716
> 
> 
> 
> @HannaMaklakova  Why was this reopened? We have discussed that the notification cannot be a ticket on its own without the update payment process existing, which is whew moved it to #716 

https://github.com/daostack/common-backend/issues/716#issuecomment-1077609547

**Comment by HannaMaklakova** [comment]
Since we canceled all old PayIns, and we're about to change the whole PayIn mechanism with the new governance, there is no point in this notification.
