### ISSUE TITLE
The page for ¨Terms of Use¨ link is not found, error 404.

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1162]
Error 404 "This page couldn't be found", when clicking on the ¨Terms of Use¨ link.

![photo_2022-02-24_00-03-32 — копия](https://user-images.githubusercontent.com/68247034/155408156-ef03c29f-b6c1-4d0a-9cf9-3206c033ba40.jpg)
![photo_2022-02-24_00-03-40 — копия](https://user-images.githubusercontent.com/68247034/155408163-01b5b158-4bae-4739-b46c-5292b44ccddc.jpg)
![photo_2022-02-24_00-03-43 — копия](https://user-images.githubusercontent.com/68247034/155408166-8f1141f7-4188-4ddc-b583-4d05bb5284e6.jpg)
![photo_2022-02-24_00-03-35](https://user-images.githubusercontent.com/68247034/155408168-426092b3-ba04-41a9-aaf3-943a25db2eab.jpg)

**Comment by yanivi71** [comment]
@watchtower314 Still not fixed.
When creating a new common and click on "term of use" i still get 404 error

**Comment by yanivi71** [comment]
@watchtower314 @MeyerPVKernelics Still not fixed.
When creating a new common and click on "term of use" i still get 404 error

**Comment by yanivi71** [comment]
@watchtower314 @MeyerPVKernelics Still not fixed.
When creating a new common and click on "term of use" i still get 404 error
please check it . i reopened this issue several times. let me know if u need my help

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.11.3 (17-317)
Tested on Staging Android version v1.0 (402)
found ok
