### ISSUE TITLE
Request to join - Empty pop-up after membership request

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1164]
An empty pop-up appears after the membership was requested.

![photo_2022-02-24_22-44-22](https://user-images.githubusercontent.com/68247034/155595895-c40592d9-084c-4f4e-b776-a71b7de158dd.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.7 (10-307)
Tested on Staging Android version v1.0 (391)
tested on 4 different devices could not reproduce this problem anymore
