### ISSUE TITLE
Proposal - Buttons for voting appear after user has voted

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1165]
The buttons "X" and "V" for voting appear after the user has already voted.

https://user-images.githubusercontent.com/68247034/155596960-1bad6f10-0bf9-4d5f-8342-cb73b987c12e.mp4

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.7 (10-307)
Tested on Staging Android version v1.0 (391)
Tested with 4 different devices. the problem does not reproduce
