### ISSUE TITLE
Request to join - the payment frame is too small

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1167]
Reported by @Shaidao 

Steps to reproduce:
1. Join a common with user that did not fill his card details
2. Navigate to card details

Actual results:
the payment frame is too small. user need to scroll to confirm the details
![File (76)](https://user-images.githubusercontent.com/69141571/155876506-ea7490fb-dc71-43a2-97c6-807aa3fb249d.jpg)

Expected results;
increase the Iframe so user will see all the details

**Comment by watchtower314** [comment]
@yanivi71  This is not a bug, we have a scroller, since the credit card details form belongs to payme, and we cannot control the height
https://user-images.githubusercontent.com/30501647/155892483-5d2dde71-7b0f-4dc1-9c59-451c18fba4e9.mov
