### ISSUE TITLE
Emails - When clicking on Support chat redirect to 404 page could not be found.

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1168]
Tested on Staging iOS version 1.10.6 (9-306)
Tested on Staging Android version v1.0 (389)

Steps to reproduce:
1. Get email for any process (approved proposal, join a common etc)
2. when email is received click on "support chat" link 

Actual results:
 When clicking on Support chat redirect to 404 page could not be found.
![image](https://user-images.githubusercontent.com/69141571/155877099-0c57f3cd-f807-4c56-935f-89dc54e7273a.png)

Expected results:
user should redirect to support chat

**Comment by roienatan** [comment]
Currently there is no such path in the web as will as no design. There is the old version of web which have this path under `https://old.common.io/help` but we don't think it's a good idea to redirect users to an old unmaintained page.

**Comment by watchtower314** [comment]
@Jan-Blarky @noamso1 can you guys look at this?

@roienatan what should the design look like? The app is also redirecting to a text file

**Comment by roienatan** [comment]
> @Jan-Blarky @noamso1 can you guys look at this?
> 
> 
> 
> @roienatan what should the design look like? The app is also redirecting to a text file

I'm not sure as the current old page is not maintained. I think it's something for Michele/Shay and also brio to have an updated design for that.

**Comment by ariel-dao** [comment]
@MicheleFarhi Old task, can you please check it out? I don't think it's urgent but it's clutter, don't know if relevant at all

**Comment by ariel-dao** [comment]
@MicheleFarhi Closing, not a backend bug
