### ISSUE TITLE
Common - discussion - post - comments - user can see only his comments

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1169]
Tested on Staging iOS version 1.10.6 (9-306)
Tested on Staging Android version v1.0 (389)

Steps to reproduce:
1. Go to a common with several members
2. go to discussion
3. add comments from several members

Actual results:
user can see only his comments, and the numbers of the comments is incorrect

https://user-images.githubusercontent.com/69141571/155994739-8ebdcd97-18ee-4db7-8d23-131989070803.mp4

Note: should be also implemented on proposal chat 
Expected results:
all members should see all comments. and the number of comment in the post should be resemble to the comments

**Comment by MeyerPVKernelics** [comment]
Also fixed sorting for Discussion messages

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.8 (11-308)
Tested on Staging Android version v1.0 (392)
Found OK
