### ISSUE TITLE
Sign in with phone number

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#1180]
- [x] Phone number way:

- page for filling phone number: https://zpl.io/Q0Ad33k
- phone number filled: https://zpl.io/jZL7KKA
- after choosing 'Send code': https://zpl.io/GEkR33r
- time is over: https://zpl.io/g8qOEEA 
- in case user haven't get a code and choose 'Resend code' we will show: https://zpl.io/GEkR33r
- code is filled: https://zpl.io/Emkx33Y
- loading page after choosing 'Submit': https://zpl.io/Nwk533k
- page for completing the account: https://zpl.io/xmGQWWW

- [x] Error page: https://zpl.io/z85jzOA

- [x] Profile looks with different ways of registration:

- Apple ID: https://zpl.io/RMg9k3z
- Google: https://zpl.io/kDB7P8G
- Facebook: https://zpl.io/z85jz07
- Phone number: https://zpl.io/wqQglZJ

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.9 (12-309)
Tested on Staging Android version v1.0 (393)
user can sign in with Phone number, Facebook, Apple id Google account.
i am closing this task.
other issues will be open for each login
