### ISSUE TITLE
Add "Cardholder name" and "Expiration Date" to Card collection metadata

### ISSUE THREAD

**Issue by MeyerPVKernelics** [daostack/common-backend#1195]
Add "Cardholder name" and "Expiration Date" to Card collection metadata

We need it according the design
https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/6033f34bbd2b1510de2b27ee
![Screenshot 2022-03-11 at 16 44 38](https://user-images.githubusercontent.com/92447173/157879513-4411c816-f5b9-42f0-acdd-b773440a9bb7.png)

![Screenshot 2022-03-11 at 16 45 12](https://user-images.githubusercontent.com/92447173/157879599-4578e0ef-26a2-400e-9e72-778da3a56a8d.png)

**Comment by ariel-dao** [comment]
@MeyerPVKernelics @watchtower314 
this was already merged 7 days ago:
https://github.com/daostack/common-backend/pull/1185
https://github.com/daostack/common-backend/issues/1174

was this tested and not working? if so it should be re-opened as a bug

if not, please avoid opening already completed tasks as blockers and high priority tags

if there are existing cards in the systems they won't have the full name in the metadata
