### ISSUE TITLE
Extend User card info

### ISSUE THREAD

**Issue by MeyerPVKernelics** [daostack/common-backend#1199]
User Card also should contain
- Cardholder name
- Expiration Date
According the design
![Screenshot 2022-03-14 at 13 45 58](https://user-images.githubusercontent.com/92447173/158157086-9e178b6c-47fd-4b67-8bee-5ec5dca98093.png)

https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/6033f34bbd2b1510de2b27ee

**Comment by ariel-dao** [comment]
@MeyerPVKernelics @watchtower314 have you read this ?
https://github.com/daostack/common-backend/issues/1195
same task...
