### ISSUE TITLE
Request to join - user is stuck after the credit card details step

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1203]
Tested on Staging iOS version 1.10.9 (12-309)
Tested on Staging Android version v1.0 (393)

Steps to reproduce:
1. Join a common (verify user has not filled credit card details )
2. navigate to the screen of the credit card details
3. add details
4. Click on continue

Actual results:
user is stuck after the credit card details step

https://user-images.githubusercontent.com/69141571/158230253-7830126c-fb9d-40b7-9ed2-dde318069855.mp4

Expected results:
user should pass this step and becomes a member

**Comment by ariel-dao** [comment]
BE log check found no issues in the process

**Comment by MeyerPVKernelics** [comment]
Cannot reproduce

Most likely internet connection related.

**Comment by yanivi71** [comment]
Cannot reproduce
Closing this issue
