### ISSUE TITLE
Codebase refactoring using MVC-pattern (by each feature)

### ISSUE THREAD

**Issue by SobolevYuri** [daostack/common-backend#1207]
features list:
- [x] common (#1208)
- [ ] event
- [ ] payoutLogs
- [x] subscriptions
- [ ] commonEditHistory
- [ ] permissions
- [x] users
- [ ] metadata
- [x] proposals
- [ ] moderation
- [ ] reports
- [ ] discussion
- [ ] notification
- [ ] discussionMessage
- [ ] payments

**Comment by ariel-dao** [comment]
@SobolevYuri payoutLogs, commonEditHistory and metadata can be left as is for now, I think we can merge them into existing functions, I don't see a reason for them to have a separate function as they are very specific on the functionality

**Comment by ariel-dao** [comment]
mostly refactored in governance migration
