### ISSUE TITLE
User Stuck after submitting Payment details Form

### ISSUE THREAD

**Issue by MeyerPVKernelics** [daostack/common-backend#1211]
**Preconditions**:
 I already had a card, but I deleted it directly through the firestore and tried to make a request to join to Common ( 20c97f59-d176-41a5-9cfa-1b31b017718f )
 
1. Enter valid card Details
![Screenshot 2022-03-17 at 14 58 57](https://user-images.githubusercontent.com/92447173/158804887-cdf26e06-c39c-44b5-8f1a-a8e69d8ab425.png)
2. Click on submit button
![Screenshot 2022-03-17 at 14 59 19](https://user-images.githubusercontent.com/92447173/158804874-c533c559-d82c-4997-a296-d35b5b76c996.png)

**Comment by ariel-dao** [comment]
@yanivi71 please test this feature to see if this is reproducible before we involve payme

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.9 (12-309)
Tested on Staging Android version v1.0 (393)

Cannot reproduce t now
seems like internet problem
