### ISSUE TITLE
Contribution: Initiate single / change monthly [S10-20]

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#1216]
Let users initiate single contribution and/or change monthly contribution.
- common menu options: https://zpl.io/a3mAKYN
- after choosing my contributions: https://zpl.io/r1yAYKD
- after opening monthly contribution: https://zpl.io/Z09w5Ol
- after choosing edit payment details: https://zpl.io/9qk6lBp
- edit payment details: https://zpl.io/Q0Apor4
- change monthly contribution amount: https://zpl.io/6NkAZwW
- add 'other' amount: https://zpl.io/1yk3J44 - in the case when user entered sum less than 10 ILS we should show unable 'Continue' button
- after adding 'other' monthly amount: https://zpl.io/RMgRrKg
- monthly contribution was changed pop-up: https://zpl.io/3Xkr3PQ
- 
- change one-time contribution amount: https://zpl.io/YYd5wML
- add 'other' amount: https://zpl.io/09kreNo - in the case when user entered sum less than 10 ILS we should show unable 'Continue' button
- after adding 'other' one-time amount: https://zpl.io/Amkxjw6
- one-time contribution was sent: https://zpl.io/kDBMO9L
- in case when something went wrong: https://zpl.io/wqQ5Lwj

**Comment by watchtower314** [comment]
Backend is not ready, so hiding from this sprint for now

**Comment by kazaryan-t** [comment]
Checked.
