### ISSUE TITLE
Endpoint - Leave common

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#1221]
create endpoint for exit common

**Comment by watchtower314** [comment]
@HannaMaklakova I opened a similar ticket right before you did  https://github.com/daostack/common-backend/issues/1220 ☺️

I'll remove mine and keep yours, one request though, can you make the title of the ticket the same as the title in notion, please? 
<img width="562" alt="Screen Shot 2022-03-21 at 16 08 53" src="https://user-images.githubusercontent.com/30501647/159278700-9bc96dd5-5d2d-4806-8569-cafbc64f7637.png">

**Comment by HannaMaklakova** [comment]
> @HannaMaklakova I opened a similar ticket right before you did  https://github.com/daostack/common-backend/issues/1220 ☺️
> 
> 
> 
> I'll remove mine and keep yours, one request though, can you make the title of the ticket the same as the title in notion, please? 
> 
> <img width="562" alt="Screen Shot 2022-03-21 at 16 08 53" src="https://user-images.githubusercontent.com/30501647/159278700-9bc96dd5-5d2d-4806-8569-cafbc64f7637.png">
> 
> 
> 
> 

Sure
