### ISSUE TITLE
Common - Edit common - When user click on "leave without saving" he stay at the same screen

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1225]
Tested on Staging Android version v1.0 (396)
Steps to reproduce:
1. Go to a common you created (moderator)
2. edit info and cover photo
3. change values and click on "x" or "<" (back button)
4. when pop up appear click on "leave without saving"

Actual results:
user stay at the same page
only when user click on save button he is return to common page

https://user-images.githubusercontent.com/69141571/159432367-df79e286-6479-4226-8f43-2fe627a523c9.mp4

Expected results:
User should navigate to common page and changes are not save

**Comment by yanivi71** [comment]
@watchtower314 this issue is not fixed. i still gets the same results

**Comment by kazaryan-t** [comment]
Checked
