### ISSUE TITLE
When unsigned user reports a content and the app is stuck

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1230]
tested on Staging iOS version 1.11.1 (14-314)
Tested on Staging Android version v1.0 (396)

Steps to reproduce:
1. open the app - Do not log in (user as unsigned user)
2. Go to common list
3. choose common with discussions/proposal/membership request
4. Click on the 3 dot menu (see video) 
5. click report
6. fill all the relevant field and click on report

Actual results:
there is endless loading and the app is stuck
https://user-images.githubusercontent.com/69141571/159864079-82f28a9c-f7d0-4b74-a33c-559ed05c79d6.mp4

Expected results:
unsigned user can report content , and app should stuck

**Comment by IlyaDylko** [comment]
Bug on the Backend

**Comment by ariel-dao** [comment]
@IlyaDylko does this happen only on staging or on dev too ?

**Comment by noamso1** [comment]
@yanivi71 What are you trying to report? the whole common? I only see options to report about "proposal", "discussion" and "discussionMessage".

@IlyaDylko @MeyerPV can you please specify the end-point that you use for this action?

**Comment by yanivi71** [comment]
@noamso1 these are the features that user can report:

discussions
discussion comment
proposal
proposal chat
membership request

**Comment by noamso1** [comment]
@IlyaDylko @MeyerPV can you please specify the end-point that you use for this action?

**Comment by yanivi71** [comment]
@noamso1 @ariel-dau i reopen it again. now there is error message when unsigned user reports a content
I get the error "Something went wrong"

**Comment by ariel-dao** [comment]
@yanivi71 can you add an error log?

**Comment by yanivi71** [comment]
@watchtower314 @noamso1 @MeyerPV 
now each report display "reported by anonymousness" even is the use is logged in 
![File (78)](https://user-images.githubusercontent.com/69141571/169756565-aafaf301-b77a-4d79-9921-db513a205088.jpg)

**Comment by watchtower314** [comment]
@yanivi71 the Anonymous tag is about the name of the reporter, not the name of the current user.
If I wasn't logged in and I reported something, it will save the report in the database with an anonymous user, when I log in, the report still can't know it was me who reported it, because my id was not saved in the report, because I was not logged it

**Comment by yanivi71** [comment]
@watchtower314 i mean that i get "reported by anonymousness" always even if i m login .
i was logped in and i reported a content when i m login and i get "reported by anonymousness"
