### ISSUE TITLE
Create Common - about - About field is not mandatory

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1232]
Tested on Staging iOS version 1.11.1 (14-314)
Tested on Staging Android version v1.0 (396)

Steps to reproduce:
1. Create a new common
2. enter common name 
3. Click on "Continue to funding" button

Actual results:
user proceed to funding
![image](https://user-images.githubusercontent.com/69141571/159913981-49826def-1eff-41ec-8ff7-260fc2b94473.png)

Expected results:
According to @Shaidao About Field should be mandatory too
So Common name and About fields should be mandatory for creating a common

**Comment by kazaryan-t** [comment]
Checked.
