### ISSUE TITLE
Log in with phone number - Weird error when closing the window for inserting verification code

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1235]
A weird error appears when closing the window for inserting the verification code.

![photo_2022-03-24_19-19-26](https://user-images.githubusercontent.com/68247034/159962175-09e7fbdf-e3ea-49c5-a0d8-9d6f5d5d5502.jpg)

https://user-images.githubusercontent.com/68247034/159962179-7d27f321-d557-45a7-9a74-66977d4c352a.mp4

**Comment by kazaryan-t** [comment]
Not fixed on Android.

https://user-images.githubusercontent.com/68247034/162726916-b22aa368-d51e-493e-a5d1-a5ef861ff332.mp4

**Comment by IlyaDylko** [comment]
Could not reproduce the initial issue, but fixed a bug with short country code.

**Comment by kazaryan-t** [comment]
Can we change the actual error to "Canceled"?
@IlyaDylko @HannaMaklakova 

![photo_2022-03-24_19-19-26](https://user-images.githubusercontent.com/68247034/164777446-84a38336-141e-4185-9170-da59c6b30045.jpg)
![photo_2022-04-22_21-59-42](https://user-images.githubusercontent.com/68247034/164777357-338c7c6a-d777-4358-ba9a-009aaf992667.jpg)

**Comment by HannaMaklakova** [comment]
> Can we change the actual error to "Canceled"?
> 
> @IlyaDylko @HannaMaklakova 
> 
> 
> 
> ![photo_2022-03-24_19-19-26](https://user-images.githubusercontent.com/68247034/164777446-84a38336-141e-4185-9170-da59c6b30045.jpg)
> 
> ![photo_2022-04-22_21-59-42](https://user-images.githubusercontent.com/68247034/164777357-338c7c6a-d777-4358-ba9a-009aaf992667.jpg)
> 
> 
> 
> 

We've agreed with @IlyaDylko to change it to 'something went wrong'

**Comment by yanivi71** [comment]
@IlyaDylko @HannaMaklakova the error message did not change to " 'something went wrong'"
i am moving it to sprint 12

**Comment by watchtower314** [comment]
@yanivi71 can you please provide more details about the error that you're seeing?

**Comment by yanivi71** [comment]
@kazaryan-t please explain where do u see this error

**Comment by kazaryan-t** [comment]
Irrelevant
