### ISSUE TITLE
Proposal Page - Redesign Votes and  add Abstain column

### ISSUE THREAD

**Issue by MeyerPVKernelics** [daostack/common-backend#1236]
1. Add new design for votes column and count of voted users
https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/6033e89e8154f61200c8568a
<img width="384" alt="Screenshot 2022-03-25 at 12 03 41" src="https://user-images.githubusercontent.com/92447173/160089713-5cc30f1c-3547-401b-b120-597f1d5fcaaf.png">

2. Add an icon for which column the user voted for
https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/6033e8a025bfbd10eb3c6d96

![Screenshot 2022-03-25 at 12 19 04](https://user-images.githubusercontent.com/92447173/160092136-32365b3a-11ff-46e6-a8b0-0834fd22ac25.png)
![Screenshot 2022-03-25 at 12 19 11](https://user-images.githubusercontent.com/92447173/160092168-cfdf39f8-570a-4499-94ff-23dacb667fe6.png)
![Screenshot 2022-03-25 at 12 19 17](https://user-images.githubusercontent.com/92447173/160092198-83abab70-d605-46a4-9254-51f78380dd97.png)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.11.2 (15-316)
Tested on Staging Android version v1.0 (401)
found ok
