### ISSUE TITLE
Voting Page - navigation and Tabs: All, Approved, Abstained, Rejected

### ISSUE THREAD

**Issue by MeyerPVKernelics** [daostack/common-backend#1237]
1. Added navigation to Voting Page by clicking `count of voted users` ( 75/100 votes > )
https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/6033e89e8154f61200c8568a
![Screenshot 2022-03-25 at 12 20 59](https://user-images.githubusercontent.com/92447173/160092477-5e049c33-6666-4a7e-87ba-65cbad8b7229.png)
o

2. Added Voting Page with Tabs: `All`, `Approved`, `Abstained`, `Rejected`
https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/6033e8a7e5a35512fc350beb
![Screenshot 2022-03-25 at 12 22 26](https://user-images.githubusercontent.com/92447173/160092721-562c22f9-b56b-4798-a893-ff302c845e6f.png)

https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/6033e8a9407503117a3d8c45
![Screenshot 2022-03-25 at 12 22 39](https://user-images.githubusercontent.com/92447173/160092741-e5dcf888-0fad-4079-9a35-7047d41c161e.png)

https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/6033e8a900e0392921df0e28
![Screenshot 2022-03-25 at 12 22 53](https://user-images.githubusercontent.com/92447173/160092789-e96b8984-3891-4121-8c07-c3b6e02e6584.png)

https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/6224ce9c7f1a711094a3dba0
![Screenshot 2022-03-25 at 12 23 05](https://user-images.githubusercontent.com/92447173/160092831-5dabf2b9-d39e-4146-9c7a-ac4d7b319e0f.png)

**Comment by kazaryan-t** [comment]
1. When user opens Tabs (All, Approved, Abstained, Rejected) the number of votes doesn't fit on the same line with the name of the tabs.
2. Leave only two characters after comma (for example when the number of votes is divided into three equal parts, some elements do not fit on the screen)
3. Remove border-radius from bottom corners on the voting pop-up.

![photo_2022-04-12_21-45-09](https://user-images.githubusercontent.com/68247034/163032644-05cb8a15-4b20-4890-bd82-f5327950dbaf.jpg)
![photo_2022-04-12_21-45-16](https://user-images.githubusercontent.com/68247034/163032638-af65011d-79c7-4dbd-bcf9-8cdca1f7a960.jpg)
![photo_2022-04-12_21-45-12](https://user-images.githubusercontent.com/68247034/163032641-19e99512-f438-4744-bec4-3cabd2487b0f.jpg)
![photo_2022-04-12_21-45-09](https://user-images.githubusercontent.com/68247034/163032644-05cb8a15-4b20-4890-bd82-f5327950dbaf.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.11.3 (17-317)
Tested on Staging Android version v1.0 (402)
found ok
