### ISSUE TITLE
Proposal Page - Loading bottom sheets for voting API call

### ISSUE THREAD

**Issue by MeyerPVKernelics** [daostack/common-backend#1238]
1. Add Loader for `Approve`
https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/6224d0c5e2d83e142fd2464e
<img width="387" alt="Screenshot 2022-03-25 at 12 25 58" src="https://user-images.githubusercontent.com/92447173/160093302-26512aa2-e96f-4cee-8235-2d45180d2b76.png">

2. Add Loader for `Abstain`
https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/6224d0c6f5d3c4180e1e6067
<img width="378" alt="Screenshot 2022-03-25 at 12 26 19" src="https://user-images.githubusercontent.com/92447173/160093353-c139e12c-6743-4919-81c7-1759519c2549.png">

3. Add Loader for `Reject`
https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/6224d0c7fb299d127aa1ebad
<img width="376" alt="Screenshot 2022-03-25 at 12 26 43" src="https://user-images.githubusercontent.com/92447173/160093428-83d9b7de-b1b7-46c4-b93f-e419e9aeb9af.png">

4. Add Bottom Sheet with "Vote to approve", "Vote to reject", "Vote to abstain" which opens when you click on the button.
![Screenshot 2022-03-28 at 15 21 03](https://user-images.githubusercontent.com/92447173/160396629-3141eb01-1033-4e63-b64e-71e802a010a9.png)
![Screenshot 2022-03-28 at 15 21 12](https://user-images.githubusercontent.com/92447173/160396662-9a2bafdc-02a7-45ed-a3a5-2499abcebc76.png)
![Screenshot 2022-03-28 at 15 21 22](https://user-images.githubusercontent.com/92447173/160396681-9cae2173-543a-4c5a-84ca-9317e81e3bae.png)

**Comment by yanivi71** [comment]
@MeyerPV @IlyaDylko please see issue 
https://github.com/daostack/common-backend/issues/1266

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.11.3 (17-317)
Tested on Staging Android version v1.0 (402)
found ok
