### ISSUE TITLE
Change the name of the buttons in onboarding/intro screens

### ISSUE THREAD

**Issue by lpetkov-sw** [daostack/common-backend#124]
Change the text in the action buttons in the Onboarding screens and the Intro screens for creating a common.
The new Button names should have the following behaviour:
- Button should say "Continue" and lead to the next tab. 
- The 4th and last tab should be like it is now - "Get started" which closes the intro

![image](https://user-images.githubusercontent.com/26001304/109147927-430d8700-776e-11eb-8e35-addc7227803d.png)

![image](https://user-images.githubusercontent.com/26001304/109148149-85cf5f00-776e-11eb-9a23-1cf1c1a0e14f.png)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-232)
Tested on Staging Android version 1.9.5 (4978-193)

Found OK
tested on create common
tested on open the new app for the first time

**Comment by kazaryan-t** [comment]
Tested on Production Android version 1.9.5 (4998-53)
Tested on Production iOS version 1.9.5 (4998-44)
