### ISSUE TITLE
Leave common [S11-24]

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#1244]
Let user leave common

- menu options for the common owner: https://www.figma.com/proto/QGUiojKFDQntipgkMeBEpi/%F0%9F%9F%A3-Shared---Common1?node-id=135%3A34272&scaling=min-zoom&page-id=135%3A33848
- menu options for the member: https://www.figma.com/proto/QGUiojKFDQntipgkMeBEpi/%F0%9F%9F%A3-Shared---Common1?node-id=135%3A34313&scaling=min-zoom&page-id=135%3A33848
- popup 'Are you sure?': https://www.figma.com/proto/QGUiojKFDQntipgkMeBEpi/%F0%9F%9F%A3-Shared---Common1?node-id=135%3A34350&scaling=min-zoom&page-id=135%3A33848

**Comment by HannaMaklakova** [comment]
> Let user leave common
> 
> 
> 
> @HannaMaklakova can you please provide the design

I cannot because it's still not ready from Brio

**Comment by IlyaDylko** [comment]
This task is basically a part of the https://github.com/daostack/common-backend/issues/1301 task. Which waits for the design.

**Comment by yanivi71** [comment]
@HannaMaklakova can u verify if a moderator (common owner) can have the option "Leave common".
it is weird that the common owner can leave common. i think he should have the option to delete common

**Comment by HannaMaklakova** [comment]
> @HannaMaklakova can u verify if a moderator (common owner) can have the option "Leave common". it is weird that the common owner can leave common. i think he should have the option to delete common

@yanivi71 I'll clarify and let you know then
