### ISSUE TITLE
Improve the validation of the link value field

### ISSUE THREAD

**Issue by lpetkov-sw** [daostack/common-backend#125]
The change is for the MultiLinkField component for it's second field which contains the value of the URL.
When adding links, the field should work not only for "http://" starting string, but also for 'www'. Our custom rule at the moment is checking only for 'http' . Consider using a lib/methodology for validating the URL as well.

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-232)
Tested on Staging Android version 1.9.5 (4978-193)
Not fixed.

please test these links on
1. Create a new common
2. Join a common
3. Create a new proposal


www.test.com
http://www.test.com
https://test.com
https://www.volvocars.com/il?site=google&lp=volvo.brand&utm_source=google&utm_campaig[…]ChMIz7C_m6D_6wIVZbR3Ch2POwFPEAAYASAAEgKyxvD_BwE&gclsrc=aw.ds


![Screenshot_20210309-130035_common-stg](https://user-images.githubusercontent.com/69141571/110462907-f3b64780-80d9-11eb-8393-e31a84893881.jpg)
![Screenshot_20210309-141524_common-stg (1)](https://user-images.githubusercontent.com/69141571/110462912-f5800b00-80d9-11eb-8cfd-fed7cfb20e17.jpg)

**Comment by yanivi71** [comment]
@MeyerPV 
i cannot add this like "www.test.com"
to proposal

see attached image 
![Screenshot_20210311-181555_common](https://user-images.githubusercontent.com/69141571/110818711-302ea280-8296-11eb-89b9-49dd160df544.jpg)

**Comment by yanivi71** [comment]
@MeyerPV Created proposal on android with the links  display this error at the end of the process 

![Screenshot_2021-03-15-09-53-20-166_com daostack common staging](https://user-images.githubusercontent.com/69141571/111121872-e1268d00-8575-11eb-9894-f36276420cec.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-240)
Tested on Staging Android version 1.9.5 (4978-2001)

Found OK
Tested on Create common, Create proposal, Join a Common
