### ISSUE TITLE
Discussion - comments - user avatar - clicking on the user avatar always display the profile of the same user

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1259]
Tested on Staging iOS version 1.11.1 (14-315)
Tested on Staging Android version v1.0 (396)

Steps to reproduce:
1. Go to a common with discussions
2. view a discussion with several users
3. click on the user avatar for each use

Actual results:
clicking on the user avatar always display the profile of the same user (the user who is using the phone)
https://user-images.githubusercontent.com/69141571/162624759-3e389b61-15a5-4f1c-b247-95b9b60bbd62.mp4

Expected results:
clicking on the user avatar should open the user profile page

**Comment by kazaryan-t** [comment]
Checked.
