### ISSUE TITLE
Common page - common name and tag line are display incorrectly

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1264]
Tested on Staging Android version v1.0 (401)

Steps to reproduce:
1. open the app
2. go to common list
3. choose any common 

Actual results:
 It seems that the common name and tag line are display incorrectly. They moved down
![Screenshot_2022-04-11-13-56-33-454_com daostack common staging](https://user-images.githubusercontent.com/69141571/162726977-f24d23c1-c699-4b9b-9c70-e8ff06fc6fed.jpg)

Expected results:
Common name and tagline should be centered

**Comment by kazaryan-t** [comment]
Checked.
