### ISSUE TITLE
Request to join - endless loading when user request to join

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1265]
Tested on Staging Android version v1.0 (401)

Steps to reproduce:
1. Request to join a common
2. fill all the relevant details
3. choose contribution and click on continue

Actual results:
endless loading-see attached file
https://user-images.githubusercontent.com/69141571/162732453-1b24a107-f6dc-4d4b-8e2a-06ac667b5f45.mp4

Expected results:
user is able to join a common

**Comment by kazaryan-t** [comment]
Checked.
