### ISSUE TITLE
Make links clickable & text copiable in chat and other pages

### ISSUE THREAD

**Issue by lpetkov-sw** [daostack/common-backend#127]
Basically, for all user-generated texts (discussions, comments, common agenda, etc) - 

- Users should be able to copy the text
- If there are links (URL's), they should be clickable.

This should not apply to other text, like the app's titles, explanations, etc.

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-233)
Tested on Staging Android version 1.9.5 (4978-194)
