### ISSUE TITLE
Votes - The header title is break line

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1270]
Tested on Staging Android version v1.0 (401)

Steps to reproduce:
1. Go to a common with proposals
2. View proposal
3. Click on XX/YY votes
4. look at the tab header title 

Actual results:
The header title is break line
![Screenshot_2022-04-12-10-11-22-976_com daostack common staging](https://user-images.githubusercontent.com/69141571/162902439-d5d1a32e-45ac-4884-958d-d2dea1d3d2a9.jpg)
![Screenshot_2022-04-12-10-12-02-716_com daostack common staging](https://user-images.githubusercontent.com/69141571/162902942-3608d490-7cf0-45b5-88fe-5762199e76d8.jpg)

Expected results:
The header title should not break
Note: should be implemented on votes in membership request

**Comment by kazaryan-t** [comment]
The number of votes is not displayed when the tab is open.
![photo_2022-04-22_20-56-18](https://user-images.githubusercontent.com/68247034/164768754-22a62b7d-4eb3-4f7d-a71c-73c3e886a270.jpg)
![photo_2022-04-22_20-56-20](https://user-images.githubusercontent.com/68247034/164768761-ddadbf3c-3c46-4013-ab8a-94d3a5227c83.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.11.4 (18-318)
Tested on Staging Android version v1.0 (404)
found ok
