### ISSUE TITLE
Create common - monthly - personal contribution - user is stuck in processing your payment details

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1271]
Tested on Staging iOS version 1.11.2 (15-316)
Tested on Staging Android version v1.0 (401)

Steps to reproduce:
1. Create a common (verify user has no card details)
2. Choose monthly common
3. fill all the relevant details
4. Click on personal contribution
5. Choose amount
6. Fill card details
7. Click on continue

Actual results:
user is stuck in processing your payment details. but the common was created with the contribution.
This does not happens when user has card details in the db. see attached video

https://user-images.githubusercontent.com/69141571/162923188-67609f99-9a44-4a00-8e5d-eaaaca172231.mp4

Expected results:
user should be able to go to the common or share it with others

**Comment by ariel-dao** [comment]
@noamso1 env: staging
