### ISSUE TITLE
personal contribution - wrong screen title

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1273]
Tested on Staging iOS version 1.11.2 (15-316)
Tested on Staging Android version v1.0 (401)

Steps to reproduce:
1. Create a new common
2. navigate to personal contribution
3. look at the screen title

Actual results:
The title is membership request instead of "Personal contribution"
![image](https://user-images.githubusercontent.com/69141571/163139179-940eab49-da23-49bd-894c-f857c614eefe.png)

Expected results:
Tittle should be  "Personal contribution"

**Comment by kazaryan-t** [comment]
@HannaMaklakova 
**Need to discuss:** maybe we need to remove one title "Personal contribution"

![photo_2022-04-22_21-03-13](https://user-images.githubusercontent.com/68247034/164769661-1330a8cd-dfab-4309-a92f-cb73bd1ff856.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.11.3 (17-317)
Tested on Staging Android version v1.0 (402)
the title is changed to personal contribution
@HannaMaklakova please comment on @kazaryan-t  comment above

**Comment by HannaMaklakova** [comment]
> @HannaMaklakova 
> 
> **Need to discuss:** maybe we need to remove one title "Personal contribution"
> 
> 
> 
> ![photo_2022-04-22_21-03-13](https://user-images.githubusercontent.com/68247034/164769661-1330a8cd-dfab-4309-a92f-cb73bd1ff856.jpg)
> 
> 

Need to remove the small one
