### ISSUE TITLE
Personal - the screen rout is broken

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1274]
Tested on Staging iOS version 1.11.2 (15-316)
Tested on Staging Android version v1.0 (401)

Steps to reproduce:
1. Create a new common
2. navigate to personal contribution
3. look at the rout on the top screen

Actual results:
the screen rout is broken
![image](https://user-images.githubusercontent.com/69141571/163139619-b88dbec3-e019-4469-9531-d7e0eefdd02e.png)

Expected results:
Should be a design for this rough please take the design images

**Comment by kazaryan-t** [comment]
Checked.
