### ISSUE TITLE
Common Card - in Explore [S12-03]

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#1281]
**Common card (in explore) should include the followings**
https://www.figma.com/file/9fox8n9BHoqMSTzttXvkWe/?node-id=932%3A25546

1. **Title**
2. **Subtitle (short version description)**
3. **Common background image**
4. Recent activity: “Active: 2hrs ago”, “Active: 3d ago”, etc.
5. Stats
    1. **Members (Number)**
    2. **Raised** (Number in shekels)
    3. Balance (Number in shekels) 
    4. Proposals (Number of proposals that were created)
    5. Discussions (Number of discussions that were created) 
    6. Messages (Number of Messages)
https://www.figma.com/proto/9fox8n9BHoqMSTzttXvkWe/%F0%9F%9F%A9-Dev---Common-v1.0---Mobile-App?node-id=932%3A25549&scaling=min-zoom&page-id=932%3A25546

**Comment by IlyaDylko** [comment]
Waiting for backend.
https://github.com/daostack/common-backend/issues/1307

**Comment by IlyaDylko** [comment]
Need to update db. Noam is notified.

**Comment by yanivi71** [comment]
@IlyaDylko 
please see this issue
https://github.com/daostack/common-backend/issues/1334
