### ISSUE TITLE
Log in - Incorrect icon when logging in via FB or phone number

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1288]
Tested on iOS v 1.11.2 (15-316)
Tested on Android v 1.0 (401)
Designs -  https://zpl.io/z85jz07, https://zpl.io/wqQglZJ

When logging in via FB or with a phone number, the google icon and the email are displayed under the users First and Last name.

https://user-images.githubusercontent.com/68247034/164181840-644425e0-d2fb-4a70-a636-6f00645576dc.mp4

**Comment by MeyerPV** [comment]
The user was created before the introduction of the feature

**Comment by kazaryan-t** [comment]
checked.
