### ISSUE TITLE
Edit rules - No Add rule button after adding a rule

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1291]
The button "Add rule" does not appear after adding the rule to the common.

https://user-images.githubusercontent.com/68247034/164278861-4ee06c77-08fd-4b98-bb2d-6cfbd694a727.mp4

**Comment by MeyerPV** [comment]
@kazaryan-t 
Also fixed design
![Screenshot 2022-04-25 at 10 58 30](https://user-images.githubusercontent.com/35873164/165036517-731222d7-1a14-4e9e-b636-db40e4699d8c.png)

Add button appears only if all required fields are not empty
![Screenshot 2022-04-25 at 10 58 42](https://user-images.githubusercontent.com/35873164/165036536-3f38bcd0-af36-445c-9115-5f8d9916fac0.png)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.11.4 (18-318)
Tested on Staging Android version v1.0 (404)
found ok
