### ISSUE TITLE
Create "verification failed" for PayMe sellers

### ISSUE THREAD

**Issue by ariel-dao** [daostack/common-backend#1297]
We need a cron to check sellers in `pending` status after 7 days from creation date. (cron should run daily)

In the cron, check on PayMe if the seller is validated,
if the seller is validated, update it and omit `PAYME_SELLER_VALIDATION_APPROVED` as it is omitted in`payme/listener`. 

if the seller is not validated, remove `bankAccountDetails` (set to `null`) from the `seller` and emit a notification + email to prompt the user to re-upload the documents.

The documents need to be validated and sent through the same endpoint as it is sent when the user adds the bank account details, but there should be a variable to state that the update is also for the seller and not just the bank account details (default behavior).

When the seller documents are re-uploaded, they should be sent using `business/uploadSellerFiles`.

- known bug: `uploadSellerFiles` is pulling the bankAccountDetails from the bank account details collection and not from the seller, this should be fixed in this PR.

We also need a second cron similar to `checkInvoicesUploading` that will emit an event to prompt the user to re-upload the bank account details, add a `bankAccountDocsNotReuploadedNotificationsCounter` to funding proposal type to keep track. 
- Once the counter reaches 4, fail the proposal.

* Seller should have a status of `rejected due to bad bank account details` or something similar to indicated that the seller validation failed and is pending for new bank account details
* I think that the proposal funding process stage can be left at `PENDING_SELLER_APPROVAL`, if the user won't upload the docs for 4 weeks the proposal will just fail, and if the user will upload and the seller will be approved the proposal will continue.

**Comment by ariel-dao** [comment]
@MicheleFarhi @Shaidao We need to know which variables to send to the email template, and we also need to know what text to write in the notification

email template on sendgrid: `PAYME_SELLER_VALIDATION_REJECTED_USER_EN`

@roienatan we need to know which link to send in the notification and email

**Comment by ariel-dao** [comment]
`PAYME_SELLER_VALIDATION_WARNING_USER_EN` needs to be added to sendgrid with template @Shaidao @MicheleFarhi

**Comment by MicheleFarhi** [comment]
> `PAYME_SELLER_VALIDATION_WARNING_USER_EN` needs to be added to sendgrid with template @Shaidao @MicheleFarhi

This is the template - "Payme seller validation failed - User - EN"
Template ID: d-85858b97406e4c358f4e19c220ee1dba

These are the parameters -
    "proposerName"
    "addBankAccountLink"

@ariel-dao

**Comment by Shaidao** [comment]
כפי שהצעתי קודם צריך מסמך שכולל את כל האימיילים האלה ושכל מי שמעורב (פיתוח, מוצר, קשרי לקוחות) יוכל לגשת אליו ולהשלים מה שצריך

Shai Schwartz

**Comment by ariel-dao** [comment]
> כפי שהצעתי קודם צריך מסמך שכולל את כל האימיילים האלה ושכל מי שמעורב (פיתוח, מוצר, קשרי לקוחות) יוכל לגשת אליו ולהשלים מה שצריך
> 
> Shai Schwartz
> 
> > On 17 May 2022, at 22:27, MicheleFarhi ***@***.***> wrote:
> > 
> > ﻿
> > PAYME_SELLER_VALIDATION_WARNING_USER_EN needs to be added to sendgrid with template @Shaidao @MicheleFarhi
> > 
> > This is the template - "Payme seller validation failed - User - EN"
> > Template ID: d-85858b97406e4c358f4e19c220ee1dba
> > 
> > These are the parameters -
> > "proposerName"
> > "addBankAccountLink"
> > 
> > @ariel-dao
> > 
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you were mentioned.
> 

אחלה, תרים את זה ותעביר אלינו לפיתוח? כל המיילים בסנדגריד

**Comment by MicheleFarhi** [comment]
אני עובדת על זה
