### ISSUE TITLE
Common - Proposal history - A white screen appears when user opens proposal history screen.

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#130]
Tested on Staging iOS version 1.9.5 (4978-224)
Tested on Staging Android version 1.9.5 (4978-185)

Steps to reproduce:
1. Open Common "insomania" (last on the list of featured)
2. Go to the History tab
3. Click "View proposal"

Actual result: 
A white screen appears.

Expected result:
The proposal screen should be displayed.

https://user-images.githubusercontent.com/68247034/109272360-d227a700-7821-11eb-86c7-5154d3abbdce.mp4

**Comment by lpetkov-sw** [comment]
I checked that issue together with @yanivi71 and he confirmed it's not happening for new proposals currently in our staging version. I think that problem is related with a bug that we had in the past but it's already fixed.

**Comment by BigRomanov** [comment]
We should display a message saying: "This message was deleted" or something like this in case the message is no longer available

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Verified on staging- old proposal has white screen.
i have tested new proposal with images and and view proposal works fine
