### ISSUE TITLE
Sort commons in Explore page [S12-02]

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#1300]
Sorting common in explore by the following SCORE formula calculation of: 

- Number of members*100,
- balance in shekels *20,
- Raised in shekels *5,
- Number of proposals *30,
- Number of discussions *10,
- Number of posts *1
- Last updated in days -*100
- Time since creation in days *2

Highest score first

This feature will be instead the “featured” mechanism. Hence, all public commons will be shown in the explore ordered by their scoring. 

Private commons will be shown in explore only for members (for non members they could accessed by direct link)

**Comment by IlyaDylko** [comment]
@ariel-dao I guess I can order commons from the front side, but I need this task to be done on the backend first.
https://github.com/daostack/common-backend/issues/1307
