### ISSUE TITLE
Common Menu [S11-24]

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#1301]
Each common has a user menu that includes the following (according to user access level)

for common owner: https://www.figma.com/proto/QGUiojKFDQntipgkMeBEpi/%F0%9F%9F%A3-Shared---Common1?node-id=135%3A34272&scaling=min-zoom&page-id=135%3A33848

for member of the common: https://www.figma.com/proto/QGUiojKFDQntipgkMeBEpi/%F0%9F%9F%A3-Shared---Common1?node-id=135%3A34313&scaling=min-zoom&page-id=135%3A33848

**Note**
Currently rules are removed from common so there is not 'Edit rules' option. Other edit option will be under 'Edit Agenda'

Common Menu for Common Owner:

1. Share Common
2. My Wallet - will be implemented in next sprints
3. Common Wallet - will be implemented in next sprints
4. Leave Common 
5. Edit agenda DEV: (Currently only to common owner) - currently it's implemented as 'edit info and cover photo'
7. Delete common DEV: (currently only to common owner)

Common Menu for Common Member:

1. Share Common
2. My Wallet - will be implemented in next sprints
3. Common Wallet - will be implemented in next sprints
4. Leave Common

**Comment by yanivi71** [comment]
@HannaMaklakova @IlyaDylko please see this issue
https://github.com/daostack/common-backend/issues/1333
