### ISSUE TITLE
user profile - help and  support & private policy are redirect to 404 

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1306]
Tested on production and staging

Steps to reproduce:
1. Go to user profile
2. Click on Help and support 
3. Click on private policy

Actual results:
user redirect to 404 page
![Screenshot_2022-04-27-11-52-26-080_com android chrome](https://user-images.githubusercontent.com/69141571/165480862-fdd30d4a-a582-4162-adbb-f3441d520667.jpg)

Expected results:
Help and support page should be display
private policy page should be display

**Comment by watchtower314** [comment]
@Jan-Blarky right now, in the app, we have the following links:
https://common.io/help -> should redirect to help and support (doesn't work)
https://common.io/privacy -> should redirect to privacy policy (doesn't work)
https://common.io/static/media/terms_and_conditions.56194db4.pdf -> redirects to terms and condition (this one works)


We need these links fixed, or if you can provide new links that work, please :)

**Comment by Jan-Blarky** [comment]
i think right now this task is more related to @roienatan and @andreymikhadyuk

**Comment by roienatan** [comment]
@watchtower314 @Jan-Blarky hey we a suggestion to redirect the help to the "Contact Us" form in the web and regarding the privacy policy it can be PDF just like the terms and conditions. What do you say? 

_EDIT:_ 
- This link can be used to privacy https://common.io/static/media/privacy_policy.92cbb685.pdf
- Help can also refer to the support email
