### ISSUE TITLE
Common Card - Add number of Discussions, Proposals and Messages to daos collection item

### ISSUE THREAD

**Issue by IlyaDylko** [daostack/common-backend#1307]
We have this new design. And now we should display numbers of proposals, discussions and messages before opening the common page. If we want to keep a good app performance, we should implement it on the backend side. Kinda the same as we did for number of messages for discussions.
Related to https://github.com/daostack/common-backend/issues/1281.
[https://www.figma.com/file/9fox8n9BHoqMSTzttXvkWe/🟩-Dev---Common-v1.0---Mobile-App?node-id=932%3A25546](https://www.figma.com/file/9fox8n9BHoqMSTzttXvkWe/%F0%9F%9F%A9-Dev---Common-v1.0---Mobile-App?node-id=932%3A25546)

**Comment by ariel-dao** [comment]
waiting for update from @MicheleFarhi  about the discussion messages before implementation
