### ISSUE TITLE
Excess "Request to join" button appears on the Common page.

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#131]
Tested on Staging iOS version 1.9.5 (4978-224)
iPhone 7 - display resolution - 750 x 1334 pixels

Tested on Staging Android version 1.9.5 (4978-185)
Samsung s10e - display resolution - 1080 x 2280 pixels

Steps to reproduce:

1. Open any Common from the featured list
2. Scroll down the page

Actual result:
Another "Request to join" button appears on the page.

Expected result:
It should be only one "Request to join" button on the page. https://zpl.io/bzKpDX3

https://user-images.githubusercontent.com/68247034/109272929-97723e80-7822-11eb-92c2-e4a8bd8b96b0.mp4

**Comment by lpetkov-sw** [comment]
@kazaryan-t  I remember that we had a requirement for a second button in the bottom which will appear once the first button hides because of the scroll. Are you sure we have to remove it ?

**Comment by gingervik** [comment]
@lpetkov-sw on her devices the second button is shown when the first one is still visible.
I've attached a screenshot
<img width="309" alt="Screenshot 2021-03-01 at 16 47 36" src="https://user-images.githubusercontent.com/28015224/109505677-e7186a80-7aad-11eb-9f86-32307f1f283c.png">

**Comment by yanivi71** [comment]
@kazaryan-t this is not a bug
