### ISSUE TITLE
Jumping Commons and Profile buttons

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#133]
Tested on Staging Android version 1.9.5 (4978-185)

Steps to reproduce:

1. Open the app
2. Pay attention to the Commons and Profile buttons

Actual result:
When the user opens the application, Commons and Profile buttons are situated higher than they should be displayed and then they jump down.

Expected result:
Commons and Profile buttons should be stable

https://user-images.githubusercontent.com/68247034/109278885-1d45b800-782a-11eb-854f-75bb0b228e6b.mp4

**Comment by yanivi71** [comment]
@kazaryan-t that is fixed already
