### ISSUE TITLE
Add bank account - Missing bank names in list

### ISSUE THREAD

**Issue by MicheleFarhi** [daostack/common-backend#1332]
The list of banks available is very partial and users complained their bank name is missing

See attached list of bank names and codes
https://www.ezcount.co.il/bank-numbers

Also, bank code should be automatically complete according to the bank name

<img width="300" src="https://user-images.githubusercontent.com/100122213/168141286-c64292b3-6a07-4ecc-9df7-c66ea9cface4.jpeg">

**Comment by MicheleFarhi** [comment]
See list on web 
https://github.com/daostack/common-web/pull/517
Only Israeli Banks (confirmed with Shai)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.12.1 (20-320)
Tested on Staging Android version v1.0 (408)
found ok
