### ISSUE TITLE
Common Card - Proposals - Wrong proposals number

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1334]
Tested on Staging iOS version 1.12.1 (20)
Tested on Staging Android version v1.0 (407)

Steps to reproduce:
1. go to common explorer page
2. choose a common with several proposal (see attached example)
3. enter this common
4. count the proposal in proposal + history

Actual results:
the number is incorrect - see attached images. it seem that membership request is counted as proposal
![image](https://user-images.githubusercontent.com/69141571/168442736-041f83b9-f716-47ba-b490-0edfe055f416.png)
![image](https://user-images.githubusercontent.com/69141571/168442793-70747c75-7ba5-4225-a976-9aad2eef72b1.png)

Expected results:
the number of the proposal on the common card must be resemble to the proposal number in the common.
membership request should counted as proposal

**Comment by IlyaDylko** [comment]
It seems we count all the proposals in proposalCount field. We need to filter it for only type: "join". And maybe can change the approach? Cuz if we manually remove some proposals from the db, it seems that proposalCount won't change. So we'll constantly face some unmatched values.
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/9967079/168649302-4c6e7814-169c-400f-a04b-bd7452878121.png">

**Comment by ariel-dao** [comment]
@noamso1 please check

**Comment by noamso1** [comment]
@yanivi71 @IlyaDylko @ariel-dao 
This is fixed now, in the migration script, and i ran the migration on all 3 environments. please recheck.

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.12.1 (20)
Tested on Staging Android version v1.0 (407)
found ok
