### ISSUE TITLE
Monthly contribution - Changed monthly contribution does not display in the common agenda

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1335]
The monthly contribution amount disaplayed in the Common agenda does not change, when the user changes the monthly contribution amount.

https://user-images.githubusercontent.com/68247034/168656074-ec5be82b-b970-4946-aae8-f2f3b14cc452.mp4

**Comment by MeyerPV** [comment]
What the user chooses in My Contributions - refers only specifically to him and does not affect the common itself, he has the right to decide how much money to pay.

Agenda related to Common itself

Is that right @HannaMaklakova ?

**Comment by HannaMaklakova** [comment]
> What the user chooses in My Contributions - refers only specifically to him and does not affect the common itself, he has the right to decide how much money to pay.
> 
> Agenda related to Common itself
> 
> Is that right @HannaMaklakova ?

Yes. You're right

**Comment by kazaryan-t** [comment]
@MeyerPV and @HannaMaklakova, sorry, it is my mistake. I agree with you.
The bug is irrelevant.
