### ISSUE TITLE
Proposal Approval / Declined notification [S10-23]

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#1338]
Let users know about approving of their proposals:
- push mobile notification: https://zpl.io/JEkJjNW
- approved proposal pop-up: https://zpl.io/XYDAnWX
- declined proposal pop-up: https://zpl.io/llJwRNk

**Comment by yanivi71** [comment]
@IvanSantiagoUk @watchtower314 @kazaryan-t 
Can we check this? we do not see any notification

**Comment by kazaryan-t** [comment]
1. There is no push notification on Android.
2. The text of the notification on iOS is not the same as in the design.
3. When clicking on the push notification on iOS, the system redirects user to the proposal screen (no proposal pop-up about approving or declining proposals).

![image](https://user-images.githubusercontent.com/68247034/163159989-d6ecbf63-9dea-4ae2-abe2-9281c2d11e84.png)
![16 00 01 - Approved proposal popup - Common MVP 1](https://user-images.githubusercontent.com/68247034/163160307-fdf01edd-09d0-44ef-b194-7c28fb703ab4.png)
![16 00 01 - Declined proposal popup - Common MVP 1](https://user-images.githubusercontent.com/68247034/163160325-efec6aac-b9ce-44ab-bce1-447281c930bd.png)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.11.4 (18-319)
Tested on Staging Android version v1.0 (404)

Backend is not implemented here

**Comment by kazaryan-t** [comment]
When clicking the push notification, the system redirects to the explore commons page.

https://user-images.githubusercontent.com/68247034/169215320-c3912e76-dec6-4431-bc42-8bf5b3d6f85c.mp4

**Comment by ariel-dao** [comment]
@kazarant @MeyerPV @HannaMaklakova so is there a push notification coming from back end or not? because it seems iOS gets it but android doesn't?

**Comment by yanivi71** [comment]
@ariel-dao this is still not implemented on mobile app
