### ISSUE TITLE
Main Menu restructure [S11-04]

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#1339]
We should add new format of the menu:
For general menu with general notification:
<img width="250" src="https://user-images.githubusercontent.com/87295860/169793350-e17e57e6-dd26-41ab-bd9b-e6c065010a88.jpeg">

And for common menu (in the next sprint will be released feature with counters here for each of the activities):
<img width="250" src="https://user-images.githubusercontent.com/87295860/169793671-ffe36a74-1ae0-461a-a12c-caef6cd9be23.jpeg">

**Updated**: User should can open via the menu each of the tabs option: Agenda, Proposals, Discussions, Wallet, Notifications

## **Main menu** (The menu exists, please add label)

1. Explore
2. Profile
3. Notifications (General notifications)

**Bottom fixed menu (see screenshot below)**

1. Agenda (Common landing page)
2. Proposals (unified > current proposals+history sorted by date)
3. Discussions (exists)
4. Common Wallet (Common Wallet)
5. Notifications (specific notifications for the current common)

Counters: All menu icons above will include counters for content not seen yet by the user

the whole flow: https://www.figma.com/file/9fox8n9BHoqMSTzttXvkWe?node-id=1195:28949

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.12.4 (24-321)
Tested on Staging Android version v1.0 (412)
Found OK
Counters are not display at the moment
