### ISSUE TITLE
Agenda - New UI [S12-01]

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#1340]
Let users add video, tags, images

hidden about section:
https://www.figma.com/proto/9fox8n9BHoqMSTzttXvkWe/%F0%9F%9F%A9-Dev---Common-v1.0---Mobile-App?node-id=927%3A25522&scaling=min-zoom&page-id=927%3A25444

opened about section:
https://www.figma.com/proto/9fox8n9BHoqMSTzttXvkWe/%F0%9F%9F%A9-Dev---Common-v1.0---Mobile-App?node-id=927%3A25606&scaling=min-zoom&page-id=927%3A25444

Editor mode for parsing icons: https://www.figma.com/file/9fox8n9BHoqMSTzttXvkWe/%F0%9F%9F%A9-Dev---Common-v1.0---Mobile-App?node-id=927%3A25522 

**NB!**
Please make sure that all signs and buttons are the same (size)

**Comment by watchtower314** [comment]
@HannaMaklakova Are we sure this is the Agenda screen? It looks like Common Profile, and not agenda (agenda doesn't have request to join option). It's important to know which it is, because time estimation depend on this.
(if it Common Profile, the task will take less time)

**Comment by HannaMaklakova** [comment]
> @HannaMaklakova Are we sure this is the Agenda screen? It looks like Common Profile, and not agenda (agenda doesn't have request to join option). It's important to know which it is, because time estimation depend on this. (if it Common Profile, the task will take less time)

@watchtower314 from the definition I can see that in the Agenda we have “Join Common” button (for non-members)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.12.4 (24-321)
Tested on Staging Android version v1.0 (412)
Found OK
Agenda appears first at the common profile.
the agenda contain only text and links
rules and images are not display
