### ISSUE TITLE
Upload invoices - Wrong proposal name in the push notification

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1342]
Tested on Android staging v1.0 (407)
Tested on iOS staging v1.12.1 (20)

Wrong proposal name in the push notification "You haven't uploaded the invoices" appears.

![photo_2022-05-19_07-43-21](https://user-images.githubusercontent.com/68247034/169208054-f5b97ad4-33f3-465b-8341-5ee2bf795c32.jpg)

**Comment by noamso1** [comment]
@ariel-dao why in functions/src/shared/interfaces/proposals/IFundingRequestProposal.ts we have "description" with an OR option?

**Comment by ariel-dao** [comment]
@noamso1 I'm not sure what is the context. Please send specific details to me in private (slack)

**Comment by ariel-dao** [comment]
@yanivi71 please retest
