### ISSUE TITLE
Discussion - Add space to a New Discussion page name

### ISSUE THREAD

**Issue by kazarant** [daostack/common-backend#1345]
Tested on Android staging v1.0 (407)
Tested on iOS staging v1.12.1 (20)

Need to add space to a New Discussion page name.

![photo_2022-05-19_10-32-20](https://user-images.githubusercontent.com/105843229/169237109-b96bc76c-28f3-4af9-b0b0-bd72c7b5a8e3.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.12.1 (20-320)
Tested on Staging Android version v1.0 (408)
found ok
