### ISSUE TITLE
Migrate existing commons to new governance common structure

### ISSUE THREAD

**Issue by ariel-dao** [daostack/common-backend#1347]
Specific list will be given by @elatif2020 @MicheleFarhi 

Test on some common in staging before moving to prod

**Comment by MicheleFarhi** [comment]
Relevant commons:
הורים למען האקלים
50b389d5-5045-4180-8e95-f38ce4d99871

מחסן כלי עבודה קשת
99e293a8-4beb-4cec-99e9-a15fb3a60909

אאוטאיירנט
28651a94-1dbf-4c9a-aa41-92394bbe9735


Relevant details to migrate:

- [x] Available Funds, Total Raised
- [x] Agenda
- [x] Members - such that all members have Senior Circle, and moderator has Leader circle

All history to be extracted to json file:

- [x] Past proposals
- [x] Discussions

@ariel-dao

**Comment by ariel-dao** [comment]
History backup: https://drive.google.com/drive/folders/11Xd6sTWSVpF1cLtg4cEcpdwSu0nqyekv?usp=sharing

**Comment by ariel-dao** [comment]
@yanivi71 @MicheleFarhi Migration on staging seems to be successful, waiting for official results before running on prod
