### ISSUE TITLE
Production: Users with more than one cards can't join

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#1351]
(This has a frontend issue also https://github.com/daostack/common-backend/issues/1352)

For users that have more than one cards, and some of them are not PAYME, user cannot join because PAYME cards was not chosen to be charged

For example, user with UID: Yu4wcBwtsgbQBDFZ9dRKha3l8mk2
has several cards, probably a different card was chosen in the `chargeBuyerTokenJoinProposal` function, so we got the following error

<img width="896" alt="Screen Shot 2022-05-22 at 14 11 24" src="https://user-images.githubusercontent.com/30501647/169692308-ee6a974d-6e95-4a3d-b073-3b574990bfb2.png">

**Comment by ariel-dao** [comment]
@yanivi71 please retest

**Comment by yanivi71** [comment]
this issue cannot be tested. now each has only one card.
