### ISSUE TITLE
Common - edit common - Save changes - Regression issues

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#136]
Tested on Staging iOS version 1.9.5 (4978-224)
Tested on Staging Android version 1.9.5 (4978-185)

Steps to reproduce:
1. Go to a common you created
2. Click on edit common menu
3. edit rules or info and cover message
4. change info and save

Actual results:
1. Error message appears when user save his changes - see attached image
"Could not update your common". But changes are saved
2. changes are saved only on the moderator view. other users does get the change (image about, & rules)

Expected results:
1. Message that changes are saved. and changes appears
2. Changes should affect all users that related to the common

![Screenshot_20210228-074457_common-stg](https://user-images.githubusercontent.com/69141571/109409207-5a7c8800-7999-11eb-8168-aef7ef6548e5.jpg)

**Comment by watchtower314** [comment]
PR: https://github.com/daostack/common/pull/944

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-231)
Tested on Staging Android version 1.9.5 (4978-192)

Found OK
Message that changes are saved. and changes appears
Changes affect all users that related to the common

**Comment by yanivi71** [comment]
Verify On Production
