### ISSUE TITLE
Main Menu - Notifications filtration

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#1364]
Re notifications in new menu: its should received for the commons' and for the general notifications separately.
[Here](https://www.figma.com/proto/9fox8n9BHoqMSTzttXvkWe/%F0%9F%9F%A9-Dev---Common-v1.0---Mobile-App?node-id=1195%3A29683&scaling=min-zoom&page-id=1195%3A28949) and [here](https://www.figma.com/proto/9fox8n9BHoqMSTzttXvkWe/%F0%9F%9F%A9-Dev---Common-v1.0---Mobile-App?node-id=1195%3A29580&scaling=min-zoom&page-id=1195%3A28949) it should be different notifications:

<img width="250" src="https://user-images.githubusercontent.com/87295860/170980911-0f62d2da-43e9-4885-9654-c22915c55425.JPG">  <img width="250" src="https://user-images.githubusercontent.com/87295860/170981263-f1eca732-7ba1-45a6-ab50-8f3e8a8225ca.JPG">

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.12.4 (24-321)
Tested on Staging Android version v1.0 (412)
Found OK
notifications are separate. 
on the main screen the notification for all common.
on the common profile screen the notification appears for the current common only

The counters are not display
