### ISSUE TITLE
Proposals, Discussions, Notifications screens - new UI

### ISSUE THREAD

**Issue by IlyaDylko** [daostack/common-backend#1373]
https://www.figma.com/file/9fox8n9BHoqMSTzttXvkWe/🟪-Common-Dev-MobileApp?node-id=1195%3A28949

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.12.4 (24-327)
Tested on Staging Android version v1.0 (414)
Closing this issue.
problem are reported in different issues
