### ISSUE TITLE
Create Common - The error appears after creating a new common and clicking on 'Go to Common' button

### ISSUE THREAD

**Issue by kazarant** [daostack/common-backend#1383]
Tested on Android - staging version v1.0 (412)
Tested on iOS- staging version v1.12.4 (24-321)

The error appears after creating a new common and clicking on 'Go to Common' button.

https://user-images.githubusercontent.com/105843229/173077950-22664c0f-56bd-4a9d-b8d1-e514b9217a89.mp4

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.12.4 (24-327)
Tested on Staging Android version v1.0 (414)
Found OK
