### ISSUE TITLE
Sign in with phone number - endless loading when entering code

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1384]
Tested on Staging iOS version 1.12.4 (24-321)
Tested on Staging Android version v1.0 (412)

Steps to reproduce:
1. Install the app
2. sign in as a new user with phone number (verify that the phone number does not exist in the DB)
3. enter phone number and click send code
4. When code is send enter the code
5. Click on submit

Actual results:
Endless loading and user cannot login. user need to close the app and reinstall it

Expected results:
once the user enter the code he should redirect to complete his details and logged in

**Comment by watchtower314** [comment]
We changed the requirement of first and last name to allow non alphabetical values

**Comment by yanivi71** [comment]
@watchtower314 I have tested it on android version v1.0 (413) and still i got endless loading and user cannot login

**Comment by watchtower314** [comment]
@yanivi71 I just tested on iOS and android, both work, can you try again and make sure you logout from your iOS before you delete the details from the backend?

https://user-images.githubusercontent.com/30501647/174593805-ebe26477-3004-485b-98f6-adf678cb5371.mov


https://user-images.githubusercontent.com/30501647/174593894-43e82986-0b73-4dda-a137-5be768958081.MP4

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.12.4 (24-327)
Tested on Staging Android version v1.0 (414)
found ok
