### ISSUE TITLE
Wallet - Production -  Pay-out - There is no pay-out line when proposal is approved by payme

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1403]
Tested on Production TestFlight version v1.10.5(9)

Steps to reproduce:
1. create a new proposal 
2. Approved the proposal 
3. Add invoice for this proposal
4. Approved the proposal by the trustee
5. Get from payme approval and that the funs have been transferred to user bank account
6. Go to Common wallet

Actual results:
proposal is accepted and money is transferred 
but there is no indication for the pay-out amount - see details below
![image](https://user-images.githubusercontent.com/69141571/174586125-57beab79-9ad8-4ebc-a75c-2b0e5c57fbb7.png)
![File (84)](https://user-images.githubusercontent.com/69141571/174586593-27278219-9265-4e70-9ddf-13c2142c7b13.jpg)

Expected results:
wallet must contain pay-out indication when proposal approved by payme and money is transferred to use account.

**Comment by ariel-dao** [comment]
@yanivi71 I'm not sure how this is related to backend, the issue is in front. are the balance or pending balance show incorrect amounts?

**Comment by HannaMaklakova** [comment]
> @yanivi71 I'm not sure how this is related to backend, the issue is in front. are the balance or pending balance show incorrect amounts?

There are no amounts in payouts as I understand from our discussion earlier on dev call
