### ISSUE TITLE
Proposals allow gov to define if at least one vote is needed to approve

### ISSUE THREAD

**Issue by ariel-dao** [daostack/common-backend#1416]
Currently a proposal with `quorum: 0, minApprove: 0` will require at least one approving vote, we need to add the ability to define in the governance if at least one vote is needed to approve a proposal.

**Comment by ariel-dao** [comment]
we'll add a property on proposal.global called "requiredAtleastOneVote" or something like that

**Comment by ariel-dao** [comment]
I think marking quorum as `>0` is cleaner

**Comment by ariel-dao** [comment]
![image](https://user-images.githubusercontent.com/89919079/183592970-dd5edc95-46aa-4e4c-9cb4-02b16edfcef2.png)
We are waiting for @Shaidao @elatif2020 to clarify if this is needed

@MicheleFarhi fyi

**Comment by MicheleFarhi** [comment]
the definition of the voting conditions:

1. We are defining the conditions to be `>=`  everywhere for the `quorum` and `min support`, and `<=` for `max against`.
2. In the MVP governance setting "Request to join" we will take min support of 10%, and quorum 0%. This will require at least one supporting vote for the proposal to pass. Also we are replacing >50% with >=51% support in all other proposals conditions.
3. In the DSG governance setting "Request to join" we will take min support 0% and quorum 0%. This will enable automatic acceptance.
