### ISSUE TITLE
Email - There is no link to support chat in email when user cancels monthly contribution

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#142]
Tested on Staging iOS version 1.9.5 (4978-225)
Tested on Staging Android version 1.9.5 (4978-186)

Steps to reproduce:
1. Cancel your monthly contribution

**Actual result:**
The user receives the email but there is no link to the support chat.

![22](https://user-images.githubusercontent.com/68247034/109500037-c39df180-7aa6-11eb-9df7-3d9889b793d7.png)

**Expected result:**
The user can quickly get the support chat link and contact us.

Email template - 
![222](https://user-images.githubusercontent.com/68247034/109500102-d6182b00-7aa6-11eb-9d68-db8edf803b66.png)

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-232)
Tested on Staging Android version 1.9.5 (4978-193)

The link to the support chat appears in the emails when the user cancels monthly contribution.

**Comment by yanivi71** [comment]
verified on production
