### ISSUE TITLE
Implement private Discussions

### ISSUE THREAD

**Issue by ariel-dao** [daostack/common-backend#1431]
https://www.notion.so/daostack/Private-Discussions-cd0f28b9a9294bf69b3113d2fa1bdbfd

Proposal and discussion are coupled, first step is to decouple them by creating a discussion when a proposal is created and link it to the proposal.

Any message that is created should always be linked to a discussion entity.

Next step is to add specific circle ids to common member entity because bitwise operations are not an option in firestore rules.

After that, when a discussion is created visibility options should be defined according to existing circles.

Frontend should support the proposal/discussion decoupling, and also when querying for discussions to show, the filter needs to fit the rules or else the query will fail. (A detailed example will be given when it's ready)

Private/public discussions are based on whether the common is public or private, so it will not be implemented for discussions, that should be tested if for some reason a user is trying to reach that discussion. If so, and he is not a member and has no circle permissions, an error should be shown. Db will throw a permission error if this occurs and it should be handled in the frontend.

**Changelog details in the PR attached**

**Comment by ariel-dao** [comment]
@andreymikhadyuk fyi

**Comment by andreymikhadyuk** [comment]
@ariel-dao FE will add changes once BE changes are done.

**Comment by yanivi71** [comment]
Tested on staging web and mobile web
private discussion was implement.
bug on functionality will be reported in different issues
