### ISSUE TITLE
Create new circle [S14-06a]

### ISSUE THREAD

**Issue by MicheleFarhi** [daostack/common-backend#1435]
https://www.notion.so/daostack/Proposal-Create-new-Circle-Multi-Circle-FE-96a08ab414894190976424471864830f

**Create new circle will include**

1. Name, Description
2. Allow actions
3. Allow proposals
4. Assign/remove proposal creation permission
5. Weight in existing proposals (optional/0%) - voting power
6. Assign/remove proposal global definition

**Comment by andreymikhadyuk** [comment]
@MicheleFarhi Not sure how to verify this until we start working on FE on it.

**Comment by MicheleFarhi** [comment]
Right.
