### ISSUE TITLE
Moderation - proposal - Regular view - Hidden proposal - The proposal is not hidden

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#144]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:
1. Go to a common as moderator
2. go to proposal tab
3. click on proposal menu
4. click on hide
5. Go to the common as regular user
6. Go to the hidden proposal

Actual results:
1. The proposal is not hidden - see attached image
2. the title of the hidden proposal is not correct

Expected results:
1. The proposal should be hidden like the design - see attached image
2. The title should be "the proposal was hidden by a moderator"

![File (51)](https://user-images.githubusercontent.com/69141571/109534646-3bc6e000-7ac4-11eb-84bb-23c6cdab9bad.jpg)
![image (16)](https://user-images.githubusercontent.com/69141571/109534683-45504800-7ac4-11eb-8cc7-9ccbd840d89e.png)

**Comment by watchtower314** [comment]
@Taikaish @yanivi71 I used this design for hidden proposals (ignoring the fact that we see the countdown in my implementation, there's a ticket for that too) so which is the correct design?
![IMG_7408](https://user-images.githubusercontent.com/30501647/109778467-d6154980-7bd2-11eb-9b42-13422fc9ad04.PNG)

**Comment by watchtower314** [comment]
fix in pr: https://github.com/daostack/common/pull/949

discussions
<img width="726" alt="Screen Shot 2021-03-03 at 10 51 43" src="https://user-images.githubusercontent.com/30501647/109832716-a08e5180-7c0e-11eb-87f6-611cb8ff8995.png">

proposals:
<img width="701" alt="Screen Shot 2021-03-03 at 12 27 35" src="https://user-images.githubusercontent.com/30501647/109846306-0df4af00-7c1c-11eb-869b-da343c9da935.png">

membership requests:
<img width="717" alt="Screen Shot 2021-03-03 at 12 28 00" src="https://user-images.githubusercontent.com/30501647/109846492-42686b00-7c1c-11eb-81ad-c10da01686e0.png">

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189(

Found OK
The proposal is hidden like the design 
The title is "the proposal was hidden by <moderator name>"

**Comment by yanivi71** [comment]
verified on production
