### ISSUE TITLE
Implement min fee to join in member admittance [S15-04]

### ISSUE THREAD

**Issue by MeyerPV** [daostack/common-backend#1443]
1) Member admittance governance definition will now have in the `limitations` field:
payment:
```
export const price = object({
    amount: number().min(0).required(),

    currency: string().oneOf(Object.values(CURRENCIES)).defined().required()
}).noUnknown(true)

```

```
        minFeeOneTime: price.shape({ amount: number().min(500).required() }).nullable(),
        minFeeMonthly: price.shape({ amount: number().min(500).required() }).nullable(),
        paymentMustGoThrough: boolean().required()
```

When creating a common, the default values will be provided by the governance, i.e:
```
        minFeeOneTime: null
        minFeeMonthly: {amount: 500, currency: ILS}
        paymentMustGoThrough: false
```
**there is not amount: 0, proposal min fees are either min 500 or the entire object is null**

But the common creation endpoint will accept those arguments as optional (parameters on `memberAdmittanceOptions` object) if a founder wants to set different rules.

2) When creating a member admittance proposal, the min fee must be reached for both types (`minFeeOneTime`, `minFeeMonthly`).
This is done using `feeMonthly` and `feeOneTime` when creating a new member admittance proposal.
- if there is a min fee (one time or monthly > 0) and `paymentMustGoThrough` is `true`, the user will need to have card attached to his `userId` as this will be checked before creating the proposal. (This step can be done prior to creating the proposal itself)

3) `CONTRIBUTION_SOURCE_TYPE` - removed `JOIN_PROPOSAL`, will now have instead `MEMBER_ADMITTANCE`

4) update subscription will now receive price (amount, currency) instead of amount

5) payments and subscriptions will have a required `commonId` field

6) subscription metadata removed, will contain required `commonId` field

**Comment by ariel-dao** [comment]
This task requires a migration:
1) governance (member admittance) needs to have rules set
2) amount needs to be migrated to unified `price: {currency, amount}` - Payment amount will now be called price for unification
3) payments and subscriptions will have a required `commonId` field
4) subscription metadata removed, will contain required `commonId` field
