### ISSUE TITLE
Moderation - proposal - hide proposal does not contain icon

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#145]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:

1. Go to a common as moderator
2. go to proposal tab
3. click on proposal menu

Actual results:
Hide does not contain icon -see attached image

Expected results:
Hide should contain icon - see attached image
![File (52)](https://user-images.githubusercontent.com/69141571/109535936-cd831d00-7ac5-11eb-8c7e-c8f98b18aa83.jpg)
![image](https://user-images.githubusercontent.com/69141571/109536073-f1def980-7ac5-11eb-8eb6-8ed3098c5f91.png)

**Comment by watchtower314** [comment]
No icon from brio yet

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Found OK.
Hide has icon

**Comment by kazaryan-t** [comment]
Tested on Production Android version 1.9.5 (4998-53)
Tested on Production iOS version 1.9.5 (4998-44)
