### ISSUE TITLE
Implement Circle hierarchy

### ISSUE THREAD

**Issue by ariel-dao** [daostack/common-backend#1453]
https://www.notion.so/daostack/Circle-hierarchy-BE-03cb6686e81a410eb92f06604e6ad120

```
Supporters | 0
Followers | 0
Voters | 1
Team | 2
Leaders | 3

Project1 | 1, 2, 3 
Project2 | 1, 2 
```
```
userX - circles: [voters, project2] → derived: [supporters, followers, voters, project2]

userY - circles: [team] → derived: [supporters, followers, voters, team]

userZ - circles: [leader] → derived: [supporters, followers, voters, team, project2]

userA - circles: [project2] → derived: [supporters, followers, project2]
```

The hierarchy should imperative based on a new field inside each circle.

Note: this new field will probably be an array of indexes that has exclusion logic based on the feature definition, and the indexes that relate to the hierarchy are **unrelated** to the indexes used to derive the binary number for voting calculation.

**Comment by andreymikhadyuk** [comment]
This ticket can be moved to `Verified` once https://github.com/daostack/common-web/issues/861 is moved there.
