### ISSUE TITLE
Sub-common doesn't have members after creation

### ISSUE THREAD

**Issue by andreymikhadyuk** [daostack/common-backend#1458]
I do not have any errors. Just tried to create a sub-common and I see that there are no members in it.
Sub-common id: `32cada23-5e0b-4c92-8a13-455e36ee709b`.
![image](https://user-images.githubusercontent.com/29727923/191971120-da8537a7-3b7a-44ef-bd83-a84436766a5e.png)

**Comment by ariel-dao** [comment]
fixed in https://github.com/daostack/common-backend/commit/fbf44f001c6bdfb1573c314d0f6a46c581199bb4

**Comment by watchtower314** [comment]
Tested and verified

**Comment by andreymikhadyuk** [comment]
Now I am a member of sub-common after creating it.
