### ISSUE TITLE
More emails to support [S16-10]

### ISSUE THREAD

**Issue by MicheleFarhi** [daostack/common-backend#1459]
https://www.notion.so/daostack/More-emails-to-support-711502bdb8ef4305862dadfc13372fdd

send emails to [support@common.io](mailto:support@common.io) on the following events:

- [x]  A user completed the supporters flow (d-86b82e4bcda346a7a29ce7601d642def
- [x]  A new user joined a common
- [x]  A proposal (of any kind) was approved (Template : d-9ac1aaf2367c478c9b66815c0ea6acea)
- [x]  A user made a contribution (one-time\monthly) to a common

**Comment by ariel-dao** [comment]
@Shaidao fyi we don't have any mails that are being sent when any proposal type other than member admittance and funds allocation are accepted/rejected.

**Comment by ariel-dao** [comment]
@andreymikhadyuk We have no indication on backend if a user completed a supporters flow, what is the indication for it?
