### ISSUE TITLE
Moderation - proposal - Show proposal does not contain icon and color

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#146]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:

1. Go to a common as moderator
2. go to proposal tab
3. go to hidden proposal
4. click on proposal menu

Actual results:
Show does not contain icon and does not contain the correct color -see attached image

Expected results:
"Show" should contain icon and correct color - see attached design image
![File (53)](https://user-images.githubusercontent.com/69141571/109537630-c52be180-7ac7-11eb-91b8-b52092bba18a.jpg)
![image](https://user-images.githubusercontent.com/69141571/109537868-120fb800-7ac8-11eb-8371-b91b730fe7fa.png)

**Comment by watchtower314** [comment]
Yes, brio hasn't provided me with the icon yet

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Found OK
"Show" should contain icon and correct color

**Comment by yanivi71** [comment]
Verified on production
