### ISSUE TITLE
Funds allocation to sub-common - email to proposer request to upload invoices

### ISSUE THREAD

**Issue by MicheleFarhi** [daostack/common-backend#1464]
Email indicates the user needs to upload invoices.

![Image](https://user-images.githubusercontent.com/100122213/193140401-f07fc07b-2f4b-45b9-b545-c16055927e1e.png)

When clicking on link - 

> Invoices upload is not available yet

![Image](https://user-images.githubusercontent.com/100122213/193140371-2a05d585-e3d3-4c31-ac5e-50b897e66c47.png)

**Comment by ariel-dao** [comment]
https://github.com/daostack/common-backend/commit/b2d0a2aebf10621dfc7f1fffe20a4d75adf9727b

**Comment by andreymikhadyuk** [comment]
@MicheleFarhi @ariel-dao what is the proper way of testing this ticket?

**Comment by ariel-dao** [comment]
Create a funds allocation proposal to a different member than proposer, he should get the email instead of the proposer.

**Comment by MicheleFarhi** [comment]
> @MicheleFarhi @ariel-dao what is the proper way of testing this ticket?

- Create proposal: funds allocation to sub-common
- Approve proposal

Expected results:
- Funds moved from common's balance, to sub-common's balance
- **No** request to upload invoices should occur (not by mail, not by notification pop-up)

**Comment by andreymikhadyuk** [comment]
@MicheleFarhi @ariel-dao 
✅ Funds were successfully moved.
✅ I didn't get the notification in the web app after approval.
❌ But I got email that I need to upload invoices:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/29727923/197770511-cfd60eaf-0417-43d0-b8c2-4975effbd1dc.png">

**Comment by MicheleFarhi** [comment]
@andreymikhadyuk 
Could you try it again?

I tried to move funds to sub-common (on staging), 
https://web-staging.common.io/proposals/7d0785d8-2ceb-4927-bf7a-9f7199f6a589

and got a mail like this


![Image](https://user-images.githubusercontent.com/100122213/198204623-6e5429f0-74e2-4217-9da6-0ee453b5467f.png)

(no request to upload invoices)

**Comment by ariel-dao** [comment]
That's the correct email.
