### ISSUE TITLE
Moderation - proposal - Hide - When user click on  hide proposal menu does not display 

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#147]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:

1. Go to a common as moderator
2. go to proposal tab
3. click on proposal menu
4. click on hide

Actual results:
the proposal is hidden
no menu for hidden reason 

Expected results:
Menu for hidden proposal should appear - see attached image
![image](https://user-images.githubusercontent.com/69141571/109541737-ce6b7d00-7acc-11eb-9bb0-ba4a16acb08c.png)

**Comment by watchtower314** [comment]
I spoke with Tai about this, the hide option should only allow hiding, and not hide & report @yanivi71
