### ISSUE TITLE
Common unstructured rules - have no order

### ISSUE THREAD

**Issue by MicheleFarhi** [daostack/common-backend#1470]
Since the unstructured rules have no order in DB - they appear in the app in a different order every time.

See example here (on staging https://web-staging.common.io/commons/05548c5d-e4e7-4cf1-a839-3b831fdfb1cd)

in membership request:

![Image](https://user-images.githubusercontent.com/100122213/194948275-9c563c06-f78e-4b8d-b00a-49b2ece960d1.png)

in membership request (on mobile):

![Image](https://user-images.githubusercontent.com/100122213/194948389-0cfa7d88-9e2b-4c2e-a1df-729d56d85fa1.PNG)

in supporters flow:

![Image](https://user-images.githubusercontent.com/100122213/194948307-fde6554e-bec6-4fa3-9774-8ed84346cc33.png)

**Comment by ariel-dao** [comment]
@andreymikhadyuk I'll change the unstructured rules to be an array, can we open a task on FE for this please?

**Comment by MicheleFarhi** [comment]
Tested on FE via https://github.com/daostack/common-web/issues/893
Found OK
