### ISSUE TITLE
Trustee reports - not working in Production

### ISSUE THREAD

**Issue by MicheleFarhi** [daostack/common-backend#1485]
Tested on trustees site on **Production** - downloads a corrupted zip file of 2kb that cannot be opened
Tested on staging - and it's corrupted as well

Original spec for reports:

https://www.notion.so/daostack/Reports-43c8f5550273456d8b6fb74d42609fcb

**Comment by andreymikhadyuk** [comment]
@ariel-dao Cannot understand why I get 401 error from the report downloading endpoint.
