### ISSUE TITLE
Create update unstructured rules endpoint

### ISSUE THREAD

**Issue by ariel-dao** [daostack/common-backend#1489]

**Comment by ariel-dao** [comment]
@elatif2020 @MicheleFarhi Who should be allowed to update the common? we'll need to add it to the templates and migrate the users

**Comment by MicheleFarhi** [comment]
I suggest we keep it identical to permissions to update agenda, for now.

**Comment by ariel-dao** [comment]
@MicheleFarhi So I'll just use the permission for update agenda for the unstructured rules
