### ISSUE TITLE
Moderation - proposal - regular view - menu title is incorrect

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#149]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:

1. Go to a common as regular user
2. go to proposal tab
3. click on proposal menu

Actual results:
"Moderator tool" title appear
see attached image

Expected results:
Title should be "Options" only

![Screenshot_2021-03-01-21-11-24-755_com daostack common staging](https://user-images.githubusercontent.com/69141571/109546543-0675be80-7ad3-11eb-8175-cc769c99e98a.jpg)

**Comment by watchtower314** [comment]
pr: https://github.com/daostack/common/pull/949

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Found OK
Title is options on regular users

**Comment by kazaryan-t** [comment]
Tested on Production Android version 1.9.5 (4998-53)
Tested on Production iOS version 1.9.5 (4998-44)
