### ISSUE TITLE
Moderation - proposal - regular view - report - wrong screen is display

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#150]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:

1. Go to a common as regular user
2. go to proposal tab
3. click on proposal menu
4. Click on Report

Actual results:
wrong screen appears (look like it display moderator screen)
see attached image
![Screenshot_2021-03-01-21-18-28-664_com daostack common staging](https://user-images.githubusercontent.com/69141571/109547337-ed214200-7ad3-11eb-9013-3e3a41c1b804.jpg)

Expected results:
Design screen should appears - See attached image
![image](https://user-images.githubusercontent.com/69141571/109547530-248fee80-7ad4-11eb-844e-26df3d752140.png)

**Comment by watchtower314** [comment]
@Taikaish should we have the same reporting "problems" for both proposals and discussions?

**Comment by Taikaish** [comment]
It's the same "problem", but we have one additional "problem" when it's a proposal or membership request.
This is "Breaks common agenda" but I asked brio to update it to: "Violates the Common agenda"
@watchtower314

**Comment by watchtower314** [comment]
pr: https://github.com/daostack/common/pull/949

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Found ok
Screen are resemble for regular user and moderator

**Comment by yanivi71** [comment]
Verified on Production

**Comment by yanivi71** [comment]
Verified on Production
