### ISSUE TITLE
Moderation - comments - The user name does not display when comment is reported

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#151]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:

1. Go to a common as regular user
2. go to discussion tab
3. Choose post
4. Choose comment
5. Report on this comment
6. enter with other user to the same comment

Actual results:
The user name does not display when comment is reported . see attached images

Expected results:
The user name should be display 
![Screenshot_2021-03-02-09-30-48-888_com daostack common staging](https://user-images.githubusercontent.com/69141571/109614074-c64a2680-7b3a-11eb-8bda-792b5e57c297.jpg)
![Screenshot_20210302-093015_common-stg](https://user-images.githubusercontent.com/69141571/109614077-c77b5380-7b3a-11eb-9289-32f4bbc21d0c.jpg)

**Comment by watchtower314** [comment]
@yanivi71 i don't see the problem here actually, the scenario is-if you reported something, and you're on the app, you will see `reported by you` and not your username, other users will see your username

**Comment by yanivi71** [comment]
@watchtower314 see attached image. when i m the reporter i can see the the user name. but on the comment under , i do not see the user name. 
![image](https://user-images.githubusercontent.com/69141571/109765684-e0990880-7bfd-11eb-90ec-f2e0c8f946a1.png)

**Comment by yanivi71** [comment]
Not a bug @watchtower314
