### ISSUE TITLE
Moderation - Post - comments - moderator view - moderator cannot hide comments

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#152]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:

1. Go to a common as a moderator
2. go to discussion tab
3. Choose post
4. Choose comment
5. Hide this comment

Actual results:
moderator cannot hide comments
only report option is display

Expected results:
moderator must be able to hide comments

**Comment by watchtower314** [comment]
@yanivi71  Could not reproduce, this is the current behaviour:
<img width="681" alt="Screen Shot 2021-03-04 at 2 29 18" src="https://user-images.githubusercontent.com/30501647/109927137-c01a8e00-7c91-11eb-84ad-01f36899683f.png">

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Found OK
moderator is able to hide comments

**Comment by kazaryan-t** [comment]
Tested on Production Android version 1.9.5 (4998-53)
Tested on Production iOS version 1.9.5 (4998-44)
