### ISSUE TITLE
Impossible to enter non-integral numbers

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#155]
Tested on Staging iOS version 1.9.5 (4978-227) - iPhone 7

It is impossible to enter non-integral numbers for common contribution or proposal funding.
 
Steps to reproduce:
1. Create a Common or funding proposal.
2. Insert non-integral number to the "Minimum monthly/one-time contribution" or "Funding amount requested" fields.

Actual result:
The amount is changed automatically to the integral number.

Expected result:
The user should be able to insert non-integral numbers too.

https://user-images.githubusercontent.com/68247034/109648128-4be5ca80-7b6b-11eb-99d5-bc5c4e362a72.mp4

**Comment by watchtower314** [comment]
pr: https://github.com/daostack/common/pull/1041

![IMG_7837](https://user-images.githubusercontent.com/30501647/114296442-60c25180-9a79-11eb-8e07-9c1045911491.PNG)
![IMG_7836](https://user-images.githubusercontent.com/30501647/114296446-63bd4200-9a79-11eb-817d-cb3d420dbc1c.PNG)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-267)
Tested on Staging Android version 1.9.5 (4978-228)

Found OK
user can insert non integer numbers.
Tested on :
Create common - one time contribution
Create common - monthly contribution
Create funding proposal

**Comment by kazaryan-t** [comment]
Verified on Production.
