### ISSUE TITLE
Send email to specific recipients 

### ISSUE THREAD

**Issue by ariel-dao** [daostack/common-backend#1554]
according to https://www.notion.so/705acefe0a0f4160b7493f5b97c99aea?v=850209be578f4bf5867dabae8e86db49
@Shaidao fyi

**Comment by ariel-dao** [comment]
@elatif2020 @Shaidao All common members even if visibility settings are defined?

**Comment by elatif2020** [comment]
Good point. yes we should send the email to all the members that can see it

**Comment by ariel-dao** [comment]
https://github.com/daostack/common-backend/commit/9ebfdc44c14605774ea61eb16dba16fe65e591c4
