### ISSUE TITLE
Bug - Create a Project validation error

### ISSUE THREAD

**Issue by MeyerPV** [daostack/common-backend#1565]
![image](https://user-images.githubusercontent.com/35873164/207286257-69db9e63-0d9a-43e8-b424-26d03c503f2d.png)
![image](https://user-images.githubusercontent.com/35873164/207286275-740c17ac-0992-4875-b0b3-9aeaa5411119.png)

**Comment by ariel-dao** [comment]
https://github.com/daostack/common-backend/commit/96f15db83d520ef511f6b0d1cde7ddd931c19ec2

**Comment by elatif2020** [comment]
@MeyerPV could you verify this?
