### ISSUE TITLE
Common creation - Unnecessary error appears

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#157]
Tested on Staging iOS version 1.9.5 (4978-227)
Tested on Staging Android version 1.9.5 (4978-188)

When creating a new common, the user enters a link title, an error "Link format is invalid" appears immediately even if the user does not insert any characters to the link field (https://).

Steps to reproduce:

1. Click on the "Create a Common" button.
2. Click "Get started".
3. Fill in Common name, Tagine, About fields.
4. Insert any characters to the Link Title field.

Actual result:
An error "Link format is invalid" appears immediately.

Expected result:
An error "Link format is invalid" should appear only when the user inserts invalid characters to the link field (https://).

https://user-images.githubusercontent.com/68247034/109662619-4fce1880-7b7c-11eb-8669-eb55dc4cfc5e.mp4

**Comment by yanivi71** [comment]
@kazaryan-t this is not a bug
this is the behaviour
