### ISSUE TITLE
Trustees - Payout report fields

### ISSUE THREAD

**Issue by MicheleFarhi** [daostack/common-backend#1575]
receiver_name
receiver_email
sum_requested.amount
sum_requested.currency
bank_account_details.socialId
bank_account_details.phoneNumber
bank_account_details.gender
bank_account_details.createdAt
bank_account_details.identificationDocs.1.downloadURL
bank_account_details.streetAddress
bank_account_details.streetNumber
bank_account_details.city
bank_account_details.birthdate
bank_account_details.birthdate
bank_account_details.birthdate
bank_account_details.accountNumber
bank_account_details.country
common_name
proposal_title
approved_at
invoices_amount
invoices_links
withdrawn_at
trustee_approved_at
currency
seller.warningCounter
seller.userId
seller.status
seller.createdAt
seller.paymeSellerId

**Comment by ariel-dao** [comment]
https://github.com/daostack/common-backend/commit/9901e78464d57f9eb061250301af33be17457ff1

**Comment by andreymikhadyuk** [comment]
As I see, columns are correct in the downloaded file.
