### ISSUE TITLE
[Backend] Feed Collection Entity

### ISSUE THREAD

**Issue by MeyerPV** [daostack/common-backend#1577]
```
userId
discussionId
proposalId
createdAt
type: Proposal | Discussion ...
circleVisibility: string[]; circleIds - the same as for Discussion entity
title
```
![Screenshot 2022-12-27 at 12 27 42](https://user-images.githubusercontent.com/35873164/209644879-f72c8e44-834f-4518-9df3-8edf81225cb5.png)

**Comment by ariel-dao** [comment]
@MeyerPV I think `type` can be omitted if we have `discussionId` or `proposalId` 

Also, I think either way you'll need to read the entity so I don't think adding a `title` here would be useful, Same for `userId`.

I think the same applies to `circleVisibility` but maybe that would could be used for filtering?

**Comment by ariel-dao** [comment]
@elatif2020 @MicheleFarhi How should we approach this in retrospective for existing commons? We'll need to populate the feed collection for each common.

I think that this object might not be necessary at all if all the logic is simply reading the last 5 proposals/discussions. Do we have an actual logic to require this?

**Comment by MicheleFarhi** [comment]
Events to be represented in Feed:

- [x] All proposals
- [x] All discussions
- [x] Pay-ins
- [x] Join common / projects in common
- [x] Project creation

**Comment by ariel-dao** [comment]
- [x] Add updated at update (on common feed entity) for proposal when a vote is casted
- [x] Add optional discussion Id for every type
- [x] Change `PayIn` to include metadata
