### ISSUE TITLE
Complete Emails

### ISSUE THREAD

**Issue by MicheleFarhi** [daostack/common-backend#1578]
`Thank you for your contribution` email missing details:

> Dear , 
We appreciate your contribution of to the Wing Women. 
You may see your contribution shown in the common wallet and under Billing section in your account.
Thank you,
Wing Women

- [ ] User name
- [ ] Amount
- [ ] Link to common

`New Discussion` email to all members of the common - still missing

**Comment by ariel-dao** [comment]
@MicheleFarhi @Shaidao There is no link to common used in the email.
![image](https://user-images.githubusercontent.com/89919079/210159656-60ed552a-6987-4313-8c09-6c99fc5f7d86.png)
I've added it as `commonLink` in case you want to use it.

**Comment by ariel-dao** [comment]
fixed and pushed to prod (including discussions)
