### ISSUE TITLE
Moderation - user profile - app crashes when user click on the menu of proposal/request

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#158]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:

1. Go to user profile
2. go to proposal/membership request
3. click on the menu of the proposal/request

Actual results:
app crashes

Expected results:
menu should be open/ or maybe user should not have menu on his own proposals

**Comment by watchtower314** [comment]
pr: https://github.com/daostack/common/pull/949

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Found OK
menu is not available on his own proposals/requests

**Comment by yanivi71** [comment]
Verified on Production
