### ISSUE TITLE
Add gallery of images to entities

### ISSUE THREAD

**Issue by MicheleFarhi** [daostack/common-backend#1586]
Add array of links (so that images can be stored and links saved to entities):

- [x] Common / Project
- [x] Proposal
- [x] Discussion

**Comment by ariel-dao** [comment]
on Common / Project: `gallery`
on Discussion: `images` (it's there for sometime now, I can rename it to gallery but I think that might have unknown outcomes)
on Proposal: `images` (it's there for sometime now, I can rename it to gallery but I think that might have unknown outcomes)
