### ISSUE TITLE
Common management interface [S18-04]

### ISSUE THREAD

**Issue by MicheleFarhi** [daostack/common-backend#1587]
https://www.notion.so/daostack/Common-management-interface-8b89b5d043394d28911417f3d7f4b55f

- [x] Circles : Display circles of a common / project, Edit details, Create new circle
- [ ] Proposals : Edit setting of proposal type for a common
- [ ] Templates : Upload default governance template for a common, or a project

**Comment by ariel-dao** [comment]
@danielr18 can we close this?

**Comment by danielr18** [comment]
Yeah
