### ISSUE TITLE
User profile - membership request - the common name is missing

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#159]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:

1. Create membership request
2. Go to user profile
3. go to membership request
4. look on the request

Actual results:
the name of the common is missing - see attached image

Expected results:
The name of the common must appear

![Screenshot_2021-03-02-17-22-07-557_com daostack common staging](https://user-images.githubusercontent.com/69141571/109680504-3bdae480-7b85-11eb-9b62-400e5c93bca6.jpg)

**Comment by watchtower314** [comment]
@yanivi71  Note: This is not actually related to moderation as none of the steps include operations introduced by the moderation feature :)

**Comment by yanivi71** [comment]
@watchtower314 thanks. but still its a bug :-) . i will assign it also to @lpetkov-sw

**Comment by yanivi71** [comment]
This is not a bug
