### ISSUE TITLE
New proposal types

### ISSUE THREAD

**Issue by MicheleFarhi** [daostack/common-backend#1593]
https://www.notion.so/daostack/New-proposal-types-Team-decision-and-Quick-funding-fdf3daf3879f4bf180d89cd159d58489

- [ ] Team decision
- Like `Survey`

- [ ] Quick funding
- Like `Funds Allocation`

- [ ] Funds Allocation to 3rd party
- https://www.notion.so/daostack/Proposal-Funds-Allocation-to-3rd-party-d630124e12ff404b99b7c111f9585008

**Comment by elatif2020** [comment]
on hold
