### ISSUE TITLE
Discussion - Remove

### ISSUE THREAD

**Issue by andreymikhadyuk** [daostack/common-backend#1594]
- Can't delete discussions for proposals that has passed
- Can't delete General discussion

Use soft delete

**Comment by elatif2020** [comment]
This is an action that can be made by users with the appropriate permissions in the common to 
 "HIDE_OR_UNHIDE_DISCUSSION" or "HIDE_OR_UNHIDE_PROPOSAL" (probably Leaders)
We might have to separate it to 
1. removing a discussion 
2. removing a proposal
