### ISSUE TITLE
Discussion - Edit

### ISSUE THREAD

**Issue by andreymikhadyuk** [daostack/common-backend#1595]

**Comment by elatif2020** [comment]
Edit is an action available to the creator of a discussion\proposal.
Currently the user can only edit the content (title and description).

**Comment by pepoospina** [comment]
@elatif2020 @andreymikhadyuk, can you please elaborate on what is currently missing?

**Comment by NoamQA** [comment]
@danielr18 - the ticket is about giving an option to edit a discussion?
is there a link to a deploy preview to test it?

**Comment by ariel-dao** [comment]
@daniel18 you can deploy to dev, you have the keys for it so feel free to
deploy branches

**Comment by andreymikhadyuk** [comment]
@NoamQA It is implemented from the BE side, on the FE it is not done yet.
