### ISSUE TITLE
Moderation - unsigned user - Unsigned user can report and he gets endless loading

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#160]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:

1. Enter as unsign user or log out
2. go to and data (proposal discussion ,comments..)
3. Click on menu
4. Choose report

Actual results:
unsign user can report and get endless loading
user need to reopen the app

Expected results:
Unsign user must not able to open menu and report

**Comment by watchtower314** [comment]
- fix is in pr: https://github.com/daostack/common/pull/949

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Found OK.
Unsign user cannot report on content

**Comment by kazaryan-t** [comment]
Tested on Production Android version 1.9.5 (4998-53)
Tested on Production iOS version 1.9.5 (4998-44)
