### ISSUE TITLE
Moderation - Report - Wrong message appears when user report on content

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#161]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:

1. Go to a common as regular user
2. go to proposal tab
3. click on proposal menu
4. click on report
5. report and submit

Actual results:
The messages that display is incorrect. Note: this should be fixed on all report content (comments. post. proposals..)
see attached image

Expected results:
Should be resemble to zeplin message

![Screenshot_20210303-092918_common-stg](https://user-images.githubusercontent.com/69141571/109771035-07a70880-7c05-11eb-88b9-fcd610fb0113.jpg)
![image (17)](https://user-images.githubusercontent.com/69141571/109771023-0249be00-7c05-11eb-962c-57b032ff6409.png)

**Comment by watchtower314** [comment]
- fix is in https://github.com/daostack/common/pull/949

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Found OK
Message is resemble to zeplin design

**Comment by yanivi71** [comment]
Verified on Production
