### ISSUE TITLE
Moderation - Report option is enable to user own content

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#162]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:

1. Go to a common as regular/moderator user
2. go to proposal tab
3. click on menu of proposal that you created 

Actual results:
Report option is enable

Expected results:
Report option should be disable for user own content (menu should be active. only report should be disable)
Note: should be implemented on all user content (proposals, comments, join, post)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Report option is disable for user own content

**Comment by kazaryan-t** [comment]
Tested on Production Android version 1.9.5 (4998-53)
Tested on Production iOS version 1.9.5 (4998-44)
