### ISSUE TITLE
Refactor chat to Firebase Messaging

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1629]

**Comment by ariel-dao** [comment]
closing irrelevant for now, reopen if needed

**Comment by pepoospina** [comment]
@elatif2020, the issue with the "send message" delay will be solved using an optimistic approach. Maybe it's better to create a another new issue for this, and keep this one closed.

**Comment by elatif2020** [comment]
Agree, it was left open by mistake. I just closed it
