### ISSUE TITLE
New Project create a circle without type = "project" inside circle entity

### ISSUE THREAD

**Issue by MeyerPV** [daostack/common-backend#1638]
After creating a new project the circle is added to the governance of parent without type = `project`, but should be so.

**Comment by ariel-dao** [comment]
did you pass `  { type: "project" }  ` in your schema?

**Comment by andreymikhadyuk** [comment]
@ariel-dao I do not think so. Where should we pass it? In `circleDefinition` object?

**Comment by ariel-dao** [comment]
yes
![image](https://user-images.githubusercontent.com/89919079/218053385-ae9c0a5f-9363-4443-8c7c-4aa1fe77b574.png)

**Comment by ariel-dao** [comment]
fixed https://github.com/daostack/common-backend/commit/be74698733eb8c6306dff64645ecf98595c94932

**Comment by ariel-dao** [comment]
waiting for confirm before closing
