### ISSUE TITLE
 EditProfile: Improve with Formik and yup

### ISSUE THREAD

**Issue by MeyerPV** [daostack/common-backend#164]
Rewrite EditProfile form with `Formik` and `yup`

https://github.com/formium/formik

https://github.com/jquense/yup

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.6 (4978-272)
Tested on Staging Android version 1.9.6 (4978-233)

Found OK
The user profile behaves the same .
other tests will be verify on the regression tests

**Comment by yanivi71** [comment]
Verified on production
