### ISSUE TITLE
Vulnerability `addPayoutDocs` (probably not an issue)

### ISSUE THREAD

**Issue by pepoospina** [daostack/common-backend#1643]
The `addPayoutDocs` does not check the status of the proposal nor that the caller is the proposer. Thus, any user can upload docs to any FUNDS_ALLOCATION proposal at any time.

Not sure if this is critical, but I'd guess it's not desired. Maybe a user can change the payment bank account with this documents?

**Comment by ariel-dao** [comment]
Bank account doc addition is limited for each user, uploading payout docs can be done by different users in common as far as I remember by defintion
