### ISSUE TITLE
[Backend/Bug] Feed - Display notifications amount

### ISSUE THREAD

**Issue by MeyerPV** [daostack/common-backend#1645]
Call https://us-central1-common-dev-dea4e.cloudfunctions.net/commons/mark-feed-object-seen-for-user with

`{"feedObjectId":"4e722cd3-5a8e-49a0-85e3-12a95d7eb0df","commonId":"22a07f25-4090-4877-9aa7-49cc84b70757","lastSeenId":"2e913f34-8839-4e97-b1ff-8dad9cda2e6a","type":"discussionMessage"}`

But it not working. Also commonFeedObjectUserUnique collection is not updating after sending msg.

commonId: 22a07f25-4090-4877-9aa7-49cc84b70757.

**Comment by MeyerPV** [comment]
We should have `lastSeen` field in this collection

![Image](https://user-images.githubusercontent.com/35873164/219036798-07e1b254-04ca-4171-af8d-838686200be4.png)

**Comment by ariel-dao** [comment]
Fixed and deployed
