### ISSUE TITLE
Add governance document url field to common

### ISSUE THREAD

**Issue by andreymikhadyuk** [daostack/common-backend#1647]
Something like `governanceDocumentId?: string`.
Or it is worth to add the field to the governance itself.

**Comment by pepoospina** [comment]
I will work on this. Ok @ariel-dao?

**Comment by andreymikhadyuk** [comment]
@pepoospina Maybe it is worth to add this field to the governance itself. Decide what it is better from the BE.

**Comment by ariel-dao** [comment]
@pepoospina It was already added on https://github.com/daostack/common-backend/commit/f889da4493e41f3074c5b63c75ded48f5abcba9a

Let's keep it on the Common entity for now, changing it won't be an issue. Already on staging.
