### ISSUE TITLE
Common Edit - Project name uniqueness

### ISSUE THREAD

**Issue by andreymikhadyuk** [daostack/common-backend#1649]
During project creation we have a check for unique project names in a common, but during updating a project this check is not performed.
It should return same error code as during project creation.

**Comment by andreymikhadyuk** [comment]
@ariel-dao In `dev` env I still can update project name to the one which has another project.

parent common id: `958dca85-7bc1-4714-95bd-1fc6343f0654`
project id: `04c5b56d-0225-4166-b1f2-fa32cb435bd8`

**Comment by ariel-dao** [comment]
fixed and deployed to dev and staging

**Comment by andreymikhadyuk** [comment]
@ariel-dao
1. Correct, I get error during project editing about existing name, but could you add the error code `ArgumentDuplicatedError` as we have for project creation for the same case?
2. I started to get this error during common editing, but commons can have same names as I know (@elatif2020 correct me if I am wrong please).
3. Project names should be unique within one parent common. We can have projects with the same name if they are part of different commons (@elatif2020 correct me if I am wrong please).

**Comment by ariel-dao** [comment]
@elatif2020 Waiting for a defined set of rules for name uniqueness, will apply after we have it

**Comment by elatif2020** [comment]
> @elatif2020 Waiting for a defined set of rules for name uniqueness, will apply after we have it

Commons can have the same name, but we shouldn't allow two project with the same name and the same parent-common

**Comment by elatif2020** [comment]
@andreymikhadyuk @ariel-dao 
I see that this change have been deployed to production, and it causes an error when trying to edit the agenda of a common (via the old ui). We should fix the logic, and maybe also deploy an hotfix to production (if it's not too complicated).

**Comment by andreymikhadyuk** [comment]
@elatif2020 What error do you get?

**Comment by elatif2020** [comment]
common name Common Playground! already exists (530afd29-8508-40f5-9440-5d6a6a79b9cf)

`{"error":"common name Common Playground! already exists (530afd29-8508-40f5-9440-5d6a6a79b9cf)","errorName":"Common Error","errorId":"530afd29-8508-40f5-9440-5d6a6a79b9cf","errorCode":"GenericError","errorMessage":"Something bad happened.","request":{"id":"82767fa1-8282-4163-a70b-ce4caffc96a9","body":{"commonId":"e13b4c18-e9a9-4cad-adb8-3cde0957126a","changes":{"name":"Common Playground!","image":"https://firebasestorage.googleapis.com/v0/b/common-daostack.appspot.com/o/public_img%2Ffile_63d71192eeaf4eeb8a84a1e4ef80543e.png?alt=media&token=abc82820-0a56-4a7b-84eb-1bb9c800f0b2","byline":"Let's play common","description":"We have many test commons, but let's have one for more deep and playful testings of the usability of the app.\nSo we can try to include here:\n- Testing new features.\n- Trying to get some sense of the user experience in somehow more real scenarios.\n- Discuss our thoughts and ideas on the app and on how to improve it.\n- and probably more\nOf-course, we should be ready to be patience to some friction, of using a product which is not yet ready\n/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\","links":[{"title":"Common home","value":"https://common.io"}]}},"query":{},"headers":{"host":"us-central1-common-daostack.cloudfunctions.net","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0","transfer-encoding":"chunked","accept":"application/json, text/plain, */*","accept-encoding":"gzip, deflate, br","accept-language":"he,en-US;q=0.7,en;q=0.3","authorization":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImY4NzZiNzIxNDAwYmZhZmEyOWQ0MTFmZTYwODE2YmRhZWMyM2IzODIiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiTGF0aWYgRWxpYXoiLCJwaWN0dXJlIjoiaHR0cHM6Ly9maXJlYmFzZXN0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vdjAvYi9jb21tb24tZGFvc3RhY2suYXBwc3BvdC5jb20vby9wdWJsaWNfaW1nJTJGaW1nXzE2MDg0NjgwNjA1MTkuanBnP2FsdD1tZWRpYSZ0b2tlbj05ZmE3NDIyYS1mZTQyLTRhMWYtOTBhOC0yYmYxZmI3NzFhMTIiLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29tbW9uLWRhb3N0YWNrIiwiYXVkIjoiY29tbW9uLWRhb3N0YWNrIiwiYXV0aF90aW1lIjoxNjc1OTgyNjE3LCJ1c2VyX2lkIjoiWXU0d2NCd3RzZ2JRQkRGWjlkUktoYTNsOG1rMiIsInN1YiI6Ill1NHdjQnd0c2diUUJERlo5ZFJLaGEzbDhtazIiLCJpYXQiOjE2Nzc0MDQ1NTksImV4cCI6MTY3NzQwODE1OSwiZW1haWwiOiJsYXRpZkBkYW9zdGFjay5pbyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7Imdvb2dsZS5jb20iOlsiMTA3Mjc0MzI1NjU4MjAxODc2ODY5Il0sImVtYWlsIjpbImxhdGlmQGRhb3N0YWNrLmlvIl19LCJzaWduX2luX3Byb3ZpZGVyIjoiZ29vZ2xlLmNvbSJ9fQ.a7mnHB015MgkabFk0o6SRvP2z_9Sybt22PxC4fqnH8NQBCBNGFcdM9FDHVuOuKDT7Nkql_6RVL8yophjQwSwGkbLPoxrtXCfBc4JXFNH4qn8cH7HeyT8Uf2sI8MMSXLyZ7gLQ1EZLgRnCq2VCGZ2M4ZyfJLrsD-tDIoKVVpf8u0zgC8WduiO4DK5OhEWeVHeR67xCW3FfvlKw2uCoi9vwn5sUBJWnJq0rbWn_e4xrmX1ii6p9BLAtIfA3bRUkIyu935UTM1c4X8A0JSA-m5LO3wxbNTzWVO99R4f-b6Y903NEpMgMYUjA3rKDg1iGfgnsCelKwtAO2SnUT_EH0yg3A","content-type":"application/json","forwarded":"for=\"84.109.53.218\";proto=https","function-execution-id":"ca96dibwm9us","origin":"https://common.io","referer":"https://common.io/","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"cross-site","traceparent":"00-a7de9b98b4bdf899f4f6c3e52e8593de-7cf46f3e6b483055-00","x-appengine-city":"jerusalem","x-appengine-citylatlong":"31.768319,35.213710","x-appengine-country":"IL","x-appengine-default-version-hostname":"f25aa528d8c6be0c2p-tp.appspot.com","x-appengine-https":"on","x-appengine-region":"jm","x-appengine-request-log-id":"63fb299800ff0dd625d6fce89f0001737e6632356161353238643863366265306332702d7470000138373934396462626265616664396334346439383666306462373331363766363a3135340001010e","x-appengine-timeout-ms":"599999","x-appengine-user-ip":"84.109.53.218","x-cloud-trace-context":"a7de9b98b4bdf899f4f6c3e52e8593de/9003943868899012693","x-forwarded-for":"84.109.53.218","x-forwarded-proto":"https","x-google-serverless-node-envoy-config-gaewithsupervisor":"","connection":"close"}},"data":{"statusCode":409}}`

**Comment by ariel-dao** [comment]
Removed from production, closing
