### ISSUE TITLE
Files - users cannot open and view a pdf file

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#165]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:
1. Create proposal/post
2. upload a pdf file .
3. Submit the post/proposal
4. view it and download the pdf file 

Actual results:
The file is not open. seems like additional "_" is added to the file
see attached image

![Screenshot_20210303-160217](https://user-images.githubusercontent.com/69141571/109818480-b2d2b480-7c3b-11eb-9c14-ce01911bcad6.png)

Expected results:
User is able to open and view pdf files

**Comment by IlyaDylko** [comment]
Assigned to me
