### ISSUE TITLE
Return correct user list in eligible voters endpoint

### ISSUE THREAD

**Issue by andreymikhadyuk** [daostack/common-backend#1658]
Reference: https://github.com/daostack/common-web/issues/1178#issuecomment-1436254652.
- The amount of eligible voters is 2, but we get new users which have valid for voting circle. But they joined common after the proposal voting was ended.
- I think we also should take into account here people, who voted and then removed his circle and now he would not be able to vote.

**Comment by andreymikhadyuk** [comment]
@elatif2020 Please check the description, maybe I missed a case?

**Comment by elatif2020** [comment]
Yes, we should show all members who had voting rights at the moment that the voting was ended. 
Regarding people who voted and lost their voting rights - this is a very special case - we should probably show them as well, but maybe we should add later some special indication that the vote isn't counted.

**Comment by ariel-dao** [comment]
I've pushed a change that now when a proposal is finalized a vote will be created (in the subcollection votes) for every common member, if that member didn't vote - the outcome will be **null**.

Circle data is not included at the moment as we assume circles are not deleted, that part is handled in another task.

I've also ran a migration on dev and deployed the commit to dev.

**Comment by andreymikhadyuk** [comment]
@ariel-dao Okay, is there something different for FE? Should we just keep calling that endpoint for eligible voters and it will always return correct data to us?
@roienatan fyi

**Comment by ariel-dao** [comment]
@andreymikhadyuk You should pull data for non live proposals from the proposal entity and votes subcollection it self, not from the endpoint.
(`proposal.votes.notVoted` for the count, etc)

**Comment by andreymikhadyuk** [comment]
@ariel-dao tbh, I do not like that we have 2 different ways on the FE for fetching same data. Why the endpoint cannot return correct data to us? So if it is non live proposal, then endpoint will send data based on the proposal entity and votes subcollection.

**Comment by ariel-dao** [comment]
I'll change the endpoint logic to return the proposal data from the finalized proposal from the entity, this should save the changes on FE

**Comment by roienatan** [comment]
> I'll change the endpoint logic to return the proposal data from the finalized proposal from the entity, this should save the changes on FE

So the FE has the use only `get-all-eligible-proposal-voters` endpoint?

**Comment by ariel-dao** [comment]
Yes, no changes required on FE, deployed to dev.

**Comment by elatif2020** [comment]
currently the drop-down shows all the members of the common, and it should be filtered to members of a circle with voting permissions 
see e.g. here: 
![Screenshot_20230306_151020_Firefox.jpg](https://user-images.githubusercontent.com/72435714/223119969-8dccc4b6-1f9c-41e1-b595-e0b104257b03.jpg)

https://web-dev.common.io/new-commons/5bfa46db-5021-4821-9a6d-f831e85305a0

**Comment by elatif2020** [comment]
still an issue

> currently the drop-down shows all the members of the common, and it should be filtered to members of a circle with voting permissions see e.g. here: ![Screenshot_20230306_151020_Firefox.jpg](https://user-images.githubusercontent.com/72435714/223119969-8dccc4b6-1f9c-41e1-b595-e0b104257b03.jpg)
> 
> https://web-dev.common.io/new-commons/5bfa46db-5021-4821-9a6d-f831e85305a0

**Comment by ariel-dao** [comment]
https://daostack.slack.com/archives/CUSPS1A7N/p1678211987088799
This will be fixed once we decide to revert or drop db

**Comment by ariel-dao** [comment]
pushed a fix https://github.com/daostack/common-backend/commit/8af5877c6d5710a3ec06ce44917a61441e950411

**Comment by elatif2020** [comment]
@ariel-dao 
The current voters data both on staging and on dev is wrong. Not sure whether it was not fixed or not deployed correctly.
This is the correct format the BE:

![Image](https://user-images.githubusercontent.com/72435714/224549257-d5f560de-86cd-4657-9105-2d532b55f30e.png)

And this is the data returned for an expired proposal (after the voting ended):

![Image](https://user-images.githubusercontent.com/72435714/224549277-293cb4d8-15ce-4671-99c2-afcf6127d37d.png)
It include "vote" for users with a null outcome, and should not include vote in this case.

**Comment by ariel-dao** [comment]
this is valid

**Comment by elatif2020** [comment]
> this is valid
@ariel-dao 
There is extra data here of `vote` for eligible voters who haven't voted, which is redundant. It can be filtered out in the FE but seems better just to transfer from the BE the exact data needed.

**Comment by roienatan** [comment]
> this is valid

@ariel-dao it makes no sense that for some proposals we get one structure and for some other proposals we get a different structure. The structure should be identical. If the pics above are not clear so:
- for one proposal we get a structure of eligible voters when they don't have the `vote` key in case they haven't voted yet.
- for the other proposal we do get `vote` key even if they haven't voted yet.

In my opinion all should be the first option --> no vote `key` in case one hasn't voted yet. It was also what we agreed at the time the ticket was created if I recall.
