### ISSUE TITLE
Adjust leave common endpoint to support leave project

### ISSUE THREAD

**Issue by ariel-dao** [daostack/common-backend#1661]
Should also leave circle if the project is based on a circle.

https://github.com/daostack/common-web/issues/1235

**Comment by ariel-dao** [comment]
@elatif2020

1) What should happen if the member is last in project? Currently the logic is the same as leave common, you need to delete the project

2) What should happen if the circle is now empty?

**Comment by elatif2020** [comment]
> @elatif2020
> 
>     1. What should happen if the member is last in project? Currently the logic is the same as leave common, you need to delete the project

Yes, it should be the same as leave common, you shouldn't be allowed to leave project if you're the only member with deletion permission.

> 
>     2. What should happen if the circle is now empty?

So this is should happen only on deletion of the project. In this case we should also delete the project-circle.

**Comment by elatif2020** [comment]
@ariel-dao 
Couldn't we use instead the leave circle functionality that we have, applied to the corresponding project-circle in the parent common? (we don't allow joining the project in other ways, but through joining the project-circle in the parent common)

**Comment by ariel-dao** [comment]
@andreymikhadyuk Deployed to dev, the endpoint will now support projects. If the project is attached to a circle, the flow will be remove circle into leave common. same endpoint same behavior.

**Comment by andreymikhadyuk** [comment]
@ariel-dao I didn't get your point about `If the project is attached to a circle`.

**Comment by ariel-dao** [comment]
> @ariel-dao I didn't get your point about `If the project is attached to a circle`.

I think we still have sub commons in the system that are not projects, they have no circle in the parent common

**Comment by andreymikhadyuk** [comment]
@danielr18 fyi
