### ISSUE TITLE
[Fund Allocation] - Cannot create fund allocation if user don't have Bank Account details

### ISSUE THREAD

**Issue by MeyerPV** [daostack/common-backend#1674]
![Screenshot 2023-03-01 at 11 36 06](https://user-images.githubusercontent.com/35873164/222086658-1c08de33-2cc7-49d3-8f92-a379bf685a4b.png)

```
{"args":{"title":"asdasd","description":"[{\"type\":\"paragraph\",\"children\":[{\"text\":\"asdas\"}]}]","images":[],"files":[],"links":[],"commonId":"22a07f25-4090-4877-9aa7-49cc84b70757","amount":{"amount":12300,"currency":"ILS"},"to":"otherMember","otherMemberId":"xH2YtP3wzrf7qMhp4O8bhAp0R9v2"},"type":"FUNDS_ALLOCATION"}
```

**Comment by ariel-dao** [comment]
I've removed the restriction, with that - if there won't be bank account details, the proposal will fail at a later stage automatically. we don't have enforcement flow defined.

https://github.com/daostack/common-backend/commit/779e24736fb05d2f6691a9cb394e407ea92add03

deployed to dev.
