### ISSUE TITLE
Add pinned general discussion for each space

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1683]
also migration for existing commons

**Comment by danielr18** [comment]
Approach:

Create a trigger for `EVENT_TYPES.COMMON_CREATED` to create and pin a General discussion.

The handler will:
- Use `createDiscussionService` to create a discussion
  - Set `ownerId` to the `userId` associated to the event
  - Should `circleVisibility` be an empty array (would that mean it's visible to anyone)?
- Get `commonFeedObject` by querying for the `discussionId`
- Update the common with a pinned item.
  ```ts
  const pinnedFeedItems = [
     { pinnedAt: Timestamp.now(), feedObjectId },
     ...common?.pinnedFeedItems || []
  ];
  await commonsDb.update({ pinnedFeedItems }, commonId, true);
  ```

**Comment by ariel-dao** [comment]
@danielr18 Looks good

**Comment by elatif2020** [comment]
@danielr18 
I believe we should also have a flag to indicate that this discussion is a channel (we will use this flag to display it differently in the FE). 
Not sure whether it is already included in what you did.

**Comment by danielr18** [comment]
@elatif2020 I did not add a flag.
It's currently treated as a regular discussion

**Comment by elatif2020** [comment]
OK I'm opening a separate ticket for this

**Comment by elatif2020** [comment]
here https://github.com/daostack/common-backend/issues/1701
