### ISSUE TITLE
Feed items endpoint

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1689]
[Here](https://github.com/daostack/common-web/blob/dev/src/services/CommonFeed.ts#L57-L91) is the function that FE uses to fetch feed items. As `startAfter` we use the `updatedAt` of the latest item of previously fetched ones.
FE also [listens to](https://github.com/daostack/common-web/blob/dev/src/services/CommonFeed.ts#L93-L120) the feed items with the new `updatedAt` value based on the first feed item in our list.

**Comment by elatif2020** [comment]
We also need the last message from the chat

**Comment by ariel-dao** [comment]
> We also need the last message from the chat

@elatif2020 Please provide more info

**Comment by ariel-dao** [comment]
@andreymikhadyuk merged, see PR for endpoint structure, summary:
`commons/:commonId/feed-items&limit=10&startAfter=2023-03-15T13%3A30%3A00.000Z`

startAfter is encoded ISO date.
both query params are optional, limit will always be at least 10.

should work exactly as the function you've provided.

deployed to dev

**Comment by ariel-dao** [comment]
> > We also need the last message from the chat
> 
> @elatif2020 Please provide more info

I think this is another issue so I've closed the task.

**Comment by elatif2020** [comment]
@ariel-dao 
Okay, I opened a ticket for this, here: https://github.com/daostack/common-backend/issues/1702
