### ISSUE TITLE
Eligble voters issue for retracted proposals

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1690]
See [here](https://web-dev.common.io/commons/016bbb95-384d-4851-ad0b-9a027a0134a9), the eligible voters dropdown is empty:

![Image](https://user-images.githubusercontent.com/72435714/224710807-a35270c5-170d-4bd4-b884-ff951e447afc.png)

The call is to: /proposals/get-all-eligible-proposal-voters/b6a2b229-5a35-4e09-9826-fcf1e092c6c4

**Comment by ariel-dao** [comment]
fixed, new retracted will now show correct votes.
