### ISSUE TITLE
Feed items - follow\unfollow functionality

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1692]
- [x] Allow users to follow or un-follow updates for a feed items. Followed items will appear in the Inbox.

- [x] User is automatically following his created items, or if commented on an item.

- [x] allow to choose for feed item to subscribe\unsubscribe to email notifications.

**Comment by ariel-dao** [comment]
@elatif2020 @andreymikhadyuk info for FE is in PR description

**Comment by elatif2020** [comment]
@ariel-dao 
An addition: 

- [ ] User should automatically follow the general channel of each common\project he joins (and is member of).

**Comment by ariel-dao** [comment]
@elatif2020 What is a "General channel"? This is not a part of the original task, let's open a new one for this.

**Comment by elatif2020** [comment]
@ariel-dao 
This is the pinned discussion channel we added for each common\project, this task: https://github.com/daostack/common-backend/issues/1683

**Comment by elatif2020** [comment]
Here is a new task for this: https://github.com/daostack/common-backend/issues/1726
