### ISSUE TITLE
Emails Fixes

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1694]
- [x] A proposal was approved - Leaders - `d-25fc12001c7d48e5bd002fc9912bbff8`  - Add missing fields: proposerName, proposalTitle, proposalLink. 
- [x] Common successfully created - `d-c24f665295f246479f4eac0da696af35`  - Should exclude project creation
- [x] Someone added a message in your discussion - `d-744ce77afb08455ab217e7480bc21d48`  - Should exclude my own message
- [x] Someone commented on your message - `d-b06b34a051214004a9a07b4a3ae72d56`  - Should exclude my own message
- [ ] Yuhu! Your proposal was approved - `d-f65353985a184807905815b966c550c9`  - Should exclude proposals with automatic admittance. And also exclude requests to join a circle (also for project circle).

**Comment by ariel-dao** [comment]
Proposal title is sent as proposal name. I'll send both to avoid breaking something

**Comment by ariel-dao** [comment]
@elatif2020 About `d-f65353985a184807905815b966c550c9` - we have a different email for joining a common. `COMMON_MEMBER_ADDED_USER_EN = "d-2a176e5677344853b2d24c699dac702d"`.

deployed the rest to dev for now

**Comment by elatif2020** [comment]
> @elatif2020 About `d-f65353985a184807905815b966c550c9` - we have a different email for joining a common. `COMMON_MEMBER_ADDED_USER_EN = "d-2a176e5677344853b2d24c699dac702d"`.
> 
> deployed the rest to dev for now

@ariel-dao 
Yes I know, so Membership request should already excluded, yes? 
And we should add an exclude for automatic admittance and for requests to join a circle.

Also, I realized that we need to exclude the proposer in `d-25fc12001c7d48e5bd002fc9912bbff8` (A proposal was approved - Leaders).
