### ISSUE TITLE
Feed items endpoint - include last message for each card

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1702]
We also need for the last message the user name

**Comment by ariel-dao** [comment]
@elatif2020 What do you mean for the user name? for each user? or just the user that is logged in?

**Comment by elatif2020** [comment]
@ariel-dao 
We want to show in the feed cards a preview of the last message in the chat, similar to what you see for a whatsapp group, of the form "UserName: text text text..."
So we need the last message and the userName who wrote the message.

**Comment by andreymikhadyuk** [comment]
@ariel-dao I see that you've added `lastMessage` to the common feed object data. Will it be updated automatically after new discussion messages are sent?

**Comment by NoamQA** [comment]
last message is shown on feed with the user name that wrote it

**Comment by NoamQA** [comment]
works fine in web stage env.
