### ISSUE TITLE
Mention a user in the chat

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1712]

**Comment by ariel-dao** [comment]
@elatif2020  what should happen when mentioning? email / notification?

**Comment by ariel-dao** [comment]
@andreymikhadyuk What can you send from FE? I was thinking about saving this as an object of `{ string: userId }`
where `string` is the `@UserName` or whatever you want to use to spot it as a mention

**Comment by elatif2020** [comment]
> @elatif2020  what should happen when mentioning? email / notification?

Yes we should add an email and a notification. 
And also make you follow future messages in this conversation (this is related to the follow-unfollow task).

**Comment by andreymikhadyuk** [comment]
@ariel-dao @elatif2020 At the moment I do not know what is the better approach for mentioning feature.
In the text editor it should store data just by id somehow, because if user changes his name, then the new one should be displayed in the message.
But I think for BE purposes we can send array of user ids.

**Comment by andreymikhadyuk** [comment]
Maybe @MeyerPV has any thoughts as well.

**Comment by MeyerPV** [comment]
I think we should send array of userIds to BE, because a user can mention more than 1 person.

Also usually if you mention someone, then by clicking you can open his profile and we will need a user id

**Comment by ariel-dao** [comment]
@MeyerPV np an array of Ids is fine, but I was just wandering how will you map the id to the text mention. So an array of userIds?

**Comment by ariel-dao** [comment]
create and update discussion message will now accept a mentions array of userIds. It'll check that those user Ids are common members, if not, it'll throw
