### ISSUE TITLE
User should automatically follow the general channel of each common\project he joins

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1726]
And of course unfollow it if he leaves the common\project 
(Actually user should automatically unfollow everything he followed in common\project when leaving)

general channel: the pinned discussion channel we added for each common\project

**Comment by ariel-dao** [comment]
@elatif2020 What is a general channel?

**Comment by elatif2020** [comment]
@ariel-dao see my reply here: https://github.com/daostack/common-backend/issues/1692#issuecomment-1488210665
