### ISSUE TITLE
Discussion - Comments - Copy comment and moderation option are conflict

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#173]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:
1. Go to a common that you are a member
2. Go to discussion tab
3. goto a comment within the discussion 
4. long press on the comment (to copy or report)

Actual results:
copy comment and moderation option are conflict - see attached image
there is too small aria to both option in this case and sometime they appears together

Expected results:
Both functionality should be separate 

![File (56)](https://user-images.githubusercontent.com/69141571/109961142-436bcc00-7cf2-11eb-9ca8-c42a7c81da8a.jpg)

**Comment by Taikaish** [comment]
Moderators should see another option in the menu - "Copy text".
The device default "copy button" should be disabled for them.

**Comment by Taikaish** [comment]
https://zpl.io/2ppz0Rj

**Comment by yanivi71** [comment]
@Taikaish What about regular users?

**Comment by Taikaish** [comment]
For now, we can keep the default "Copy" functionality for regular users.

Soon we'll develop more chat options for regular users - reply to a reply, download (if it's an image), edit & delete (if it's your own message). Then we'll add the "Copy text" button and disable the Copy functionality for everyone.
