### ISSUE TITLE
Mark "new" feed items for a user

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1730]
Every item which was added to my common\project which I havn't opened yet

**Comment by andreymikhadyuk** [comment]
@ariel-dao @danielr18 The thing is that we need to show to user feed item as `New` if he didn't open that feed item yet. Maybe we should add a flag to `CommonFeedObjectUserUnique` which will be changed after we first time mark something as `seen`.

**Comment by ariel-dao** [comment]
> @ariel-dao @danielr18 The think is that we need to should to user feed item as `New` if he didn't open that feed item yet. Maybe we should add a flag to `CommonFeedObjectUserUnique` which will be changed after we first time mark something as `seen`.

sounds good
