### ISSUE TITLE
BE Direct message functionality

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1732]

**Comment by ariel-dao** [comment]
@elatif2020 Let's add some context and specific definitions here please

**Comment by elatif2020** [comment]
> @elatif2020 Let's add some context and specific definitions here please

@ariel-dao 
We should figure it out.
In general Direct messages appears only in my Inbox. It is a new type of Inbox item. 
They are not tight to the context of a single common\project. 
It have a usual chat component, that only the two participants can see and take part in. 
Similar to other feed items we should keep track of which messages are new for a user (so we will have an unread counter and the "new" separator).

**Comment by NoamQA** [comment]
backend issue
cant be tested on the common web
