### ISSUE TITLE
unreadMessages and seenOnce are not updated on dev

### ISSUE THREAD

**Issue by roienatan** [daostack/common-backend#1749]
`unreadMessages` and `seenOnce` are not updated after FE calls `mark-feed-object-seen-for-user`:

Payload: 
`{"feedObjectId":"abaa2b43-b1d3-4550-919b-09ea99b5f51a","commonId":"085b21ae-baab-43ed-8cfb-490ecf9abcb3","lastSeenId":"5218c9c6-f0d7-43e8-a8c6-21e3b125a14f","type":"discussionMessage"}`
Response:
`{"message":"Seen marked"}` but data from BE is not updated, also after app refresh.

![image](https://user-images.githubusercontent.com/34843014/231068153-5929ce23-25d0-424e-af00-b57f0769eb84.png)

**Comment by NoamQA** [comment]
backend issue
cant be tested on the common web
