### ISSUE TITLE
Moderation - Comment - Fix the hidden comments for regular users

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#175]
Tested on Staging iOS version 1.9.5 (4978-227)
Tested on Staging Android version 1.9.5 (4978-188)

When the moderator hides the comment, and the regular user's name is quite long, the moderator's name does not get into the message box. 
Please fix it as is shown in the design - https://zpl.io/25Q7KDo

![Screenshot_20210304-155352_common-stg](https://user-images.githubusercontent.com/68247034/109967098-10313900-7d02-11eb-86e9-81dba131597a.jpg)

**Comment by gingervik** [comment]
irrelevant
