### ISSUE TITLE
The app crashes when opening some notifications

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#176]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

The app crashes when the user opens New comment and New proposal notifications.

Steps to reproduce:
1. Open the app
2. Go to the Notifications screen
3. Click on New comment or New proposal notification

https://user-images.githubusercontent.com/68247034/109994714-a1160d80-7d1e-11eb-9646-791eaceae4c7.mp4

https://user-images.githubusercontent.com/68247034/109994721-a2dfd100-7d1e-11eb-9ff5-926fbc7149d3.mp4

**Comment by IvanSantiagoUk** [comment]
- New proposal fixed
- New comment is a big data managment issue and @lpetkov-sw will investigate further, for the moment being I disabled the click

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

@IvanSantiagoUk
1. Clicking on "new proposal" on android devices still crashes the app
2. Clicking on "new proposal" on ios devices still crashes the app (i clicked on the first notification)
3. Clicking on "Membership request created" on android devices still crashes the app

**Comment by watchtower314** [comment]
@IvanSantiagoUk  the fix will be ready here : https://github.com/daostack/common/pull/962
along with the push notification issues that cause crashes and endless loading

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-241)
Tested on Staging Android version 1.9.5 (4978-202)

Clicking on notifications the app does not crash.

**Comment by kazaryan-t** [comment]
Tested on Production Android version 1.9.5 (4998-53)
Tested on Production iOS version 1.9.5 (4998-44)
