### ISSUE TITLE
Allow the creator of a feed item to delete his item

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1764]
with the conditions we have regardless (so not a proposal that was resolved)

**Comment by NoamQA** [comment]
@elatif2020 

- [ ] it is possible to delete a chat item

- [ ] needs to refresh for it to disappear 

- [ ] if its a last comment it keeps appear in the main bar and counter doesnt decrease 

is it OK for us?

**Comment by elatif2020** [comment]
@NoamQA 
in which env did you made the test?
points 2 & 3 should should be fixed

**Comment by NoamQA** [comment]
@elatif2020 

dev + web stage


![Image](https://github.com/daostack/common-backend/assets/129174316/24c49a66-b077-4372-8415-e3e636bbbb70)

**Comment by elatif2020** [comment]
@NoamQA 
Sorry I didn't noticed this is not the right place for the functionality you tested. This ticket is for **BE** functionality related to deletion of **feed items**. 
Could you please move those comments to a new ticket?
I'm moving this ticket to verified.
