### ISSUE TITLE
User photo is not displayed

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#177]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

User photo is not displayed on New comment notifications.

Steps to reproduce:

1. Open the app
2. Go to the Notifications screen
3. Pay attention to New comment notification

Actual result:
User photo is not displayed

Expected result:
User photo should be displayed as for other notifications

![Screenshot_20210304-190843_common-stg](https://user-images.githubusercontent.com/68247034/109995996-d8d18500-7d1f-11eb-9750-5ba0db23b776.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Found OK
Seems like user has no image in his profile or has white image therefore the image is not display

**Comment by yanivi71** [comment]
verified on production
