### ISSUE TITLE
Support the new messages text format in emails

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1777]
[{“type”:“paragraph”,“children”:[{“text”:“”},{“type”:“mention”,“displayName”:“Daniel Reinoso”,“userId”:“wPHSJ1TrkkRK89GEyumwAnH9H2A2”,“children”:[{“text”:” “}]},{“text”:” “},{“type”:“mention”,“displayName”:“Latif Eliaz”,“userId”:“N1ZK0Rf8A1SxlY0bO0XRX6BLFDg2",“children”:[{“text”:” “}]},{“text”:” “},{“type”:“mention”,“displayName”:“Roie Natan”,“userId”:“xVKzzYHqsSPrcfKgOcwmSgPj8HE3",“children”:[{“text”:” “}]},{“text”:” “},{“type”:“mention”,“displayName”:“Matan Field”,“userId”:“FY3mSDJ1FwQOeCaYteLh7X42QA73",“children”:[{“text”:” “}]},{“text”:“”}]}]

**Comment by elatif2020** [comment]
@andreymikhadyuk please add here about the logic

**Comment by elatif2020** [comment]
Just for fun, I tried using AI (Bing chat) for this. 
@ariel-dao @andreymikhadyuk 
First I gave it 3 examples and asked for a specification of the convert method. And next I asked for a JS implementation of this method. As you can see below it is nice, but not exact...
Next, I tried again from the begining, this time I asked for a recursive implementation.

**The examples I gave**
_Example 1_ [{"type":"paragraph","children":[{"text":"test just text"}]}] should be formatted to: 
`test just text` 
_Example 2_ [{"type":"paragraph","children":[{"text":"test mention "},{"type":"mention","displayName":"Latif Eliaz","userId":"DDLlUToombZCVE4hf6Ir0NEsOvg2","children":[{"text":" "}]},{"text":" and more text after"}]}] should be formatted to: 
`test mention @Latif Eliaz and more text after `
_Example 3_ [{"type":"paragraph","children":[{"text":"paragraph1"}]}, {"type":"paragraph","children":[{"text":"paragraph2"}]}] Should be formatted to 
```
paragraph1
paragraph2
```

**The specification it gave me:**

> 
> - The format method takes an array of objects as input and returns a string as output.
> - Each object in the array has a type property and a children property.
> - The type property can be either “paragraph” or “mention”.
> - The children property is an array of objects or strings that represent the content of the paragraph or mention.
> - If the type property is “paragraph”, then the format method concatenates all the elements in the children array and adds a newline character at the end.
> - If the type property is “mention”, then the format method adds an “@” symbol before the displayName property of the object and ignores the userId and children properties.
> - The format method repeats this process for each object in the input array and returns the final string.
> 
> 

**And the first implementation repond**

> Based on the search results, I found that JavaScript has a built-in toString() method that can convert an array to a string, but it does not handle the mention type properly. So I wrote a custom function that checks the type of each object and formats it accordingly. Here is the code:


```
// A function that takes an array of objects and returns a string
function format(array) {
  // Initialize an empty string to store the output
  let output = "";
  // Loop through each object in the array
  for (let obj of array) {
    // Check the type of the object
    if (obj.type === "paragraph") {
      // Use the toString() method to convert the children array to a string
      output += obj.children.toString();
      // Add a newline character at the end
      output += "\n";
    } else if (obj.type === "mention") {
      // Add an "@" symbol before the displayName property
      output += "@" + obj.displayName;
    } else {
      // Ignore other types
    }
  }
  // Return the output string
  return output;
}

```

**The recursive implementation**

> Sure, I can try to provide a recursive implementation of the above. Here is one possible way to do that:

```js
// Define a function that takes an array of objects and an output string as input and returns a string
function convert(array, output = "") {
  // Check if the array is empty
  if (array.length === 0) {
    // Return the output string
    return output;
  }
  // Get the first object in the array
  let obj = array[0];
  // Check if the object has a type property and if it is "paragraph"
  if (obj.type && obj.type === "paragraph") {
    // Check if the object has a children property and if it is an array
    if (obj.children && Array.isArray(obj.children)) {
      // Call the convert function recursively on the children array and append the result to the output string
      output += convert(obj.children);
      // Append a newline character to the output string after each paragraph
      output += "\n";
    }
  }
  // Check if the object has a text property and if it is a string
  if (obj.text && typeof obj.text === "string") {
    // Append the text to the output string
    output += obj.text;
  }
  // Check if the object has a type property and if it is "mention"
  if (obj.type && obj.type === "mention") {
    // Check if the object has a displayName property and if it is a string
    if (obj.displayName && typeof obj.displayName === "string") {
      // Append the mention with "@" symbol to the output string
      output += "@" + obj.displayName;
    }
  }
  // Call the convert function recursively on the rest of the array and return the result
  return convert(array.slice(1), output);
}
```

**Comment by ariel-dao** [comment]
Ok. I need an official specification from you so I'll know what to
implement.

**Comment by andreymikhadyuk** [comment]
@elatif2020 @ariel-dao I've checked what the library which we use provides and it seems that we should write our custom util to convert rich text to plain text.
@ariel-dao Let me know whether that's fine for you to implement it or you want me to do this.

**Comment by ariel-dao** [comment]
@andreymikhadyuk Check the commit please, if it's fine close the issue.

As far as I understand, the discussion messages are not using this format at the moment so it's not actually being used

**Comment by andreymikhadyuk** [comment]
Seems to be ok, but better to cover it with tests. Hope you tested it at least with Latif's examples.

**Comment by ariel-dao** [comment]
@andreymikhadyuk Yes all three of them, I can set up some test cases if there are more complex combos we should take into consideration (I'll need examples)

**Comment by andreymikhadyuk** [comment]
@ariel-dao I think that it is worth to add test cases for what we have in the examples. For now those are the only possible element types for cases where we need to convert data to the plain text, so the your function can be as it is for now.

**Comment by elatif2020** [comment]
@ariel-dao
As I see we still send unformatted messages text in emails (this is the title of this issue...)
See here an example:


![Image](https://user-images.githubusercontent.com/72435714/236927859-67d0070f-5f84-4be4-a613-c0dbf23e6701.png)

@NoamQA fyi

**Comment by ariel-dao** [comment]
> @ariel-dao As I see we still send unformatted messages text in emails (this is the title of this issue...) See here an example:
> 
> ![Image](https://user-images.githubusercontent.com/72435714/236927859-67d0070f-5f84-4be4-a613-c0dbf23e6701.png)
> 
> @NoamQA fyi

Yes it wasn't implement, we still have a lot of messages without this format...

**Comment by elatif2020** [comment]
Reminding what we were saying: check whether the message format is a string or an array of objects, and in the 2nd case convert it to string.
Notice it's relatively high priority
@ariel-dao @danielr18

**Comment by ariel-dao** [comment]
Parser is now active in emails, deployed to dev

**Comment by NoamQA** [comment]
:white_check_mark: works fine in DEV env.

**Comment by elatif2020** [comment]
✅ works in Staging env. 

But there is one issue (in a new card https://github.com/daostack/common-backend/issues/1820)

- [ ] Add a space instead of new lines in the message in the emails as a new line doesn't appear there
