### ISSUE TITLE
Create common - example images error - 403 Forbidden

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1778]
`GET /v0/b/common-daostack.appspot.com/o/public_img%2Fcover_template_05.png?alt=media HTTP/2
Host: firebasestorage.googleapis.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Accept: image/avif,image/webp,*/*
Accept-Language: he,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Referer: https://common.io/
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: cross-site
TE: trailers`

`HTTP/2 403 Forbidden
x-guploader-uploadid: ADPycdvd5eTvDkkWgU2Ymgv4k_8RpCwFjsE_X5dRwIPgU6N3bR6L9CEueeTid94d1hv4scPe66EeMWlweMssdXSx3-mg4A
x-content-type-options: nosniff
content-type: application/json; charset=UTF-8
access-control-expose-headers: Content-Range, X-Firebase-Storage-XSRF
access-control-allow-origin: *
date: Tue, 25 Apr 2023 10:43:46 GMT
expires: Tue, 25 Apr 2023 10:43:46 GMT
cache-control: private, max-age=0
content-length: 73
server: UploadServer
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
X-Firefox-Spdy: h2`

**Comment by ariel-dao** [comment]
fixed

**Comment by NoamQA** [comment]
backend issue
cant be tested on the common web
