### ISSUE TITLE
Add PIN_OR_UNPIN_FEED_ITEMS and INVITE_TO_CIRCLE actions to governance template

### ISSUE THREAD

**Issue by danielr18** [daostack/common-backend#1781]
- [x] New commons and new spaces created should have PIN_OR_UNPIN_FEED_ITEMS and INVITE_TO_CIRCLE  actions enabled
- [x] Leader circle should have PIN_OR_UNPIN_FEED_ITEMS and INVITE_TO_CIRCLE actions enabled
- [x] Create migration to add the PIN_OR_UNPIN_FEED_ITEMS and INVITE_TO_CIRCLE  to all commons/spaces and leader circles

**Comment by elatif2020** [comment]
@danielr18 
We should also add INVITE_TO_CIRCLE action similarly -
so enable it for new commons\spaces, for the leaders circle, and add to the migration.

Can you take care of this together with this ticket?

**Comment by elatif2020** [comment]
@danielr18 
does points 2 & 3 here are also done?

**Comment by danielr18** [comment]
Yes

**Comment by elatif2020** [comment]
Reopened. As I understand the migration has to be activated. 
@danielr18 Could you please update on it here?
