### ISSUE TITLE
`markFeedObjectSeenForUser` make lastSeenId optional

### ISSUE THREAD

**Issue by ariel-dao** [daostack/common-backend#1791]
to allow seen once to be marked true when there are no messages

**Comment by ariel-dao** [comment]
@andreymikhadyuk fyi

**Comment by andreymikhadyuk** [comment]
@ariel-dao Not sure how the type of `lastSeen` field will be changed in the `CommonFeedObjectUserUnique` model. But maybe better to make it to be different on `LastSeenEntity` type? Like this (maybe there is an error in the type deslaration, but I think you understand what I mean):
```
type LastSeen =
  | {
      type: LastSeenEntity.DiscussionMessage;
      id: string;
    }
  | {
      type: LastSeenEntity;
    };
```

**Comment by ariel-dao** [comment]
@andreymikhadyuk `type` and `lastSeenId` are now optional. if they are not provided, seen once will be marked as true

deployed to dev

**Comment by NoamQA** [comment]
backend issue
there is no way to test on the common web
