### ISSUE TITLE
Add `Assign circle` action

### ISSUE THREAD

**Issue by ariel-dao** [daostack/common-backend#1792]

**Comment by ariel-dao** [comment]
@roienatan fyi

**Comment by ariel-dao** [comment]
#1741 @roienatan the action already exist. use `ACTIONS.ASSIGN_CIRCLE`

**Comment by roienatan** [comment]
> #1741 @roienatan the action already exist. use `ACTIONS.ASSIGN_CIRCLE`

@ariel-dao 
Hey, I tried using `ASSIGN_CIRCLE` with the endpoint:
`https://us-central1-common-dev-dea4e.cloudfunctions.net/proposals/action`
payload:
```
{
	"type": "ASSIGN_CIRCLE",
	"args": {
		"commonId": "fab8c28d-f42b-448b-9b2e-f2161cff6e2f",
		"circleId": "a8db0cbf-d54c-447f-9d42-59ed224bd205",
		"inviteeId": "DDLlUToombZCVE4hf6Ir0NEsOvg2"
	}
}
```
response:
`{"message":"assign circle action successfully executed"}`
but no change also after refresh. Any idea? It should immediately update the invitee circle, correct?

**Comment by ariel-dao** [comment]
@roienatan You are using the wrong args.
![image](https://user-images.githubusercontent.com/89919079/236423180-3b558e62-3561-4716-b582-ad8d1df592c0.png)

**Comment by roienatan** [comment]
> @roienatan You are using the wrong args.
> ![image](https://user-images.githubusercontent.com/89919079/236423180-3b558e62-3561-4716-b582-ad8d1df592c0.png)

@ariel-dao I'm sending `circleId`, `commonId` and the `memberId`. Why wrong args?

**Comment by ariel-dao** [comment]
`
export const assignCircleActionArgs = object({
    circleId: string().uuid().required(),
    commonId: string().uuid().required(),
    userId: string().required()
})
`
These are the args you're suppose to send.

**Comment by roienatan** [comment]
> `export const assignCircleActionArgs = object({ circleId: string().uuid().required(), commonId: string().uuid().required(), userId: string().required() })`
> These are the args you're suppose to send.

@ariel-dao okay thanks, it works. But the BE should have thrown an error in that case and not `200`.

**Comment by ariel-dao** [comment]
> > `export const assignCircleActionArgs = object({ circleId: string().uuid().required(), commonId: string().uuid().required(), userId: string().required() })`
> > These are the args you're suppose to send.
> 
> @ariel-dao okay thanks, it works. But the BE should have thrown an error in that case and not `200`.

I agree, will check why it passed

**Comment by NoamQA** [comment]
backend issue
cant be tested on the common web
