### ISSUE TITLE
Update Inbox counter upon deletion of a feed item

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1795]
related to the ticket: https://github.com/daostack/common-backend/issues/1794

For every user who followed this item the inbox counter should be updated - decrease one if this item had updates which were unseen by that user.

**Comment by ariel-dao** [comment]
@danielr18 If you're considering to use the deleted trigger, it might be better to use events instead. triggers can be unexpected sometimes in an event driven system

**Comment by NoamQA** [comment]
cant test this tickets because the counter doesnt shown
to be tested later in the sprint

**Comment by NoamQA** [comment]
@elatif2020 
as far as i can see it doesnt happens
i think it needs to be tested again after the issues with the counter fixed
i added a note in the related [ticket ](https://github.com/daostack/common-backend/issues/1795)
