### ISSUE TITLE
Proposals - delete

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1796]
see related specs here https://github.com/daostack/common-backend/issues/1594

~~~~~

@elatif2020 The backend doesn't have a delete proposal endpoint, but rather a discussion delete endpoint that deletes the discussion/feed item objects.

_Originally posted by @danielr18 in https://github.com/daostack/common-web/issues/1370#issuecomment-1534802368_

**Comment by ariel-dao** [comment]
@elatif2020 isn't retract enough? or do we want to specifically delete

**Comment by elatif2020** [comment]
@ariel-dao This delete action is for moderators in order to be able to remove inappropriate content or something...

**Comment by andreymikhadyuk** [comment]
@ariel-dao @danielr18 What should happen with feed items after proposal removal? I call the endpoint to remove proposal, it is marked in the DB as `deleted`, but the feed item is still there.

Also in the PR I see new `deleted` field in the `BaseProposal` model. Why didn't we use existing `SoftDeleteEntity` model?
