### ISSUE TITLE
Follow unFollow a common\ a space

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1797]
- A user who follows a common (a space) automatically follows every new feed item, and also follows every existing item. 
- A user can stop following a common (space), in this case she would not automatically follow new feed items in this common (space)
- A user can also mute a common (space), in this case all feed items in it are unfollowed (in addition to disabling auto follow)
- Let's add a flag in the governance to indicate for each common, something like autoFollowed. When this flag is on, users automatically follow this common when they join. Currently this flag is off by default.

**Comment by ariel-dao** [comment]
What does a `stream` mean? we don't have that definition technically. Do you mean the common feed?

**Comment by elatif2020** [comment]
> What does a `stream` mean? we don't have that definition technically. Do you mean the common feed?

see the update above 
stream = feed item
