### ISSUE TITLE
Duplicated pinned items

### ISSUE THREAD

**Issue by roienatan** [daostack/common-backend#1798]
Endpoint `feed-items` returns element that is also returned in `pinned-items`.

See the duplicated ID `390844b7-d50a-4670-822e-3eae8f17f798`:

Feed items endpoint:
`https://us-central1-common-dev-dea4e.cloudfunctions.net/commons/30b851e0-015d-4654-987b-380f34784dd6/feed-items?limit=15
`
Response:
```
{
	"message": "Ok",
	"data": {
		"feedItems": [{
			"createdAt": {
				"_seconds": 1681711520,
				"_nanoseconds": 617000000
			},
			"data": {
				"discussionId": null,
				"id": "339bd0bf-4435-45cc-ae07-bb442c142489",
				"type": "ProjectCreation"
			},
			"circleVisibility": [],
			"id": "1bfdc0de-0caf-47f9-9908-6605391c42cf",
			"userId": "xVKzzYHqsSPrcfKgOcwmSgPj8HE3",
			"updatedAt": {
				"_seconds": 1681711520,
				"_nanoseconds": 617000000
			},
			"commonId": "30b851e0-015d-4654-987b-380f34784dd6"
		}, {
			"createdAt": {
				"_seconds": 1680418305,
				"_nanoseconds": 402000000
			},
			"data": {
				"discussionId": null,
				"id": "f660c3e1-302d-4de6-a32e-56dbc11d82f4",
				"type": "Discussion"
			},
			"circleVisibility": [],
			"id": "390844b7-d50a-4670-822e-3eae8f17f798",
			"userId": "xVKzzYHqsSPrcfKgOcwmSgPj8HE3",
			"updatedAt": {
				"_seconds": 1680418305,
				"_nanoseconds": 402000000
			},
			"commonId": "30b851e0-015d-4654-987b-380f34784dd6"
		}]
	},
	"firstDocTimestamp": {
		"_seconds": 1681711520,
		"_nanoseconds": 617000000
	},
	"lastDocTimestamp": {
		"_seconds": 1680418305,
		"_nanoseconds": 402000000
	},
	"hasMore": false
}

```
<img width="1436" alt="Screen Shot 2023-05-05 at 11 20 34" src="https://user-images.githubusercontent.com/34843014/236389733-4597d5fd-d6e8-414f-9865-9ae34f56597b.png">

Pinned feed items endpoint:
`https://us-central1-common-dev-dea4e.cloudfunctions.net/commons/30b851e0-015d-4654-987b-380f34784dd6/pinned-feed-items`

Response:
```
{
	"message": "Ok",
	"data": {
		"pinnedFeedItems": [{
			"createdAt": {
				"_seconds": 1680418305,
				"_nanoseconds": 402000000
			},
			"data": {
				"discussionId": null,
				"id": "f660c3e1-302d-4de6-a32e-56dbc11d82f4",
				"type": "Discussion"
			},
			"circleVisibility": [],
			"id": "390844b7-d50a-4670-822e-3eae8f17f798",
			"userId": "xVKzzYHqsSPrcfKgOcwmSgPj8HE3",
			"updatedAt": {
				"_seconds": 1680418305,
				"_nanoseconds": 402000000
			}
		}]
	}
}

```
<img width="1437" alt="Screen Shot 2023-05-05 at 11 20 02" src="https://user-images.githubusercontent.com/34843014/236389916-eebaa264-7879-460b-bbb6-47612cf696c9.png">

**Comment by ariel-dao** [comment]
Tested and deployed to dev

**Comment by roienatan** [comment]
> Tested and deployed to dev

@ariel-dao are you sure? still see the duplicated items.

**Comment by ariel-dao** [comment]
Yes.
Not reproducing on new and existing commons, maybe something is broken (or broke before fix) in the common you are testing on, but it doesn't matter because this bug was opened on dev and closed on dev so it won't reproduce. check on new commons.

**Comment by NoamQA** [comment]
:white_check_mark: works fine in web staging env.
