### ISSUE TITLE
System messages

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1799]
For each common (space) we should create system messages upon some events. 
The system messages should be added to the "General" discussion (which is created automatically for each common), and appear with the correct date & time of the corresponding event. They should somehow be flagged as system messages. Also some of those messages should trigger a push notification \ an email.
Here is the list of the messages we should create:
* User create this common (space) -> message: "@userName created this $commonType." where if this common has a parent common $commonType="space" and otherwise $commonType="common". And the user name should appear as mention.
* A user create a sub-common (space) to this common (space) -> message: "@userName created the space $subCommonName." where the $subCommonName should be a link to the subcommon (/commons/subCommonId). This message should trigger a push notification and and email (TBD).
* A user join the common -> message: "@userName joined this $commonType" (In the future we might want to batch all the users who joined each day).
* A user edit this common's about -> "@userName edited this $commonType's info." With a link on the word info to the about page of this common (commons/commonId/about).

In the future we will probably want to add messages on more events, such as creation of feed items (discussions & proposal), decisions that were made, funds transactions, changes in the roles (circles) of users in the common, users leaving the common, deletion of spaces, and deletion of feed items. 
Also for the future, it might be useful to be able to configure which system events are activated.

**Comment by elatif2020** [comment]
@ariel-dao @danielr18 @andreymikhadyuk @MeyerPV @roienatan 
Notice this card with a new feature. Your review on it could be useful.

**Comment by ariel-dao** [comment]
A general message will now be created for all 4 points mentioned with the text in a rich text format, the user id that is creating the discussion message is "system", we might need to handle that somehow, maybe create manually a system user for this.

deployed to dev
