### ISSUE TITLE
Discussion message create API - validation schema update

### ISSUE THREAD

**Issue by MeyerPV** [daostack/common-backend#1806]
Could you add condition to API - if we have images we can skip text.required validation?
 
https://us-central1-common-dev-dea4e.cloudfunctions.net/discussions/message
Request Method: POST
![image](https://user-images.githubusercontent.com/35873164/236813267-92ca2ddd-acd0-4bec-b09f-3e26eb031799.png)

**Comment by ariel-dao** [comment]
deployed to dev

**Comment by elatif2020** [comment]
Not sure it can be tested currently.
Anyway sending just an image works.
-> Verified

**Comment by NoamQA** [comment]
:white_check_mark: works fine in PROD env.
