### ISSUE TITLE
No New post notification on Notifications screen

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#181]
Tested on Staging iOS version 1.9.5 (4978-229)
Tested on Staging Android version 1.9.5 (4978-190)

New post notifications are not displayed on the Notifications screen. A user receives the notification about a New post created in the common, but when he opens the Notifications screen, there is no notification about New post.

Steps to reproduce:
There are at least two accounts - members of the same common (A and B)
1. User A creates a new post in the common
2. User B receives the notification
3. User B opens the app and navigates to the Notifications screen

Actual result:
There is no notification about New post created.

Expected result:
The notification about New post created is displayed on the Notifications screen as the other notifications (e.g. new proposal, new comment, new featured common, etc.)

**iOS** 

![IMG_0031](https://user-images.githubusercontent.com/68247034/110110483-efc7b400-7dbf-11eb-9605-b018c914e0b3.PNG)
![IMG_0032](https://user-images.githubusercontent.com/68247034/110110485-f0f8e100-7dbf-11eb-97b8-017698523995.PNG)

**Android**

![Screenshot_20210305-141326_One UI Home](https://user-images.githubusercontent.com/68247034/110110549-0c63ec00-7dc0-11eb-9dad-5582cda95c8c.jpg)
![Screenshot_20210305-141411_common-stg](https://user-images.githubusercontent.com/68247034/110110546-0b32bf00-7dc0-11eb-96a3-9ff4db6831af.jpg)

**Comment by yanivi71** [comment]
@kazaryan-t this issues is fixed and merged to production
