### ISSUE TITLE
Add file info to the last message

### ISSUE THREAD

**Issue by andreymikhadyuk** [daostack/common-backend#1814]
In the `CommonFeed` model we have `lastMessage` field which represents actually the last message in the discussion. Now discussion messages may have `files` or `images`. So we should add a flag (e.g. `hasFiles?: boolean`) to the `lastMessage` object which will show whether the message has files/images or not.

**Comment by elatif2020** [comment]
@andreymikhadyuk @ariel-dao 
We will have a different icon for Images and Files so maybe better to separate, something like indicating `hasFileType? = { None, Image, File }`

**Comment by andreymikhadyuk** [comment]
@elatif2020 @ariel-dao As I know we may have only `files` and `images`.
So maybe:
```
hasFiles?: boolean;
hasImages?: boolean;
```

**Comment by ariel-dao** [comment]
deployed to dev, @elatif2020 do we need a migration for old messages?

**Comment by elatif2020** [comment]
> deployed to dev, @elatif2020 do we need a migration for old messages?

@ariel-dao 
probably not so much

**Comment by NoamQA** [comment]
backend issue
cant be tested on the common web
