### ISSUE TITLE
Auto follow chat after being mentioned

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1816]
If a user is mentioned in a chat he should become following this chat-discussion

**Comment by danielr18** [comment]
@NoamQA Can you QA this?
I believe this should be working

**Comment by NoamQA** [comment]
@danielr18 
it doesnt happens in DEV env.

![image](https://github.com/daostack/common-backend/assets/129174316/c4cfd58b-fce7-4659-8efb-83fedbd7635a)

**Comment by elatif2020** [comment]
> @danielr18 it doesnt happens in DEV env.
> 
> ![image](https://private-user-images.githubusercontent.com/129174316/237593887-c4cfd58b-fce7-4659-8efb-83fedbd7635a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJrZXkxIiwiZXhwIjoxNjgzODAxOTI1LCJuYmYiOjE2ODM4MDE2MjUsInBhdGgiOiIvMTI5MTc0MzE2LzIzNzU5Mzg4Ny1jNGNmZDU4Yi1mY2U3LTQ2NTktOGVmYi04M2ZlZGJkNzYzNWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzA1MTFUMTA0MDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWExYWQ1YzBhOGE0MGIxZTA0MGM3NjRlZjQ5Y2MwZTVlZTcyYmYzOTAzNjFkZTlmNjhlMTI2NTM5MjU5ZWUwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6pwaSiX99mxY2NijqLa7K6EIMCrjjTFPqCpdvr1J9yc)

@NoamQA 
Can you please check also that the mentioned user doesn't see this item in the inbox?

**Comment by NoamQA** [comment]
@danielr18 @elatif2020 
it doesnt appear there...
![image](https://github.com/daostack/common-backend/assets/129174316/d034a314-b69d-4d8f-be75-724e75f9d487)

**Comment by elatif2020** [comment]
As I see it is not working yet. I tried it on dev.
@danielr18 
@NoamQA fyi

**Comment by elatif2020** [comment]
@NoamQA 
Could you please check to verify whether this functionality is working?
