### ISSUE TITLE
Notification List knew issues

### ISSUE THREAD

**Issue by IvanSantiagoUk** [daostack/common-backend#182]
- Tab not refreshing when logging out and logging in
- Add loading indicator
- check why some messages has undefined users

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Tab not refreshing when logging out and logging in - Found OK
Add loading indicator - Found OK
check why some messages has undefined users - Found OK

**Comment by yanivi71** [comment]
verified on production
