### ISSUE TITLE
Add a space instead of a new line in the message text in the emails

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1820]
- [ ] Add a space instead of new lines in the message in the emails as a new line doesn't appear there

_Originally posted by @elatif2020 in https://github.com/daostack/common-backend/issues/1777#issuecomment-1544587653_

see for example:
![image](https://github.com/daostack/common-backend/assets/72435714/bac0329b-1f06-4f7a-9654-1814738175bd)
Where the original text is: 
```
text
new line
2nd new line
```

**Comment by ariel-dao** [comment]
@elatif2020 Having hard time reproducing it. Please provide the message in the structure that is being parsed.

**Comment by elatif2020** [comment]
> @elatif2020 Having hard time reproducing it. Please provide the message in the structure that is being parsed.

@ariel-dao 

[{"type":"paragraph","children":[{"text":"text"}]},{"type":"paragraph","children":[{"text":"new line"}]},{"type":"paragraph","children":[{"text":"2nd new line"}]}]

**Comment by ariel-dao** [comment]
deployed to dev

**Comment by elatif2020** [comment]
❌ 
The full text is displayed in the email but we're missing the space before a new line

see for example
![Image](https://github.com/daostack/common-backend/assets/72435714/82b9d171-9c8c-41cc-80d4-7973c600e6fe)

![Image](https://github.com/daostack/common-backend/assets/72435714/dbe2a501-ba40-4ec0-a137-949b24ca5020)

In the email it should be: "test email with a new line here and here"

**Comment by ariel-dao** [comment]
Deployed to dev. Tested, if this happens again please add the message it self (in the object format)

**Comment by NoamQA** [comment]
:x: it still happens in DEV. env.

[{"type":"paragraph","children":[{"text":"test"}]},{"type":"paragraph","children":[{"text":"new"}]},{"type":"paragraph","children":[{"text":"line"}]},{"type":"paragraph","children":[{"text":"message"}]},{"type":"paragraph","children":[{"text":"in"}]},{"type":"paragraph","children":[{"text":"email"}]}]

![Image](https://github.com/daostack/common-backend/assets/129174316/a2e7f71e-ac36-4b43-9980-3764fe5e0484)

**Comment by ariel-dao** [comment]
on it

**Comment by ariel-dao** [comment]
deployed to dev, tested on your example @NoamQA
