### ISSUE TITLE
Edit space - name uniqueness error

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1836]
Getting the following error when trying to edit space's about.
See also Andrey's comment [here](https://github.com/daostack/common-web/issues/1403#issuecomment-1501387135), so should allow sending the same name if the edited common (space) is the same common (space) with this name

![Image](https://github.com/daostack/common-backend/assets/72435714/578dbb9e-c6a6-4897-8d7e-4fd239933426)

**Comment by ariel-dao** [comment]
on dev, sending same name should no longer trigger error.

i.e common name is "random name", sending "random name" in the update will not fail the request

**Comment by NoamQA** [comment]
:white_check_mark: works fine in DEV env.
it is now possible to edit a space
