### ISSUE TITLE
Fix to show correct names on mentions

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1838]
When the `displayName` field of that user is empty we get an empty user name in mention list.

In this case we should use the `firstName `+ `LastName` fields instead (and if empty use email, and if empty use phone number).
We should either make sure to populate the display name for each user (new users+ migration) or alternatively read this data when creating the users list for "Mention".

See the related FE ticket here: https://github.com/daostack/common-web/issues/1606

**Comment by ariel-dao** [comment]
@elatif2020 @andreymikhadyuk Not a backend issue as far as I see, backend saves user ids not names.

**Comment by andreymikhadyuk** [comment]
@MeyerPV Check the comment above please.

**Comment by NoamQA** [comment]
@elatif2020 
how come displayName field of a user is empty?
how can i reproduce it?
is there a way i can check this ticket in web stage?
because i uploaded it for PROD env.
