### ISSUE TITLE
Moderation - Proposal - Report Proposal screen contain uncompleted problem

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#184]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Steps to reproduce:
1. Go To a proposal as a regular/moderator user
2. Click on the proposal menu
3. Click on Report

Actual results:
The screen contain Uncompleted problem see attached image
![File (57)](https://user-images.githubusercontent.com/69141571/110234696-8cab5e00-7f34-11eb-92e8-0de8899297bf.jpg)

Expected results:
Should display "Violates the common agenda"

**Comment by yanivi71** [comment]
@watchtower314 not fixed. I moved to "in progress column

**Comment by watchtower314** [comment]
@yanivi71  This is what I see on iPhone 11, XR, and Nexsus 5X

<img width="343" alt="Screen Shot 2021-03-08 at 15 45 23" src="https://user-images.githubusercontent.com/30501647/110379960-7b8e4a00-8025-11eb-844c-6bed4253f1ac.png">

<img width="372" alt="Screen Shot 2021-03-08 at 15 43 40" src="https://user-images.githubusercontent.com/30501647/110379962-7c26e080-8025-11eb-9676-469b5a2588d4.png">


<img width="352" alt="Screen Shot 2021-03-08 at 15 45 37" src="https://user-images.githubusercontent.com/30501647/110379956-79c48680-8025-11eb-99fd-134401a2e652.png">

<img width="360" alt="Screen Shot 2021-03-08 at 15 50 42" src="https://user-images.githubusercontent.com/30501647/110380420-1129d980-8026-11eb-9537-90e6224d5aea.png">
