### ISSUE TITLE
Immediate, single vote approval for proposals

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1844]
will be used for join circle requests

**Comment by elatif2020** [comment]
@danielr18 
Please add here the details on the implementation

by "Join circle request" I mean ASSIGN_TO_CIRCLE proposal created by the user for himself.
After closing this ticket we will follow up with changes in the gov templates (+migration) and changes in the FE (we will need change the appearance of the proposal block for this type of proposals)

**Comment by danielr18** [comment]
The solution adds a `resolutionType` property to the proposal which is either `IMMEDIATE` or `WAIT_FOR_EXPIRATION`.

- `WAIT_FOR_EXPIRATION`: Current behavior.
- `IMMEDIATE`: The proposal will be checked if it has passed every minute. Once it passes, it will finalize.

It also adds `minApproveUnit` and `maxRejectUnit` to governances, to support single vote proposals that would be defined with:

```
minApproveUnit: 'absolute',
minApprove: 1,
```

**Comment by elatif2020** [comment]
> The solution adds a `resolutionType` property to the proposal which is either `IMMEDIATE` or `WAIT_FOR_EXPIRATION`.
> 
> - `WAIT_FOR_EXPIRATION`: Current behavior.
> - `IMMEDIATE`: The proposal will be checked if it has passed every minute. Once it passes, it will finalize.
> 
> It also adds `minApproveUnit` and `maxRejectUnit` to governances, to support single vote proposals that would be defined with:
> 
> ```
> minApproveUnit: 'absolute',
> minApprove: 1,
> ```
> 

sounds good

**Comment by elatif2020** [comment]
@danielr18 @ariel-dao 
Getting an error with creating a new space, with code 400 (maxRejectUnit validation):
![image](https://github.com/daostack/common-backend/assets/72435714/954b388d-0734-43b3-9b89-b45d306e9d5c)
![image](https://github.com/daostack/common-backend/assets/72435714/a758263c-0caf-499b-b5d8-f58bd2a5f883)
If possible maybe it would be better to allow the new parameters to be not defined (with the current behavior)
