### ISSUE TITLE
Update last message preview on edit\delete

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1846]
If the last message in the chat is edited or deleted we should update the last message preview text on the card
#1858 might be related

**Comment by NoamQA** [comment]
:white_check_mark: works fine in DEV env.

**Comment by NoamQA** [comment]
@danielr18 
:x: last message preview and time of it doesnt change now in dev. when delete it
only in inbox preview change but it disappears instead of showing the new last message
![image](https://github.com/daostack/common-backend/assets/129174316/5b3cffee-4b84-44f9-a392-0cdb633162a7)

**Comment by elatif2020** [comment]
Creating new issues for related fixes:

1. #1915 
2. #1916
