### ISSUE TITLE
Update users' new messages counters on delete

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1847]
If a message is deleted from the chat we should make sure the counter is updated for all the members of this common. 
(Maybe we should somehow check if there are users for whom this message is included in the new messages counter and decrease the counter, or somehow make sure to calculate the counter correctly when needed. )

Also a migration to recount the messages

**Comment by ariel-dao** [comment]
@elatif2020 Chat or discussion?

**Comment by elatif2020** [comment]
> @elatif2020 Chat or discussion?

this is about deletion of a message in the discussion

**Comment by NoamQA** [comment]
@danielr18 

:x: counter and preview not updated after message delete

![Image](https://github.com/daostack/common-backend/assets/129174316/fb121ac9-ce54-4066-8546-ebb4850fe151)
