### ISSUE TITLE
Unfollow all relevant items on leave common

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1848]
If a user leaves a common he should unfollow all items from that common (and recursively for any sub-commons it might effect).

**Comment by elatif2020** [comment]
Related work have been done as part of #1917
Need to fix\confirm it was done properly

**Comment by ariel-dao** [comment]
@elatif2020 Unrelated, unfollow in this task should be handled differently

**Comment by ariel-dao** [comment]
Deployed to dev, expensive function but there was no other worthy way around it with Firestore.

Will remove all inbox, feedItemFollows and commonFeedObjectUnique entitiy related to the feed items.

Doesn't include logic for chat channels as there could be multiple shared commons and this is not checked in this logic for now.

**Comment by NoamQA** [comment]
@ariel-dao @elatif2020 
i get an error message when try to leave a common or a space
opened a separate [ticket](https://github.com/daostack/common-web/issues/1852)
will test this one after it solved

**Comment by NoamQA** [comment]
@ariel-dao 
:x: when leave a common/space - the general channel keeps appearing in the inbox


![Image](https://github.com/daostack/common-backend/assets/129174316/ab57e6d8-6574-466e-8676-df5cd0a150fd)

**Comment by ariel-dao** [comment]
deployed fix to dev
