### ISSUE TITLE
Notification screen - Clicking on new proposal display "undefine votes"

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#185]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Steps to reproduce:
1. Go to notification screen
2. Click on "new proposal" (the proposal is rejected )

Actual results:
user is navigate to the proposal page.
but votes display "undefined votes" - see attached image

Expected results:
Should display "X votes" if there was a voting
on display "No votes yet" if no one voted. 

![File (58)](https://user-images.githubusercontent.com/69141571/110234902-b9ac4080-7f35-11eb-8029-a0e9254766e9.jpg)

**Comment by watchtower314** [comment]
fix will be in this pr: https://github.com/daostack/common/pull/962

**Comment by kazaryan-t** [comment]
Tested on Staging Android version 1.9.5 (4978-197)
Tested on Staging iOS version 1.9.5 (4978-236)

When clicking on the New proposal notification on the Notifications tab the user navigates to the proposal page, but votes display "No votes yet" even if there are some votes for approval or rejection. 
Please, see attached screenshots.

![Screenshot_20210312-114831_common-stg](https://user-images.githubusercontent.com/68247034/110917445-f9ef3280-832a-11eb-9e53-8ae79107b292.jpg)
![Screenshot_20210312-120221_common-stg](https://user-images.githubusercontent.com/68247034/110917450-fb205f80-832a-11eb-9938-f542f8ee852b.jpg)

Expected result:
Should display "X votes" if there are some votes, or display "No votes yet" if no one voted.

![Screenshot_20210312-115823_common-stg](https://user-images.githubusercontent.com/68247034/110917526-0d020280-832b-11eb-8841-728e31fd073b.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-240)
Tested on Staging Android version 1.9.5 (4978-2001)

Found OK
No it display the vote number. when vote is empty it display "no votes yet"

**Comment by yanivi71** [comment]
Verified on Production
