### ISSUE TITLE
Moderation - Hidden content - View - Moderator/regular use note is not display

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#186]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Steps to reproduce:
1. Go to a Content (proposal comment....) as regular/moderator user
2. Report on the content 
3. Choose several problems
4. add note
5. click on report.
6. As a moderator hide this content
7. as regular/moderato view this contents

Actual results:
Display a message with hidden content with all the problems but the nite does not display - see attached image

Expected results:
Messages must display with hidden content problems and note - see attached image

![image (18)](https://user-images.githubusercontent.com/69141571/110235477-df871480-7f38-11eb-86b1-808fd1863da4.png)

![Screenshot_20210307-112116_common-stg](https://user-images.githubusercontent.com/69141571/110235327-20caf480-7f38-11eb-8759-45e255036456.jpg)

**Comment by watchtower314** [comment]
This also has a backend fix which was merged to main but not to staging

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-243)
Tested on Staging Android version 1.9.5 (4978-204)

Found OK
Messages is display with hidden content problems and note
@watchtower314 There is an issue that the note does not seen in full. I will open a new issue on this

**Comment by yanivi71** [comment]
Verified on Production
