### ISSUE TITLE
when delete a discussion- it can be opened via the email link

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#1869]
when creating a discussion i get mail for it with a link
if i delete the discussion i can still open it with the link
for example [this ](https://web-staging.common.io/commons/cebec23e-1de5-45a8-9d62-617fe627b445?item=ac3cab31-20cf-43e9-9a82-a1c491a6ca9d)discussion

if you open it and move to another item it will disappear

**Comment by elatif2020** [comment]
This is the desired behavior currently
