### ISSUE TITLE
PROD- error 500 when trying to create a new space

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#1873]
error when trying to create a new space (project) from a newly created common, with the following message in the console: "actions in circle are not contained in the governance definition (a4dcf40a-3cc3-4d7b-999d-e929c1c30bdd)"

(notion ticket [here](https://www.notion.so/daostack/Opening-a-new-space-failed-and-stuck-d04e30fa2eb94a3aa31eeaa55396dd9c?pvs=4))

**Comment by danielr18** [comment]
Closed by https://github.com/daostack/common-backend/pull/1878
