### ISSUE TITLE
user profile - Log out - When user is logout and relogin he gets endless loading - Regression

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#188]
Tested on Staging Android version 1.9.5 (4978-189)

**Reported on Samsung galaxy A51** 

Steps to reproduce:
1. open the app
2. login with user
3. Go to profile and log out
4. login again with the same user

Actual results:
1. Endless loading. 
2. user have to close the app and open it again
3. when user logged it and go to notification screen he get endless loading and the notifications screen is not display

When i performed clear cash from the app i could see the notification screen 

Expected results:
User must login again and see his notification screen

**Comment by watchtower314** [comment]
Update: seems like the loading is not endless, it ends eventually, but it takes too much time

https://user-images.githubusercontent.com/30501647/110305140-6801c580-7fca-11eb-8709-f0a9d4c2c06b.mov
