### ISSUE TITLE
Chat messages endpoint doesn't return correct data

### ISSUE THREAD

**Issue by andreymikhadyuk** [daostack/common-backend#1885]
Env: `dev`
Endpoint: `GET /chat/channel/422afc39-9def-4a21-bbd7-a6b0de652488/messages?limit=50`

1. `messageCount` of the channel says `0`, but there are 4 messages at the moment;
2. The channel has some messages, but endpoint doesn't return them. I get:
```
{
    "message": "Chat channel messages fetched successfully",
    "data": {
        "chatMessages": [],
        "firstDocTimestamp": null,
        "lastDocTimestamp": null,
        "count": 0,
        "hasMore": false
    }
}
```
3. I do not see `chatChannelUserUnique` sub-collection under chat channel.

**Comment by ariel-dao** [comment]
1. Fixed
2. Fixed
3. Can't reproduce I see it:
![image](https://github.com/daostack/common-backend/assets/89919079/52459f92-bdef-4ff9-af04-aff662a542b3)

Deployed to dev
