### ISSUE TITLE
inbox counter increase when there are more than 1 message in a stream (should stay the same as this counter should count the number of streams with new messages) (BE)

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1892]

**Comment by ariel-dao** [comment]
removed duplicated inbox counter, will now be calculated on the fly based on chat channel and common feed object user uniques
deployed to dev

**Comment by NoamQA** [comment]
to be tested after counter issues fixed [#1347 ](https://github.com/daostack/common-web/issues/1347)

**Comment by elatif2020** [comment]
> to be tested after counter issues fixed [#1347 ](https://github.com/daostack/common-web/issues/1347)

@NoamQA it might worth it if you could already test it
