### ISSUE TITLE
When there are no new messages in the inbox, and i add one in a stream - the Inbox counter shows higher number then 1 (not sure is it BE or FE, probably BE)

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1893]

**Comment by ariel-dao** [comment]
@elatif2020 Probably because of system messages

**Comment by elatif2020** [comment]
> @elatif2020 Probably because of system messages

Interesting Ok let's see when we will have the system messages visible

**Comment by elatif2020** [comment]
Closing this ticket.
Created a new ticket for fixing the Inbox counter, here: https://github.com/daostack/common-backend/issues/1917
