### ISSUE TITLE
BE app notification for new messages

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1895]
- [x] clean all existing notifications from the db (for now in dev)
- [ ] #1997

Next let's make changes to make the `messageCreated` notifications functional:

- [x] Address also messages from dm's (channels)
- [x] Trigger a notification only for new messages in channels (dm) or discussions\proposals which are **followed** by the user (notice that in particular a message mentioning this user or a new reply to user's message should appear)
- [x] Filter out messages the user wrote (so I should not get notifications for my own message) and also system messages. except messages about a creation of a new subspace that should be displayed without the "System" userName. 
- [x] Data to be included in the notification: For items which are discussions\proposals the notification should be the following: `senderName`, `itemTitle` , `messagePreview`, `creation time` of the message, the avatar of the common (or space) it is in, the name of the common (it will be the title). Here `messagePreview` should be the same that we display in the last message preview, including indication to add image\file icon if there are. If the user is mentioned it should be indicated to display additional icon in the notification. It should also be indicated if it's a reply to a message. 
- [x] Similarly, for channels (dm's) the notification should be just: "`messagePreview`" it should include the `creation time` of the message and the avatar of the other user. The name of the other user should be the title of this notification.
- [x] We should make sure to delete a notification if the relevant message is deleted, and to update it if it's edited.
- [x] Notifications should include the url path to the relevant items. It should be of the format `/inbox?item=itemId&message=messageId`.
- [x] Of course, notifications should disappear once the relevant message has been read. But additionally, it should disappear when the user opens the inbox. We might need a new variable for this for each user, something like `lastSeenInbox`.  **NOTE: there is already seen logic on BE for this (seen array)**
- [x] If there are several messages from the same feedItem\channel they should be aggregated. Not sure whether the aggregation should be done in the FE or BE. Messages from the same sender should be displayed without displaying the userName again, and with the latest time once. If there are messages from multiple senders we just need the messages from the last user, the first unread message, and the number of unread messages.  **NOTE: SHOULD BE DONE ON FE, MARKING AS SOLVED FOR BE**

**Comment by ariel-dao** [comment]
Keeping it open for more changes, for now what is done up until now (which is what was marked as this point in time) is ready for checking on FE @elatif2020 @MeyerPV @andreymikhadyuk

**Comment by ariel-dao** [comment]
@elatif2020 I've tried to set the definition for a chat message but the structure is different with the visibility options and the following, could you please provide who this notification should be sent to and the exact structure of the payload? Thank you

**Comment by elatif2020** [comment]
> @elatif2020 I've tried to set the definition for a chat message but the structure is different with the visibility options and the following, could you please provide who this notification should be sent to and the exact structure of the payload? Thank you

@ariel-dao 
For channels (dm) notification should appear only to the other user(s), for any new unseen message (according also to lastSeenInbox)
the data:
`senderName` (for dms. If there are 3 or more participants in the channel it should be different) = the title of this notification 
`messagePreview`
`creation time` of the message 
`senderAvatar`

Similar to the specification for discussions, also here `messagePreview` should be the same that we display in the last message preview, including indication to add image\file icon if there are. It should also be indicated if it's a reply to a message.

**Comment by ariel-dao** [comment]
deployed chat message definition to dev

**Comment by elatif2020** [comment]
@ariel-dao I have created a separate ticket for the feature toggles, here https://github.com/daostack/common-backend/issues/1997 
So we can close this ticket once it works with the app
