### ISSUE TITLE
Sort new dm user list not to be case-sensitive

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#1908]
connected to [#1686](https://github.com/daostack/common-web/issues/1686)

BE issue

![Image](https://user-images.githubusercontent.com/129174316/245712644-3493829c-7869-4f97-9915-8078c5dbae8b.png)

**Comment by andreymikhadyuk** [comment]
@NoamQA @elatif2020 What is the issue exactly? It is correct sorting from the characters perspective. All lower case letters are lower in sorting than all upper case letters. So for me everything is fine on the screenshot.

**Comment by NoamQA** [comment]
@andreymikhadyuk @elatif2020 

i think it should be sorted alphabetically without connection if its upper or lower case
so all that starts with an "a" will be first regardless upper/lower case

**Comment by andreymikhadyuk** [comment]
@elatif2020 Please elaborate on this.

**Comment by elatif2020** [comment]
> @elatif2020 Please elaborate on this.

Yes, I agree, sorting should not be case sensitive @andreymikhadyuk

**Comment by ariel-dao** [comment]
deployed to dev
