### ISSUE TITLE
Add size property for files atached to messages

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1909]
related to https://github.com/daostack/common-web/issues/1690

file size property 
to be given upon uploading a file
and is read to be displayed on the message with the file

**Comment by ariel-dao** [comment]
@elatif2020 More info please

**Comment by elatif2020** [comment]
> @elatif2020 More info please

@ariel-dao added above

**Comment by MeyerPV** [comment]
We should add `size`  property to uploaded files - number type

![Image](https://github.com/daostack/common-backend/assets/35873164/736320f7-8348-4a2e-871b-14da029d8be6)
