### ISSUE TITLE
Notification screen - "Common created" is display to all members includes the one who create it

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#191]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Steps to reproduce:
1. Create a new Common
2. Whitelist this common

Actual results:
notification "Common created" is display to all members includes the one who create it

Expected results:
all members should get the notification except the user who created the common

![Screenshot_20210307-160903_common-stg](https://user-images.githubusercontent.com/69141571/110242644-a4e4a280-7f5f-11eb-8ba7-1de4ca4e6894.jpg)
![Screenshot_20210307-160835_common-stg](https://user-images.githubusercontent.com/69141571/110242646-a7df9300-7f5f-11eb-841d-b09e3e119a78.jpg)

**Comment by IvanSantiagoUk** [comment]
mmm this can be tricky let's chat on the call about

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-239)
Tested on Staging Android version 1.9.5 (4978-200)

Found ok
all members gets the notification except the user who created the common
The title that display is "New Featured Common"

**Comment by yanivi71** [comment]
verified on Production
