### ISSUE TITLE
BE fixs for DM

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1910]
- [x] after editing a message editedAt field is not added/changed

- [x] error in the endpoint for deleting a chat message

**Comment by ariel-dao** [comment]
deployed to dev

**Comment by elatif2020** [comment]
@andreymikhadyuk fyi

**Comment by andreymikhadyuk** [comment]
@elatif2020 @NoamQA Seems that everything works fine.

**Comment by NoamQA** [comment]
@andreymikhadyuk @elatif2020 
also looks fine to me
opened a related ticket for issue i found [#1722](https://github.com/daostack/common-web/issues/1722)
