### ISSUE TITLE
DM (chat messages) last seen fixs

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1911]
- [x] If we have some messages in a chat and then delete the last one, the lastMessage field is removed from chat channel entity and is not updated to the previous one.
- [x] How can I mark chat channel as seen once when there are no messages?
- [x] As I see when I send a new chat message, then lastSeenChatMessageId field of other user’s unique data is updated with the id of the new message. I think that field should not be changed on new message sending.

**Comment by NoamQA** [comment]
@ariel-dao 
:x: when i delete last message- preview become empty
and the previous message doesnt shown

also when i edit last message- preview doesnt change


![Image](https://github.com/daostack/common-backend/assets/129174316/dc980d3b-5058-4ee9-8c74-3559eea6593c)


also counter doesnt decrease 

happens in dev+web stage

![Image](https://github.com/daostack/common-backend/assets/129174316/8bcbdcbb-9b65-4039-a820-ab6eaed7ff01)

**Comment by elatif2020** [comment]
@ariel-dao please check, see @NoamQA's comment

**Comment by ariel-dao** [comment]
Fixed, deployed to dev, should also be deployed to prod asap

**Comment by elatif2020** [comment]
> Fixed, deployed to dev, should also be deployed to prod asap

@ariel-dao 
Did you deployed it to staging and to production?
If not please deploy first to staging and lmk so we will test it
