### ISSUE TITLE
Fix the logic for marking my own messages as seen

### ISSUE THREAD

**Issue by andreymikhadyuk** [daostack/common-backend#1913]
Currently many times my own messages appears as unseen for me.

**Comment by elatif2020** [comment]
~~old description: We should record the last time that each chat is open for a user (preferably we should mark it open only if it's scrolled down to the bottom with same margin), i.e. the last time before closing\ moving to another chat.
If there are new messages after this time the separator should appear before the first new message (and before the first date separator if there is such).~~

**Comment by ariel-dao** [comment]
Fixed deployed to dev, includes critical fixes that need to be deployed to production @elatif2020
