### ISSUE TITLE
Fix last message preview upon edit of the last message for channels (dm)

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1916]
following https://github.com/daostack/common-backend/issues/1846#issuecomment-1596027374
 
Upon edit of the last message in the chat, the last message preview is updated for discussions but isn't updated chat channels (dm). It should be similar.

**Comment by ariel-dao** [comment]
deployed to dev, update chat message endpoint now returns full chat message (after update) and not partial update data

**Comment by elatif2020** [comment]
> deployed to dev, update chat message endpoint now returns full chat message (after update) and not partial update data

@ariel-dao 
was it deployed to staging and production?

**Comment by NoamQA** [comment]
opened related ticket #1956
