### ISSUE TITLE
Fix Inbox counter

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1917]
The inbox counter should match the total number of streams with unread messages \ "new" tag which appear in the inbox.

Inbox counter should increase when there is 
- new message(s) in a stream the user is following, which didn't had new activity before
- new dm message(s) (in a channel which didn't had new activity before)
- The user follows a new stream with new activity (either by joining a space or being mentioned)

The inbox counter should decrease in some cases:
- The user opens a stream with new activity
- The user stops following a stream with new activity
- User lose access to the followed stream with new activity (when leaving a circle\ leaving a common)
- New activity have been deleted (all new messages deleted\ feed item deleted\ common deleted)

Should make sure to filter out from the counter:

- System messages
- Streams which are filtered from the feed, such as Member admittance and Assign circle proposals

**Comment by ariel-dao** [comment]
@elatif2020 Deployed to dev

**Comment by ariel-dao** [comment]
https://github.com/daostack/common-backend/commit/6cdaef4d44f714818ab0babdfe68b60db8f6148e

**Comment by ariel-dao** [comment]
I've made sure all options are working correctly, but I think that:
* User lose access to the followed stream with new activity (when leaving a circle\ leaving a common)
* New activity have been deleted (all new messages deleted\ feed item deleted\ common deleted)
Are not enforced properly yet with the deletion so there might be some issues specifically in those areas, I suggest to make a task to set up (or make sure) proper deletion for stale data in response to common deletion etc

**Comment by NoamQA** [comment]
it looks good on dev
opened a separate ticket for a bug on delete #1947
