### ISSUE TITLE
Notification screen - The notification screen is not refreshed with new notification

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#192]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Steps to reproduce:
1. Go to a common you are a member (verify there are several members)
2. Create a new proposal
3. Go to notification screen

Actual results:
1. Proposal is created 
2. Push Notification is sent to all users
3. notification screen is not refreshed with new notification - when user reopen the app the notification appear

Expected results:
 The notification screen must refreshed with new notification

**Comment by IvanSantiagoUk** [comment]
Related with data management @lpetkov-sw

**Comment by kazaryan-t** [comment]
Tested on Staging Android version 1.9.5 (4978-198)
Tested on Staging iOS version 1.9.5 (4978-237)

The notification screen is still not refreshed with the new notifications.

**Comment by watchtower314** [comment]
Notifications that aren't refreshed:
- New discussion

********

Notifications that are refreshed:
- New proposal

https://user-images.githubusercontent.com/30501647/111067364-45741e80-849a-11eb-9446-681a9381f501.mov

- New comment 

https://user-images.githubusercontent.com/30501647/111067357-40af6a80-849a-11eb-8b6b-ed29aaa1b399.mov

- Membership request

https://user-images.githubusercontent.com/30501647/111067436-9b48c680-849a-11eb-8d17-90f47ad466cb.mov

**Comment by watchtower314** [comment]
pr with demo: https://github.com/daostack/common/pull/974

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-240)
Tested on Staging Android version 1.9.5 (4978-2001)

Found OK
The notification screen is refreshed with new notification

**Comment by yanivi71** [comment]
Verified on Production
