### ISSUE TITLE
Feed items counter doesn't increase when a user writes in multiple streams

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1928]
this is an example from web stage
i wrote comments in few channels
but the counter appear only in the first one

![Image](https://github.com/daostack/common-backend/assets/72435714/a9951749-f179-4921-978f-e985678197eb)

**Comment by elatif2020** [comment]
@NoamQA could be useful if you could check this ticket

**Comment by NoamQA** [comment]
@elatif2020 
strange...
it only happens in wed stage
works fine in dev+prod
