### ISSUE TITLE
Notification screen - issues that not implemented

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#193]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Steps to reproduce:
1. Open the app
2. get new notification

Actual results:
1. there is no indication for new notification on the notification icon 
2. No Welcome notification

Expected results:
1. Should display red dot when new notification arrive
2. welcome notification message should be displayed

![image](https://user-images.githubusercontent.com/69141571/110246914-44129580-7f72-11eb-9275-977d7968e73f.png)

**Comment by kazaryan-t** [comment]
Tested on Staging Android version 1.9.5 (4978-197)
Tested on Staging iOS version 1.9.5 (4978-236)

There is no red dot for unread notifications on the notification tab icon.
Design - https://zpl.io/bP6d74p

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-249)
Tested on Staging Android version 1.9.5 (4978-210)

Some mismatchings (red dot appearance and disappearance) that should be fixed or implemented, are described in the comment for https://github.com/daostack/common-monorepo/issues/276 issue.

**Comment by yanivi71** [comment]
Verified on production
