### ISSUE TITLE
Create a script to reset counters to zero

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1930]
- [x] Given a user id reset to 0 all the counters of that user (in this case also the inbox counter should be reset to 0)
- [x] On a trigger reset to 0 the counters of all users

**Comment by ariel-dao** [comment]
Should I run it? @elatif2020

**Comment by ariel-dao** [comment]
The script is created

**Comment by ariel-dao** [comment]
https://github.com/daostack/common-backend/commit/23f3ffaebffbfe0cfbac3d7d87068bc9ab9c8387

**Comment by NoamQA** [comment]
@elatif2020 
i moved the to the current sprint
lets run it to see that it works?
the issue of unread messages counter that doesnt reset in old discussions also happens in PROD
so we will need to run it also there if it works in DEV

**Comment by ariel-dao** [comment]
Reopening to track script execution

**Comment by elatif2020** [comment]
> Should I run it? @elatif2020

@ariel-dao (@NoamQA fyi)
Yes please execute for all users (or all active users) on all environments. 
Please start with Dev & Staging to test it is working correctly

**Comment by danielr18** [comment]
Script was run in dev and staging

**Comment by NoamQA** [comment]
@danielr18 
i have users that for them there is no main bar counters
but have number in the inbox counter
so we need to make sure that both of them are reset
![image](https://github.com/daostack/common-backend/assets/129174316/1f798eb5-892b-4e4c-a67c-74ff7c117721)

**Comment by danielr18** [comment]
@NoamQA Can you check again?

**Comment by NoamQA** [comment]
@danielr18 
inbox counters are reset now
also for channels 
but not for direct messages 
could be that its OK for us
@elatif2020 what do you think?

![image](https://github.com/daostack/common-backend/assets/129174316/9a97c853-8a9e-445e-9c5a-d3448137c17a)

**Comment by elatif2020** [comment]
ok yes it's good enough
@NoamQA @danielr18 
Let's run it in production 🚀 🙏

**Comment by NoamQA** [comment]
@danielr18 
great
let me know when its done and i will test

**Comment by danielr18** [comment]
@NoamQA It's done
