### ISSUE TITLE
Migrations to cleanup deleted items

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1931]
- [x] correct feed items counters in the case that deleted messages are counted
- [x] update lastMessage previews and the updatedAt field if last message is deleted

- [x] Clean from the inbox\feedItemsFollow feed items that have been deleted
- [x] Clean from the inbox\feedItemsFollow feed items from commons that doesn't exist anymore

**Comment by danielr18** [comment]
Feed items cleaned in all environments
