### ISSUE TITLE
Migration to fix old system messages

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1932]
We have to fix those old system messages that appear incorrectly to the correct format

![Image](https://user-images.githubusercontent.com/72435714/247695275-90a65339-560b-4996-bc29-edadb31c99b7.png)

**Comment by NoamQA** [comment]
@elatif2020 
it looks good in spaces i tested on PROD
can you see that it also fixed in the one shown in the picture?
i am not a member there...

**Comment by elatif2020** [comment]
> @elatif2020 it looks good in spaces i tested on PROD can you see that it also fixed in the one shown in the picture? i am not a member there...

@NoamQA 
Old system messages have been deleted as we discussed in our sync meeting. Also for the common in the picture
