### ISSUE TITLE
Add 'name' property for files attached in chats

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1933]
@MeyerPV : I get file name from firebase storage and it changed to avoid file duplication. We can add `name `property to the file to keep the original file names

**Comment by ariel-dao** [comment]
![image](https://github.com/daostack/common-backend/assets/89919079/3a4836cf-1ebc-42a5-9fe6-0c643e389fa4)
The link to a file is saved as a link and it has a title

**Comment by danielr18** [comment]
From Pavel:
> we cannot rely on title, because it generates on frontend side for avoiding duplication of files
We want name property for exact file name

**Comment by ariel-dao** [comment]
deployed to dev @MeyerPV
