### ISSUE TITLE
Join space error (migration)

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1934]
`{"error":"Cannot read properties of undefined (reading 'defaultCircle') (977190cd-d0ef-4933-af02-393e3a3d989a)","errorName":"Common Error","errorId":"977190cd-d0ef-4933-af02-393e3a3d989a","errorCode":"GenericError","errorMessage":"Something bad happened.","request":{"id":"51998537-728f-4d60-a980-22edfa162fd8","body":{"args":{"commonId":"be00dded-ff92-43d0-b9fd-32c1d81fbd6d","description":"hi","images":[],"files":[],"links":[],"title":"Membership request from Latif Eliaz","feeMonthly":null,"feeOneTime":null},"type":"MEMBER_ADMITTANCE"},"query":{},"headers":...`

**Comment by danielr18** [comment]
Migration was fixed, data corrected and migration rerun in all environments
