### ISSUE TITLE
PROD -inbox - duplication in some items

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#1936]
there are 2 duplicated items in my inbox on PROD env.
doesnt happens in DEV

![Image](https://user-images.githubusercontent.com/129174316/248540948-c04c5237-4149-43eb-bfdd-b476fa0674e8.png)

**Comment by elatif2020** [comment]
@NoamQA 
does it stays after refresh? 
do you have duplicate items also for other users?

**Comment by NoamQA** [comment]
@elatif2020 
it only happens in one user that i tested PROD with
and stays after refresh
these are spaces that was created in 2.6.23 and not an old ones
this is a [link ](https://common.io/commons/a21308ea-9e44-47d5-8bb9-2afd03857179?item=3179c85b-b070-41f1-82bf-cb67a7901d9d&message=f6d718ea-0eb0-449f-ae8a-76af0f3d11da)to a message in one of the duplications

i cant reproduce it...
![image](https://github.com/daostack/common-web/assets/129174316/359616c2-f6be-400d-b129-6fda60629d5f)

**Comment by elatif2020** [comment]
@NoamQA 
Could you try writing a message there and see if it change?

**Comment by NoamQA** [comment]
@elatif2020 
still appears twice...
![image](https://github.com/daostack/common-web/assets/129174316/a929ad54-33f2-451a-bdb4-0e88681f12a1)

**Comment by elatif2020** [comment]
@NoamQA 
Which email address this user is logged in with?

**Comment by NoamQA** [comment]
@elatif2020 
workinginbox33@gmail.com

**Comment by NoamQA** [comment]
@elatif2020 
it still happens for the same items in prod
only in one of me test users


![Image](https://github.com/daostack/common-backend/assets/129174316/e917d69c-8dcc-42fa-b5e2-b2fe326d780b)
