### ISSUE TITLE
Can't create a space with the same name of a previously deleted space

### ISSUE THREAD

**Issue by roienatan** [daostack/common-backend#1938]
If you create a space, delete it and try to create a new space with the same name I get an error `msg: "Name must be unique"`

**Comment by NoamQA** [comment]
@danielr18 @elatif2020 
now i can create 2 spaces with same name
is it OK for us?


![Image](https://github.com/daostack/common-backend/assets/129174316/1b47d626-bf85-4a53-b402-148c72cce1f1)

**Comment by elatif2020** [comment]
> @danielr18 @elatif2020 now i can create 2 spaces with same name is it OK for us?
> 
> ![Image](https://private-user-images.githubusercontent.com/129174316/249716454-1b47d626-bf85-4a53-b402-148c72cce1f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJrZXkxIiwiZXhwIjoxNjg4MTM1ODE3LCJuYmYiOjE2ODgxMzU1MTcsInBhdGgiOiIvMTI5MTc0MzE2LzI0OTcxNjQ1NC0xYjQ3ZDYyNi1iZjg1LTRhNTMtYjQwMi0xNDhjNzJjY2UxZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzA2MzBUMTQzMTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjI1ZDlhODIyNDEyYzBlODI1YjdjMGIwMjNmNmQyOWU1Y2I1YmQwZTdkMDUxYWE3YTQ5MzJiNTM3MTViMjNhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-rbfGXpnzJRIo-Nm95P7IPPAVVRLHskbdMmoIQHgFgQ)

no we should not have two subspaces (of the same common) alive with the same name
@danielr18 @NoamQA

**Comment by danielr18** [comment]
@NoamQA Can you create a list of steps to recreate?
<img width="1728" alt="image" src="https://github.com/daostack/common-backend/assets/9046616/dd17027b-31a5-432c-8a3e-e7a4b515d1f7">

**Comment by NoamQA** [comment]
@danielr18 
yes
create a new space
insert a name of an exist space
it lets you save it
so there are 2 spaces with the same name

**Comment by elatif2020** [comment]
@NoamQA 
Are you sure it does so?
Now I also can't reproduce

**Comment by NoamQA** [comment]
@danielr18 
you are right
now i get an error message
should be a message that it is impossible to create a space with exist name
something like- 
"there is already a space with the chosen name
please change space name"
@elatif2020 - do you want to write what should be in the message?

![image](https://github.com/daostack/common-backend/assets/129174316/2c7aab13-718c-4768-a2d2-6927d081fb8d)

**Comment by elatif2020** [comment]
Yes:

Space name $spaceName is already in use, please choose another name.

@NoamQA Could you create a FE ticket for this?

**Comment by NoamQA** [comment]
@danielr18 @elatif2020 
now on dev + web stage  i can create a space with exist name
can you check?
it worked yesterday... 


![Image](https://github.com/daostack/common-backend/assets/129174316/fcd49085-3b4c-4166-85b1-8755ccea9ad7)

**Comment by danielr18** [comment]
I believe this is a FE issue where the deleted space still shows up until you refresh.
`space no image` was deleted, the circle was renamed, and thus it allowed you to create a project with the same name

**Comment by NoamQA** [comment]
works fine on dev
opened separate [ticket ](https://github.com/daostack/common-web/issues/1799)for refresh
