### ISSUE TITLE
Google: Refresh Token for mobile

### ISSUE THREAD

**Issue by MeyerPV** [daostack/common-backend#1944]
https://levelup.gitconnected.com/handling-access-tokens-for-google-apis-with-react-node-js-tutorial-5ebf94d8f90f

https://console.firebase.google.com/u/1/project/common-dev-dea4e/authentication/providers

Client secret and client Id you can get from 
![Screenshot 2023-06-26 at 11 35 47](https://github.com/daostack/common-backend/assets/35873164/cf4e9044-7274-4532-a249-7dff3b86b1fa)

Example of code
```
app.post("/getValidToken", async (req, res) => {
  try {
    const request = await fetch("https://www.googleapis.com/oauth2/v4/token", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        client_id: process.env.GOOGLE_CLIENT_ID,
        client_secret: process.env.GOOGLE_CLIENT_SECRET,
        refresh_token: req.body.refreshToken,
        grant_type: "refresh_token",
      }),
    });

    const data = await request.json();
    console.log("server 74 | data", data.access_token);

    res.json({
      accessToken: data.access_token,
    });
  } catch (error) {
    res.json({ error: error.message });
  }
});
```

**Comment by elatif2020** [comment]
As I understand we still have an issue with this. @MeyerPV correct?
I'm reopening this ticket

**Comment by elatif2020** [comment]
@ariel-dao @danielr18 
We were discussing this issue today. Maybe it was already implemented?

**Comment by danielr18** [comment]
The endpoint has been implemented, however, the mobile app was not getting a refresh token so it wasn't able to test it

**Comment by elatif2020** [comment]
@danielr18 I assume this ticket merged to staging, correct?
