### ISSUE TITLE
inbox counter- when delete last message the counter doesnt decrease

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#1947]
when there is 1 new message in a channel the inbox counter increase
but when i delete it the channel counter disappear
but the inbox counter remains
also after refresh

same when i delete a channel with new messages in it

related to #1917

**Comment by ariel-dao** [comment]
deployed to dev

**Comment by NoamQA** [comment]
@ariel-dao @elatif2020 
now the inbox decrease 
still needs to refresh or make an action for it to happen
to open a ticket for it?
is it possible to deploy it to web stage?

**Comment by elatif2020** [comment]
> @ariel-dao @elatif2020 
> now the inbox decrease 
> still needs to refresh or make an action for it to happen
> to open a ticket for it?
> is it possible to deploy it to web stage?
> 

@NoamQA 
yes if we don't have a ticket for the refresh please open one

**Comment by NoamQA** [comment]
@ariel-dao @elatif2020 
now inbox counter doesnt decrease again
in dev+web stage
