### ISSUE TITLE
System messages for new feed items in the space

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1950]
A user create a new feed item to this common (space) -> message: "@userName created the $feedItemType $feedItemTitle." where the $feedItemTitle should be a link to the feedItem and $feedItemType should be discussion\proposal\channel according to type of this feed item.
Notice that we should filter out items which aren't visible in the feed, such as Membership request proposal. Also hide items with Visibility higher than the base circle.

**Comment by NoamQA** [comment]
@ariel-dao 
messages are empty for this activities 


![Image](https://github.com/daostack/common-backend/assets/129174316/15353a5f-d913-4abf-8e38-177ef04c7d9a)

**Comment by elatif2020** [comment]
> @ariel-dao messages are empty for this activities
> 
> ![Image](https://private-user-images.githubusercontent.com/129174316/259693260-15353a5f-d913-4abf-8e38-177ef04c7d9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTE2NjQzNDYsIm5iZiI6MTY5MTY2NDA0NiwicGF0aCI6Ii8xMjkxNzQzMTYvMjU5NjkzMjYwLTE1MzUzYTVmLWQ5MTMtNGFiZi04ZTM4LTE3N2VmMDRjN2Q5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMDgxMFQxMDQwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTkyYjA0OTkwNzcyMDU5ZjhlYzJkNDc4NTAxYTFkNThkMTFkNDY2YmE1MzU5OWVkMGRlNmU0ZTA4ZDliOTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y8iG81_MKIaDvWpj_wpnF5u60BJcQhDJTqt_X4FSEiE)

Maybe it should be taken care of in the FE?

**Comment by andreymikhadyuk** [comment]
@elatif2020 am I correct that `feedItemType` can be only `proposal`, `discussion`? why did you mention `channel` in the ticket description, channels are not related to commons.
