### ISSUE TITLE
Set voting expiration time to current timestamp when immediate proposals end

### ISSUE THREAD

**Issue by danielr18** [daostack/common-backend#1957]

**Comment by danielr18** [comment]
Closed with ea78074f2d032e4a302cd11dd73ee697e04d39c2

**Comment by elatif2020** [comment]
@danielr18 
Is it on dev? 
For me it doesn't display the correct ending time (but the original expiry time)


![Image](https://github.com/daostack/common-backend/assets/72435714/03120452-7073-4508-bbcb-88d46af15060)

**Comment by danielr18** [comment]
@elatif2020 It's on dev

**Comment by NoamQA** [comment]
looks fine now
in shows the hour that the voting ended
with no date
@elatif2020 - is it ok for us?


![Image](https://github.com/daostack/common-backend/assets/129174316/55deb26a-28b1-40af-9197-cfb33e7b6a65)

**Comment by elatif2020** [comment]
Still not for me


![Image](https://github.com/daostack/common-backend/assets/72435714/ac168240-8a34-4462-bd85-384b1ac8cfb8)

@NoamQA you have to test it in a common with more than one Leader
@danielr18 can you please check this?

**Comment by NoamQA** [comment]
yes you are right
now i tested with 2 leaders
and it doesnt work...


![Image](https://github.com/daostack/common-backend/assets/129174316/6da5ba28-e881-430f-b7f0-56f91a497991)

**Comment by NoamQA** [comment]
@elatif2020 
when its a request to join a circle in common the end timestamp is an hour
and for a space it is date
what should be there for both of them?


![Image](https://github.com/daostack/common-backend/assets/129174316/d88c759a-b942-466f-b348-c8188d2cce5d)

**Comment by danielr18** [comment]
@elatif2020 @NoamQA I've made some fixes and ran QA
