### ISSUE TITLE
Don’t show “new” separator for my own messages in chats

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1961]
update lastSeenMessage to my last message at the BE

**Comment by ariel-dao** [comment]
seenAt will now be set for first new messages created for the owner, deployed to dev

**Comment by elatif2020** [comment]
> seenAt will now be set for first new messages created for the owner, deployed to dev


@ariel-dao not sure I got you. Maybe the last new message created by the owner?
Also it still doesn't work properly for me

**Comment by NoamQA** [comment]
yes also for me the new separator appears sometimes in messages that i write 


![Image](https://github.com/daostack/common-backend/assets/129174316/713aa76a-db65-4935-a5b9-16893ae09f2b)

**Comment by ariel-dao** [comment]
There might be a slight delay between the update of the discussion last message and the message creation, when it happens, does it reproduce when refreshing? @NoamQA

**Comment by elatif2020** [comment]
> There might be a slight delay between the update of the discussion last message and the message creation, when it happens, does it reproduce when refreshing? @NoamQA

@ariel-dao It doesn't stay after refresh, but it appears almost always before refresh and should be fixed. Should it be now solved in the FE? 
@andreymikhadyuk

**Comment by andreymikhadyuk** [comment]
@elatif2020 I will check.

**Comment by andreymikhadyuk** [comment]
I decided to add a fix as well on the FE side [here](https://github.com/daostack/common-web/issues/1859).

**Comment by ariel-dao** [comment]
@elatif2020 @andreymikhadyuk chat message creation will now update the chat user unique (unique only for owner) and chat channel objects right away when creating the message, this should remove any delay. deployed to dev
