### ISSUE TITLE
Update last message preview after deleting a file\image message

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1962]
BE

**Comment by ariel-dao** [comment]
@elatif2020 More info and steps to reproduce please
When I delete a discussion message it's being updated in the discussion

**Comment by elatif2020** [comment]
@NoamQA could you please have a look whether this ticket is still relevant?

**Comment by NoamQA** [comment]
@elatif2020 
it works fine now
opened another [ticket ](https://github.com/daostack/common-web/issues/1850)now for related issue
