### ISSUE TITLE
Enable multi levels commons BE

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1963]
- [x] Change the gov template for new spaces to allow CREATE_PROJECT in the actions and for the Leaders circle
- [x] Similar as a migration for existing commons

Maybe we also want to have a look and consider whether having multi-levels breaks something in the FE

**Comment by ariel-dao** [comment]
@elatif2020 Already allowed in projects, maybe it's not being rendered on FE? @andreymikhadyuk

**Comment by elatif2020** [comment]
Okay yes I see it is working
