### ISSUE TITLE
Add sub commons to feed items endpoint

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#1966]
Should be in the same list with feed items, and the list should be sorted by lastActivity.
Type: Subspace
Basic data: commonId, lastActivity
Additional: user's new activity counters, as in https://github.com/daostack/common-backend/issues/1965

**Comment by danielr18** [comment]
I'm blocked
I'm getting this error when trying to query feed items from multiple commons:
`9 FAILED_PRECONDITION: `

It works locally, but not when deployed.
I've created the index that is used locally, but still nothing.

https://github.com/daostack/common-backend/pull/1975

**Comment by elatif2020** [comment]
> I'm blocked
> I'm getting this error when trying to query feed items from multiple commons:
> `9 FAILED_PRECONDITION: `
> 
> It works locally, but not when deployed.
> I've created the index that is used locally, but still nothing.
> 
> https://github.com/daostack/common-backend/pull/1975
> 

@danielr18 just to make sure notice that here we don't want feed items from multiple commons, we want a new type of items to appear in the feed which represents subspaces of this common

**Comment by danielr18** [comment]
Hmm, and what would show up when you click those feed items?

@elatif2020

**Comment by elatif2020** [comment]
> Hmm, and what would show up when you click those feed items?
> 
> @elatif2020 

@danielr18 

it should browse to the selected space

**Comment by elatif2020** [comment]
> > Hmm, and what would show up when you click those feed items?
> > 
> > @elatif2020 
> 
> @danielr18 
> 
> it should browse to the selected space

@danielr18 
probably we need to implement first https://github.com/daostack/common-backend/issues/1964

**Comment by elatif2020** [comment]
I see that if I delete a sub space an empty card is left in the feed of the parent space. 
I guess we should fix it in the BE? @danielr18 
@NoamQA fyi
