### ISSUE TITLE
[Backend] Get Refresh Token for Mobile

### ISSUE THREAD

**Issue by MeyerPV** [daostack/common-backend#1984]
App gives me only idToken, accessToken, and serverAuthCode

**Comment by ariel-dao** [comment]
Firebase doesn't support refresh tokens, it's working in a stateless way. Need to use 

`firebase.auth().currentUser.getIdToken(/* forceRefresh */ true).`

https://firebase.google.com/docs/auth/admin/verify-id-tokens#web
