### ISSUE TITLE
infinite loader when try to join a common with fund contribution amount

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#1990]
maybe related to [#1989 ](https://github.com/daostack/common-backend/issues/1989)

when i create a common
and set one time contribution as a term to registration -
when a user try to join the common there is infinite loader  

![Image](https://user-images.githubusercontent.com/129174316/254898258-546820ff-8f81-448f-ba65-862e650b869e.png)

**Comment by elatif2020** [comment]
@NoamQA Can you please check whether it work on staging?

**Comment by NoamQA** [comment]
@elatif2020 
yes it works fine in web stage env.

**Comment by elatif2020** [comment]
@NoamQA can you please check this again now on dev?

**Comment by NoamQA** [comment]
@elatif2020 
works fine now in dev
