### ISSUE TITLE
Unable to retrieve join space proposal

### ISSUE THREAD

**Issue by roienatan** [daostack/common-backend#1996]
Using the bellow code in the FE to fetch the proposal to get the intro of a member in a **space**:
```
export async function fetchUserMemberAdmittanceProposalWithCommonId(
  userId: string,
  commonId: string,
) {
  const proposal = await firebase
    .firestore()
    .collection(Collection.Proposals)
    .where("data.args.proposerId", "==", userId)
    .where("data.args.commonId", "==", commonId)
    .where("type", "==", "ASSIGN_CIRCLE")
    .get();

  return transformFirebaseDataList<Proposal>(proposal)[0];
}
```
Result is `undefined` (also with type `MEMBER_ADMITTANCE`)

Example: for the given `userId: ow5Vlg0OsMfFfOcPOx6Le1Kh05s1` and `spaceId: 1a582c8a-7c45-4a34-96b9-daffe40a16d5` the result is `undefined` but the user is a member in the space.

**Comment by ariel-dao** [comment]
The assign circle proposal is created in the parent common, is common Id the id of the subcommon or the parent?

**Comment by roienatan** [comment]
> The assign circle proposal is created in the parent common, is common Id the id of the subcommon or the parent?

Of the sub common. So I should send the parent common? But even if so, it could be more than one "assign circle" proposals per user in space since a user can ask to join a higher circle.

**Comment by ariel-dao** [comment]
query by the circle id that represents the subcommon

**Comment by ariel-dao** [comment]
![image](https://github.com/daostack/common-backend/assets/89919079/0561163d-aa5b-41ee-8a71-9c0a0fdcdc9c)
You can get the circle id from the subcommon under directParent
