### ISSUE TITLE
Change text in New Proposal snackbar

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#200]
Please, remove id and change the text to “Your proposal was created!”
Discussed with @Taikaish 
![image](https://user-images.githubusercontent.com/28015224/110483843-2a508a00-80fb-11eb-9ea0-61f9ed737841.png)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.7 (6591)
Tested on Staging Android version 1.9.7 (6591-240)
Found OK
 text to “Your proposal was created!” is appears instead on the old message

**Comment by yanivi71** [comment]
Tested on production
Found OK
text to “Your proposal was created!” is appears instead on the old message
