### ISSUE TITLE
I see project feed item of the deleted project

### ISSUE THREAD

**Issue by andreymikhadyuk** [daostack/common-backend#2000]
![Image](https://github.com/daostack/common-backend/assets/29727923/93c6ad40-83d4-4181-8b5f-286d6a1cf6b7)

**Comment by NoamQA** [comment]
@danielr18 @elatif2020 

- [ ] after i delete a space it keeps appear in the feed items of the common
if i click on the deleted space channel i get 404 page


![Image](https://github.com/daostack/common-backend/assets/129174316/888b7449-c159-4e43-8d2b-69732eedfd32)

**Comment by danielr18** [comment]
Issue fixed and date corrected with migration.
Added migration: 03082023-remove-deleted-project-feed-items.ts
