### ISSUE TITLE
Sync space's about into the General (Home) discussion card

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2007]
- [x] Rename "General" into "Home"
- [ ] For newly created commons add the common's about text (rich format) & images into the message & images content of the relevant General discussion
- [ ] Migration to rename & add this data for existing commons
- [ ] Maintain the text & images in sync upon edit of the about of the common (space)

See the relevant FE ticket and the discussion about it [here](https://github.com/daostack/common-web/issues/1894)

**Comment by ariel-dao** [comment]
@elatif2020 The last 3 tasks should be done on FE as a default message in case it's empty, we shouldn't duplicate this data in the db.

**Comment by elatif2020** [comment]
okay, I'm archiving this ticket for now

**Comment by roienatan** [comment]
@elatif2020 @ariel-dao regarding the first one: `Rename "General" into "Home"` it wasn't done in the BE. Are you planning to do a migration for this also?

**Comment by elatif2020** [comment]
Renaming was taken care of in another ticket #2026
