### ISSUE TITLE
PROD- there is a space that doesnt opened. could be deleted but still appears

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#2014]
there is a [space ](https://common.io/commons/5b91b037-65aa-4be6-9b37-7104d1a0a38f/about)that appears in prod under "test [common](https://common.io/commons/3584cb01-d3c1-4035-9792-eac9be1d9be5)"

when click on it there is infinite loader 

![Image](https://user-images.githubusercontent.com/129174316/258369532-023acc07-9656-4f82-9094-316f55f8de7f.png)

**Comment by elatif2020** [comment]
@NoamQA 
Please try again now, It should be fixed.
