### ISSUE TITLE
Include userId of message owner to the lastMessage data of feed item and chat channel

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2021]
Needed in the FE in order to display the userName as "You" if it is that user

FE ticket here https://github.com/daostack/common-web/issues/1561

also add message id

**Comment by danielr18** [comment]
@elatif2020 Do we need the userId for system messages (who took the action)?

**Comment by elatif2020** [comment]
@danielr18 yes

**Comment by danielr18** [comment]
There are no system messages in chat yet.

**Comment by elatif2020** [comment]
> There are no system messages in chat yet.

@danielr18 Can you please clarify? I'm not sure I got you
