### ISSUE TITLE
Filter notifications about system messages regarding user's own activity

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2022]

**Comment by NoamQA** [comment]
:x: i still get notification for my activity
when i wright a comment in a chat that i follow

**Comment by danielr18** [comment]
It's possible that if you sign in with multiple accounts, you could get notifications for multiple accounts in one device, regardless of the current account you're signed in. If @NoamQA has logged in with multiple accounts, that could explain this.

@elatif2020 @ariel-dao We probably need to improve the FCM token management to account for this.

**Comment by NoamQA** [comment]
@danielr18 @elatif2020 
thanks
can you open a separate ticket for the FCM token management?

**Comment by elatif2020** [comment]
@NoamQA 
Here https://github.com/daostack/common-backend/issues/2052, not the highest priority currently
