### ISSUE TITLE
Improve the dm user list endpoint efficiency by showing all registered users

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2035]

**Comment by NoamQA** [comment]
@elatif2020 
it works fine in prod
but we have there a lot of users...
which makes it hard to find someone by scroll
do we have a ticket to make it more efficient? 


![Image](https://github.com/daostack/common-backend/assets/129174316/67b418c7-19ef-4dfb-915e-8c7844bcc7ab)
