### ISSUE TITLE
PROD- a new created common appears twice in my inbox

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#2037]
i created a new [common ](https://common.io/commons/a8495eb1-e623-417e-a564-84f66265b953)in prod env
it appears twice in my inbox
and doesn't disappear when i refresh

doesnt happens every time i create a common

![Image](https://user-images.githubusercontent.com/129174316/261843974-7f189d6a-61cb-4877-bda6-ec8a4c9bda31.png)

**Comment by ariel-dao** [comment]
Can you give steps to reproduce when it happens? and in which cases it doesn't happen? maybe a video if possible @NoamQA

**Comment by elatif2020** [comment]
@ariel-dao @danielr18 @NoamQA 

It might not be clear ho to reproduce. 
Alternatively we can first investigate the existing issue Noam have. 
@NoamQA Maybe it could be useful if you can write: the user email and the link to this feed item

**Comment by NoamQA** [comment]
@elatif2020 @danielr18 @ariel-dao 

it doesnt happen again so i cant make a video
i just created a new common and it happened,...

https://common.io/commons/a8495eb1-e623-417e-a564-84f66265b953
anothertestqa7@gmail.com

**Comment by danielr18** [comment]
This can happen when a call to add an inbox item is made in parallel.

**Comment by NoamQA** [comment]
doesnt reproduce now...
