### ISSUE TITLE
Endpoint for renaming circles names

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2041]

**Comment by ariel-dao** [comment]
@elatif2020 Should this affect the subcommon name as well if it exists based on a circle?
Are there any other areas this name change could affect? from a quick check I mainly saw it in notifications and system messages

**Comment by elatif2020** [comment]
@ariel-dao 
Should not effect subcommon name

**Comment by ariel-dao** [comment]
https://github.com/daostack/common-backend/commit/c547135ea9edfd1a1674cbd26d9e6e4dd64bbcec

PUT `/governance/circle-name`

{
        commonId: string().required(),
        circleId: string().required(),
        userId: string().required(),
        newName: string().required(),
      }
    
      must be common member

**Comment by elatif2020** [comment]
@arieller could we add this option to the edit common endpoint? 
Also we should check for appropriate permission of the user to allow this action. Could be UPDATE_COMMON or a new permission like UPDATE_GOVERNANCE . Anyway it should be enabled only for the Admin circle.
