### ISSUE TITLE
Add root common property for spaces

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2047]
The root common of a space (common with parent) is either its' parent common (if it doesn't have a parent) or the root common of its' parent-space

**Comment by ariel-dao** [comment]
@elatif2020 The description is confusing, doesn't directParent property on Common answer this?
If not, by "root common" is it referring to the first common without a directParent assuming no subcommons were deleted after creation?

**Comment by elatif2020** [comment]
> @elatif2020 The description is confusing, doesn't directParent property on Common answer this? If not, by "root common" is it referring to the first common without a directParent assuming no subcommons were deleted after creation?

@ariel-dao 
yes
the first ancestor common without a directParent

**Comment by ariel-dao** [comment]
@elatif2020 This might become an issue if root commons will be deleted
