### ISSUE TITLE
Add hasPublicItems property to commons

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2049]
Keep track of whether a common has any public items in the feed or not
could be updated upon creation of new streams and possibly upon deletion of a public item

**Comment by andreymikhadyuk** [comment]
and we also should allow to fetch common feed and pinned items for unauthenticated users.

**Comment by ariel-dao** [comment]
@elatif2020 @andreymikhadyuk What is defined as a public item? a feed item with circleVisibility as empty array?

**Comment by elatif2020** [comment]
> @elatif2020 @andreymikhadyuk What is defined as a public item? a feed item with circleVisibility as empty array?

@ariel-dao yes

**Comment by elatif2020** [comment]
@andreymikhadyuk notice this property was added and could be now used for determining the screen displayed for guests

**Comment by andreymikhadyuk** [comment]
> @andreymikhadyuk notice this property was added and could be now used for determining the screen displayed for guests

I've already added it to the code.
