### ISSUE TITLE
changes to system messages for created feed item

### ISSUE THREAD

**Issue by andreymikhadyuk** [daostack/common-backend#2069]
- right now on a space creation we have 2 system messages: `common-created` and `feed-item-created`. `common-created` one is already implemented, so we should not create another system message for created space (`feed-item-created`);
- if we remove `feed-item-created` system message for created spaces then I think we do not need `commonType` in the `systemMessageData` for that system message;
- I think for `feed-item-created` system message we need following data:
```
{
  userId: string;
  commonId: string;
  feedItemId: string;
  feedItemType: FeedObjectTypes;
  feedItemDataId: {feedItem.data.id};
}
```

**Comment by andreymikhadyuk** [comment]
@elatif2020 please double-check the description.

**Comment by elatif2020** [comment]
> * right now on a space creation we have 2 system messages: `common-created` and `feed-item-created`. `common-created` one is already implemented, so we should not create another system message for created space (`feed-item-created`);
> 
>     * if we remove `feed-item-created` system message for created spaces then I think we do not need `commonType` in the `systemMessageData` for that system message;
> 
>     * I think for `feed-item-created` system message we need following data:
> 
> 
> ```
> {
>   userId: string;
>   commonId: string;
>   feedItemId: string;
>   feedItemType: FeedObjectTypes;
>   feedItemDataId: {feedItem.data.id};
> }
> ```

@andreymikhadyuk 

Could you please clarify, whether those system messages you mentioned appear in the created space or in the parent common?

**Comment by andreymikhadyuk** [comment]
@elatif2020 Does it matter?

**Comment by elatif2020** [comment]
> 

@andreymikhadyuk I am not sure I completely understand so it could help me

**Comment by elatif2020** [comment]
We realized that the `feed-item-created` message for space's creation doesn't appear in the application. 
@andreymikhadyuk Maybe you can point out the relevant place where you see it in the code (if you find it) ?
