### ISSUE TITLE
my profile - error message when try to delete account

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#2077]
![Image](https://user-images.githubusercontent.com/129174316/265282705-ac56d8c0-acaa-4e56-8d0d-3c8e61d92ed5.png)

**Comment by elatif2020** [comment]
@NoamQA can you try again with the console open?

**Comment by NoamQA** [comment]
@elatif2020 
not sure i understood...
what do you mean console open?
i am trying to delete ne of my users in t he web system
and then get the error message
![image](https://github.com/daostack/common-backend/assets/129174316/0f2616d9-1191-4faa-9c0a-f518a4167668)

**Comment by NoamQA** [comment]
@elatif2020 
![image](https://github.com/daostack/common-backend/assets/129174316/8288e9eb-902d-4749-a820-d4ee6b17cc9e)

**Comment by elatif2020** [comment]
@NoamQA in which environment is it?  
if production - could you please try again now after the deployment?

**Comment by NoamQA** [comment]
@elatif2020 
works fine in prod
in dev i get error message
![image](https://github.com/daostack/common-backend/assets/129174316/1a4b2bc0-4bbf-48c8-a809-597e256e244f)

**Comment by elatif2020** [comment]
@NoamQA please try again now

**Comment by NoamQA** [comment]
@elatif2020 
looks like it works now
