### ISSUE TITLE
PROD- when delete a common it doesnt disappear (delete common proposal) not working

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#2082]
when i delete a common in dev it works fine
but in prod it stay
for example [this ](https://common.io/commons/c6687f1f-2bd6-46e1-923e-07a1f1234703)space 

![Image](https://user-images.githubusercontent.com/129174316/266229163-9584353c-6710-49c0-b763-5b2022905231.png)

**Comment by elatif2020** [comment]
As I understand it was solved with the deployment of S28 to production

**Comment by NoamQA** [comment]
@elatif2020 
yes now it disappears
open another [ticket ](https://github.com/daostack/common-web/issues/2087)for redirect to another common
