### ISSUE TITLE
when delete a space - its channels remains in the inbox

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#2083]
when click on the links in the channels i get 404 

for example [this ](https://web-dev.common.io/commons/103e7144-5d45-4673-9e6f-b59567f8dfea?item=7ef4a978-c1e5-46e1-b689-cf40f8c7e8fb)link to home channel of deleted space

![Image](https://user-images.githubusercontent.com/129174316/266231896-1f0973eb-515c-4c50-9ff6-4b2107862959.png)

**Comment by elatif2020** [comment]
should be solved by https://github.com/daostack/common-backend/issues/2081

**Comment by NoamQA** [comment]
to be tested after #2122 is fixed
