### ISSUE TITLE
Home appearing twice

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2102]
https://web-staging.common.io/commons/080a2f93-c8b8-4b3f-ade3-9042438e7246

doesn't disappear upon refresh

![Image](https://user-images.githubusercontent.com/72435714/267020347-2742af52-901d-4b89-99a2-e0bd48446147.png)

Also there is a duplicated system message about creation of this space

![Image](https://user-images.githubusercontent.com/72435714/267020584-990a2333-3fe1-4a05-9e45-a793212dc869.png)

**Comment by elatif2020** [comment]
The second item doesn't appear for a guest user,

I am thinking maybe it's somehow related to the creation of a private discussion in the parent common 🤔

**Comment by elatif2020** [comment]
@danielr18 did you had a look on this?

**Comment by danielr18** [comment]
https://firebase.google.com/docs/functions/firestore-events?gen=2nd#limitations

> Events are delivered at least once, but a single event may result in multiple function invocations. Avoid depending on exactly-once mechanics, and write [idempotent functions](https://cloud.google.com/blog/products/serverless/cloud-functions-pro-tips-building-idempotent-functions).


The onCreate event was called twice, and it created two home discussions.
The onCreate event handler is not idempotent.

I'd say the majority of our event handlers are not idempotent, so this kind of issues can happen unless we design idempotent functions.

**Comment by elatif2020** [comment]
> idempotent

ok thanks for the explanation 
what do you think? is it difficult to make it idempotent? does it requires also a change in the FE?
@danielr18 @ariel-dao
