### ISSUE TITLE
PROD -the are common/spaces that i cant open new discussion/proposal in them

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#2106]
when i try to create one nothing happens
and there is 401 error in the console

for example this [common ](https://common.io/commons/6dddf5a1-dcfa-4960-b78a-c3949b40c557)and this [space ](https://common.io/commons/3984c91e-331b-4254-9794-ee112b285de1)
![Image](https://user-images.githubusercontent.com/129174316/267714434-4922b2ef-7fcb-4f54-b9be-de8784afb8e6.png)

**Comment by NoamQA** [comment]
now it works
maybe was temporary problem
@elatif2020 can you check?

**Comment by elatif2020** [comment]
@NoamQA 
seems good to me
