### ISSUE TITLE
PROD I'm getting notifications for my own messages

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2108]

**Comment by danielr18** [comment]
Confirmed this is not related to #2052 

I was included in my own message notification 
![image](https://github.com/daostack/common-backend/assets/9046616/56248e32-d146-4cd4-820e-cbf531a47a56)
![image](https://github.com/daostack/common-backend/assets/9046616/31fad431-2ecb-4603-969e-2ec1e8863807)
