### ISSUE TITLE
Add userName and stream title to notifications

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2110]
It should be for discussions

Title: Common\SpaceName
Content: UserName @ StreamName: MessageText
(if possible make userName and StreamName in bold)

And if it is direct message it should stay as it is now (Title: OtherUserName Content: MessageText)

**Comment by elatif2020** [comment]
@danielr18 is it deployed to dev? I tried testing it and don't see the change

**Comment by elatif2020** [comment]
Rethinking let's change it as follow:

Title: 
SpaceName \ StreamName
Content: 
UserName: MessageText

So moving stream name to the title.

**Comment by NoamQA** [comment]
to be tested after [#2122](https://github.com/daostack/common/issues/1468) fixed

**Comment by elatif2020** [comment]
couldn't check it on staging but on dev it's good
