### ISSUE TITLE
when there is a message that only contains emoji -mobile notification is empty

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#2112]
Currently emojis messages appears empty in the notifications. Can we handle it better?

![Image](https://user-images.githubusercontent.com/129174316/267578577-c244cc27-6f58-4eae-91b5-77f2ba7216bf.png)

**Comment by elatif2020** [comment]
@MeyerPV 
should it be fixed in the BE or in the app?

**Comment by NoamQA** [comment]
to be tested after [#2122](https://github.com/daostack/common/issues/1468) fixed

**Comment by elatif2020** [comment]
can't check on staging but on dev it's good
