### ISSUE TITLE
Proposal chat - The app crashes when clicking on the arrow

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#212]
Tested on Staging Android version 1.9.5 (4978-197)
Tested on Staging iOS version 1.9.5 (4978-236)

When the user clicks on New comment notification (new comment for a proposal), he is redirected to a chat. But if he clicks on the arrow on the top of the screen, the app crashes.

Steps to reproduce:

1. Receive a notification for a new comment in a proposal
2. Click on this notification from the Notification tab
3. Click on the arrow on the top of the screen

https://user-images.githubusercontent.com/68247034/110779638-d36ec000-8274-11eb-9b74-b0ba3b027f3e.mp4

**Comment by gingervik** [comment]
We need to use Proposal chat for displaying these messages. now we redirect a user to the wrong chat

**Comment by kazaryan-t** [comment]
Fixed.
Tested on Staging Android version 1.9.5 (4978-204)
Tested on Staging iOS version 1.9.5 (4978-243)

**Comment by kazaryan-t** [comment]
Tested on Production Android version 1.9.5 (4998-53)
Tested on Production iOS version 1.9.5 (4998-44)

**Comment by yanivi71** [comment]
Verified on Producton
