### ISSUE TITLE
Expand /governance/circle-name endpoint to support multiple circles

### ISSUE THREAD

**Issue by roienatan** [daostack/common-backend#2127]
Currently this endpoint supports updating one circle at a time. We would like to support an array of `circleIds` and `circleNames`.

**Comment by roienatan** [comment]
Also getting `500 Internal Server Error`.

request URL:
`PUT https://europe-west1-common-dev-34b09.cloudfunctions.net/api/governance/circle-name`

payload:
```
circleId: "27bd770d-b3bf-4081-963e-f2ae478b4117"
commonId: "d2bb2e62-79e2-421a-b581-eee0f3f360a3"
newName: "Member_NEW_NAME"
userId: "xVKzzYHqsSPrcfKgOcwmSgPj8HE3"
```

**Comment by ariel-dao** [comment]
https://github.com/daostack/common-backend/commit/72c350b3aa327d2008081dfdf813bb16c92d1a83
