### ISSUE TITLE
prod- wrong discussion visibility shown

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#2129]
when i create discussion to admins or contributors it is shown as public in the description
 it does behave the right way and not visible to users that are not members of the circle
and only happens in prod

![Image](https://user-images.githubusercontent.com/129174316/268589344-21989b3c-e21e-484c-b869-2077df509317.png)

**Comment by andreymikhadyuk** [comment]
@elatif2020 @danielr18 Did we have a migration for `circleVisibilityByCommon` in prod?

**Comment by andreymikhadyuk** [comment]
@elatif2020 @danielr18 I still see `circleVisibility` in the discussion, but in the code we use `discussion?.circleVisibilityByCommon?.[commonId]` already.
<img width="338" alt="image" src="https://github.com/daostack/common-web/assets/29727923/7fec25e0-23d4-4912-8aad-6a022030cdcc">

**Comment by danielr18** [comment]
`circleVisibilityByCommon` is not deployed to staging/production yet in the BE.
What env is this from?

**Comment by andreymikhadyuk** [comment]
> `circleVisibilityByCommon` is not deployed to staging/production yet in the BE. What env is this from?

@danielr18  – `production`
@elatif2020 @NoamQA that is why we have the issue.

**Comment by elatif2020** [comment]
> > `circleVisibilityByCommon` is not deployed to staging/production yet in the BE. What env is this from?
> 
> @danielr18  – `production`
> @elatif2020 @NoamQA that is why we have the issue.
> 

so should we deploy it? or maybe better to create an hotfix in the FE to read both?

**Comment by andreymikhadyuk** [comment]
> > > `circleVisibilityByCommon` is not deployed to staging/production yet in the BE. What env is this from?
> > 
> > 
> > @danielr18  – `production`
> > @elatif2020 @NoamQA that is why we have the issue.
> 
> so should we deploy it? or maybe better to create an hotfix in the FE to read both?

the question to @danielr18.

**Comment by danielr18** [comment]
@andreymikhadyuk @elatif2020 It would ideally not have been merged in FE to production. But we can deploy it as hotfix to production BE.

**Comment by elatif2020** [comment]
Ok so we can revert it in the FE
https://github.com/daostack/common-web/pull/2096
