### ISSUE TITLE
Change my commons sorting to be by last activity

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2130]
Should effect the sorting of the list of commons in the navbar to be by last activity

**Comment by ariel-dao** [comment]
@andreymikhadyuk See my message in common, can't find endpoint used for this on backend

**Comment by elatif2020** [comment]
> @andreymikhadyuk See my message in common, can't find endpoint used for this on backend

@arieller If I understand correctly we're using an index on the daos collection. And maybe we just need a new index sorted by the (correct) last activity

**Comment by andreymikhadyuk** [comment]
@ariel-dao @elatif2020 There is `CommonService` with some methods which we use to get commons/spaces. I think we need a field for last activity in `Common` model and we will add this field usage for sorting on the FE side.

**Comment by elatif2020** [comment]
Currently as I see the change made in the BE does not reflect in the FE (in the commons dropdown in the breadcrumb and in the sidenav), so probably we have to make some change in the FE now. 
@ariel-dao could you please explain what is the change you made and how should it be used?

**Comment by ariel-dao** [comment]
@elatif2020 I've added `lastActivity` to the common entity and FE should use it for sorting @andreymikhadyuk

**Comment by elatif2020** [comment]
> @elatif2020 I've added `lastActivity` to the common entity and FE should use it for sorting @andreymikhadyuk

@ariel-dao do we need a new index for this?
@andreymikhadyuk

**Comment by ariel-dao** [comment]
It was added as well

**Comment by elatif2020** [comment]
ok 
created a FE ticket https://github.com/daostack/common-web/issues/2183
