### ISSUE TITLE
e2e BE testing for Linked streams

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2139]
Test to verify
- [x] - No duplication in the inbox of users
- [x] - Follow\unfollow actions behave correctly 
- [x] - No duplication of push\email notification on new messages
- [x] - Edit title behave correctly
- [x] - Last activity & last message preview are updated correctly

**Comment by elatif2020** [comment]
@danielr18 can you link relevant pr?

**Comment by danielr18** [comment]
https://github.com/daostack/common-backend/commit/a7a6baa4cf4a2e11910b437ea64dd92de0cbcdff
https://github.com/daostack/common-backend/commit/bc6df3be31d937fc65d2dfce8267edf94cb6dd2b
