### ISSUE TITLE
Buttons for voting don't disappear after the voting

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#214]
Tested on Staging Android version 1.9.5 (4978-197)
Tested on Staging iOS version 1.9.5 (4978-236)

Steps to reproduce:

1. Go to a proposal or membership voting
2. Vote (V to approve or X to reject)
3. Swipe the slider to approve or reject

Actual result:
Buttons for voting don't disappear. Nothing has changed on the page.

https://user-images.githubusercontent.com/68247034/110794782-294c6380-8287-11eb-9e78-c34b6a492629.MP4

Expected result:
The user should receive the message Approved/Rejected by you. Count for reject or approve increases by 1, the total number of votes increases by 1, and the buttons for voting disappear.

![IMG_0053](https://user-images.githubusercontent.com/68247034/110794848-39fcd980-8287-11eb-980c-d81f9cf037f3.PNG)

**Comment by yanivi71** [comment]
@lpetkov-sw See also the the voted does not count. and status is not refreshed

**Comment by kazaryan-t** [comment]
Tested on Staging Android version 1.9.5 (4978-201)
Tested on Staging iOS version 1.9.5 (4978-240)

Membership request:
Buttons for voting don't disappear and the page for voting does not refresh when the first voter votes for approval. 
Only if we click Back and return to the voting page we can see the count and there are no buttons for voting.

https://user-images.githubusercontent.com/68247034/111307856-0ba64200-866b-11eb-851a-236041036c58.MP4

**Comment by kazaryan-t** [comment]
Fixed.
Tested on Staging Android version 1.9.5 (4978-202)
Tested on Staging iOS version 1.9.5 (4978-241)

**Comment by kazaryan-t** [comment]
Tested on Production Android version 1.9.5 (4998-53)
Tested on Production iOS version 1.9.5 (4998-44)
