### ISSUE TITLE
Endpoint to mark a chat channel (dm) as unseen

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2141]
@elatif2020 A new endpoint must be created to mark a chat channel as unseen 
              (for example `/chat/channel/{channelId}/unseen`)
              Also we need to update `chatChannelUserUnique` subCollection with the new attribute `seen: boolean`

_Originally posted by @budnik9 in https://github.com/daostack/common-web/issues/2048#issuecomment-1734886501_

**Comment by danielr18** [comment]
The endpoint is `chat/channel/:channelId/unseen`

**Comment by danielr18** [comment]
@budnik9 FYI: This is in dev now

**Comment by elatif2020** [comment]
@danielr18 
See the comment in
https://github.com/daostack/common-web/issues/2048#issuecomment-1752762097
marking a dm as seen does not work

**Comment by danielr18** [comment]
It's working now
