### ISSUE TITLE
PROD- there are Space counters (messages & stream) that doesnt reset

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#2143]
see Matan discussion [here](https://common.io/commons/e9f7ecd2-617a-448c-a1b9-e52df9f7d427?item=5459f42b-18a1-4ff2-8785-e0c5c5cdecdc)

Space counters are nonzero while all the content inside is read

**Comment by danielr18** [comment]
@NoamQA Have you been able to reproduce this?

**Comment by NoamQA** [comment]
@elatif2020 
couldnt reproduce now...
i think this is duplicate with [#2079](https://github.com/daostack/common-web/issues/2079)
see kirel comment there

**Comment by elatif2020** [comment]
> @elatif2020 couldnt reproduce now... i think this is duplicate with [#2079](https://github.com/daostack/common-web/issues/2079) see kirel comment there

looking at it again - it is another issue

**Comment by danielr18** [comment]
Probably fixed by https://github.com/daostack/common-backend/issues/2156
