### ISSUE TITLE
Script to fix wrong number-of-members indicator appears at the back page and feed

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#2151]
for example in [this ](https://web-dev.common.io/commons/0f5fb625-2c9d-487b-8778-28deec5c920b/about)space
there are 16 members
but in the back page and feed number is 13

(bug discussion [here](https://common.io/commons/e9f7ecd2-617a-448c-a1b9-e52df9f7d427))

**Comment by elatif2020** [comment]
@andreymikhadyuk can you please check is it in the BE or FE?

**Comment by andreymikhadyuk** [comment]
@elatif2020 I take this number from the DB. For that common it is `13` there.
<img width="344" alt="image" src="https://github.com/daostack/common-web/assets/29727923/bccb2974-ec25-4a9d-9ab2-f909658acf5b">

**Comment by ariel-dao** [comment]
@NoamQA @elatif2020 Does this reproduce for every common? it seems this is stale data issue and a migration to align would fix it

**Comment by elatif2020** [comment]
> @NoamQA @elatif2020 Does this reproduce for every common? it seems this is stale data issue and a migration to align would fix it

@ariel-dao 
it does reproduce in other commons

**Comment by ariel-dao** [comment]
I can't reproduce it on new commons locally, tried to join/leave etc and the count seems to work correctly. I'm going to create a migration to align the count to the actual member count and if this reproduces we'll need to catch what was the scenario it happens @elatif2020
