### ISSUE TITLE
Inbox counter is out of sync DEV

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2155]
My inbox counter on dev is showing 88 while I have around 12 unread streams

![Image](https://github.com/daostack/common-backend/assets/72435714/f20fa653-26ce-43fa-adde-4b9dbc7179cf)

**Comment by elatif2020** [comment]
On staging with unread=true 
counter = 2 there are 6 items with this filtration but none of them with new\unread indication


![Image](https://github.com/daostack/common-backend/assets/72435714/9101c146-dd0f-4a10-8405-002653db9aae)

**Comment by NoamQA** [comment]
it looks fine in dev 
but for some of the another users (anothertestqa7@gmail.com + harmony888@walla.co.il) the counter still shows number in web stage

![Image](https://github.com/daostack/common-backend/assets/129174316/1e3ea8e1-0e44-42c2-a4ea-d759c70c6b48)

**Comment by NoamQA** [comment]
for user anothertestqa7@gmail.com](mailto:anothertestqa7@gmail.com)
when i put address:
web-staging.common.io/inbox?unread=true
there are no items

when i did the same for user harmony888@walla.co.il -
it showed few channels
when i opened them the counter decreased and is now zero

![Image](https://github.com/daostack/common-backend/assets/129174316/21a04046-ef6b-4a0a-9b5b-665403245365)
