### ISSUE TITLE
Some subspace card do not show up for a newly joined user

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2172]
the example [here](https://web-staging.common.io/commons/cfec83ed-deec-4548-95fc-e26189d8636a) (staging)
It stays like this also after refresh

This is for the user who joined this common (and also is a member of Space A)
latif.eliaz@gmail.com

![Image](https://github.com/daostack/common-backend/assets/72435714/4ef2ad52-7df9-42e7-88fe-860f35cc5733)

And for the founder user:

![Image](https://github.com/daostack/common-backend/assets/72435714/d9b42594-078d-4ff4-bf70-b06c5a1886c1)

**Comment by NoamQA** [comment]
@elatif2020 
works for me
can you check with your user on staging?

**Comment by elatif2020** [comment]
Also works for me
But it seems to appear only after refresh (this is a different issue, should be taken care in the FE)
