### ISSUE TITLE
Request to join button hides other buttons

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#218]
Tested on Staging Android version 1.9.5 (4978-198)
Tested on Staging iOS version 1.9.5 (4978-237)

Steps to reproduce:
1. Open the app
2. Open one Common where you are NOT a member
3. Scroll down the page

Actual result:
The Request to join button hides Start the discussion/Join the discussion buttons.

Expected result:
Start the discussion/Join the discussion buttons should be easily accessible and clickable.

https://user-images.githubusercontent.com/68247034/110943134-e7392580-834b-11eb-9f90-02569e8489f8.mp4

**Comment by yanivi71** [comment]
@kazaryan-t this is not a bug
This is the behavior
