### ISSUE TITLE
Proposal chat - Member can´t leave a comment when clicking on New comment notification from the Notification tab

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#219]
Tested on Staging Android version 1.9.5 (4978-198)
Tested on Staging iOS version 1.9.5 (4978-237)

When a member of a common receives a notification about a new comment in a proposal chat and clicks on this notification from the Notification tab, he is redirected to a proposal chat, but there is a message that Only members can send messages.

Steps to reproduce:
1. Receive notification about a new comment in a proposal chat.
2. Click on this notification from the Notification tab
3. Try to send a message

Actual result:
In place of the textbox, there is a message that Only members can send messages.

Expected result:
The user should be able to leave comments in the chats if he is a member of the common.

In this video, you can see that if we open the proposal chat from the common page, the user is able to insert his comments, but if he is redirected to a proposal chat from the Notification tab he isn´t. 

https://user-images.githubusercontent.com/68247034/110949359-8f9eb800-8353-11eb-8dd1-6311c4d0e9c4.mp4

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-243)
Tested on Staging Android version 1.9.5 (4978-204)

Found OK
The user is be able to leave comments in the chats if he is a member of the common.

**Comment by kazaryan-t** [comment]
Tested on Production Android version 1.9.5 (4998-53)
Tested on Production iOS version 1.9.5 (4998-44)

**Comment by yanivi71** [comment]
Verified on Production
