### ISSUE TITLE
Feed item counter isn't counting some new messages

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2196]
It happens after User 2 sees the item
User 1 create the discussion
User 2 sees the item. New tag disappears. User 2 go to another item (for example Home)
User 1 writes the message in the newly created discussion
User 2 doesn't see the unread messages counter on this discussion

_Originally posted by @budnik9 in https://github.com/daostack/common-web/issues/2233#issuecomment-1780809322_

**Comment by NoamQA** [comment]
@elatif2020 @danielr18 @budnik9 
this one still happens
now counter for new discussions
