### ISSUE TITLE
Notification screen - when proposal title in hebrew , wrong display when proposal is approved

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#220]
Tested on Staging iOS version 1.9.5 (4978-239)
Tested on Staging Android version 1.9.5 (4978-200)

Steps to reproduce:
1. Create a new proposal Use language hebrew for the proposal title 
2. approved the proposal
3. Go to notification screen
4. See the notification of approved proposal

Actual results:
The proposal is approved but the format display is wrong - see attached image
![Screenshot_2021-03-14-10-22-25-334_com daostack common staging (1)](https://user-images.githubusercontent.com/69141571/111062550-36996600-84b2-11eb-862e-b245cc4bb9c4.jpg)

Expected results:
1. title should be "proposal approved"
2. the tittle and the amount requested are replace position

![image](https://user-images.githubusercontent.com/69141571/111062603-8aa44a80-84b2-11eb-9ab1-b0d849fb535d.png)

**Comment by watchtower314** [comment]
pr: https://github.com/daostack/common/pull/975
![IMG_3E709DE2D348-1](https://user-images.githubusercontent.com/30501647/111079593-0614f480-84d1-11eb-8e88-0d60f7ec8cb8.jpeg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-241)
Tested on Staging Android version 1.9.5 (4978-201)

@watchtower314 Not fixed. see attached images from staging

![Screenshot_2021-03-17-10-35-36-431_com daostack common staging](https://user-images.githubusercontent.com/69141571/111439118-b53e0f80-870d-11eb-8bde-7d96e96ee45c.jpg)

**Comment by yanivi71** [comment]
@watchtower314 there are more issues. please verify in all notification that has hebrew on their title

![Screenshot_2021-03-18-18-37-35-717_com daostack common](https://user-images.githubusercontent.com/69141571/111663773-cd02ba00-8819-11eb-9fa4-118b67f2c049.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-268)
Tested on Staging Android version 1.9.5 (4978-229)
@watchtower314 on android the display is still incorrect with hebrew language - see attache image
![image](https://user-images.githubusercontent.com/69141571/114547238-db9c8f80-9c66-11eb-918f-98359f5de907.png)

**Comment by yanivi71** [comment]
Image from iOS
![image (21)](https://user-images.githubusercontent.com/69141571/115214445-302e8780-a10b-11eb-8767-a20537ca97ec.png)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.7 (6591-280)
Tested on Staging Android version 1.9.7 (6591-241)

For hebrew title
Android display from RTL
iOS display from LTR

We need from brio a design for hebrew title in notification screen.
meantime moving this issue to verify
