### ISSUE TITLE
Add items link to the notifications

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2202]
add link to the relevant item
of the format /inbox?item=$feedItemId 
e.g. https://common.io/inbox?item=73922a25-cbe1-4643-86a7-e3453214dd8a

**Comment by danielr18** [comment]
Added `commonId` and `feedItemId` to the discussion notifications, and `chatChannelId` to chat.

If the FE wants to open the inbox, they have to query the inbox item.

This is because the discussion push notification is a single notification broadcast to N users, not N notifications.
