### ISSUE TITLE
Add lastVisitedCommon property to users

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2225]

**Comment by danielr18** [comment]
Collection: usersActivity

**Comment by elatif2020** [comment]
@danielr18 can you please explain how to interact with this property? I don't see it in firebase

**Comment by danielr18** [comment]
It's a public read collection. The BE does not use it.
The FE has to set the property and use it.

**Comment by danielr18** [comment]
`set(db.collection(usersActivity).doc(userId), { lastVisitedCommon })`
