### ISSUE TITLE
Update PayMe endpoints with our new standard

### ISSUE THREAD

**Issue by roienatan** [daostack/common-backend#2228]
Update both `update-buyer-token-status` and `update-payment-status` with our new endpoint standard. Need to add `api/` before the `payments`.

@danielr18 we realized those endpoints are defined in the environment settings in the BE

**Comment by danielr18** [comment]
This was deployed in production

**Comment by roienatan** [comment]
> This was deployed in production

@danielr18 we need it in `dev` also.
