### ISSUE TITLE
Moderation for setting permission manually

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#223]
- when we set moderators manually, we need to show them the moderators menu
- add permissions in `common.members` for cheaper iteration through the moderators

this has a frontend pr: https://github.com/daostack/common/pull/978
and a backend pr: https://github.com/daostack/common-monorepo/pull/224

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-242)
Tested on Staging Android version 1.9.5 (4978-203)

Found OK
Tested together with @watchtower314  

adding permission (through the DB) for mederatore to another user , works ok
![image](https://user-images.githubusercontent.com/69141571/111471231-5d190480-8731-11eb-9e58-137cf558f5f0.png)

**Comment by yanivi71** [comment]
Verified on Production
