### ISSUE TITLE
Space deletion as an action

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2234]
We should have in the governance the permission to delete space as an action
should enable it for spaces, so any admin can delete a space by a single action

**Comment by elatif2020** [comment]
@danielr18 
Can you please write down what endpoint the FE should use and what is the permission to check for?
Also, did you prepared also a migration for this? 
I haven't mentioned it but we should (can open separate ticket if you haven't done it yet)

**Comment by danielr18** [comment]
The ` CreateAction: "/proposals/action"` endpoint.
Type is `DELETE_COMMON`
Payload: { commonId }

**Comment by NoamQA** [comment]
@elatif2020 
do we have FE for delete space in single action?
now it still create a proposal for it

**Comment by elatif2020** [comment]
> @elatif2020 do we have FE for delete space in single action? now it still create a proposal for it


not yet
