### ISSUE TITLE
Follow subspace (recursively) when following a space

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2238]
For each item we should have flag with 3 states:
Followed \ None \ unFollowed
Then the status of the item $i$ with parent $p$ should be:
status($i$) = ( status($p$) AND (NOT unFollowed) ) OR Followed

As a consequence:

- [ ] Parent followed (and son not unfollowed) -> son status followed
- [ ] Grandfather followed (& both parent and son not unfollowed) -> parent & son status followed
- [ ] Parent followed, son **unfollowed** -> son status **not** followed
- [ ] Son followed, parent followed, parent unfollowed -> son status remain followed
- [ ] Parent followed,  son **unfollowed**, parent unfollowed, parent followed -> son status remains **not** followed

**Comment by elatif2020** [comment]
@danielr18 I added some more details here

**Comment by NoamQA** [comment]
@elatif2020 
1.it should happen only when creating subspace
or also automatically when i change parents the subspace get a follow star?
looks looks now it happens only on creation...

2.what should happen when i have parent and son unfollowed and i create a subspace?
now it is followed

3.Grandfather followed (& both parent and son not unfollowed) -> parent & son status followed ----- when i create grandson the son and parent doesnt become follow
did i understood it correctly?

4. Parent followed, son unfollowed -> son status not followed -----
when i create subspace and Parent followed, son unfollowed - there is a follow star there

**Comment by elatif2020** [comment]
> @elatif2020 1.it should happen only when creating subspace or also automatically when i change parents the subspace get a follow star? looks looks now it happens only on creation...
> 
> 2.what should happen when i have parent and son unfollowed and i create a subspace? now it is followed
> 
> 3.Grandfather followed (& both parent and son not unfollowed) -> parent & son status followed ----- when i create grandson the son and parent doesnt become follow did i understood it correctly?
> 
>     4. Parent followed, son unfollowed -> son status not followed -----
>        when i create subspace and Parent followed, son unfollowed - there is a follow star there

@NoamQA 
Notice we have another ticket for auto follow my own created spaces.
This ticket is regarding the inheritance from parent to son space.
1. So it should happen also when following parent space (but not if son spaces were unfollowed before).
2. Should be followed by the creator and not followed if you're not the creator.
3. Yes, they shouldn't become followed
4. For the creator or for other user?

**Comment by NoamQA** [comment]
@elatif2020 
retested the ticket
works fine in DEV env.
