### ISSUE TITLE
Filter out subspaces cards from the inbox

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2239]

**Comment by elatif2020** [comment]
@danielr18 maybe better to discuss the implementation here with @andreymikhadyuk 
If I understand correctly the FE doesn't use the user inbox subcollection, and instead uses the feedItemsFollow & the BE endpoint
And we can either add type property for the feedItemsFollow to allow filtration, 
or make sure not have spaces items there. 
Looking forward I suspect the use of a type property correspond better with the functionality we will want (allowing to have a unified screen for the inbox and the spaces), but I'm not sure if we should implement now according to this.

**Comment by danielr18** [comment]
<img width="574" alt="image" src="https://github.com/daostack/common-backend/assets/9046616/c369e808-f352-4143-8405-252fd057730a">

Feed item follows already have a type
