### ISSUE TITLE
include also "new" streams in the updated streams counter

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2241]
currently new streams without messages aren't counted and they should be counted
We should update the counter streamsUnreadCountByProjectStream

**Comment by NoamQA** [comment]
@elatif2020 
not sure i understood this one...
when i create a new stream (discussion or proposal) in a space
then other user in the root common should see indication of it in the space stream?

now i can see in the time changed but no number of updates


![Image](https://github.com/daostack/common-backend/assets/129174316/347718da-aab9-4d0f-9f95-7ea9d397227b)

**Comment by elatif2020** [comment]
> @elatif2020 not sure i understood this one... when i create a new stream (discussion or proposal) in a space then other user in the root common should see indication of it in the space stream?
> 
> now i can see in the time changed but no number of updates
> 

Yes you wrote correctly
I'm reopening this ticket

**Comment by NoamQA** [comment]
@elatif2020 @danielr18 
i still see only time of update...
also after refresh and cache clean 


![Image](https://github.com/daostack/common-backend/assets/129174316/4b893ac5-c39d-4fd3-b892-3c2a0da2fa68)

**Comment by elatif2020** [comment]
This ticket no longer relevant since we added a system message a streams creation, which triggers the counters anyhow

**Comment by NoamQA** [comment]
@elatif2020 @danielr18 
now i dont see any indication for new and updated streams in subspace
both in dev and web stage


![Image](https://github.com/daostack/common-backend/assets/129174316/b05286ea-b359-47af-965c-8017009dd4e1)

**Comment by elatif2020** [comment]
@NoamQA 
I see, 
could please you open a new ticket for this?

**Comment by NoamQA** [comment]
@elatif2020 
sure
opened #2268
