### ISSUE TITLE
Roles (members) inharitance BE

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2244]
1. Allow syncing the members of Circle (role) X in a space to Circle Y in the parent space (or common).
Upon opening or editing a space, we should be able to configure each role X to not inherit or inherit role Y in its parent

- [ ] Plan db re-structure
- [ ] Specify changes needed in the FE
- [ ] Implement the logic
- [ ] Implement the endpoint for the configuration of the inheritance
- [ ] Migration

2. We should be able to configure available circles names (and in the future configure also the permissions) at the root common and inherit the circles to spaces. In each space allow choosing which of the available circles be enabled (And maybe also configuring some specific permissions in the future, but use the same base permissions).

**Comment by elatif2020** [comment]
Still have to be done:

- [x] making sure we add new common members to all relevant sub-commons (recursively)
- [x] Endpoint for configuring the inheritance -> upon space creation (easier)
- [ ] Endpoint for configuring the inheritance -> upon space edit (easier) -> overwrite the existing members ?
- [x] Logic to update membership (recursively) once a user leaves a circle in the common
- [ ] create requests to join inherited circle in the relevant parent common where it's defined
- [ ] See how to allow the FE the information regarding which subspace cards should be visible for  a user

In a different ticket we need to take care of
allowing adding members to a sub space with closed base circle

in the FE will need
show add to circle option only for non-inheriting circles
show leave\join space options depending whether the base circle of that space is inheriting
or whether the membership in this common is by inheritance

**Comment by elatif2020** [comment]
@danielr18 please update on the status here

**Comment by danielr18** [comment]
I've been doing the modifications to the governance template to support the changes we talked about last week.
I removed the project template, and now have a function that creates a new governance template from a config object that allows for inheriting circles and inheriting permissions.

I'm still working on the indexes re-calculation for actions, and haven't done anything with regards to the circle hierarchy property.

**Comment by elatif2020** [comment]
> Still have to be done:
> 
>     * [x]  making sure we add new common members to all relevant sub-commons (recursively)
> 
>     * [x]  Endpoint for configuring the inheritance -> upon space creation (easier)
> 
>     * [ ]  Endpoint for configuring the inheritance -> upon space edit (easier) -> overwrite the existing members ?
> 
>     * [x]  Logic to update membership (recursively) once a user leaves a circle in the common
> 
>     * [ ]  create requests to join inherited circle in the relevant parent common where it's defined
> 
>     * [ ]  See how to allow the FE the information regarding which subspace cards should be visible for  a user
> 
> 
> In a different ticket we need to take care of allowing adding members to a sub space with closed base circle
> 
> in the FE will need show add to circle option only for non-inheriting circles show leave\join space options depending whether the base circle of that space is inheriting or whether the membership in this common is by inheritance

@danielr18 I see in the specification here that I wrote: "Create requests to join inherited circle in the relevant parent common where it's defined". Which is what you were speaking about. Maybe it's a better way to make it. You were asking regarding circle visibility setting in this case. It should be visible to the eligible voters of this request in the relevant parent common. Maybe we can override the FE request in this case?
