### ISSUE TITLE
Space's card "updated streams" counter mismatch

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2246]
See [here](https://web-dev.common.io/commons/8f80bb74-32a7-4380-9157-0fbc4b7e61b7) with my user latif@daostack.io:
![Image](https://github.com/daostack/common-backend/assets/72435714/d14b49a8-3c71-44a9-9c5c-2ea65a16ff91)

It doesn't match with:
![Image](https://github.com/daostack/common-backend/assets/72435714/71915c9e-ef67-44ab-b99b-45a0a5a62f05)

![Image](https://github.com/daostack/common-backend/assets/72435714/d4af0b91-7fb4-49e5-93cb-507f8877b62b)

![Image](https://github.com/daostack/common-backend/assets/72435714/fdb24b0b-710d-4082-abe7-b65f4a7b1026)

**Comment by NoamQA** [comment]
@elatif2020 @danielr18 
it doesnt seems to work when i update a stream in a space
the counter doesnt change only time of update
is it connected to #2241 ?

**Comment by elatif2020** [comment]
@NoamQA can you try again now? Daniel fixed some issues here

**Comment by NoamQA** [comment]
@elatif2020 
works fine now

**Comment by NoamQA** [comment]
@elatif2020 @danielr18 
it doesnt work again...
see my comment in #2241

**Comment by elatif2020** [comment]
We have a new ticket for the issue Noam mentioned, here:
https://github.com/daostack/common-backend/issues/2268
