### ISSUE TITLE
Moderation - Hide comments - The is no icon for hidden content

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#225]
Tested on Staging iOS version 1.9.5 (4978-239)
Tested on Staging Android version 1.9.5 (4978-200)

Steps to reproduce:
1. Go To a hidden comment as a moderator/Regular user
2. look for hidden comment

Actual results:
Hidden comment text appears but does not contain hidden icon - see attached image

Expected results:
Hidden icon should appears next to the text - see attached image 
![Screenshot_20210316-113757_common-stg](https://user-images.githubusercontent.com/69141571/111288092-8c097a80-864c-11eb-9063-012c8bab090d.jpg)
![image](https://user-images.githubusercontent.com/69141571/111288371-c541ea80-864c-11eb-8476-275d5e1aad88.png)

**Comment by watchtower314** [comment]
This is no longer an issue
