### ISSUE TITLE
Change emails notifications default

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2250]
Currently it's all emails
should change to the option of dm, mentions and replies 
(including groups messages which we didn't had previously)

**Comment by NoamQA** [comment]
@elatif2020 @danielr18 
is it only for new users or also exist ones?

**Comment by elatif2020** [comment]
> @elatif2020 @danielr18 is it only for new users or also exist ones?

@NoamQA 
only for users who didn't changed the notifications settings so far
