### ISSUE TITLE
System messages about space\stream deletion

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2251]
In the Home of the space:

Upon stream deletion:
"$streamName was deleted by $userName"

Upon sub-space deletion:
"The $spaceName space was deleted by $userName"

**Comment by elatif2020** [comment]
@danielr18 
is it on dev?

**Comment by danielr18** [comment]
Stream deletion should

**Comment by NoamQA** [comment]
@danielr18 @elatif2020 
there is a message for sub space delete
but for discussion no new message
only in the old message of create the discussion it is written "deleted"


![Image](https://github.com/daostack/common-backend/assets/129174316/dab672e1-96cd-41b6-ae43-a6de6e42a367)

**Comment by andreymikhadyuk** [comment]
@danielr18 For `common-deleted` system message in `systemMessageData.commonId` I have the id of parent common, not delete space. If you open common `59fdad34-68fa-43a3-bdcd-58e2af00684c` you will that the name is `Andrey's common v2`.
<img width="541" alt="image" src="https://github.com/daostack/common-backend/assets/29727923/8f9ffdf7-8dc3-4139-b9b4-17215e60999b">

**Comment by andreymikhadyuk** [comment]
@danielr18 I also do not see system message about deleting a stream.

**Comment by elatif2020** [comment]
@danielr18 for you attention 
I see the stream deletion upon moving a stream (which shouldn't be) but not upon deleting
