### ISSUE TITLE
Rename DELETE_COMMON action permission

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2253]

**Comment by danielr18** [comment]
@elatif2020 @roienatan ASSIGN_CIRCLE and REMOVE_CIRCLE also have the same name in Proposals/Actions. Do we need to rename them?

And @roienatan Do those two also face the same issue?

**Comment by roienatan** [comment]
@elatif2020 The issue has been solved in the FE and in the BE. The `hasPermission` function has been modified in both FE and BE to distinguish between `action` and `proposal`. Now we can use same key names for both proposal and actions.
