### ISSUE TITLE
Update the inbox counter on updates

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2255]
Currently the Inbox counter remains the same after reading unread items in the inbox
or after marking items as unread
and probably also if new items appear

It is updating only once switching to another page.
It should be updated once there is a change

**Comment by andreymikhadyuk** [comment]
@elatif2020 The number is updated when we get new value from BE.

**Comment by elatif2020** [comment]
> @elatif2020 The number is updated when we get new value from BE.

@andreymikhadyuk  did it reproduced for you? not sure then why is it like this...

**Comment by andreymikhadyuk** [comment]
> > @elatif2020 The number is updated when we get new value from BE.
> 
> @andreymikhadyuk did it reproduced for you? not sure then why is it like this...

For me the value is updated correctly, but it takes some time.

**Comment by elatif2020** [comment]
> > > @elatif2020 The number is updated when we get new value from BE.
> > 
> > @andreymikhadyuk did it reproduced for you? not sure then why is it like this...
> 
> For me the value is updated correctly, but it takes some time.

interesting, for me it isn't 
so maybe it's related to caching?

**Comment by andreymikhadyuk** [comment]
> > > > @elatif2020 The number is updated when we get new value from BE.
> > > 
> > > 
> > > @andreymikhadyuk did it reproduced for you? not sure then why is it like this...
> > 
> > 
> > For me the value is updated correctly, but it takes some time.
> 
> interesting, for me it isn't so maybe it's related to caching?

I do not think so. You can compare the value in the DB (`inboxCounter` field in your user from `users` collection) with the value you see in header.

**Comment by andreymikhadyuk** [comment]
@elatif2020 I think it works for the same as for you.

**Comment by andreymikhadyuk** [comment]
I would ask @danielr18, because on the FE we just display the value from the users collection.

**Comment by elatif2020** [comment]
Closing this ticket here. Will open new one if needed after further checks.
