### ISSUE TITLE
Unread tag doesn't disappears for moved items

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2256]
After moving an item to another space the unread tag appear
and it doesn't disappear: 
- [ ] when opening the item
- [x] when marking as read 
- [ ] when writing a message

![Image](https://github.com/daostack/common-backend/assets/72435714/7cd47fd3-e8fe-4fcf-9dfb-98b51cbdb7c6)

**Comment by NoamQA** [comment]
@danielr18 @elatif2020 
it still appears when i move an item
and doesnt disappear when i open it
i can only mark as read and then it dissapears

**Comment by elatif2020** [comment]
> @danielr18 @elatif2020 
> it still appears when i move an item
> and doesnt disappear when i open it
> i can only mark as read and then it dissapears

okay we need to fix it

**Comment by elatif2020** [comment]
> @danielr18 @elatif2020 
> it still appears when i move an item
> and doesnt disappear when i open it
> i can only mark as read and then it dissapears

@NoamQA does it disappear after writing a message?

**Comment by elatif2020** [comment]
@danielr18 actually I guess it will be solved once we add the system message on move

**Comment by elatif2020** [comment]
![Image](https://github.com/daostack/common-backend/assets/72435714/347800c4-71b1-4b33-927d-8d799db0568c)

**Comment by elatif2020** [comment]
@danielr18  
I looked at an example for an item I moved in staging
This item: https://web-staging.common.io/commons/fc397bc6-2e49-48a3-8d0f-718999ecbacb?item=939c6b98-4243-4c05-98e7-1613f423dc7b
![Image](https://github.com/daostack/common-backend/assets/72435714/9e860876-b422-4ee5-91df-67048dc25e74)

I see that the item is appearing in the commonFeed sub-collection (id  939c6b98-4243-4c05-98e7-1613f423dc7b) for this common.
But there are no corresponding items in the commonFeedUserUnique sub-collection:
![Image](https://github.com/daostack/common-backend/assets/72435714/5d1402d2-6295-43b1-ad1d-1b1f3cdcff01)

Also I see that in the FE request for marking this feed item as read the commonId is for some reason of the origin common (id 4588679a-731d-42c8-b807-bdbd1cbff4f5)
![Image](https://github.com/daostack/common-backend/assets/72435714/f2bbe6e8-c67e-4a66-97e4-eb441e65732c)

![Image](https://github.com/daostack/common-backend/assets/72435714/c982e3c7-77bd-46ab-82d6-aed653272acc)

I hope it is helpful in solving this issue 🙏

**Comment by elatif2020** [comment]
After playing with it a bit more the mark as read action succeeded, and a commonFeedUserUnique item have been created for this item. However, still once I open this item again I see a similar error in the console, where mark as read is called with the previous commonId. 
@andreymikhadyuk Maybe you can also have a look, it might be also related to caching maybe

**Comment by andreymikhadyuk** [comment]
@elatif2020 I think the issue is because of `commonId` usage from `lastNonUserMessage`, which is discussion message, but that message was created in the previous common.
<img width="477" alt="image" src="https://github.com/daostack/common-backend/assets/29727923/8fb27e7d-75c6-4189-a419-e10d715fd99f">

**Comment by NoamQA** [comment]
@elatif2020 @danielr18 
now the unread item appears when moving an item
and disappears when open it
i think its OK for us
