### ISSUE TITLE
Notification screen - No Notification for reported content

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#226]
Tested on Staging iOS version 1.9.5 (4978-240)
Tested on Staging Android version 1.9.5 (4978-2001)

Steps to reproduce:
1. Login as regular user (not moderator)
2. Report any content (proposal, comments,post, request to join)
3. as a moderator Go To notification screen

Actual results:
1. No Notification for reported content
2. Push notification is sent to the moderator - see attached image

Expected results:
Moderator should get Notification for reported content on the notification screen 

![image](https://user-images.githubusercontent.com/69141571/111314375-0399d280-866a-11eb-967c-26feb0965186.png)

**Comment by watchtower314** [comment]
@lpetkov-sw 
There could be a problem implementing this, because we already have 10 items we're getting from firebase
<img width="371" alt="Screen Shot 2021-03-25 at 9 58 43" src="https://user-images.githubusercontent.com/30501647/112484926-c3fd7580-8d50-11eb-9a1c-173fd64b0301.png">

We do, in fact, get this error
<img width="490" alt="Screen Shot 2021-03-25 at 10 24 05" src="https://user-images.githubusercontent.com/30501647/112488945-60754700-8d54-11eb-991d-26a16e5b4ffc.png">

**Comment by watchtower314** [comment]
@Taikaish what should be the text for the reported content in the notification screen?
This is the text for push notification:
![image](https://user-images.githubusercontent.com/30501647/112501163-63c20000-8d5f-11eb-985a-b6655c48111b.png)

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-247)
Tested on Staging Android version 1.9.5 (4978-208)

1. Incorrect name of the Notification item for reported membership request. It shouldn't be a "Proposal Reported", maybe "Membership request Reported"

![IMG_0079](https://user-images.githubusercontent.com/68247034/112637799-96e3bc80-8e4f-11eb-82a6-c7be783b2147.PNG)

2. Moderator of the common receives incorrect Push notification about reported Membership request

![IMG_0081](https://user-images.githubusercontent.com/68247034/112638440-50db2880-8e50-11eb-9a88-ae654f89b972.PNG)

**Comment by watchtower314** [comment]
Fix screenshots -
Push notification title 
<img width="333" alt="Screen Shot 2021-03-29 at 16 43 55" src="https://user-images.githubusercontent.com/30501647/112897723-f63f0800-90ad-11eb-9bbc-380ad44a08a7.png">

NotificationItem title:
<img width="666" alt="Screen Shot 2021-03-29 at 16 57 44" src="https://user-images.githubusercontent.com/30501647/112899242-e4f6fb00-90af-11eb-9a3a-d520b931963d.png">

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-251)
Tested on Staging Android version 1.9.5 (4978-212)

Found OK!
Correct notifications are sent to the moderator about reported content:

1. Membership request reported
2. Proposal reported
3. Comment reported
4. Post reported

**Comment by yanivi71** [comment]
Verified on production

**Comment by yanivi71** [comment]
Verified on production
