### ISSUE TITLE
Add custom token ability for phone authentication

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2261]

**Comment by elatif2020** [comment]
@MeyerPV can you please add here some details on what is needed here?

**Comment by MeyerPV** [comment]
Creating a custom token for Firebase Authentication typically involves using the Firebase Admin SDK on your server. This SDK provides the functionality to create custom tokens which you can use to authenticate users in your Firebase app. Custom tokens are useful when you have an existing authentication system and you want to authenticate users in Firebase based on that system.

Here's a general outline of the steps to create and use a custom token:

Step 1: Create a Custom Token
Use Firebase Admin SDK to create a custom token. You'll need to pass a unique identifier for the user (like a user ID from your existing system).

```
admin.auth().createCustomToken(uid)
  .then((customToken) => {
    // Send token back to client
  })
  .catch((error) => {
    console.log('Error creating custom token:', error);
  });
  ```
Step 2: Use the Custom Token in Your Application
On the client side (your app), use the custom token to sign in with Firebase:

```
// Assuming this is in your Firebase web app
firebase.auth().signInWithCustomToken(customToken).then((userCredential) => {
  // User is signed in
  // ...
}).catch((error) => {
  // Handle Errors
});
```

Security Considerations
Token Security: Ensure that the process of sending the custom token from your server to the client is secure.
Unique User IDs: The UID you use to create a custom token should be unique to each user.
Privileges: Be careful with the privileges you grant through custom tokens, especially if they’re used to assume roles or access specific data.
Use Cases for Custom Tokens
Integrating with an Existing User Database: If you have an existing user system, you can create Firebase accounts for your users without requiring them to go through a Firebase-specific authentication flow.
Advanced Authentication Flows: For scenarios that require more complex authentication logic than what Firebase Authentication provides out of the box.
Creating custom tokens is a powerful feature of Firebase, but it should be used judiciously and with a strong emphasis on security. Always ensure your implementation adheres to best practices for authentication and data protection.

**Comment by MeyerPV** [comment]
Flow:

1. Sign in with phone in the app
2. Call NEW Api to get the custom token
3. Send custom token to webview
4. Login with custom token in webview

**Comment by danielr18** [comment]
we now have `/auth/custom-token` which returns the custom token with firebase auth header, and `/auth/custom-token/refresh` which returns the custom token with the google refresh token.

Response: `{ token }`
