### ISSUE TITLE
Add a flag to indicate whether a discussion\chat message has unchecked items

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2262]
It's related to this FE ticket: https://github.com/daostack/common-web/issues/2455
We're add Github style checkboxs to chat messages.
We need a flag for discussion\chat messages to indicate whether they have unchecked checkboxs ☑ in it. This will be used to filter the messages and show only messages with unchecked checkboxs.

**Comment by elatif2020** [comment]
@andreymikhadyuk please review and add if there is anything more you're thinking of

**Comment by andreymikhadyuk** [comment]
I think that's correct. Not sure only who will set this value – FE or BE. If BE has the logic to parse message string to object it can look for checkbox items which are unchecked and set the value. If there is no such logic on the BE side, then FE will send this flag.

**Comment by danielr18** [comment]
Added `hasUncheckedItems` to discussion message.
Added index to query for discussion messages by `discussionId` and `hasUncheckedItems`, ordered by `updatedAt` descending.
The flag can be passed when creating or updating a message, if not passed it will default to false.
