### ISSUE TITLE
Migration to allow admins to delete existing spaces as an action

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2263]
For all existing spaces, but not for root commons

**Comment by danielr18** [comment]
Isn't this already done?
![image](https://github.com/daostack/common-backend/assets/9046616/2b8a62b3-2863-47f8-ba46-8d80c3263d78)
![image](https://github.com/daostack/common-backend/assets/9046616/40bece32-68c9-4ba9-941b-046ce83e3016)

**Comment by danielr18** [comment]
@elatif2020 Did you try?

**Comment by elatif2020** [comment]
> @elatif2020 Did you try?

@danielr18 
it doesn't work for me as an action for example for this space:  https://web-dev.common.io/commons/0fac27c8-b9f1-4969-a28c-a7d5d07ce91e?item=388aa3ac-62cb-4032-bfb1-186308dd46c1

**Comment by NoamQA** [comment]
@elatif2020 
looks good for me also in old spaces
can you check on the one you mentioned?
