### ISSUE TITLE
Some subspaces cards appears in my Inbox

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2264]
See this

![Image](https://github.com/daostack/common-backend/assets/72435714/4987f123-7dcc-4931-b516-e9eeb0a4377c)
which is a subspace in https://web-dev.common.io/commons/a977dbb7-92bc-46e6-a600-ae6c834d589a
and appears in my inbox

**Comment by NoamQA** [comment]
@elatif2020 
looks good in my inbox
was it fixed in yours?
