### ISSUE TITLE
there are commons that i cant move an item to them

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#2266]
i tried to move an item from [this common](https://web-dev.common.io/commons/3a64c0dc-6e0f-4ea0-9018-7d51aa5e1ae8) 
to [this ](https://web-dev.common.io/commons/2e642712-d5e6-4c24-b8b4-e146075adaa0)common

i can choose the common and the apply button enabled
but it doesnt move it

but if i try to move from [this ](https://web-dev.common.io/commons/117e6956-507b-4c9b-8f49-21c4d7746187)space to the same common it works

![Image](https://github.com/daostack/common-backend/assets/129174316/f93a59bb-48a7-46ed-a1f6-7b1699baf6d6)

**Comment by danielr18** [comment]
We don't allow moving between root commons.
@elatif2020 What should the rules be?

**Comment by elatif2020** [comment]
> We don't allow moving between root commons. [@elatif2020](https://github.com/elatif2020) What should the rules be?

@danielr18 
In the spec we allow it for public items

![Image](https://github.com/daostack/common-backend/assets/72435714/09c8f3af-164b-42f1-80fa-f2cfee002d4f)

**Comment by NoamQA** [comment]
@elatif2020 
i think it will be confusing for users
the default for discussions is members
maybe add a comment when mouse hover above an unitarized common/space
(like - you cant move members discussion to another common)

**Comment by elatif2020** [comment]
> [@elatif2020](https://github.com/elatif2020) i think it will be confusing for users the default for discussions is members maybe add a comment when mouse hover above an unitarized common/space (like - you cant move members discussion to another common)

yes I agree we should do something to better explain it to the users
