### ISSUE TITLE
space card new messages counter issue 

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#2268]
The space card messages counter (number in the pink dot) increase by one every time i write a message in an unread chat

**Comment by elatif2020** [comment]
@NoamQA can you figure out how to reproduce this issue (maybe better in a new common)?

**Comment by NoamQA** [comment]
@elatif2020 @danielr18 
now there is indication for updated streams
the number and update time of unread streams is fine

but the number in the pink dot increase by one every time i write a message in an unread chat
is it a bug or a feature? :-)

**Comment by elatif2020** [comment]
> @elatif2020 @danielr18 
> now there is indication for updated streams
> the number and update time of unread streams is fine
> 
> but the number in the pink dot increase by one every time i write a message in an unread chat
> is it a bug or a feature? :-) 
> 

@NoamQA this is a beautiful bug 🙃🐞

**Comment by elatif2020** [comment]
@danielr18 for your attention pleas
I have updated this card title and info with this bug Noam found

**Comment by NoamQA** [comment]
steps to reproduce:
1.with user A create a new space with a stream in it
2.open parent common with user A 
there will be 0 unread streams on the space stream

3.with user B open the new stream in the new created space
4.with user B add few comments in the chat

for user A there will be number of written messages in the pink dot (instead of one)
and another one for each message that the other user write 



![Image](https://github.com/daostack/common-backend/assets/129174316/3a3e4eb2-9cc4-4883-a0bf-0f259272ce72)

**Comment by elatif2020** [comment]
@NoamQA thanks 
I guess I didn't understood you well enough before. What you are describing is the desired behavior...
