### ISSUE TITLE
error 500 when delete a space with linked stream in it

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#2275]
when there is a space with linked stream
and i delete the space
the link icon doesnt disappears from the other stream
and there is 500 error in the console

![Image](https://github.com/daostack/common-backend/assets/129174316/5fbd4168-0d69-47a2-a873-672b9d6307eb)

**Comment by elatif2020** [comment]
If an item is linked and its' original space is deleted we should change the commonId to another common in which it's linked

**Comment by danielr18** [comment]
Discussions are now deleted when a common is deleted.
If the discussion is linked, then it wouldn't be deleted, but rather be unlinked.
