### ISSUE TITLE
Fix missing user display name for mentions in the lastMessagePreview

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2276]
For example here:

![Image](https://github.com/daostack/common-backend/assets/72435714/a7d43e46-dfc7-4727-8d52-4eb236b06de3)

**Comment by danielr18** [comment]
@elatif2020 Do you have the link to this common?

**Comment by elatif2020** [comment]
> @elatif2020 Do you have the link to this common?

https://common.io/commons/89256185-1db2-4576-b31f-af83a09ed00b
But better to make a systematic fix and not specific for this user (it is Ido)

**Comment by danielr18** [comment]
@elatif2020 Do we need a migration for this or is hotfix enough?

**Comment by elatif2020** [comment]
@danielr18 
I'm not sure what is the issue... 
Either way is fine with me as long it is solving the issue systematically (for all users where this info is missing)
