### ISSUE TITLE
Verification function to allow anyone the check\uncheck checkboxs in a message

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2279]
The richtext format is for example: 
`[{"type":"checkbox-item","children":[{"text":"test"}],"id":"9a5ae3eb-1097-43d3-b6fa-078232b78c02","checked":false}]`

And we should allow anyone to change the checked value between true\false.
Note that possibly there could be a few checkboxs in one message but probably each change is sent separately.

**Comment by elatif2020** [comment]
@danielr18 As we were speaking there is 404 error appearing now once another user is trying to check a checkbox
you can try for example [here](https://web-dev.common.io/commons/4c87126a-d764-42c5-90dc-723431fa5a46?item=a353a15d-ad4a-4e9f-9ecf-50d3cdc5d62f&message=43798f15-9ea0-4120-b5a3-bc06843ff067)

**Comment by elatif2020** [comment]
It might also be related to the FE, please let me know what you find

**Comment by NoamQA** [comment]
@elatif2020 
works for me
can you also check?

**Comment by elatif2020** [comment]
> @elatif2020 
> works for me
> can you also check?

looking good also for me
