### ISSUE TITLE
Moderation - Hidden content - Note does not display in full

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#231]
Tested on Staging iOS version 1.9.5 (4978-243)
Tested on Staging Android version 1.9.5 (4978-204)
Steps to reproduce:

1. Go to a Content (proposal comment....) as regular/moderator user
2. Report on the content
3. Choose several problems
4. add note
5. click on report.
6. As a moderator hide this content
7. as regular/moderato view this contents

Actual results:
Display a message with hidden content with all the problems but the note display partially - see attached image

Expected results:
the Note must display in full
![image (20)](https://user-images.githubusercontent.com/69141571/111489952-48de0300-8743-11eb-81d1-6cef6e15f467.png)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-246)
Tested on Staging Android version 1.9.5 (4978-207)
@watchtower314 not fixed. note is still does not display in full.
mb we need to limit the text

![1616662436566](https://user-images.githubusercontent.com/69141571/112446185-9ddbd380-8d58-11eb-976a-7a950c334dbd.jpg)

**Comment by gingervik** [comment]
Discussed this with @Taikaish 
it's ok that user can scroll moderator note. @kazaryan-t will open a separate task for char limit

**Comment by yanivi71** [comment]
Verified on production
