### ISSUE TITLE
User´s profile - There is no "View all X Proposals/ Membership requests" button in carousels

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#234]
Tested on Staging iOS version 1.9.5 (4978-244)
Tested on Staging Android version 1.9.5 (4978-205)

Precondition: User has more than 5 active Proposals/ Membership requests

Steps to reproduce:
1. Go to the user's profile page
2. Scroll till Proposals/ Membership requests carousels
3. Swipe left Proposals/ Membership requests

Actual result:
All the Proposals/ Membership requests are swiped and there is no "View all X Proposals/ Membership requests" button.

Expected result:
The "View all X Proposals/ Membership requests" button should appear after the 5th swiped Proposal/Membership request.
Design - https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/5ef4524bcb4331505d80ce9f

https://user-images.githubusercontent.com/68247034/111623050-f102d300-87fa-11eb-9c23-3f82a640a1d1.mp4

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.7 (6591-281)
Tested on Staging Android version 1.9.7 (6591-242)

Found OK.

**Comment by yanivi71** [comment]
Tested on prod

Found Ok
