### ISSUE TITLE
Notification screen - Change the image for "New Featured Common" notification

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#237]
Tested on Staging iOS version 1.9.5 (4978-245)
Tested on Staging Android version 1.9.5 (4978-206)

Please change the image for the "New Featured Common" notification, it should be a logo of the common.

Actual result:
Moderator's avatar is displayed as an image for the "New Featured Common" notification.

Expected result:
A logo of the common should be displayed as an image for the "New Featured Common" notification.

![IMG_0068](https://user-images.githubusercontent.com/68247034/111750153-e9e3cf80-88a3-11eb-9ba8-ae5f7f310bda.PNG)

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-256)
Tested on Staging Android version 1.9.5 (4978-217)

The New Featured Common item has the logo of the common.
Found ok!

**Comment by yanivi71** [comment]
Verified on production
