### ISSUE TITLE
Moderation - "Reported by" info should be shown only for moderators

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#242]
Regular users should not see that message was reported by someone.
if someone reports a post it should be only shown to moderators.
So the text "reported by..." should only be visible to moderators

Should be done for discussion messages and proposals
Proposals include membership requests
comments within the discussions
and comments for proposal chats

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-246)
Tested on Staging Android version 1.9.5 (4978-207)

@lpetkov-sw not fixed. reported message still appears in regular user view

**Comment by yanivi71** [comment]
@MeyerPV when user report on content there is a gray background. this background should not appearץ
please check it on (posts, proposal, Request to join)

![Screenshot_2021-03-29-09-46-56-887_com daostack common staging](https://user-images.githubusercontent.com/69141571/112806307-4f437780-907f-11eb-8f62-a0eb0fa5c8f0.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-250)
Tested on Staging Android version 1.9.5 (4978-211)

Found OK. Reported content shown only to moderator

Tested on
1. discussion messages 
2. proposals
3. Proposals include membership requests
4. comments within the discussions
5. comments for proposal chats

**Comment by yanivi71** [comment]
Verified on production
