### ISSUE TITLE
Discussions, Proposal chat - Remove person name for hidden messages

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#243]
Please, remove person name for hidden messages from “hidden by [name]“
So, it should be mark just as hidden

Please, do for

- messages in chats (proposal, discussions)
- discussions
- memberships request
- proposal

![image](https://user-images.githubusercontent.com/28015224/112099885-5406b800-8bb5-11eb-8f0e-2dbaf4fbfc13.png)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-246)
Tested on Staging Android version 1.9.5 (4978-207)

Found OK
The Name of the moderator does not display

**Comment by yanivi71** [comment]
Verified on production
