### ISSUE TITLE
Discussions - Design fixes

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#245]
1. Remove your logo from a chat [zeplin link](https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/5fc90f6ea26566541e657eb3)
Only test from you should be shown
<img width="289" alt="Screenshot 2021-03-23 at 13 40 42" src="https://user-images.githubusercontent.com/28015224/112134150-78768a80-8bdd-11eb-8ed9-cb9bacbc5e02.png">

2.  Input field re-design 
- round corners
- the place for + icon (should not be implemented now, just reserve a place)
How it was / How it should be
<img width="285" src="https://user-images.githubusercontent.com/28015224/112134541-ea4ed400-8bdd-11eb-8e33-7084c5e03b36.png"> <img width="285" alt="Screenshot 2021-03-23 at 13 44 57" src="https://user-images.githubusercontent.com/28015224/112134593-f6d32c80-8bdd-11eb-890b-062e871ae4e0.png">

3. Messages from other users should have blue background
<img width="287" alt="Screenshot 2021-03-23 at 13 46 22" src="https://user-images.githubusercontent.com/28015224/112134948-516c8880-8bde-11eb-83d5-f23ed795f363.png">

4. Date of discussion (example, Today) should have white background and round corners
<img width="286" alt="Screenshot 2021-03-23 at 13 49 55" src="https://user-images.githubusercontent.com/28015224/112135272-aa3c2100-8bde-11eb-9b57-cccd574e8950.png">

5. Background color should be changed to rgb 243 244 255
[zeplin link](https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/5ef45498f1a8c7a07d6e71ba
)

**Comment by watchtower314** [comment]
@Taikaish what should be the functionality of the `+` button? 
- Is it for images only, or for files as well?

(You can answer tomorrow, asking now because for I don't want to forget in the morning :) )

**Comment by watchtower314** [comment]
**IMPORTANT NOT FOR QA:**
The plus button should not be visible  at this point -> I spoke with Tai, it should be added in Better Discussion Batch 3

**Comment by kazaryan-t** [comment]
1. The time should be placed on the same line with the message text https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/5ef45489faf0aa9cd840cba9

2. Put the title of the post in the center of the screen 
![Screenshot_20210326-180120_common-stg](https://user-images.githubusercontent.com/68247034/112652397-6e16f380-8e5e-11eb-934c-0b70654e9ae6.jpg)

**Comment by watchtower314** [comment]
PR: soon
Fix screenshots:
<img width="720" alt="Screen Shot 2021-03-29 at 8 44 14" src="https://user-images.githubusercontent.com/30501647/112838518-244f2880-906b-11eb-9fef-a0d9e41768e6.png">
<img width="713" alt="Screen Shot 2021-03-29 at 8 38 00" src="https://user-images.githubusercontent.com/30501647/112838526-25805580-906b-11eb-8de2-2c668256ce29.png">

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-250)
Tested on Staging Android version 1.9.5 (4978-211)

1. Please, divide the post title into different lines if it is long.

Actual:
![Screenshot_20210330-185726_common-stg](https://user-images.githubusercontent.com/68247034/113020676-7d15e280-918b-11eb-8b1d-667aac7a0d19.jpg)

Design: https://zpl.io/VxN67vg

**Comment by watchtower314** [comment]
@kazaryan-t we already have a style for having `...` for when the text is too long, so I keep that, just fixed the text covering the arrow :) 
<img width="358" alt="Screen Shot 2021-03-31 at 13 18 27" src="https://user-images.githubusercontent.com/30501647/113184752-95394080-9223-11eb-8537-6667791029af.png">

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-256)
Tested on Staging Android version 1.9.5 (4978-217)

1. There is a lot of blank space over the arrow in post content for the Discussions.

![Screenshot_20210401-153016_common-stg](https://user-images.githubusercontent.com/68247034/113295653-25998300-9301-11eb-94d6-2d6a837bd3cd.jpg)
![Screenshot_20210401-152959_common-stg](https://user-images.githubusercontent.com/68247034/113295659-26cab000-9301-11eb-896a-b9637692b9c1.jpg)

2. When the Discussion title is too long, the menu button (three dots) moves to the border of the discussion box.

![IMG_0100](https://user-images.githubusercontent.com/68247034/113295966-8d4fce00-9301-11eb-84a5-16ba7c8f0e18.PNG)

**Comment by watchtower314** [comment]
Demo:

https://user-images.githubusercontent.com/30501647/113298060-67a6d280-92c9-11eb-9196-baf5eca79f7e.mov

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-257)
Tested on Staging Android version 1.9.5 (4978-218)

Found OK
The gap in discussion is resized

**Comment by yanivi71** [comment]
Verified on production
