### ISSUE TITLE
New post - Redesign

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#246]
When creating a post, users should no longer be able to add images, links, and files
The screen should look like this 
[zeplin link](https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/5ef454a3a2feb5a02a4b1d17)
<img width="290" alt="Screenshot 2021-03-23 at 14 02 06" src="https://user-images.githubusercontent.com/28015224/112136704-5c281d00-8be0-11eb-8c37-3903ddc2d4ac.png">
1. Bold font for the title
2. Limit for message 690 chars
3. Char counter should be added
4. Change "Title" to 'Post title'

**Comment by watchtower314** [comment]
@Taikaish 

So just to make sure I've got everything clear:
1. Should I remove the `What do you have to say?` message place holder that is not in the new design
<img width="247" alt="Screen Shot 2021-03-24 at 15 03 27" src="https://user-images.githubusercontent.com/30501647/112369018-1d629780-8cb2-11eb-9402-81e2c2e74174.png">

2. The counter in other screens appears inside the textInput box like this
<img width="313" alt="Screen Shot 2021-03-24 at 14 57 40" src="https://user-images.githubusercontent.com/30501647/112368611-a62d0380-8cb1-11eb-993c-31c498800ac3.png">

Should I do the same here, or put it outside like in the new design?
(New design:  
<img width="275" alt="Screen Shot 2021-03-24 at 15 00 50" src="https://user-images.githubusercontent.com/30501647/112368948-00c65f80-8cb2-11eb-8e86-b83c38c6a7a0.png">
)

3. The new design does not have the option to add files and images, should I remove them altogether?
<img width="341" alt="Screen Shot 2021-03-24 at 15 03 59" src="https://user-images.githubusercontent.com/30501647/112369069-2eaba400-8cb2-11eb-9cdf-f7a268ab5d90.png">

**Comment by Taikaish** [comment]
Hey. 

1. Yes
2. Good catch, let's use what we have for a new common (inside the box). I'll ask brio to fix
3. Yes

**Comment by watchtower314** [comment]
screenshots of the new design
<img width="340" alt="Screen Shot 2021-03-24 at 16 12 10" src="https://user-images.githubusercontent.com/30501647/112377388-0de84c00-8cbc-11eb-8ad4-35e2e636c8b2.png">
![IMG_61677F771459-1](https://user-images.githubusercontent.com/30501647/112377411-15a7f080-8cbc-11eb-8d5d-3c3bbee77f26.jpeg)

**Comment by kazaryan-t** [comment]
1. Android - Put the title of the page "New Post" in the center of the screen

![Screenshot_20210326-175025_common-stg](https://user-images.githubusercontent.com/68247034/112651990-fd6fd700-8e5d-11eb-83c8-5a098692e5df.jpg)

2. Change the back button for a Cancel (X) button 

![10 11 1 Common page_ new discussion topic - Common](https://user-images.githubusercontent.com/68247034/112663111-80e2f580-8e69-11eb-8e77-f9995c14d9b8.png)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-250)
Tested on Staging Android version 1.9.5 (4978-211)

Found OK
1. When creating a post, users should no longer be able to add images, links, and files
2. The screen look like zeplin design
3. Android - title of the page "New Post" in the center of the screen
4. the back button is changed to a Cancel (X) button

**Comment by yanivi71** [comment]
Verified on production
