### ISSUE TITLE
Common Creation - Rules - Apply a limit for 512 chars in Rule description field

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#248]
Please, apply a limit for 512 chars in the Rule description field when creating or editing the Common. 

Actual result:
The user is able to insert or type more than 512 chars, but there is an error when creating a Common.

![Screenshot_20210323-153535_common-stg](https://user-images.githubusercontent.com/68247034/112147607-f5a9fb80-8bed-11eb-8466-bba14913e4e8.jpg)

Expected result: 
The user cannot insert or type more than 512 chars in the Rule description field.

![Screenshot_20210323-134643_common-stg](https://user-images.githubusercontent.com/68247034/112147630-fe9acd00-8bed-11eb-829f-2b8650da3160.jpg)

**Comment by kazaryan-t** [comment]
The limit for rule description works fine. 
User is not able to insert or type more than 512 chars.

Tested on Staging iOS version 1.9.5 (4978-248)
Tested on Staging Android version 1.9.5 (4978-209)

![Screenshot_20210326-182243_common-stg](https://user-images.githubusercontent.com/68247034/112654416-6ce6c600-8e60-11eb-8523-346aaf8361a9.jpg)

**Comment by yanivi71** [comment]
Verified on production
