### ISSUE TITLE
Notification item nav back crash

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#256]
Steps to reproduce:
- click open on a proposal/discussion notification item from notification screen
- click the back button

expected result:
- user goes back to notification screen

actually result:
app crashes

**Comment by kazaryan-t** [comment]
No crashes anymore clicking on Back button from open proposal/discussion notification item.

Tested on Staging iOS version 1.9.5 (4978-247)
Tested on Staging Android version 1.9.5 (4978-208)

**Comment by yanivi71** [comment]
Verified on production
