### ISSUE TITLE
The app crashes when clicking on back button from voting page

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#259]
Tested on Staging iOS version 1.9.5 (4978-247)
Tested on Staging Android version 1.9.5 (4978-208)

Precondition:
The common has active proposals or membership requests

Steps to reproduce:
1. Go to a common page
2. Click on Proposals icon
3. Click on View proposal button
4. Click on Back button
5. Go to a common page that has pending members
6. Go to a pending members screen
7. Click on View request button
8. Click on Back button

Also, it happens when going to a View proposal or View request screen from the user's profile.

Actual result:
The app crashes after clicking on Back button

Expected result:
There is no crash and the app returns to the previous page.

https://user-images.githubusercontent.com/68247034/112616254-8c67f980-8e34-11eb-9357-680b3cfcfa1a.mp4

https://user-images.githubusercontent.com/68247034/112616290-97228e80-8e34-11eb-979b-4e5fbf2022fb.MP4

https://user-images.githubusercontent.com/68247034/112616470-d3ee8580-8e34-11eb-85ce-0064adbf7ae0.mp4

**Comment by yanivi71** [comment]
@watchtower314 @lpetkov-sw there is another crash in history tab

Steps to reproduce:

1. Go to a common page
2. Click on History tab
3. Choose item and Click on View proposal button
4. Click on Back button

app crashes

**Comment by watchtower314** [comment]
PR: https://github.com/daostack/common/pull/1000
Demo:
https://user-images.githubusercontent.com/30501647/112826265-c1ee2c00-905a-11eb-8fda-ad3a5ed8592c.mov

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-250)
Tested on Staging Android version 1.9.5 (4978-211)

Found ok.

Tested on:
1. Proposals (user's profile)
2. Membership request (user's profile)
3. Proposals (history)
4. Membership request (history)

**Comment by yanivi71** [comment]
Verified on production
