### ISSUE TITLE
We need to get our Production secrets only when running in production

### ISSUE THREAD

**Issue by BigRomanov** [daostack/common-backend#26]
Currently, all of devs have access to the secrets on production, because that is the only way they can run the app locally with "production data".

This is not good at all - we want to have a situation where the secret is, well, more secret  

The solution here is to chang ethe code of our `getSecret` fucntion somewhat - if we run in production, locally, it should not try to read the secret from the server (but instead, mb, print a warning and return a "dummy secret" - it is ok that paymnets and updates will fail in this case)

**Comment by gingervik** [comment]
discussed with @alexander2001i 
closed as irrelevant
