### ISSUE TITLE
Remove fontWeight from the TextInputField and add style prop, which will override the entire style of the component.

### ISSUE THREAD

**Issue by lpetkov-sw** [daostack/common-backend#260]
That ticket was created after reviewing a PR. 
Here is my comment in the PR https://github.com/daostack/common/pull/988#discussion_r602222554

**Comment by gingervik** [comment]
Relates to #227

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-261)
Tested on Staging Android version 1.9.5 (4978-222)

Found OK
the change was within create a new post. the title should be in bold when user types it

**Comment by yanivi71** [comment]
Cannot verified
