### ISSUE TITLE
Create Common - Tagline and About fields should be not required

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#265]
Allow users to create commons without a tagline and about.
They can always add it later.

Please, remove this limitation from **Tagline** and **About** fields
[zepplin link](https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/5ef452bf296d33a142bc200c)
<img width="284" alt="Screenshot 2021-03-28 at 11 27 48" src="https://user-images.githubusercontent.com/28015224/112746625-a29ec280-8fb8-11eb-95b0-a11814d3b0a3.png">

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-266)
Tested on Staging Android version 1.9.5 (4978-227)

**1. When creating a common without Tagline and About fields, the error appears.**

Steps to reproduce:
1. Click on Create a common button
2. Put the name of the common, but leave tagline and about fields empty
3. Continue with creating a common and click on Publish common

Actual:
The error appears (Screenshot)
![Screenshot_20210410-093812_common-stg](https://user-images.githubusercontent.com/68247034/114261075-4341a900-99e1-11eb-88b4-fc895a3287b4.jpg)

**2. When editing the common without About field, an error appears "The about field is required" and user can't save changes without filling the About field.**


https://user-images.githubusercontent.com/68247034/114262040-6884e600-99e6-11eb-99a1-18f95db94de5.mp4

**Comment by alexander2001i** [comment]
PR #348 is merged. @watchtower314 Does this ticket have a frontend companion PR?

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-268)
Tested on Staging Android version 1.9.5 (4978-229)

Found ok!
Users can create commons without Tagline and About fields.

**Comment by kazaryan-t** [comment]
Verified on Production
