### ISSUE TITLE
Create Common - Prevent credit card payments of below $5

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#266]
The minimum contribution should be at least $5
DO NOT FORGET TO CHANGE WARNING MESSAGE ALSO
For this, we will split the current field of "Minimum contribution" into two fields.

On the "Minimum contribution" field, the minimum will be $5 (not $0 as it is today).

We also changed the title and text to match the new functionality.

In addition, we should add a new checkbox, for founders who want to allow members to join without a personal contribution. If this option is selected, the "minimum contribution" field will be disabled and set automatically for "5$".

!!!Remove Funds safety period section from common creation, and let anyone create proposals from day one.

1 - [Create common - funding](https://zpl.io/VxzyAqm)

2 - [No-contribution members selected](https://zpl.io/2p8d45Q)

3 - [Error message for minimum contribution below $5](https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/604635ba52527f162286479b/)

**Comment by alexander2001i** [comment]
@lpetkov-sw - The backend part of this PR is merged, ping me when you need it deployed

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-268)
Tested on Staging Android version 1.9.5 (4978-229)

There are some mismatches with the design:

1. We should add the word TYPE near the word Contribution
2. Delete (min. $5) and Required 
3. Change the error when a user enters less than 5$ in the contribution field (it should be "The minimum contribution must be $5 or higher")
4. When the moderator of the common clicks on the checkbox (that allows members to join without a personal contribution), the contribution field should be inactive. - https://zpl.io/2p8d45Q

Design - 
![04 02 2 create common_ funding - error - Common MV](https://user-images.githubusercontent.com/68247034/114564002-97b28600-9c78-11eb-8ba1-a40454250c93.png)

Actual - 
![Screenshot_20210413-162010_common-stg](https://user-images.githubusercontent.com/68247034/114564085-ab5dec80-9c78-11eb-86ea-b96bab6f9e0c.jpg)

**Comment by watchtower314** [comment]
@Taikaish I have a question about the limit of the funding, right now for one-time it's between $5-$3000, and for monthly it's $5-$500, but the design doesn't have that anymore, so should I remove this at all, or we still need this?

<img width="320" alt="Screen Shot 2021-04-14 at 7 50 23" src="https://user-images.githubusercontent.com/30501647/114705745-139ee380-9cf6-11eb-9e14-33bf9707de03.png">
<img width="315" alt="Screen Shot 2021-04-14 at 7 50 30" src="https://user-images.githubusercontent.com/30501647/114705761-17326a80-9cf6-11eb-8102-e4d40b725c7d.png">

**Comment by watchtower314** [comment]
@kazaryan-t what about monthly contribution?
this is how it looks when I change the error message:
<img width="278" alt="Screen Shot 2021-04-14 at 8 01 51" src="https://user-images.githubusercontent.com/30501647/114707071-c7ed3980-9cf7-11eb-9bd5-af28420f062e.png">

**Comment by watchtower314** [comment]
@kazaryan-t I spoke with Tai, regarding the upper limit, we still need to have this error message for amount that is greater than the correct max contributio:
(max for one-time contribution should be $3000 and for monthly, it's $500)


monthly
<img width="319" alt="Screen Shot 2021-04-18 at 4 25 34" src="https://user-images.githubusercontent.com/30501647/115139106-223f1080-9ffe-11eb-9645-99fe4b3bb5f8.png">

 one-time
<img width="328" alt="Screen Shot 2021-04-18 at 4 24 29" src="https://user-images.githubusercontent.com/30501647/115139073-f885e980-9ffd-11eb-9a31-038d13abf994.png">

**Comment by watchtower314** [comment]
What to test:
- allow users to join without contribution: only FOR ONE-TIME contribution
- remove `(min $5)` from title, and remove `required`
<img width="277" alt="Screen Shot 2021-04-18 at 4 27 21" src="https://user-images.githubusercontent.com/30501647/115139149-5f0b0780-9ffe-11eb-9684-1c58e946bc38.png">
- add `type` to title 
<img width="271" alt="Screen Shot 2021-04-18 at 4 27 41" src="https://user-images.githubusercontent.com/30501647/115139163-6b8f6000-9ffe-11eb-861e-be6bd844e670.png">

**Comment by kazaryan-t** [comment]
Tested on Staging Android version 1.9.6 (6433-233)

Strange behavior of the contribution field on the Funding page

Steps to reproduce:
1. Start to create a Common
2. On the Funding page click on the checkbox "Let users join the Common without a personal contribution"
3. Click on the checkbox one more time
4. Try to insert an amount
5. Click on the back arrow
6. Click on Continue to Funding button

Actual:
- The text "Minimum **one-time** contribution" disappears
- Impossible to insert the amount to the amount field
- Incorrect amount appears after clicking back and returning to the Funding page


https://user-images.githubusercontent.com/68247034/115275485-840c9100-a14a-11eb-8cd0-feba9f40352e.mp4

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.6 (6433-274)
Tested on Staging Android version 1.9.6 (6433-235)

Found ok!
1. The min contribution for one-time and monthly contributions - 5$
2. The founder of commons with a one-time contribution is able to allow members to join without a personal contribution - there is a checkbox for that.
3. Funds safety period section was removed.
4. Some UI changes were implemented.

**Comment by yanivi71** [comment]
Verified on production
