### ISSUE TITLE
Align common title in the centre if there is no a tagline

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#267]
This is how commons will look without a tagline: (name should be centered)

2 - [Create common - review](https://zpl.io/V4wAXOQ)

3 - [Explore commons](https://zpl.io/aR59NPp)

4 - [Common page](https://zpl.io/aRnNkxN)

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.6 (6433-271)
Tested on Staging Android version 1.9.6 (6433-232)

Found OK.

**Comment by kazaryan-t** [comment]
Verified on production
