### ISSUE TITLE
Change Agenda and Rules screen design

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#268]
<img width="280" alt="Screenshot 2021-03-28 at 11 50 33" src="https://user-images.githubusercontent.com/28015224/112747091-cf080e00-8fbb-11eb-86ac-cbc7d31d834d.png"> <img width="280" alt="Screenshot 2021-03-28 at 12 05 40" src="https://user-images.githubusercontent.com/28015224/112747400-ecd67280-8fbd-11eb-950b-72c516b404d0.png">

* The moderator should be able to change or add Rules here
* Any user should see the contribution
* About and Rules should be displayed if they are filled but with ability for editing

**No agenda + no rules:**

1 - [Moderator view](https://zpl.io/b6nD3OP)

2 - [Regular user view](https://zpl.io/Vk4XE38)

**Comment by lpetkov-sw** [comment]
The ticket explains that we need to implement functionality for editing common rules, but actually we already have it implement in the app for a while.  That's confirmed with @yanivi71 .
Currently we have the following implementations on staging:
* The moderator should be able to change Rules here
* About and Rules should be displayed if they are filled but with ability for editing

The only missing part of the ticket description that I can see is the information about **Minimum contribution** . So, I think we need to edit the ticket with only that UI improvement. This week Moore was working on ticket  https://github.com/daostack/common-monorepo/issues/266 which is related to a change in the Minimum contribution logic, so we should apply it here as well.
My understanding is that we need to implement only the following point:
* Any user should see the contribution

FYI: @BigRomanov @gingervik

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.6 (6433-270)
Tested on Staging Android version 1.9.6 (6433-231)

Already implemented:
1. Moderator and a regular user are able to see the Minimum Contribution of the common. 
2. About and Rules of conduct fields are displayed if they are filled in. 
3. Moderator can edit the About field.

**The possibility to change or add rules directly from Agenda and Rules screen will be implemented in issue #381.**

**Comment by kazaryan-t** [comment]
Verified on Production
