### ISSUE TITLE
Intercom support chat - Backend part

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#269]
This is meant to allow users to easily report problems or send their feedback.

The integration docs for Intercom:

[https://www.intercom.com/help/en/articles/567786-install-and-use-intercom-in-your-mobile-app](https://www.intercom.com/help/en/articles/567786-install-and-use-intercom-in-your-mobile-app)

Contact @Taikaish Tai to get access to our account on Intercom + API credentials etc.

The support chat should open when the Help icon is clicked.

Task for UI part #270

**Comment by lpetkov-sw** [comment]
Closing the issue as the implementation was made only in the frontend by integrating a react-native library for that. FYI: @gingervik
