### ISSUE TITLE
Intercom support chat - add help buttons on screens

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#270]
The support chat should open when the Help icon is clicked.

**The Help icon will be embedded at the following screens:**

1 - [My profile](https://zpl.io/beqO1oY)

2 - [Billing](https://zpl.io/a7myJxM)

3 - [Create common](https://zpl.io/bzgjyJX)

4 - [New proposal](https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/5ef45f055b8a0da114cbfca7/)

(Example for a common with a long name)

5 - [Membership Request](https://zpl.io/2ENxwgx)

6 - [Request to join proposal - Payment Failed](https://zpl.io/2yr3q6G)

Backend part should be done in #269

**Comment by baticpro** [comment]
Issues #270 and #269 were too related and I make one PR for them: https://github.com/daostack/common/pull/1076

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.7 (6591)
Tested on Staging Android version 1.9.7 (6591-240)

@baticpro  - on billing there is no intercom -
1 - My profile - OK

**2 - Billing - there is no intercom**

3 - Create common - OK

4 - New proposal - OK

5 - Membership Request- OK

6 - Request to join proposal - Payment Failed - Cannot checked

**Comment by baticpro** [comment]
@yanivi71 - Could you describe me flow how can I reach "Billing" screen, I can't find it ))) Lyubo also thinks that we don’t have that screen

**Comment by yanivi71** [comment]
@baticpro 
1. go to user profile
2. Scroll down
3. Choose monthly contribution

This is the billing page. The intercom should be there also

**Comment by kazaryan-t** [comment]
Tested on Android - 1.9.7 (6591-241)
Tested on iOS - 1.9.7. (6591-280)

1 - My profile - OK
2 - Billing - OK
3 - Create common - OK
4 - New proposal - OK
5 - Membership Request- OK
6 - Request to join proposal - Payment Failed - Cannot check

**Comment by yanivi71** [comment]
Tested on production
1 - My profile - OK
2 - Billing - OK
3 - Create common - OK
4 - New proposal - OK
5 - Membership Request- OK
6 - Request to join proposal - Payment Failed - Cannot check
