### ISSUE TITLE
Change the name & email of the sender for automatic emails

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#271]
General emails: 
**Common Team** (team@common.io)

Payouts (currently sent from payouts@common.io):

**Common Payouts** (payouts@common.io)

**Comment by watchtower314** [comment]
@gingervik currently this is the sender we have:
 STAGING
- general emails from: `staging@common.io`
- payout emails from `payout@common.io`

PRODUCTION
- general emails from: `support@common.io`
- payout emails from: `payout@common.io`

My question is:
Should I change the sender text on the email template to look like `Common Team (team@common.io)` and `Common Payouts (payouts@common.io)`, or just have the emails sign `Common Team` and `Common payouts` without the email address?

**Comment by Taikaish** [comment]
Hey! The first option - both the sender name and address

**Comment by watchtower314** [comment]
@Taikaish regarding this email `team@common.io`, I tested it to verify its existence, and this is what I got back:

![IMG_8080](https://user-images.githubusercontent.com/30501647/116886208-73bbe200-ac31-11eb-92e4-fb03caa87e80.PNG)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.7 (6591-284)
Tested on Staging Android version 1.9.7 (6591-245)
@watchtower314 
Found OK 
except - common in feature screen . which did not has the email address.
will be reported in a different issue
