### ISSUE TITLE
Allow more chars in the name and Tagline of Commons

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#273]
[Zepplin link](https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/5ef454c2a72777a0c7546e57)

Update card design according to:
[Card comparison](https://miro.com/app/board/o9J_lXUPFyo=/?moveToWidget=3074457353945194803&cot=14)

Common name - 49 Character
Tagline -  89 Character

Also, new limits should be implemented on all screens
![image](https://user-images.githubusercontent.com/28015224/112748145-9fa8cf80-8fc2-11eb-895f-708ebc352724.png)
1. New common
2. Edit common

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.6 (4978-274ye)
Tested on Staging Android version 1.9.6 (4978-235)

Found Ok
Common name is now 49 characters
Tagline is 89 characters

**Comment by yanivi71** [comment]
Verified on production
