### ISSUE TITLE
Design for commons with long "About" field

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#274]
Design: [zepplin](https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/5ef45856f9f25f818a3d55ba)
When the "About" is longer, the max character is **492**
<img width="286" alt="Screenshot 2021-03-28 at 12 44 43" src="https://user-images.githubusercontent.com/28015224/112748271-61f87680-8fc3-11eb-86b0-32ac3e0508c1.png">

**Comment by kazaryan-t** [comment]
Verified on production
