### ISSUE TITLE
Display welcome notification in notification Screen

### ISSUE THREAD

**Issue by lpetkov-sw** [daostack/common-backend#276]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Steps to reproduce:
1. Open the app

Actual results:
1. No Welcome notification

Expected results:
1. welcome notification message should be displayed

![image](https://user-images.githubusercontent.com/69141571/110246771-956e5500-7f71-11eb-976e-c3b53fba4881.png)

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-249)
Tested on Staging Android version 1.9.5 (4978-210)

1) On android when user opens the app, the red dot appears only when the user clicks on the user's profile or notification icon. (on iOS the red dot appears once the user opens the app)

2) On android and iOS the red dot disappears only when a user goes to another screen e.g. user's profile or common list (not when all blue dots disappear)


https://user-images.githubusercontent.com/68247034/112813974-7a31c980-9087-11eb-8a8d-956f2ae8c3f3.mp4


https://user-images.githubusercontent.com/68247034/112813979-7bfb8d00-9087-11eb-8929-684595ba7a4a.MP4

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-256)
Tested on Staging Android version 1.9.5 (4978-217)

Found OK!

1. New Users receive the Welcome notification.
2. The red dot on Android appears once the user opens the app.
3. New ticket for red dot behavior - https://github.com/daostack/common-monorepo/issues/304

**Comment by yanivi71** [comment]
Verified on production
