### ISSUE TITLE
Moderation - Hidden comment is display to the user who wrote the comment

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#279]
Tested on Staging iOS version 1.9.5 (4978-249)
Tested on Staging Android version 1.9.5 (4978-210)

Steps to reproduce:
Verified on Common "T-Shirt" on staging with 3 members in the common

1. as a regular report a content of a comment
2. As a moderator hide the comment

Actual results:
1. The comment is hidden for the user who reported it
2. The comment is not hidden on the user who wrote the common - this is wrong
3. moderation - See the comment with title hidden

Note: this issue must be implemented also All other hidden content (proposals, post, request to join). the hidden content is display

see attached image

Expected results:
1. The comment is hidden for the user who reported it
2. The comment is hidden on the user who wrote the common
3. moderation - See the comment with title hidden

![image](https://user-images.githubusercontent.com/69141571/112808099-4fdd0d80-9081-11eb-91fa-2e0d407aebb8.png)

**Comment by watchtower314** [comment]
NOTE FOR QA:
This ticket also fixes:
- missing icon of hidden comment
- `Hidden` flag is now with a capital letter
- Remove time from hidden comments (after a talk with Tai)
<img width="240" alt="Screen Shot 2021-03-30 at 6 57 31" src="https://user-images.githubusercontent.com/30501647/112978335-342b4300-9125-11eb-9ef3-fd7211a576c2.png">

Non-moderators
![IMG_5D91DF7C76A4-1](https://user-images.githubusercontent.com/30501647/112978425-5624c580-9125-11eb-94ab-447dff4dc0f3.jpeg)

Hidden comments for comment owners:
<img width="158" alt="Screen Shot 2021-03-30 at 7 00 37" src="https://user-images.githubusercontent.com/30501647/112978830-caf7ff80-9125-11eb-9677-d4fa890fef05.png">

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-251)
Tested on Staging Android version 1.9.5 (4978-212)

Found OK
The comment is hidden for the user who reported it
The comment is hidden on the user who wrote the common
moderation - See the comment with title hidden

1. missing icon of hidden comment
2. Hidden flag is now with a capital letter
3. Remove time from hidden comments (after a talk with Tai)

**Comment by yanivi71** [comment]
Verified on production
