### ISSUE TITLE
Moderation - Hidden content - Notes don't scroll

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#280]
Tested on Staging iOS version 1.9.5 (4978-249)
Tested on Staging Android version 1.9.5 (4978-210)

Steps to reproduce:
1. Go to a Content (proposal, post, etc) as a regular user/moderator 
2. Report the content
3. Choose several problems
4. Add a long note
5. Click on the report
6. As a moderator hide this content
7. As regular/moderator view this content clicking on "?" button

Actual result:
The user sees the report information, but cannot scroll through the note.

Expected results:
The user is able to scroll the whole note.

https://user-images.githubusercontent.com/68247034/112834760-0ac8d380-90a1-11eb-967d-21a03e22858d.mp4

https://user-images.githubusercontent.com/68247034/112834735-03092f00-90a1-11eb-9cf3-8bb3465aa76e.MP4

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-251)
Tested on Staging Android version 1.9.5 (4978-212)

Found ok
The user is able to scroll the whole note.

**Comment by yanivi71** [comment]
Verified on production
