### ISSUE TITLE
Notification - Common list appear before the user redirect to the page

### ISSUE THREAD

**Issue by BigRomanov** [daostack/common-backend#29]
https://daostack1.atlassian.net/browse/CM-1392

Tested on Staging iOS version 1.8 (4249-149)
Tested on Staging Android version 1.8 (4249-105)

Steps to reproduce:
1. Create sever notificatios on your device
2. Click on the notification

Actual results:
Common list appear before the user redirect to the page

Expected results:
user should be redirect to the page or we need  to display a loading when common list appears

**Comment by yanivi71** [comment]
Not a bug
