### ISSUE TITLE
Notification screen - App crashes when a" Comment reported " notification is received

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#290]
Tested on Staging iOS version 1.9.5 (4978-251)
Tested on Staging Android version 1.9.5 (4978-212)

Steps to reproduce:
1. As a moderator user navigate to notification screen
2. As a regular user (with different device) report a comment on a post

Actual results:
Comment is reported and the moderator app crashes

Expected results:
Comment should be reported and display on moderator notification screen

**Comment by watchtower314** [comment]
@yanivi71 
I don't see a crash 🤔 perhaps you can provide more details 

in the video, I'm reporting from another device

https://user-images.githubusercontent.com/30501647/113116661-a52d3200-91db-11eb-8daf-252227012fe5.mov

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-255)
Tested on Staging Android version 1.9.5 (4978-216)

Found OK.
Comment is reported and display on moderator notification screen

**Comment by yanivi71** [comment]
Verified on production
