### ISSUE TITLE
Incorrect notification item for rejected membership request

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#294]
Tested on Staging iOS version 1.9.5 (4978-255)
Tested on Staging Android version 1.9.5 (4978-216)

The user whose Membership request was rejected receives an incorrect notification item.
Design - https://zpl.io/bJMNk8D

Current behavior iOS and Android:

![IMG_0094](https://user-images.githubusercontent.com/68247034/113158129-2fa97c00-9244-11eb-8d70-19d6cfd94e8c.PNG)

![Screenshot_20210331-165518_common-stg](https://user-images.githubusercontent.com/68247034/113158137-30421280-9244-11eb-8c40-ba74ff6b3491.jpg)

**Comment by watchtower314** [comment]
Fixed in Lyubo's pr: https://github.com/daostack/common/pull/1011#pullrequestreview-625499130

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-256)
Tested on Staging Android version 1.9.5 (4978-217)

Found OK!

**Comment by yanivi71** [comment]
Verified on production
