### ISSUE TITLE
App crashes when user logs out after clicking on Monthly contribution link

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#297]
Tested on Staging iOS version 1.9.5 (4978-255)
Tested on Staging Android version 1.9.5 (4978-216)

Steps to reproduce:
1. Navigate to User profile page
2. Click on Monthly contribution link
3. Click on Back button
4. Click on Log out and proceed the logout clocking on OK

Actual result:
The app crashes.

https://user-images.githubusercontent.com/68247034/113256852-6f1ea980-92d2-11eb-8434-9a7dc6847b57.mp4

**Comment by watchtower314** [comment]
Demo:
https://user-images.githubusercontent.com/30501647/113262129-41b80880-929e-11eb-8334-5a404fb1ec7d.mov

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-256)
Tested on Staging Android version 1.9.5 (4978-217)

The app still crashes, when the user:



1. Goes to Monthly contributions 
2. Opens any monthly contribution 
3. Goes back to user's profile 
4. Proceed with log out

https://user-images.githubusercontent.com/68247034/113291901-5fb45600-92fc-11eb-9ee7-e4dcb2ba6cf6.mp4

https://user-images.githubusercontent.com/68247034/113291881-5925de80-92fc-11eb-8442-85f8404f37d2.MP4

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-257)
Tested on Staging Android version 1.9.5 (4978-218)

Found OK
app does not crashes on log out

**Comment by yanivi71** [comment]
Verified on production
