### ISSUE TITLE
Discussion - join the discussion - The message when user is not a member hides the text

### ISSUE THREAD

**Issue by BigRomanov** [daostack/common-backend#30]
https://daostack1.atlassian.net/browse/CM-1186

Tested on Staging iOS version 1.6 (3482-115)
Tested on Staging Android version 1.6 (3482-69)

Steps to reproduce:
1. Go to a common that you are not a member
2. Go to discussion tab 
3. Choose discussion with many comments
4. Click on join the discussion
5. Scroll the screen up and down

Actual results:
The message when user is not a member hides the text - see attached image

Expected results:
The message should not hide the text . or maybe user that is not a member will not be able to click on " join the discussion " button

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-216)
Tested on Staging Android version 1.9.5 (4978-177)

Found OK
the message now is centered

**Comment by yanivi71** [comment]
Verified on Prod
