### ISSUE TITLE
Request to join - one time contribution - when joining one-time commons, It has the same texts for monthly

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#302]
ested on Staging iOS version 1.9.5 (4978-255)
Tested on Staging Android version 1.9.5 (4978-216)

Steps to reproduce:
1. Request to join a common with one time contribution
2. Navigate to membership contribution - results - wrong text at the bottom
3. Fill all detail i billing details and continue to payment details   - results - wrong text at the bottom

Actual results:
membership contribution and payment details contains wrong text see attached images
its the same texts for monthly, super confusing.

![Image from iOS (46)](https://user-images.githubusercontent.com/69141571/113277451-66859d80-92e9-11eb-8db9-51950e4ee6b2.png)
![Image from iOS (45)](https://user-images.githubusercontent.com/69141571/113277460-68e7f780-92e9-11eb-9c04-73a8da1533f5.png)

Expected results:
Change the text according to the images below
![image](https://user-images.githubusercontent.com/69141571/113277585-92088800-92e9-11eb-9c91-584924852f1d.png)
![image](https://user-images.githubusercontent.com/69141571/113277736-b6fcfb00-92e9-11eb-90fe-186165c868ff.png)

**Comment by watchtower314** [comment]
@yanivi71 this is how it should look, correct?
<img width="349" alt="Screen Shot 2021-04-01 at 6 21 23" src="https://user-images.githubusercontent.com/30501647/113280624-877ecc00-92b2-11eb-810b-c1e67a07aa80.png">
<img width="341" alt="Screen Shot 2021-04-01 at 6 21 15" src="https://user-images.githubusercontent.com/30501647/113280630-89488f80-92b2-11eb-8891-addf3e254c80.png">

**Comment by yanivi71** [comment]
@watchtower314 yes. i took it from zeplin. this should be implemented only for one time contribution

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-256)
Tested on Staging Android version 1.9.5 (4978-217)

Found OK
Screens are updated with the correct text on one time contribution

**Comment by yanivi71** [comment]
Verified on production
