### ISSUE TITLE
Moderation - Moderator - Comment on a post - hidden Icon is display when comment is reported

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#305]
Tested on Staging iOS version 1.9.5 (4978-256)
Tested on Staging Android version 1.9.5 (4978-217)

Steps to reproduce:
1. as a regular user report on a comment
2. Ad a moderator see the reported comment

Actual results:
 Hidden Icon is display when comment is reported - see attached image
![image](https://user-images.githubusercontent.com/69141571/113302806-19192880-9309-11eb-9c93-2924fb9ca017.png)

Expected results:
Hidden Icon should not display when comment is reported

**Comment by watchtower314** [comment]
@yanivi71  This was fixed and merged yesterday already 
![image](https://user-images.githubusercontent.com/30501647/113304355-f1f23500-92cf-11eb-940f-f28c83943351.png)

**Comment by yanivi71** [comment]
verified on production
