### ISSUE TITLE
Updates in discussion flow

### ISSUE THREAD

**Issue by BigRomanov** [daostack/common-backend#31]
https://daostack1.atlassian.net/browse/CM-1384

There are these screens here:

https://app.zeplin.io/project/5ef45122508c89515c9d17d8/dashboard?seid=5ef45b993deb4ca05e0bc09e

Tai (and Brio) have the details on what there is to be done exactly.

**Comment by BigRomanov** [comment]
We need to discuss with Product what to do with this animation

**Comment by gingervik** [comment]
irrelevant
