### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#319]
Fixed the crashes that was in crashlytics

The crash happened for new joined users, when a new user was added and her data was not in the store yet

**Comment by yanivi71** [comment]
@watchtower314 
Tested on Staging iOS version 1.9.5 (4978-267)
Tested on Staging Android version 1.9.5 (4978-228)

Steps to reproduce:
1. Create new google user
2. login the app with the new user

Actual results:
after the login process user gets error message . and when clicking on OK the app closes/crash.
when opening the app user is login
![Screenshot_20210411-170712_common-stg](https://user-images.githubusercontent.com/69141571/114307631-327c5a80-9ae9-11eb-9362-05ab5814ec30.jpg)

Expected results:
user should logged in

**Comment by watchtower314** [comment]
Demo:

https://user-images.githubusercontent.com/30501647/114379189-7d808700-9b56-11eb-860b-e1d233d64c43.mov


Tested with a new user

**Comment by yanivi71** [comment]
Tested on Staging Android version 1.9.6 (6433-237)

Found OK
no error message after creation of a new user on android device

**Comment by yanivi71** [comment]
Verified on production
