### ISSUE TITLE
Version update - Pop up appears on the screen after the version is updated

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#325]
Tested on Staging iOS version 1.9.5 (4978-262)
Tested on Staging Android version 1.9.5 (4978-223)

Steps to reproduce:
1. wait for version update
2. open the staging app

Actual results:
pop up appear - see attached image

Expected results:
no pop up should appear after version is updated
![File (63)](https://user-images.githubusercontent.com/69141571/113820967-1d6b9880-9784-11eb-9ed4-be513dd26c76.jpg)

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-264)
Tested on Staging Android version 1.9.5 (4978-225)

There are no pop-ups when opening the app.

**Comment by yanivi71** [comment]
Verified on production
