### ISSUE TITLE
Add explanation about the reason for Rejected Payments.

### ISSUE THREAD

**Issue by lpetkov-sw** [daostack/common-backend#341]
This is the updated screen for showing information to the users about rejected payments.
https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/601035fbfb74240f58ac272c

When there is any reason for failed payment we need to show proper error
- list of all possible 
![image](https://user-images.githubusercontent.com/28015224/114830866-5f748a00-9dd5-11eb-88fa-32eb9661b753.png)

-- | card_cvv_invalid | Incorrect CVV value provided
-- | -- | --
-- | card_expired | Card expired
- new [design](https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/601035fbfb74240f58ac272c)

**Comment by gingervik** [comment]
need to discuss details with @Taikaish

**Comment by gingervik** [comment]
should be a part of Payment Batch 1

**Comment by ariel-dao** [comment]
@HannaMaklakova what is this? any background? is Shai aware of this?
