### ISSUE TITLE
The app crashes when user clicks on "Leave without saving" button

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#342]
Tested on Staging iOS version 1.9.5 (4978-263)
Tested on Staging Android version 1.9.5 (4978-224)

The app crashes every time the user clicks on the "Leave without saving" button.

**1. Steps to reproduce:**

1. Create a new  Common
2. Within general info Click on "X" 
3. Click on "Leave without saving"

**2. Steps to reproduce:**

1. Go to a user's profile
2. Click on the edit profile button
3. Make some changes
4. Click on cancel and then click on "Leave without saving"

**3. Steps to reproduce:**

1. Go to a common 
2. Click on three dots and then click on Edit info and cover photo/Edit rules button
3. Make some changes
4. Click on the cancel button and then click on "Leave without saving"

Actual results:
App crashes - see attached video

Expected results:
User Should be redirected to Common List

https://user-images.githubusercontent.com/69141571/113994342-f8e3ef00-985d-11eb-8264-0d5686aa47c9.mp4

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-264)
Tested on Staging Android version 1.9.5 (4978-225)

The app does not crash when clicking on the "Leave without saving" button. 
Found ok!

**Comment by kazaryan-t** [comment]
Verified on Production.
