### ISSUE TITLE
Create common - review UI changes

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#344]
https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/606dcdedeb3272503f67c5ee

**Comment by watchtower314** [comment]
pr: https://github.com/daostack/common/pull/1043
iOS:
<img width="351" alt="Screen Shot 2021-04-11 at 5 15 28" src="https://user-images.githubusercontent.com/30501647/114298888-899d1380-9a86-11eb-92a3-530eb7cbcaa2.png">

android:
<img width="359" alt="Screen Shot 2021-04-11 at 5 15 02" src="https://user-images.githubusercontent.com/30501647/114298895-902b8b00-9a86-11eb-97cd-7d18d46732ed.png">

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.6 (6433-270)
Tested on Staging Android version 1.9.6 (6433-231)

1. When the moderator of the common set the minimum contribution without letting other users join without a personal contribution, the Minimum contribution field does not appear on the Final touches and review screen. 
See attached screenshot from zeplin (the contribution type should be put in bold **one-time** or **monthly**)
2. There is no link icon on the Final touches and review screen next to the link title.
3. Please, cover with the color the full line from the 1st to 2nd steps, from 2nd to 3rd, and from 3rd to 4th steps as in the design.
(pay attention to the attached video, when the user goes to the next step, not the whole line at the top of the page is covered with the color)

Actual:

https://user-images.githubusercontent.com/68247034/115031380-c1fe8080-9ed0-11eb-95c0-a375433aeaaa.mp4

Expected:
![04 04 4 create common - common without tagline - C](https://user-images.githubusercontent.com/68247034/115031632-10ac1a80-9ed1-11eb-9277-429056375925.png)

![04 02 1 create common_ funding - One-time contribu](https://user-images.githubusercontent.com/68247034/115032705-469dce80-9ed2-11eb-93a7-240c83e74574.png)
![04 03 1 create common_ Rules - Common MVP 1 1 - Ze](https://user-images.githubusercontent.com/68247034/115032707-47366500-9ed2-11eb-8406-a26d8ab12d91.png)
![04 04 1 create common_ stylize and review common -](https://user-images.githubusercontent.com/68247034/115032708-47cefb80-9ed2-11eb-8cc5-980499fd42c9.png)

**Comment by watchtower314** [comment]
@kazaryan I did not fix the things you mentioned because this is the design I followed:

https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/606dcdedeb3272503f67c5ee

This design is about adding the bottom message only:
<img width="373" alt="Screen Shot 2021-04-18 at 5 28 02" src="https://user-images.githubusercontent.com/30501647/115140752-db094d80-a006-11eb-813f-780f2faa94be.png">

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.6 (6433-270)
Tested on Staging Android version 1.9.6 (6433-231)

Found ok. The message was added at the bottom of the Final touches and review screen.

There is a new ticket for all the UI changes I mentioned above in the comment - #385.

**Comment by kazaryan-t** [comment]
Verified on production.
