### ISSUE TITLE
User Profile - Edit - wrong error message appears when user enter non latin characters

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#345]
Tested on Staging iOS version 1.9.5 (4978-264)
Tested on Staging Android version 1.9.5 (4978-225)

Steps to reproduce:
1. Go to user profile
2. Click on Edit Icon
3. edit field and insert non latin characters (e.g. hebrew)
4. Click on cancel 

Actual results:
No Respond. user stay in the same screen. also there is wrong error message that the user name must be in latin only

Expected results:
user is able to use non latin language in his profile
![Screenshot_2021-04-08-15-04-17-137_com daostack common staging](https://user-images.githubusercontent.com/69141571/114024325-95b58500-987c-11eb-9e1a-b48757842293.jpg)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-266)
Tested on Staging Android version 1.9.5 (4978-227)

Found OK
user is able to use non latin language in his profile

**Comment by kazaryan-t** [comment]
Verified on production.
