### ISSUE TITLE
Create Common - Funding - Monthly contribution - user cannot create monthly contribution

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#349]
Tested on Staging iOS version 1.9.5 (4978-266)
Tested on Staging Android version 1.9.5 (4978-227)

Steps to reproduce:
1. Create a new common
2. Navigate to Funding 
3. Choose Monthly contribution
4. add integer amount (e.g. 10$)

Actual results:
user gets error message that The amount is incorrect. user cannot continue to rules. the button "Continue to Rules" is disable
see attached image
![Screenshot_20210411-134923_common-stg](https://user-images.githubusercontent.com/69141571/114301419-72354900-9acd-11eb-921c-2a18ff81f998.jpg)

Expected results:
User is able to proceed to Rules once the amount is legal. No error message should appears

**Comment by watchtower314** [comment]
This was fixed with #155
