### ISSUE TITLE
Change email text for Israelis

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#351]
Text of funding-proposal-approved should be:

<img width="475" alt="Screen Shot 2021-04-11 at 10 17 41" src="https://user-images.githubusercontent.com/30501647/114307816-3ee3c180-9aaf-11eb-8d9d-7d2d2d59e5a6.png">

**Comment by watchtower314** [comment]
<img width="874" alt="Screen Shot 2021-04-11 at 10 23 43" src="https://user-images.githubusercontent.com/30501647/114307952-0ee8ee00-9ab0-11eb-8fee-3192e5f3cc3f.png">

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-268)
Tested on Staging Android version 1.9.5 (4978-229)

Found Ok
email template is changed. all additional changes are OK

**Comment by yanivi71** [comment]
Verified on production
