### ISSUE TITLE
Crashlytics issues

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#353]
<img width="1107" alt="Screen Shot 2021-04-11 at 9 59 47" src="https://user-images.githubusercontent.com/30501647/114307212-aba98c80-9aac-11eb-9809-2ef72666b52f.png">
<img width="838" alt="Screen Shot 2021-04-11 at 10 00 15" src="https://user-images.githubusercontent.com/30501647/114307227-bbc16c00-9aac-11eb-96f7-7d65b0ae58f0.png">

**Comment by yanivi71** [comment]
@watchtower314 Can I check this?
is there any issue i can verify?

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.7 (6591-280)
Tested on Staging Android version 1.9.7 (6591-241)

crashlytics issues. fixed by @watchtower314 . nothing to check
