### ISSUE TITLE
Moderation batch 2: allow moderators to hide content

### ISSUE THREAD

**Issue by BigRomanov** [daostack/common-backend#36]
https://daostack1.atlassian.net/browse/CM-1515

This issue is still to be specced and is just a placeholder for now. 

This is about allowing moderators to hide proposals, posts and comments. The designs also contain functionality for users to report content, which is the topic ofCM-1516: Implement report buttonTO DO 

The notion board is the main reference: https://www.notion.so/daostack/Moderation-Batch-2-d07815f36f0544878e01490e0aaf8b29

 The  Data model. for Proposals, Posts and messages: we add a new field moderation to the data model that looks like this:

```
IUser { 
  ...
  moderation?: {
    flag: "hidden" // can have other values later
    reasons: IReasons[] // like ["Nudity"]
    note?: string
  }
  ...
}
```

we will want to send an email to adminMail with the fact that this happened (this will also make it that we keep some kind of history)

“unhiding” will work by simply removing the moderation field

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

this task is verified
problems related to this task are reported in different issues

**Comment by yanivi71** [comment]
Verified on Production
