### ISSUE TITLE
Create Common - Funding - The check box does not saved when user navigates back to general info

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#364]
Tested on Staging iOS version 1.9.5 (4978-267)
Tested on Staging Android version 1.9.5 (4978-228)

Steps to reproduce:
1. Create a new common
2. navigare to fungung
3. Check "Let user join common without a personal contribution
4. Go back to general info
5. Click on  continue to funding

Actual results:
The checkbox is unchecked - see attached video

Expected results:
Checkbox must be checked

https://user-images.githubusercontent.com/69141571/114515714-5359c280-9c45-11eb-9370-34086d6d4836.mp4

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.6 (4978-271)
Tested on Staging Android version 1.9.6 (4978-232)

Found OK
Checkbox state does not change

**Comment by kazaryan-t** [comment]
Verified on production.
