### ISSUE TITLE
User profile - Empty Intro field

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#365]
Need to discuss this issue with @Taikaish.

1. In case when the Intro field is empty, should the app display the Intro field?

2. And if this field is required to be displayed on the screen, maybe we can reduce it and make it tighter?

![Screenshot_20210412-103753_common-stg](https://user-images.githubusercontent.com/68247034/114523131-b13dd880-9c4c-11eb-9b1c-0cdd27ffe06e.jpg)

**Comment by Taikaish** [comment]
Thanks @kazaryan-t !

I think the current way is fine for now since we want to encourage users to add an intro.
It's not ideal, but good enough for now. We will probably improve this in the upcoming future.
