### ISSUE TITLE
Membership request - Personal contribution screen

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#369]
Tested on Staging iOS version 1.9.5 (4978-268)
Tested on Staging Android version 1.9.5 (4978-229)

1. If the user who joins the common clicks on Others then enters an amount which is greater than $0 and smaller than $5, we should show the following error: "The minimum contribution allowed by credit card is $5” (screenshot attached) 

2. Delete the (min. $5) for commons where the user can join without personal contribution.

![Screenshot_20210413-175053_common-stg](https://user-images.githubusercontent.com/68247034/114581110-1d89fd80-9c88-11eb-8814-fe0011193d74.jpg)

**Comment by watchtower314** [comment]
@Taikaish same question here -> do we want to remove the limit of the amount of the personal contribution? meaning, the user can enter $5 or more, without limiting it at all?

**Comment by watchtower314** [comment]
What to test:

For commons that allow 0 contribution,
- I removed the `(min. $5)` from the title
<img width="284" alt="Screen Shot 2021-04-18 at 4 51 07" src="https://user-images.githubusercontent.com/30501647/115139751-b1015c80-a001-11eb-9a31-3a7909082768.png">

<img width="310" alt="Screen Shot 2021-04-18 at 4 50 29" src="https://user-images.githubusercontent.com/30501647/115139744-9b8c3280-a001-11eb-8eb8-9420c7dcd452.png">

- for monthly commons, don't allow 0 contribution 
<img width="371" alt="Screen Shot 2021-04-18 at 5 20 56" src="https://user-images.githubusercontent.com/30501647/115140544-ddb77300-a005-11eb-8e4d-4b45706d421f.png">

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.6 (6433-271)
Tested on Staging Android version 1.9.6 (6433-232)

Found ok.
The max contribution for joining the common is 2500$ (one-time and monthly contributions).

**Comment by kazaryan-t** [comment]
Verified on production
