### ISSUE TITLE
Create computed field for minFeeToJoin in the Common model and apply it in all places across the project.

### ISSUE THREAD

**Issue by lpetkov-sw** [daostack/common-backend#373]
That ticket was created based on the comments inside the following PR: https://github.com/daostack/common/pull/1050#pullrequestreview-636754888

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.6 (4978-274)
Tested on Staging Android version 1.9.6 (4978-235)

This issue is  technical improvements and we cannot verify it
