### ISSUE TITLE
Agenda and Rules screen - Add the Rules field even if the common does not have rules

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#381]
Tested on Staging iOS version 1.9.6 (6433-270)
Tested on Staging Android version 1.9.6 (6433-231)

Please add the **Rules of conduct** field on the Agenda and Rules screen with the possibility to edit rules for a moderator.

Steps to reproduce:
1. Create a common without rules
2. Go to the Common page
3. Click on View agenda

Actual result:
There is no field **Rules of conduct**

Expected result:
The Rules field appears even if the common does not have rules and the moderator is able to add or edit rules. 
Design - https://zpl.io/b6nD3OP

![Screenshot_20210416-142335_common-stg](https://user-images.githubusercontent.com/68247034/115017760-adfe5300-9ebf-11eb-990c-d36557f4460f.jpg)

![10 06 5 no agenda and rules -moderetor view - Comm](https://user-images.githubusercontent.com/68247034/115017923-e7cf5980-9ebf-11eb-87e7-4f4db26d2635.png)

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.6 (6433-274)
Tested on Staging Android version 1.9.6 (6433-235)

Found ok!
The rules of conduct field was added on the Agenda and Rules screen.

**Comment by yanivi71** [comment]
Verified on production
