### ISSUE TITLE
Final touches and review screen - UI changes

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#385]
Tested on Staging iOS version 1.9.6 (6433-270)
Tested on Staging Android version 1.9.6 (6433-231)

1. When the moderator of the common set the minimum contribution without letting other users join without a personal contribution, the Minimum contribution field does not appear on the Final touches and review screen.
See attached screenshot from zeplin (the contribution type should be put in bold one-time or monthly)

2. There is no link icon on the Final touches and review screen next to the link title.

3. Please, cover with the color the full line from the 1st to 2nd steps, from 2nd to 3rd, and from 3rd to 4th steps as in the design.
(pay attention to the attached video, when the user goes to the next step, not the whole line at the top of the page is covered with the color).

Actual:

https://user-images.githubusercontent.com/68247034/115191425-13d22100-a0f2-11eb-91ce-24da25383917.mp4

Expected:

![04 04 4 create common - common without tagline - C](https://user-images.githubusercontent.com/68247034/115191478-25b3c400-a0f2-11eb-99e6-075b250d318d.png)

![04 02 1 create common_ funding - One-time contribu](https://user-images.githubusercontent.com/68247034/115191531-39f7c100-a0f2-11eb-8c21-c99d12ff76e5.png)
![04 03 1 create common_ Rules - Common MVP 1 1 - Ze](https://user-images.githubusercontent.com/68247034/115191535-3b28ee00-a0f2-11eb-8760-a89305d24896.png)
![04 04 1 create common_ stylize and review common -](https://user-images.githubusercontent.com/68247034/115191537-3b28ee00-a0f2-11eb-872d-4d619ff4c13d.png)

**Comment by watchtower314** [comment]
@kazaryan-t 
What to test:

- step header line -> here's a screenshot from 2 iPhones and one android
<img width="1150" alt="Screen Shot 2021-04-19 at 7 11 42" src="https://user-images.githubusercontent.com/30501647/115234844-7e319400-a0e7-11eb-94d6-d0b5e3702c5d.png">

- Links icon: 

<img width="400" alt="Screen Shot 2021-04-19 at 8 19 21" src="https://user-images.githubusercontent.com/30501647/115235222-f39d6480-a0e7-11eb-97d5-71e3fd5978cf.png">


- `Minimum contribution` for when we allow users to join without contribution 
<img width="403" alt="Screen Shot 2021-04-19 at 8 11 48" src="https://user-images.githubusercontent.com/30501647/115234943-986b7200-a0e7-11eb-9978-f1116abcddd6.png">

- `Minimum contribution` for when users cannot join without contribution:
<img width="366" alt="Screen Shot 2021-04-19 at 8 14 13" src="https://user-images.githubusercontent.com/30501647/115235036-b638d700-a0e7-11eb-8359-f0cd30ab96ae.png">

- on the last step of creation, the bottom button should not be sticky, and only be visible when we scroll down

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.6 (6433-273)
Tested on Staging Android version 1.9.6 (6433-234)

Found OK.
All changes were fixed and implemented.

**Comment by kazaryan-t** [comment]
Verified on production
