### ISSUE TITLE
Push notification - comments - When entering through the push notifications comments mixed-up and not chronological

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#386]
Tested on Staging iOS version 1.9.6 (4978-270)
Tested on Staging Android version 1.9.6 (4978-231)
reported by Arava - the scenario was reproduced on android device

Steps to reproduce:

1. Get a notification for new comment in discussion
2. Click on the notification

Actual results:
When entering through the push notifications comments are mixed-up and not chronological. Also it wont let user scroll up
see attached image

Expected results:
Comments must be chronological, user is able to scroll

![Screenshot_20210418-182134_common](https://user-images.githubusercontent.com/69141571/115192684-cf478500-a0f3-11eb-8ad7-4e25f7440a1f.jpg)

**Comment by watchtower314** [comment]
Screenshot is taken from commonId: a0c5e8fb-b98b-431f-9aed-43e7eef5fc34
The chat is from the proposal with id: 1722a81c-36a1-4bf9-9fb1-74465443f76b (this proposal is in History tab)

Seems ok here:

https://user-images.githubusercontent.com/30501647/117278021-101bf980-ae69-11eb-8e9d-2c5e86bbd991.mov

**Comment by BigRomanov** [comment]
Could not reproduce. We will get it next time

**Comment by yanivi71** [comment]
Could not reproduce. We will get it next time
