### ISSUE TITLE
Notification - The counter of notifications does not changes when user enter through notification screen

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#387]
Tested on Staging iOS version 1.9.6 (4978-271)
Tested on Staging Android version 1.9.6 (4978-232)
Reported by Arava

Steps to reproduce:
1. Get Several Push notification - Results - the number of the notifications appears on the app icon - see attached image
2. Go to notification screen 
3. click on any notification

Actual results:
the counter of notifications (on top of the app icon on the home screen) does not reset when she enters the notification screen.
The only way to get the numbers down is by entering through the push notifications.

Expected results:
Counter should be change in both methods 
![Screenshot_20210419-153124_One UI Home](https://user-images.githubusercontent.com/69141571/115241591-ab9f3180-a129-11eb-81bf-c67425fbf0c3.jpg)

**Comment by watchtower314** [comment]
@BigRomanov  @Taikaish @gingervik @yanivi71 @kazaryan-t @lpetkov-sw

The icon badge is a reflection of the notification in the **Notification Center**, not the notification screen:
When we open the app from the icon and navigate to notification screen, we can see all the notifications, BUT, the notifications still exist in the Notification Center, this is why the counter doesn't change.

Given this scenario:
1. You get 5 notifications from common, all in the Notification Center.
2. You open the app NOT from clicking notifications in Notification Center
3. You checkout the notification from notification screen
4. You close the app (you can leave it open) and open Notification Center -> the notifications are still there

SO hypothetically, if we clear the count of the notification badge BUT there are still notifications in notification canter, it will confuse the user.

We could do something like what WhatsApp does -> when we open the app, clear all notifications, even from Notification Center 

This is how WhatsApp handles this:

https://user-images.githubusercontent.com/30501647/117010981-0aea6d80-acf6-11eb-949f-35bcf7e11fca.MP4



Thoughts?

**Comment by Taikaish** [comment]
Technically, can we align it to the notification screen instead of the notification center?
Meaning that once I enter the notification screen the counter resets to zero, even if the user still has open notifications on the notification center?

**Comment by watchtower314** [comment]
So I'm pretty sure we can only do it if we also clear the notification in the Notification Center, I'll look into it

**Comment by watchtower314** [comment]
pr: https://github.com/daostack/common/pull/1088

FOR THE TESTER:
What to test:
- App icon notification badge is cleared when we open notification screen

How to test:
1. Receive a notification
2. open the app from the icon, and NOT by pressing the notification in the Notification Center
3. navigate to Notification Screen
- result:
1. The notification icon on top of the phone should disappear 
2. The notification icon badge should disappear from the app icon

See demo:

android
https://user-images.githubusercontent.com/30501647/119265721-5a82d180-bbf0-11eb-8e89-583af12d1c36.mov

iOS:

https://user-images.githubusercontent.com/30501647/119266082-04169280-bbf2-11eb-986b-95a0a0b75947.MP4
