### ISSUE TITLE
Create Common - Funding - Continue to Rules button is enable before the user enter contribution amount

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#388]
Tested on Staging iOS version 1.9.6 (4978-272)
Tested on Staging Android version 1.9.6 (4978-233)

Steps to reproduce:
1. Create a new common
2. Navigate to funding
3. leave contribution field empty

Actual results:
Continue to Rules button is active before the user enter contribution value
see attached image
![Screenshot_2021-04-20-09-27-15-998_com daostack common staging](https://user-images.githubusercontent.com/69141571/115348352-3419e280-a1bb-11eb-9108-423cf8c9dc42.jpg)

Expected results:
Continue to Rules button should be disable . once user enter contribution amount it should be enable

same is happening with first step:
Steps to reproduce:
1. create new common
2. leave common name empty

Expected result:
continue button should not be enabled

Actual result:
continue button is enabled

<img width="335" alt="Screen Shot 2021-04-25 at 6 58 50" src="https://user-images.githubusercontent.com/30501647/115992735-3904da80-a59d-11eb-9d7d-927a84e7592a.png">

**Comment by watchtower314** [comment]
The behavior  of the buttons is correct -> they will become disabled when the user enters the wrong input
