### ISSUE TITLE
Email Template - Create new common - payment type appears as "one time" instead of "monthly"

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#394]
Tested on Staging iOS version 1.9.6 (4978-274)
Tested on Staging Android version 1.9.6 (4978-235)

Steps to reproduce:
1. Create a new common
2. in funding screen choose monthly

Actual results:
user gets email "New Common pending approval"
but payment type aars as "one time" instead of "monthly"

Expected results:
payment type should contain the correct common type

**Comment by watchtower314** [comment]
@yanivi71 The email of a new common created does not mention the contribution type at all
![IMG_1B84E7CDABA3-1](https://user-images.githubusercontent.com/30501647/115526232-d25e8480-a25d-11eb-8672-5b0f652b704d.jpeg)


Can you send a screenshot of the email you received, please?

**Comment by yanivi71** [comment]
@watchtower314 
![image](https://user-images.githubusercontent.com/69141571/115527105-6c8fee00-a299-11eb-80f6-6a831122c7d9.png)

**Comment by watchtower314** [comment]
Ok, this is an Admin email :)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.6 (6433-276)
Tested on Staging Android version 1.9.6 (6433-237)

Found OK
payment type contain the correct common type
