### ISSUE TITLE
Email Template - Funding proposal approved for israelis - The hebrew language display from LTR 

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#395]
Tested on Staging iOS version 1.9.6 (4978-274)
Tested on Staging Android version 1.9.6 (4978-235)

Steps to reproduce:
1. approved proposal for israelis users
2. Get mail for approval
3. open mail and view it 

Actual results:
The hebrew language display from LTR . also when user name is in english the test order is changes - see attached image

Expected results:
email text should be display from RTL
![image](https://user-images.githubusercontent.com/69141571/115528161-75cd8a80-a29a-11eb-9086-a04cb56759a5.png)

**Comment by watchtower314** [comment]
@yanivi71 
I can't reproduce this 🤷🏽‍♀️
Browser:
<img width="1440" alt="Screen Shot 2021-04-21 at 5 37 20" src="https://user-images.githubusercontent.com/30501647/115532362-b6f67800-a263-11eb-9d49-714c2ace3a23.png">

mobile phone:
![IMG_320B240C4F50-1](https://user-images.githubusercontent.com/30501647/115532449-c83f8480-a263-11eb-84f9-316c889a0ca6.jpeg)


Do you have more info?

**Comment by yanivi71** [comment]
@watchtower314 it is strange. I tested it on my machine and it is still from LTR. i m using chrome browser on my pc (not mac).
in my devices it appears ok. mb i need to change browser settings? do u know?

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.7 (6591)
Tested on Staging Android version 1.9.7 (6591-240)

Cannot reproduces
moving to verify, we be follow another check

**Comment by yanivi71** [comment]
Tested on production
Cannot reproduces
moving to verify, we be follow another check
