### ISSUE TITLE
Edit rules - Remove the error when user deletes the text of rules

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#397]
When editing rules, the user deletes the title and text of the rule, it shows this error that rules are required. 

Steps to reproduce:
1. Create common with rules
2. Go to the common page and click on View agenda or Edit rules
3. Delete the text in Rule title field and Rule description field.

Actual result:
There are errors "Rule title is required" and "Rule description is required".

Expected:
There are no errors because a user can leave the common without rules. 
And the Save button is active. 

![Screenshot_20210421-140831_common-stg](https://user-images.githubusercontent.com/68247034/115544380-2f345c00-a2ab-11eb-8718-002d3f35c8cd.jpg)

**Comment by MeyerPV** [comment]
Assigned to me
