### ISSUE TITLE
User profile - privacy policy and the terms and conditions on Android is not working as expected.

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#399]
Tested on Staging Android version 1.9.6 (6433-237)

Steps to reproduce:
1. Go To user profile
2. Click on  privacy policy 
3. click on terms and conditions

Actual results:
users are force to download these documents

Expected results:
documents should be opening in the app browser.

**Comment by kazaryan-t** [comment]
Tested on Android - 1.9.7 (6591-241)
Clicking on Terms of use and Privacy Policy links the app shows an error.

https://user-images.githubusercontent.com/68247034/118617613-77bc3800-b7cb-11eb-8ca9-3a8f005efca5.mp4
