### ISSUE TITLE
PropType console errors

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#400]
wrong propTypes, missing keys, etc.
<img width="613" alt="Screen Shot 2021-04-21 at 9 34 52" src="https://user-images.githubusercontent.com/30501647/115562777-d520a000-a284-11eb-901d-d2487e39aa3d.png">

possibly related to:
https://github.com/daostack/common-monorepo/issues/353

**Comment by yanivi71** [comment]
@watchtower314 What do i check here?

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.7 (6591-280)
Tested on Staging Android version 1.9.7 (6591-241)

Debugging issues. fixed by @watchtower314 . nothing to check
