### ISSUE TITLE
Edit common - moderators cannot edit common

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#403]
Steps to reproduce:

1. As a moderator, go to Edit Common
2. Edit some field

Expected result: 
The common is edited in the database

Actual result:
The common is only updated in the store, but the database is not updated because the user is not the founder of the common

<img width="1168" alt="Screen Shot 2021-04-22 at 4 58 54" src="https://user-images.githubusercontent.com/30501647/115686821-98f24b80-a327-11eb-86fa-bb144bd83f3c.png">

**Comment by watchtower314** [comment]
frontend pr: https://github.com/daostack/common/pull/1070
backend pr: https://github.com/daostack/common-monorepo/pull/404  (well, I guess PR not found 🤣)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.7 (6591)
Tested on Staging Android version 1.9.7 (6591-240)
Found OK
moderator can edit common.

**Comment by yanivi71** [comment]
tested on production
Found OK
moderator can edit common.
