### ISSUE TITLE
Request to join - user can enter amount < 5 when 0 contribution is allowed 

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#405]
Steps to reproduce:

1. Find a common that allows 0 contribution
2. Start a request to join
3. In contribution step, choose custom amount

Expected result:
user cannot write an amount less than $5

Actual result:
User can write an amount less than $5

<img width="309" alt="Screen Shot 2021-04-22 at 11 11 17" src="https://user-images.githubusercontent.com/30501647/115739961-6151c680-a35c-11eb-9c9b-c93818a6cff0.png">

**Comment by watchtower314** [comment]
Demo:

https://user-images.githubusercontent.com/30501647/115758426-1be9c500-a36d-11eb-92ea-b961e7de4d5d.mov

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.7 (6591)
Tested on Staging Android version 1.9.7 (6591-240)

Found ok
When user insert value between 0 and 5 , there is error message and user cannot proceed

**Comment by yanivi71** [comment]
Tested on production

Found ok
When user insert value between 0 and 5 , there is error message and user cannot proceed
