### ISSUE TITLE
Discussion - Ui issues

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#406]
Tested on 
http://35.208.173.116/

1. Common Logo - The logo image is incorrect
![image](https://user-images.githubusercontent.com/69141571/115987763-0e2b7e00-a5bf-11eb-8cf5-6a6b63f1cce7.png)
Should display different logo (black and white image) - see zeplin design

2. Share icon is missing
![image](https://user-images.githubusercontent.com/69141571/115987828-65c9e980-a5bf-11eb-8431-13d1a278cb04.png)

3. Discussion title display always in blue color - it should be black and turn to blue when mouseover
![image](https://user-images.githubusercontent.com/69141571/115987886-b3465680-a5bf-11eb-9a1a-b12b1f95a161.png)

4. Discussions - latest proposals - The are no results for each proposal
![image](https://user-images.githubusercontent.com/69141571/115988570-0d94e680-a5c3-11eb-91db-c1493964f95d.png)

5. Discussions - latest proposals - Click on "View all" does not function 
6. Discussions - View discussion - incorrect font.
![image](https://user-images.githubusercontent.com/69141571/115988681-7c723f80-a5c3-11eb-9475-85fa04e7be9f.png)

7.  Discussions -" Read more" option is missing
![image](https://user-images.githubusercontent.com/69141571/115988733-be02ea80-a5c3-11eb-8680-a0a7141d96e3.png)

8.  Discussions - View discussion - Date and time display incorrect - see zeplin design
![image](https://user-images.githubusercontent.com/69141571/115988801-fa364b00-a5c3-11eb-9093-ffd28d8f0a17.png)

9. Discussions - Empty state - Display "Join Efforts" instead of "Join the efforts"
![image](https://user-images.githubusercontent.com/69141571/115989225-120ece80-a5c6-11eb-986a-788494780ebf.png)

10. Discussions - latest proposals - empty state - image is missing - See zeplin design
![image](https://user-images.githubusercontent.com/69141571/115989322-77fb5600-a5c6-11eb-9919-1af39344bdb6.png)

**Comment by kazaryan-t** [comment]
Tested on http://35.208.173.116

1. Clicking on **"Read More", "View discussion", "View all"** buttons leads to the white screen.
![Common - Google Chrome 2021-05-17 12 28 16l](https://user-images.githubusercontent.com/68247034/118466392-7d524900-b70b-11eb-93f6-53c29709b6e3.png)

2. Add the countdown and actual results for active proposals in the Latest Proposals tab in Agenda and Discussions screens
![01 02 01 Common page - Agenda - Common Web - Zepli](https://user-images.githubusercontent.com/68247034/118468068-0ddd5900-b70d-11eb-9215-008145c910af.png)

**Comment by roienatan** [comment]
1 is resolved. 
2 is opened in separated issue https://github.com/daostack/common-monorepo/issues/493

**Comment by yanivi71** [comment]
Tested on http://35.208.173.116

Found OK
2 is opened in separated issue #493
