### ISSUE TITLE
New flow for failed payment

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#407]
Once the payment fails 
1. we should email the user <NEW EMAIL TEXT>
and they will have **14 days** to fix this or get out of the common
2. users will now have 14 days to update their details and complete the payment before we take any action. 
    a) If the first payment to a Common fails, the user will not become a member and change to the status of "payment failed". 
    b) If it's a recurring payment (after already becoming a member) - the user will remain a member for those 14 days. If they still don't update their details, we will cancel their membership and their status will change to "payment failed".

**Comment by HannaMaklakova** [comment]
not relevant
