### ISSUE TITLE
Update details screen

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#409]
When the users click on the "update details" button they will go to a shortened version of the flow when joining a common.

In this flow, the name of the Common will not appear on top of the screen (since the update isn't specific to any Common. The title "Membership request" will change to "update payment method". The "slider" will be reduced to these two steps only:

1. Billing details
https://zpl.io/aR6N4Lr
Unlike the current screen, we will not display the contribution amount to the common.
Instead, we will show the following text: "Please make sure the following details are correct".
The fields on that screen will already be filled with details the user entered when they made the last payment. The button on that screen will say "Continue to payment details".
<img width="250" src="https://user-images.githubusercontent.com/87295860/126178402-77df1eef-36f3-403e-bc9a-7b14d469ccf5.png">

2. Payment details
https://zpl.io/2G8OKPW
In this screen, we will not auto-fill the details, and let the user enter the details again.
Instead of the text "you are contributing $25 to this common" we should display the text: "Update your payment details below".
We should also remove the text below Circle's logo ("If your membership...").
The button should say: "Update details".
<img width="250" src="https://user-images.githubusercontent.com/87295860/126180135-e3ed707c-3454-4339-986b-ef71af83b7d2.png">

3. Success/Failure
Since this flow relates only to failed payments, we will try to charge the card immediately.
If the payment fails, we should display an error message ("Payment Failed. Please make sure you enter the correct details and try again" with a button - "Update details"). https://zpl.io/a7jZPEq
<img width="250" src="https://user-images.githubusercontent.com/87295860/126183637-d5521a67-3ae4-4978-8ab6-c8a9b5655aaa.png">

If the payment works, we should display a confirmation message -
For first payments to a common - "Payment details updated. Thank you! We collected your contribution and you are now a member." https://zpl.io/V4gANly
<img width="250" src="https://user-images.githubusercontent.com/87295860/126183962-f2050251-3213-4179-92a4-f4922d476d0d.png">

For recurring payments (excluding 1st payment) - "Payment details updated. Thank you! We collected your contribution and will you remain a member." https://zpl.io/aN64xok
<img width="250" src="https://user-images.githubusercontent.com/87295860/126184106-08fd75b7-6dba-4c52-9d28-2681b35b8599.png">

For both confirmation messages, the button will say "Continue".
If possible, it will lead to the last screen the user visited before entering this flow. If this is too time-consuming, we can send them back to the main screen.

**Comment by HannaMaklakova** [comment]
not relevant
