### ISSUE TITLE
Web - Explore commons

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#410]
Tested on
http://35.208.173.116/

1. Explore commons text shouldn't be put in bold - https://zpl.io/Vx4Wjkk
 
![React App - Google Chrome 2021-04-26 10 10 29](https://user-images.githubusercontent.com/68247034/116043222-0ed41b00-a678-11eb-9e79-6988b7ea8691.png)

2. At the foot of the page some information is missed.

![01 01 02 Explore commons - Common Web - Zeplin - GSED](https://user-images.githubusercontent.com/68247034/116043625-9457cb00-a678-11eb-92f4-03898f3742ec.png)
![React App - Google Chrome 2021-04-26 10 17 06](https://user-images.githubusercontent.com/68247034/116043630-94f06180-a678-11eb-8afe-ac80978c76e0.png)

3. Instead of "Load More" implement the button "Load more Commons" - https://zpl.io/bP6Qgzy

![Безымянный - Paint 2021-04-26 10 20 37](https://user-images.githubusercontent.com/68247034/116044076-27910080-a679-11eb-8d04-bc1e8909b689.png)
![01 01 03 Explore Commons - loading more commons beJ](https://user-images.githubusercontent.com/68247034/116044488-a5550c00-a679-11eb-9b87-e67a08226623.png)

4. During loading more commons, put the loading logo - https://zpl.io/bP6Qgzy

![01 01 03 Explore Commons - loading more commons be](https://user-images.githubusercontent.com/68247034/116044557-bd2c9000-a679-11eb-977d-c0af90c87fcd.png)

**Comment by kazaryan-t** [comment]
1. At the foot of the page:
- add the link for **Careers**, 
- delete _Explore commons_ 
- delete words **app**.

![Common - Google Chrome 2021-04-29 14 45 45](https://user-images.githubusercontent.com/68247034/116546000-c9bf1b80-a8f9-11eb-86a5-b6363aed8c78.png)
![01 01 02 Explore commons - Common Web - Zeplin - GSED](https://user-images.githubusercontent.com/68247034/116546139-e9eeda80-a8f9-11eb-870d-5d864b09d5ce.png)

2. The behavior of the **Load more Commons** button was discussed with @Taikaish:
_The website should automatically load more commons only two times and then display the button **Load more Commons**. 
When the button is displayed, we should not load more commons until the button is clicked.
When the button is clicked, it should disappear and the loading animation should replace it until we load the commons._

This is the desired flow:
1. user opens the Explore Commons page.
2. user scrolls to the bottom, we will automatically load more commons, the button should not appear.
3. user scrolls to the bottom again - we will automatically load more commons, the button should not appear.
4. user scrolls to the bottom again - we will show the button to load more commons, we will not automatically load more commons.

NB: actually the button appears at the same time as the loading animation, we should put in a lowercase word **more** in the button and change the loading animation according to the design.

![Безымянный](https://user-images.githubusercontent.com/68247034/116549424-2290b300-a8fe-11eb-93ff-40a5a82b009c.png)

![01 01 03 Explore Commons - loading more commons be](https://user-images.githubusercontent.com/68247034/116549553-4c49da00-a8fe-11eb-90ca-116313c27e6b.png)
![01 01 03 Explore Commons - loading more commons beDV](https://user-images.githubusercontent.com/68247034/116549555-4ce27080-a8fe-11eb-9f99-5ff34fa62674.png)

**Comment by kazaryan-t** [comment]
Tested on http://35.208.173.116/

Actually, the website automatically loads more commons only _one_ time, and then the button "Load more Commons" displays. 

The behavior of the Load more Commons button should be:
- The website should automatically load more commons **two** times and then display the button "Load more Commons".
- When the button is displayed, we should not load more commons until the button is clicked.
- When the button is clicked, it should disappear and the loading animation should replace it until we load the commons.

**Comment by roienatan** [comment]
2 - Discussed already the correct links. The current ones are correct.

**Comment by kazaryan-t** [comment]
Tested on http://35.208.173.116/

Actual:
1. the website automatically loads more commons only _one time_, and then the button "Load more Commons" displays.
2. when clicking on "Load more Commons" button and scrolling the commons, clicking on the button "Load more Commons" one more time to load more commons the website returns to the previous position (quite difficult to explain, better watch the screen recording)

https://user-images.githubusercontent.com/68247034/118953503-8c343800-b965-11eb-9e11-1b8c4fc0ab50.mp4

**The behavior of the Load more Commons button should be:**

- The website should automatically load more commons two times and then display the button "Load more Commons".
- When the button is displayed, we should not load more commons until the button is clicked.
- When the button is clicked, it should disappear and the loading animation should replace it until we load the commons.

**Comment by kazaryan-t** [comment]
Found OK.
The behavior for the _Explore Commons_ page is correct.
