### ISSUE TITLE
Common page - Agenda

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#412]
Tested on
http://35.208.173.116/

1. The page background should be light-grey - https://zpl.io/VO6MoEP

![01 02 01 Common page - Agenda - Common Web - Zeplicfd](https://user-images.githubusercontent.com/68247034/116046823-1b5a7280-a67c-11eb-9e88-f9d234086561.png)

2. About field - If there is more than one link they should be set in columnar form - https://zpl.io/VO6MoEP - http://35.208.173.116/commons/c188816a-7b2a-4a55-b1a0-54d0dd9d400a
![Common - Google Chrome 2021-04-26 10 39 48](https://user-images.githubusercontent.com/68247034/116047335-a50a4000-a67c-11eb-88dc-06766ba82400.png)

3. About field - the words **monthly** and **one-time** related to contribution should be in bold - https://zpl.io/VO6MoEP
http://35.208.173.116/commons/bbbbc81c-b27a-4da8-8096-5c39c2a2dcac
http://35.208.173.116/commons/c188816a-7b2a-4a55-b1a0-54d0dd9d400a

![Common - Google Chrome 2021-04-26 10 40 35](https://user-images.githubusercontent.com/68247034/116047598-e864ae80-a67c-11eb-9d9b-d2d8f8828cd8.png)
![Common - Google Chrome 2021-04-26 10 40 57](https://user-images.githubusercontent.com/68247034/116047601-e8fd4500-a67c-11eb-9625-128fdce01009.png)

4. In the **Latest proposals** tab empty fields appear - http://35.208.173.116/commons/644786f5-f057-4553-a961-51d8c0daf04f - http://35.208.173.116/commons/505ca135-36e4-4ea6-8978-0f6fb6a7f975 

![Common - Google Chrome 2021-04-26 10 51 44](https://user-images.githubusercontent.com/68247034/116048030-6aed6e00-a67d-11eb-9667-c3dbda6019bb.png)
![Common - Google Chrome 2021-04-26 10 52 23](https://user-images.githubusercontent.com/68247034/116048033-6b860480-a67d-11eb-8662-fffebaa929f9.png)

5. When a user points the mouse cursor on the link, the link should be highlighted in purple
![01 02 01 Common page - Agenda - Common Web - ZepliDSFRTD](https://user-images.githubusercontent.com/68247034/116048803-3d54f480-a67e-11eb-8aa5-ff0e022db089.png)

6. **View all** buttons - the word **all** should be in lowercase letters.
![01 02 01 Common page - Agenda - Common Web - Zeplidszx](https://user-images.githubusercontent.com/68247034/116050652-66768480-a680-11eb-90b0-76443a533159.png)

7. Put the _No discussions yet_ and _No proposals yet_ images if there is no discussions or proposals in the common - http://35.208.173.116/commons/1e7d3bcf-9933-44fe-8dfa-e6ec17d44c15

![01 02 02 Common page - Agenda - empty state - Comm](https://user-images.githubusercontent.com/68247034/116049835-70e44e80-a67f-11eb-85cc-16e014e5d102.png)

![01 03 05 Common page - Discussions - empty state -](https://user-images.githubusercontent.com/68247034/116050426-1eeff880-a680-11eb-93ba-335e9ebff6d5.png)

![Common - Google Chrome 2021-04-26 11 09 31](https://user-images.githubusercontent.com/68247034/116050219-e8b27900-a67f-11eb-8a96-097d19e8042f.png)

**Comment by kazaryan-t** [comment]
Please change the text for the _No discussions yet_ and _No proposals yet_ images if there are no discussions or proposals in the common (delete the word "latest" and put the words _proposals_ and _discussions_ in lowercase).

Actual:
![Common - Google Chrome 2021-04-29 16 22 55](https://user-images.githubusercontent.com/68247034/116558664-596bc680-a908-11eb-9c2a-bd2614d96a5f.png)

Expected:
![01 02 02 Common page - Agenda - empty state - Comm](https://user-images.githubusercontent.com/68247034/116558872-9041dc80-a908-11eb-9f53-d4e9c90448ac.png)

![01 03 05 Common page - Discussions - empty state -](https://user-images.githubusercontent.com/68247034/116558783-786a5880-a908-11eb-84ad-edce20c32ece.png)

**Comment by yanivi71** [comment]
Tested on http://35.208.173.116/
Found OK
