### ISSUE TITLE
Membership request screen - Update payment details (for one-time commons or 1st payment to recurring commons)

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#414]
Membership request screen (for one-time commons or 1st payment to recurring commons).
screens here:
https://zpl.io/2EX9Odl

We should now split this screen into two -
- For the user who created the request
    * Only the user who has created the membership request sees this status - during the 14 days that he can update the payment. https://zpl.io/2yr3q6G
<img width="250" src="https://user-images.githubusercontent.com/87295860/126525883-0405fc93-8dc4-4a72-8dfc-f574e34be7b1.png">

* The text will be: 
  * "**Payment Failed**   Your request was approved by the Common members but we weren't able to collect your contribution. Please update your payment details before [date of membership expiry] to become a member." The button should say "Update payment details". https://zpl.io/a85WnKQ 
 <img width="250" src="https://user-images.githubusercontent.com/87295860/126526142-bbd8bd69-3ac5-4498-b226-8a95d7c45ffc.png">

* If the 14 days have passed, the message will change to:
   * "**Payment Failed**   Your request was approved by the Common members. However, we weren't able to collect your contribution and the request was canceled.  You were not added as a member, but you can request to again". 
    In that case, the button should say "OK" and close the message. https://zpl.io/b6Gln9N
<img width="250" src="https://user-images.githubusercontent.com/87295860/126526764-22ea9297-c59c-48ca-803c-0088c5cba97a.png">

- For anyone else

    * **"Payment Failed**   This request was approved by the Common members but we weren't able to collect the contribution. [First Name] was not added as a member.**"**  https://zpl.io/a7jZPdM 
<img width="250" src="https://user-images.githubusercontent.com/87295860/126529352-3d706a92-bac1-45b6-979a-72b62f80f191.png">

* If the 14 days have passed, the message will change to:
    * **"Payment Failed**   This request was approved by the Common members. However, we weren't able to collect the contribution, and the request was canceled. [First Name] was not added as a member.**"** https://zpl.io/VQ6WN7P <img width="250" src="https://user-images.githubusercontent.com/87295860/126529672-2ad7db6e-8369-4b86-9a34-0fbfacefc674.png">

    In both cases, the button should say "OK" and close the message.

**Comment by HannaMaklakova** [comment]
not relevant
