### ISSUE TITLE
Common page - History

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#416]
Tested on
http://35.208.173.116/

1. The man icon for reject should be painted over with red color and X sign should be bigger- https://zpl.io/VO6MW1L
2. Change View proposalS to **View proposal** (singular)

![01 05 01 Common page - History - Common Web - Zepl](https://user-images.githubusercontent.com/68247034/116063595-d17a8800-a68d-11eb-9cde-6e10e022877f.png)

![Common - Google Chrome 2021-04-26 12 51 45](https://user-images.githubusercontent.com/68247034/116063856-1d2d3180-a68e-11eb-8ea7-dbda7e7b2130.png)

3. The votes bar result should be the same length as the Requested amount field - https://zpl.io/VO6MW1L
http://35.208.173.116/commons/02314122-6b05-4563-a8ce-4a10e97b72da

![Common - Google Chrome 2021-04-26 12 33 58](https://user-images.githubusercontent.com/68247034/116061999-2c12e480-a68c-11eb-89e5-1d1a6c9b4419.png)

**Comment by yanivi71** [comment]
tested on http://35.208.173.116/
Found OK
