### ISSUE TITLE
Complete your account screen

### ISSUE THREAD

**Issue by BigRomanov** [daostack/common-backend#42]
https://daostack1.atlassian.net/browse/CM-1583

Allow users to choose their correct county location

https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/5ef452329471429f8672a931

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-220)
Tested on Staging Android version 1.9.5 (4978-181)

Not fixed. the country field does display. New user gets the old screen

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-225)
Tested on Staging Android version 1.9.5 (4978-186)
@MeyerPV 
1. On Android Found OK
2. On iPhone Found OK
