### ISSUE TITLE
Mobile - Landing page

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#430]
Tested on http://35.208.173.116/
iOS - iPhone 7
Android - Samsung S10e

Design - https://zpl.io/Vq7kEvJ

**iOS & Android:**
1. Delete one Common logo
2. Change the color of the Common logo and hamburger menu 
3. Put the logo in the center
4. Raise the background photo, it should start from the menu bar (top of a page)
5. Change the phrase "Catalyze a Movement" to  "Start a Neighborhood Project".
_NB: in the design, this background photo, phone image, and text color (pink) contains another phrase "Start a Neighborhood Project"_ - https://zpl.io/Vq7kEvJ
6. Put the letter in a circle in upper-case letter
7. Pay attention that the background photo has unnecessary details (marked in red in the second screenshot)

**Android:**
8. There is no background photo on the page.

![IMG_0122 (2)](https://user-images.githubusercontent.com/68247034/116394511-aa59bd00-a82b-11eb-8ff0-df508a649934.PNG)

![IMG_0123](https://user-images.githubusercontent.com/68247034/116393672-9e213000-a82a-11eb-87f4-4f4754065199.PNG)

![Screenshot_20210428-131918_Chrome](https://user-images.githubusercontent.com/68247034/116394879-1a684300-a82c-11eb-96ae-963e8e731bfe.jpg)

**Comment by roienatan** [comment]
Hey thanks for the notes. 
I think the design is a bit confusing, or I'm missing something. See here for example the design for the desktop and the mobile. Not sure if this text should go with the sea or with the woman @kazaryan-t 

![Screen Shot 2021-04-28 at 20 47 02](https://user-images.githubusercontent.com/34843014/116449556-f7a55100-a862-11eb-93ba-e9dac0a56a52.png)
![Screen Shot 2021-04-28 at 20 46 33](https://user-images.githubusercontent.com/34843014/116449569-faa04180-a862-11eb-9206-a70531a036dc.png)

**Comment by kazaryan-t** [comment]
@roienatan 
I think @Taikaish can help us to understand better the issue.

Is it strictly to implement the text with the background as it is shown in the design or it's optional?
![Common Web - Zeplin - Google Chrome 2021-04-28 21](https://user-images.githubusercontent.com/68247034/116457503-283db880-a86c-11eb-8d4c-09fa22baa79d.png)

**Comment by Taikaish** [comment]
Thanks @roienatan @kazaryan-t !

you’re right, there’s a problem with the screens on zeplin. It should work like in common.io 

I asked brio to fix and update

**Comment by kazaryan-t** [comment]
Tested on http://35.208.173.116/

Found ok, except issue 7.
This one and some more issues were added to the ticket https://github.com/daostack/common-monorepo/issues/473.
