### ISSUE TITLE
Mobile - Landing page (2)

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#431]
Tested on http://35.208.173.116/
iOS - iPhone 7
Android - Samsung S10e

Design - https://zpl.io/Vq7kEvJ

1. Add a paragraph spacing as in the design
2. The words **Transparent, Collective, Action** should be bigger and in bold

![IMG_0124](https://user-images.githubusercontent.com/68247034/116420585-c61e8c80-a846-11eb-9cd3-8dad37151d46.PNG)
![IMG_0132](https://user-images.githubusercontent.com/68247034/116420496-af783580-a846-11eb-8ef7-8d90fa4145a5.PNG)

![02 00 01 - full screen - Common Web - Zeplin - Goo](https://user-images.githubusercontent.com/68247034/116419436-b94d6900-a845-11eb-96d6-9432a0d0ba3d.png)

3.Change the color of underlined words
4. Align left the text
5. Reduce paragraph spacing as in the design (shouldn't be so wide)

![IMG_0127](https://user-images.githubusercontent.com/68247034/116421726-c79c8480-a847-11eb-9b02-ce693a6afa24.PNG)

6. Fix the phone image as in the design (actually the photo is like outside of the box)
![IMG_0134](https://user-images.githubusercontent.com/68247034/116421974-fd416d80-a847-11eb-9aa2-4a102689b193.PNG)

7. Put in bold the marked line
8. The first shown common should place in the center of the screen
9. Add dots for scrolling commons
10. Make bigger the button _¨Explore all commons¨_ 
![IMG_0128](https://user-images.githubusercontent.com/68247034/116422360-55786f80-a848-11eb-92f9-f23c51a01c4d.PNG)

![02 00 01 - full screen - Common Web - Zeplin - Goodsxfcv](https://user-images.githubusercontent.com/68247034/116421026-2ad9e700-a847-11eb-904b-d3d35a7eb995.png)

**Comment by roienatan** [comment]
Done except of "9 - Add dots for scrolling commons".

**Comment by kazaryan-t** [comment]
Tested on http://35.208.173.116/

Found ok.
Some issues related to the landing page were added to ticket #473.
