### ISSUE TITLE
Mobile - Landing page (3)

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#432]
Tested on http://35.208.173.116/
iOS - iPhone 7
Android - Samsung S10e

Design - https://zpl.io/Vq7kEvJ

1. Place images and text in two columns as in the design
![IMG_0129](https://user-images.githubusercontent.com/68247034/116423789-aa68b580-a849-11eb-8ef1-71038bcd0d31.PNG)

![02 00 01 - full screen - Common Web - Zeplin - Gooñjgvbn](https://user-images.githubusercontent.com/68247034/116423998-d7b56380-a849-11eb-95e3-010c16d56725.png)

2. Reduce the size of the "Contact us"
3. Email shouldn't be highlighted and underlined.
4. Put some space between the email and envelope icon
5. Make a little bit bigger spaces between fields
6. Make wider 1st and 2nd fields
7. Make tighter the third field and change the text, which should be **"Your Story"**
8. Make smaller the send button, it should be the same size as the form

![IMG_0130](https://user-images.githubusercontent.com/68247034/116425216-ce78c680-a84a-11eb-9a6f-2eee0e5c8519.PNG)

![02 00 01 - full screen - Common Web - Zeplin - GooQWERGH](https://user-images.githubusercontent.com/68247034/116425257-d5073e00-a84a-11eb-997f-b645fbbc7fd7.png)

9. Show more of the background photo 
10. Change the Color of the Common logo and make it smaller
11. At the foot of the page some information is missed
12. Delete words "app" 

![IMG_0131](https://user-images.githubusercontent.com/68247034/116428333-7abbac80-a84d-11eb-9f66-1fcb2c101d55.PNG)

![02 00 01 - full screen - Common Web - Zeplin - Goo](https://user-images.githubusercontent.com/68247034/116428512-a6d72d80-a84d-11eb-86e7-eab885fc689a.png)

**Comment by roienatan** [comment]
Same here, the design is not the same for mobile and desktop in the images in the "What's Calling You?" section and for the "Contact Us" text area placeholder @Taikaish @kazaryan-t 
![Screen Shot 2021-04-29 at 11 38 25](https://user-images.githubusercontent.com/34843014/116524035-9374a280-a8df-11eb-9a50-6b7e5e80da6d.png)
![Screen Shot 2021-04-29 at 11 38 58](https://user-images.githubusercontent.com/34843014/116524044-95d6fc80-a8df-11eb-9832-82cf52733bf1.png)

**Comment by Taikaish** [comment]
@roienatan Yep :( 
There should be 4 icons, not 6 - desktop is correct.
The placeholder you highlighted should be neither of these, it should say "Notes".

Asked brio to fix and update

**Comment by kazaryan-t** [comment]
Tested on http://35.208.173.116/

Found ok.
