### ISSUE TITLE
Mobile - The headers on the landing screen should change

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#434]
Tested on http://35.208.173.116/
iOS - iPhone 7
Android - Samsung S10e

The headers on the landing page should change. It should be the same behavior as when a user opens the website https://common.io/ on his mobile phone. 

There are three designs for this behavior:
1. https://zpl.io/Vq7kEvJ
2. https://zpl.io/aMEjqWJ
3. https://zpl.io/VO4pkxQ

https://user-images.githubusercontent.com/68247034/116430277-5e207400-a84f-11eb-9fb7-140a2fa60c0d.mp4

**Comment by roienatan** [comment]
Waiting to brio for some missing assets

**Comment by kazaryan-t** [comment]
Tested on http://35.208.173.116/

Found OK!
But on iOS, sometimes the white background appears during loading the website - https://github.com/daostack/common-monorepo/issues/474
