### ISSUE TITLE
Compile types before deploy

### ISSUE THREAD

**Issue by alexander2001i** [daostack/common-backend#44]
Currently, the types are not being compiled before deployment to firebase and that causes sometimes, when the types are update, to fail the deploy. Just compile them before proceeding with the deploy

**Comment by yanivi71** [comment]
@alexander2001i Hi, What do i check here?
please advice

**Comment by alexander2001i** [comment]
Hmmm, this is a DevOps issue. I confirm that the last time when I deployed to staging it compiled them

**Comment by yanivi71** [comment]
Verified by @alexander2001i

**Comment by alexander2001i** [comment]
The last few deploys were done without compiling the types beforehand so I consider it done
