### ISSUE TITLE
Fix minimum contribution related problems

### ISSUE THREAD

**Issue by lpetkov-sw** [daostack/common-backend#442]
We have some problems related to the new feature about including 0 as minimum contribution. These are the reported problems with attached screenshots:

- The Join button says "$5 min. contribution", it should say "$0 min. contribution".
- In the agenda, the minimum appear as $5. It should be "$0 min. contribution"

![image (2)](https://user-images.githubusercontent.com/26001304/117116632-425d2680-ad97-11eb-9039-4676f2412487.png)
![image (1)](https://user-images.githubusercontent.com/26001304/117116656-48eb9e00-ad97-11eb-8009-f4eec3753964.png)
![image](https://user-images.githubusercontent.com/26001304/117116659-49843480-ad97-11eb-9c6d-c96c82f23a05.png)

**Comment by watchtower314** [comment]
pr: https://github.com/daostack/common/pull/1084
Screenshot of the fix


<img width="326" alt="Screen Shot 2021-05-18 at 13 08 39" src="https://user-images.githubusercontent.com/30501647/118633735-734b4b80-b7da-11eb-9d6d-f3a212df558c.png">
<img width="323" alt="Screen Shot 2021-05-18 at 13 08 46" src="https://user-images.githubusercontent.com/30501647/118633722-70e8f180-b7da-11eb-94ea-ea7e0742eed0.png">

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.7 (6591-281)
Tested on Staging Android version 1.9.7 (6591-242)

Found OK
1. "$0 min. contribution". is display when joining a common instead of $5
2. "$0 min. contribution" . is display in the agenda instead of $5

**Comment by yanivi71** [comment]
Tested on production
Found OK

"$0 min. contribution". is display when joining a common instead of $5
"$0 min. contribution" . is display in the agenda instead of $5
