### ISSUE TITLE
Request to join - fix validation for minFeeToJoin

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#443]
Reported by Stav via Tai
<img width="295" alt="Screen Shot 2021-05-05 at 13 11 33" src="https://user-images.githubusercontent.com/30501647/117126440-6c1c4a80-ada3-11eb-8928-ae9c180787d4.png">

Steps to reproduce:
1. Try to join a common that has min. contribution  > 0
2. Choose `other` amount and enter an amount smaller that the min fee to join.

Expected result:
- There should be a validation error that forbids entering amount less than the minimum

Actual result:
- No validation error is shown, user can proceed with the request

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.7 (6591)
Tested on Staging Android version 1.9.7 (6591-240)

Found OK
validation error is shown, user cannot proceed with the request

**Comment by yanivi71** [comment]
Tested on production
Found OK
validation error is shown, user cannot proceed with the request
