### ISSUE TITLE
Web Mobile - Explore commons

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#444]
Tested on - http://35.208.173.116/
Design - https://zpl.io/2ZRqkZd

**1. Make smaller the common logo
2. Explore commons text should be smaller and  shouldn't be in bold
3. Increase the size of Common as in the design
4. Add the button to download the app**

![IMG_0136](https://user-images.githubusercontent.com/68247034/117130847-472ad600-ada9-11eb-8e5c-97a5b6332566.PNG)
![Screenshot_20210505-120318_Chrome](https://user-images.githubusercontent.com/68247034/117130851-485c0300-ada9-11eb-9082-76b6a862f179.jpg)
![02 01 02 - explore common - mobile screen size - C](https://user-images.githubusercontent.com/68247034/117130419-b7852780-ada8-11eb-88ae-3252f977f9e5.png)

**5. Set the text of the "Load more Commons" button in the center. The word _more_ should be written in lowercase.**

![Screenshot_20210505-120304_Chrome](https://user-images.githubusercontent.com/68247034/117134067-c3bfb380-adad-11eb-98ad-01ea3b87a687.jpg)

**6. Update links to the following order:** (discussed with @Taikaish)

About
Explore Commons
Download iOS
Download Android
Terms of Use
Privacy Policy
Contact

![Screenshot_20210505-143000_Chrome](https://user-images.githubusercontent.com/68247034/117141270-02a63700-adb7-11eb-91a2-f9fa6fe71e8a.jpg)

**7. At the bottom of the page add the text _Coming soon to web_** **as in the design**
**8. Set the text "All rights reserved" in one line**

![02 01 01 - explore common - Common Web - Zeplin - ](https://user-images.githubusercontent.com/68247034/117135249-59a80e00-adaf-11eb-8465-b5da151092c2.png)

**Comment by roienatan** [comment]
7 - Can't see it in the design I'm using. Anyway I'm not sure why it's necessary since this is the web version itself.

**Comment by Taikaish** [comment]
You’re right. This line is not needed

**Comment by yanivi71** [comment]
Tested on - http://35.208.173.116/
Design - https://zpl.io/2ZRqkZd

1. Make smaller the common logo - OK
2. Explore commons text should be smaller and shouldn't be in bold - OK
3. Increase the size of Common as in the design - OK
4. Add the button to download the app - OK
5. Set the text of the "Load more Commons" button in the center. The word more should be written in lowercase. - OK
6. Update links to the following order: (discussed with @Taikaish) - OK

About
Explore Commons
Download iOS
Download Android
Terms of Use
Privacy Policy
Contact
7. At the bottom of the page add the text Coming soon to web as in the design - This line is not needed
8. Set the text "All rights reserved" in one line - OK
