### ISSUE TITLE
Web Mobile - History

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#445]
Tested on - http://35.208.173.116/
Design - https://zpl.io/2GDn9p4

1. Make smaller the Common logo
2. Delete the empty space above the image
3. Make smaller the Common name
4. Change the position of the _Share_ button (should be near the common name)
5. Reduce the font size for Available, Raised, Members and Proposals 
6. Delete words _funds, total, and active_ (look at the design)
7. Make bigger the "Join the effort" button
8. The word "History" should be highlighted in purple 
9. Add Proposal history tab as in the design

![Screenshot_20210505-151336_Chrome](https://user-images.githubusercontent.com/68247034/117140514-2ae16600-adb6-11eb-9248-4a24ee5ff2bd.jpg)
![Screenshot_20210505-151350_Chrome](https://user-images.githubusercontent.com/68247034/117140434-143b0f00-adb6-11eb-93aa-ee1815d3f848.jpg)

![02 05 01 - history tab - Common Web - Zeplin - Goo](https://user-images.githubusercontent.com/68247034/117140379-06858980-adb6-11eb-826f-77687849e85d.png)

**Comment by yanivi71** [comment]
Tested on - http://35.208.173.116/
Design - https://zpl.io/2GDn9p4

Make smaller the Common logo - OK
Delete the empty space above the image- OK
Make smaller the Common name- OK
Change the position of the Share button (should be near the common name)- OK
Reduce the font size for Available, Raised, Members and Proposals- OK
Delete words funds, total, and active (look at the design)- OK
Make bigger the "Join the effort" button- OK
The word "History" should be highlighted in purple- OK
Add Proposal history tab as in the design- OK
