### ISSUE TITLE
Web Mobile - Discussions UI issues

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#446]
Tested on - http://35.208.173.116/
Design - https://app.zeplin.io/project/603377c3d4da061120ed2961/screen/6041050e86a2b418613d38d6

1. When clicking on discussion the word "discussions does not change color
![image](https://user-images.githubusercontent.com/69141571/117249565-73e2fa00-ae4a-11eb-8526-eaf49f9fea75.png)

2. When scrolling down the button "Join the effort " does not display - see zeplin design
![image](https://user-images.githubusercontent.com/69141571/117249718-c0c6d080-ae4a-11eb-8e8e-9380a421e3bf.png)

3. Share button position is incorrect - it should be located next to the common name on the right side
4. Available funds - should be "Available"
   Total raised - Should be  "Raised"
   Active Proposal - Should be "Proposals"
5. The gap between the tag line and common details should be increased

![image](https://user-images.githubusercontent.com/69141571/117250472-f4562a80-ae4b-11eb-96f2-1178b2cec186.png)

Design image
![image](https://user-images.githubusercontent.com/69141571/117250856-83fbd900-ae4c-11eb-99bb-8081fb746ee4.png)

**Comment by roienatan** [comment]
All expect of number 2 done in https://github.com/daostack/common-monorepo/pull/457

**Comment by roienatan** [comment]
@Taikaish Can you please give a clarification regarding number 2? The "Join the Effort" button anyway always appears above the tabs (in mobile view), and appears when you have no proposals yet, so if it follows you it will appear in the third time under the proposals tab for example, or I'm missing something 🧐

**Comment by Taikaish** [comment]
Hey.

There should always be only one button displayed. 

Before the user scrolls, we show the button above the tabs. When the user scrolls and the tabs reach the top of the screen, they should remain sticky like in the screenshot on #2, and then the sticky button at the bottom should appear. It should be on the same position as I scroll down, but when I scroll to the top again - as the button above the tabs appears, the sticky button at the bottom should disappear. 

I don’t think there should be another button when there are no proposals. But I can’t find the “empty state” screens on Zeplin for mobile. Checking with Brio

**Comment by roienatan** [comment]
Closing. See issue here https://github.com/daostack/common-monorepo/issues/580
