### ISSUE TITLE
Web Mobile - Proposals Ui issues

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#447]
Tested on - http://35.208.173.116/
Design - https://app.zeplin.io/project/603377c3d4da061120ed2961/screen/604105dcbec7f7166b745ef8

1. When clicking on proposals the word "proposal" does not change color
2. Share button position is incorrect - it should be located next to the common name on the right side
3. Available funds - should be "Available"
   Total raised - Should be "Raised"
   Active Proposal - Should be "Proposals"
![image](https://user-images.githubusercontent.com/69141571/117257933-1902d000-ae55-11eb-995a-908a6a9d7eae.png)

4. Countdown value is incorrect - the day values should display  in numbers
![image](https://user-images.githubusercontent.com/69141571/117258397-9b8b8f80-ae55-11eb-9362-4fb549a960dc.png)

**Comment by roienatan** [comment]
All expect of number 4 done in #457
Number 4 is in separated issue: https://github.com/daostack/common-monorepo/issues/468

**Comment by yanivi71** [comment]
Tested on - http://35.208.173.116/
Found OK
except issue 4 which is reported in different issue

**Comment by roienatan** [comment]
@Taikaish @yanivi71 It should always be in the format for HH:DD:SS?
I guess not since for many days it'll be long number. What's the required convention? In my opinion it has to be consistent across all the app, let's decide.

**Comment by Taikaish** [comment]
@yanivi71 let’s check what we use in the mobile app? Should work the same way

**Comment by yanivi71** [comment]
@Taikaish @razoorka this is how it display on mobile app
![image](https://user-images.githubusercontent.com/69141571/118165017-74702780-b42c-11eb-99df-5e4cb3bae0ab.png)
