### ISSUE TITLE
Mobile web - Agenda

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#451]
Tested on - http://35.208.173.116/

1. Make smaller the Common logo
2. Add close button (X)
2. Delete the empty space above the Common image
3. Make smaller the Common name and it shouldn't be in bold
4. Change the position of the Share button (should be near the common name)
5. Reduce the font size for Available, Raised, Members and Proposals
6. Delete words _funds, total, and active_ (look at the design)
7. Make bigger the "Join the effort" button
8. The word "Agenda" should be highlighted in purple
9. Update links at the bottom of the page to the following order:

> 1. About
> 2. Explore Commons
> 3. Download iOS
> 4. Download Android
> 5. Terms of Use
> 6. Privacy Policy
> 7. Contact

ACTUAL:

![Screenshot_20210506-123523_Chrome](https://user-images.githubusercontent.com/68247034/117283698-b5859c00-ae6e-11eb-9eae-d0e5c1546a99.jpg)
![Screenshot_20210506-123515_Chrome](https://user-images.githubusercontent.com/68247034/117283709-b74f5f80-ae6e-11eb-9f89-80db027e843a.jpg)

DESIGNS :

![02 02 02 - common page - mobile screen size - Comm](https://user-images.githubusercontent.com/68247034/117283320-5889e600-ae6e-11eb-9387-e9bf3773ee12.png)
![02 02 01 - common page - Common Web - Zeplin - GooDFGH](https://user-images.githubusercontent.com/68247034/117283313-56c02280-ae6e-11eb-9c19-00176250aa84.png)

**Comment by roienatan** [comment]
All done here https://github.com/daostack/common-monorepo/pull/457
2 - I guess it's a mistake

**Comment by yanivi71** [comment]
Tested on - http://35.208.173.116/

Make smaller the Common logo - OK

Add close button (X) - Should be tested with brio mb its a design mistake

Delete the empty space above the Common image - OK

Make smaller the Common name and it shouldn't be in bold - OK

Change the position of the Share button (should be near the common name) - OK

Reduce the font size for Available, Raised, Members and Proposals - OK

Delete words funds, total, and active (look at the design) - OK

Make bigger the "Join the effort" button - OK

The word "Agenda" should be highlighted in purple - OK

Update links at the bottom of the page to the following order: - OK
About
Explore Commons
Download iOS
Download Android
Terms of Use
Privacy Policy
Contact
