### ISSUE TITLE
Web - explore commons - Proposals - view proposal does not function

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#464]
Steps to reproduce:
1. Go to explore common
2. Choose common with active proposal e.g "T-shirt"
3. click on view proposal / proposal title/ Read more

Actual results:
user does not redirect to full proposal view - see attached image

![image](https://user-images.githubusercontent.com/69141571/117620797-7fe7f800-b179-11eb-8184-341b40fb043d.png)

Expected results:
user should be redirect to full view of proposal

**Comment by kazaryan-t** [comment]
Tested on http://35.208.173.116

Clicking on **"Read More", "View proposal"**, **proposal title** buttons leads to the white screen.

**Comment by kazaryan-t** [comment]
If the common has any amount of Available Funds and when opening the full screen of the proposal, an incorrect value in the Requested amount field is displayed. (Look at the screen recording below)

Steps to reproduce:
1. Open a common that has Available Funds and active Proposals
2. Go to Proposals screen
3. Before opening the full screen of the proposal, look at the Requested amount field
4. Open full screen of the proposal

Actual:
Incorrect value in Requested amount field is displayed. 
(It displays the amount of Available Funds)

Expected:
The Requested amount fields show the correct value.

Common from video - http://35.208.173.116/commons/3fc54c58-f31c-43dd-94d7-c3409c109570

https://user-images.githubusercontent.com/68247034/118656909-a6e69f80-b7f3-11eb-975f-661babb9a4ff.mp4

**Comment by yanivi71** [comment]
Tested on http://35.208.173.116
Found OK
1. view proposal is available
2. proposal amount is correct when user view proposal
