### ISSUE TITLE
Fix proposal countdown value

### ISSUE THREAD

**Issue by roienatan** [daostack/common-backend#468]
See number 4: https://github.com/daostack/common-monorepo/issues/447

**Comment by kazaryan-t** [comment]
Please, delete spaces between numbers and colon in the countdown.

![Screenshot_20210517-134510_Chrome](https://user-images.githubusercontent.com/68247034/118477826-cc05e000-b717-11eb-98ee-c496a574c3bd.jpg)

![01 04 01 Common page - Proposals - Common Web - Ze](https://user-images.githubusercontent.com/68247034/118477575-7d584600-b717-11eb-9bd7-8009b6dd41a9.png)

![Common - Google Chrome 2021-05-17 13 46 38](https://user-images.githubusercontent.com/68247034/118477697-a2e54f80-b717-11eb-83e3-e8997fa9ecfb.png)

**Comment by kazaryan-t** [comment]
When opening the full screen of proposal, the countdown first shows incorrect time but then changes immediately to the correct value.

https://user-images.githubusercontent.com/68247034/118661935-46a62c80-b7f8-11eb-94ba-475fb2e7db97.mp4

**Comment by yanivi71** [comment]
Tested on iOS
Tested on  Android
tested on WEB

Found OK
