### ISSUE TITLE
Landing page - UI fixes

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#470]
Tested on http://35.208.173.116/
Design - https://zpl.io/2GDR54J

1. Show more of the background photo (the man and woman with wood)
2. Set links in the columns in the same order as in the design

![Common - Google Chrome 2021-05-12 13 06 43](https://user-images.githubusercontent.com/68247034/117957502-d2b0e380-b322-11eb-941f-ee2a55bda323.png)

![01 00 01 - English - Full Landing Page - Common W52e](https://user-images.githubusercontent.com/68247034/117957381-b0b76100-b322-11eb-9e67-d1558aa51d68.png)

**Comment by roienatan** [comment]
2: Anyway there is a new design for the footer links in desktop view, they should be in one row. Working on this...

**Comment by kazaryan-t** [comment]
Tested on http://35.208.173.116/

Found ok, new design for links at the foot of a page - https://zpl.io/2GDR54J
