### ISSUE TITLE
Create a common - disabled text input background should be grayed out

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#472]
https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/6045e47580b665a4f64bb6db

**Comment by watchtower314** [comment]
pr: https://github.com/daostack/common/pull/1085

https://user-images.githubusercontent.com/30501647/118821067-8d128e80-b8bf-11eb-9c74-2fc61cc8edf7.MP4

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.7 (6591-282)
Tested on Staging Android version 1.9.7 (6591-243)

Found OK.

**Comment by yanivi71** [comment]
Tested on production

Found OK
