### ISSUE TITLE
Mobile web - Landing page

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#473]
Tested on http://35.208.173.116/
Design - https://zpl.io/Vq7kEvJ

1. Delete the paragraph space between phrases **Catalyze a movement** and **Together**
![Screenshot_20210512-160236_Chrome](https://user-images.githubusercontent.com/68247034/117980041-3693d600-b33c-11eb-9321-593dcea2f411.jpg)

2. Put the comma after **Start a Neighborhood Project**
![02 00 03 - 3rd header - Common Web - Zeplin - Goog](https://user-images.githubusercontent.com/68247034/117980419-9be7c700-b33c-11eb-844d-a2d96f11b942.png)

3. Remove unnecessary details from the background photo (marked in yellow)
![Screenshot_20210512-160236_Chrome (2)](https://user-images.githubusercontent.com/68247034/117980916-1d3f5980-b33d-11eb-9f5f-f4f31e76d53b.jpg)

4. Separate the text in lines as it's shown in the design
![Screenshot_20210512-161717_Chrome](https://user-images.githubusercontent.com/68247034/117981850-1b29ca80-b33e-11eb-8cf4-49338f4af9de.jpg)
![02 00 03 - 3rd header - Common Web - Zeplin - Googdfg](https://user-images.githubusercontent.com/68247034/117982021-3d234d00-b33e-11eb-8ae9-11a849f5494d.png)

5. Add the part of the photo of the next common in Featured commons tab (look at the design)
![Screenshot_20210512-161859_Chrome](https://user-images.githubusercontent.com/68247034/117982191-6e9c1880-b33e-11eb-958f-3b7e84d17239.jpg)
![02 00 01 - full screen - Common Web - Zeplin - Goo](https://user-images.githubusercontent.com/68247034/117982298-8b385080-b33e-11eb-8c0e-d000ac1668e5.png)

**Comment by roienatan** [comment]
2. @Taikaish In the design only the "Start a Neighborhood Project" has a comma after it, and in the other two ("Catalyze a movement" and "Fund Independent Journalism") there is no comma after. Probably it should be consistent, so should or shouldn't be a Cooma there?

**Comment by Taikaish** [comment]
Good catch. There should be a comma for all 3 of them

**Comment by kazaryan-t** [comment]
Tested on http://35.208.173.116/

Found OK.
