### ISSUE TITLE
Mobile Web - White background appears when loading the website

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#474]
Tested on http://35.208.173.116/

The white background appears during loading the website.

https://user-images.githubusercontent.com/68247034/117996383-c8a2db00-b34a-11eb-8b29-1dfd5e158a51.MP4

**Comment by roienatan** [comment]
@kazaryan-t Still happens for you?

**Comment by kazaryan-t** [comment]
Tested on iOS with @yanivi71 

When a user opens the browser with an opened website from the background, the white background appears.


https://user-images.githubusercontent.com/68247034/120160731-3d0cc380-c1ff-11eb-82a9-d5e45d73e471.MP4

Update: The same situation is happening not only to mobile web:
![Безымянный](https://user-images.githubusercontent.com/68247034/120176907-7c8fdb80-c210-11eb-9f37-833ee38c37c1.png)

**Comment by razoorka** [comment]
Load speed should be faster now

**Comment by kazaryan-t** [comment]
1. The white screen still appears and during the loading, the fonts change.
2. This problem https://github.com/daostack/common-monorepo/issues/474#issuecomment-851291698 also reproduces.

https://user-images.githubusercontent.com/68247034/121354549-a6937d00-c937-11eb-8f25-3812373879a2.MOV

https://user-images.githubusercontent.com/68247034/121354134-43a1e600-c937-11eb-8cf9-4679923dea88.mp4
