### ISSUE TITLE
Web / mobile web - explore commons - Proposals - view proposal does not display

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#476]
Steps to reproduce:
1. click on explore commons
2. Choose common with active proposals e.g. "T-Shirt"
3. Click on proposals
4. navigate to any proposal

Actual results:
view proposal does not display - see attached image
the view proposal appears  only when there is a chat value.
![image](https://user-images.githubusercontent.com/69141571/118103277-6695b480-b3e2-11eb-8049-7b59eb3121e7.png)

Expected results:
View proposal must appears always,
Note: this fix should be implemented on mobile web too

**Comment by kazaryan-t** [comment]
Found Ok.
_View proposal_ button appears always, even if there are no messages in the proposal chat.
