### ISSUE TITLE
Web / Mobile - comments - time display is incorrect

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#477]
Steps to reproduce:
1. Click on explore commons
2. choose common with discussions and proposals e.g "Email Common abc"
3. Click on history
4. Look At the time of the comments

Actual results:
1. The comment time contain AM / PM
2. The date contain the Day in the week
3. see attached image
![image](https://user-images.githubusercontent.com/69141571/118113233-b5e1e200-b3ee-11eb-8f74-22c3b9dd23db.png)

Expected results:
1. The time of the comment should not contain format with AM/PM - it should display in 24 hours format (09:40, 17:50, 13:20)
2. The date must should not contain the "day" of the week only the date with format yyyy-mm-dd

**Comment by roienatan** [comment]
@yanivi71 Regarding 2, can you please show me where it's in the design? Can't find it. I see just examples of "Today".

**Comment by yanivi71** [comment]
@roienatan this is the design from the mobile app
![image](https://user-images.githubusercontent.com/69141571/118165523-0d06a780-b42d-11eb-8bbf-09972ae5445a.png)

**Comment by kazaryan-t** [comment]
Tested on http://35.208.173.116/

Fixed.
