### ISSUE TITLE
 Web Mobile - Remove Latest proposals and Latest discussions from the Agenda page

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#480]
Tested on http://35.208.173.116/
Design - https://zpl.io/ann6Y5v

Remove the Latest proposals and Latest discussions tabs from the Agenda page. To see Proposals and Discussions user should navigate to the relevant tab.

Steps to reproduce:
1. Open the website on the mobile device
2. Open Explore Commons page
3. Click on any Common
4. Scroll down the Agenda page

Actual:
There are Latests Discussions and Latest Proposals tabs appear.

Expected:
There are no Latest Discussions and Latest Proposals tabs on the Agenda page. 

https://user-images.githubusercontent.com/68247034/118124315-162c5000-b3fe-11eb-8e1a-c4fb6c91cd08.mp4

![02 02 01 - common page - Common Web - Zeplin - GooSDC](https://user-images.githubusercontent.com/68247034/118124183-e9783880-b3fd-11eb-8d12-89b83973bec8.png)

**Comment by roienatan** [comment]
@Taikaish In the desktop view they appear. Is it a mistake or they should not appear on the mobile agenda?

**Comment by Taikaish** [comment]
Hey. Latest discussions/proposals on the agenda page should only be displayed on desktop. 

The reason is the far greater space we have on desktop. On mobile it’s better that users will just navigate to the relevant tab.

**Comment by kazaryan-t** [comment]
Tested on http://35.208.173.116/

Found ok. 
There are no Latest Discussions and Latest Proposals on the Agenda screen.
