### ISSUE TITLE
Discussions - Blank space appears between textbox and keyboard

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#486]
Tested on Staging iOS version 1.9.7 (6591)

Blank space appears between textbox and keyboard when clicking on the textbox and the discussion title with the arrow "back" hide on the top of the screen. 

![photo_2021-05-17_13-47-28](https://user-images.githubusercontent.com/68247034/118479566-d923ce80-b719-11eb-95ae-0b186aebc99c.jpg)

![IMG_0141](https://user-images.githubusercontent.com/68247034/118479378-9d890480-b719-11eb-8dc5-d8dc0e59fe90.PNG)

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.7 (6591-284)

The issue with blank space was fixed.
The new issue related to the discussion screen - https://github.com/daostack/common-monorepo/issues/521

**Comment by yanivi71** [comment]
Tested on production

Found OK
