### ISSUE TITLE
Web - Proposals - Long proposal description goes outside the proposal tab

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#487]
Tested on http://35.208.173.116/
Common from the screenshot - http://35.208.173.116/commons/004abe8d-1006-4b63-9e7a-5d824c4fb1fd

1. Long proposal description goes outside the proposal tab
2. Absent moderator's avatar

![Screenshot_20210517-142928_Chrome](https://user-images.githubusercontent.com/68247034/118481807-8ef01c80-b71c-11eb-9238-192836ce3a5d.jpg)

![Common - Google Chrome 2021-05-17 12 29 26](https://user-images.githubusercontent.com/68247034/118480887-821ef900-b71b-11eb-8222-08e4972f6d1b.png)

**Comment by roienatan** [comment]
1. Already resolved in previous PR.
2. This is the default image when no avatar available in the backend.

**Comment by kazaryan-t** [comment]
Fixed.
