### ISSUE TITLE
Web mobile - Agenda screen - Add button and UI fixes

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#488]
Tested onhttp://35.208.173.116/
Design - https://zpl.io/ann6Y5v

1. Delete the word _"About"_ and white tab at the back of the Common description. The whole background for the agenda should be entire and white (look at the design).
2. Add the button **"Join the effort"** at the end of the Common description instead of **Share** button.
3. Remove the background from the **Share** button.
4. Make wider the button **"Join the effort"**.

![Screenshot_20210517-164457_Chrome](https://user-images.githubusercontent.com/68247034/118501939-e5b42100-b731-11eb-8c28-7bb64be8b3b7.jpg)
![Screenshot_20210517-164555_Chrome](https://user-images.githubusercontent.com/68247034/118501934-e482f400-b731-11eb-881e-15eab68a8e49.jpg)

![02 02 01 - common page - Common Web - Zeplin - Goo](https://user-images.githubusercontent.com/68247034/118501995-efd61f80-b731-11eb-943b-5bd6819cfafd.png)

**Comment by roienatan** [comment]
Regarding 2, please see Tai comment here https://github.com/daostack/common-monorepo/issues/446
Looks like the button should be hovering above all the rest. Anyway the functionality here is not yet clear so I decided for now to not show it at all until it's clear.

**Comment by kazaryan-t** [comment]
1 and 3 were fixed.
2 described better in #446 

4 not fixed. **Make wider the button "Join the effort".**

**Comment by kazaryan-t** [comment]
Fixed 1, 3, and 4.
