### ISSUE TITLE
Add countdown to the latest proposal in sidebar

### ISSUE THREAD

**Issue by roienatan** [daostack/common-backend#493]
Add the countdown and actual results for active proposals in the Latest Proposals tab in Agenda and Discussions screens

![](https://user-images.githubusercontent.com/68247034/118468068-0ddd5900-b70d-11eb-9215-008145c910af.png)

**Comment by roienatan** [comment]
@Taikaish Is it something we want to show also in the mobile view? Didn't find a design for that I think.

**Comment by Taikaish** [comment]
Hey, no - the "latest discussions"/"latest proposals" blocks should not be displayed in mobile.

**Comment by roienatan** [comment]
@razoorka Please see Tai's comment.

**Comment by kazaryan-t** [comment]
@Taikaish, should we show the full countdown (including seconds) or only days:hours:minutes as in the design? 
And is it critical that the actual countdown has a clock icon distinct from the design?

![Common - Google Chrome 2021-05-25 17 49 28](https://user-images.githubusercontent.com/68247034/119518704-71a4f900-bd81-11eb-997b-65e3e21bfaff.png)

DESIGN - 
![01 02 01 Common page - Agenda - Common Web - Zepli](https://user-images.githubusercontent.com/68247034/119518613-589c4800-bd81-11eb-9c80-914365d271a7.png)

**Comment by Taikaish** [comment]
Hey, thanks.

For the time units, we can have it either way - with or without seconds.

For the icon - all the icons we use have a similar style, so it's pretty important to use the icons Brio created/chose and to use them in right exact size

**Comment by kazaryan-t** [comment]
@razoorka, please change the countdown icon, it should be the icon created by Brio and in exact size.

![01 02 01 Common page - Agenda - Common Web - Zepli](https://user-images.githubusercontent.com/68247034/119619183-634fef00-be0c-11eb-87cb-066d15505466.png)

**Comment by kazaryan-t** [comment]
Checked.
