### ISSUE TITLE
Comments groups

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#497]
- 4 px between comments
- 16 px between groups
- time per comment
- all comments should have the same size
- max width 279 px
- min width 140 px
<img width="508" alt="Screenshot 2021-05-23 at 09 15 59" src="https://user-images.githubusercontent.com/28015224/119250257-80d04f00-bba7-11eb-8f53-2c1033ce36ca.png">

**Comment by MeyerPV** [comment]
Assigned to me
