### ISSUE TITLE
Web - Ui Issues we discussed on web meeting  

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#500]
1. Landing page - images are upload very slow
2. Contact  - redirect to empty page
3. Font size of all the web site - verify the font size with brio. 
4. Landing page - Contact - "Send" Button should be shorter - and also the background should be dark blue.
![image](https://user-images.githubusercontent.com/69141571/118939490-69e7ed80-b958-11eb-9154-444a8b6458be.png)

5. Loader - please verify with brio which loader should be display

**Comment by roienatan** [comment]
1 - There is already an issue about this. Also please see @Jan-Blarky comment here https://github.com/daostack/common-monorepo/issues/502
2 - According to brio, for now it should just open the email for the support - DONE
4 - DONE
3 and 5: https://github.com/daostack/common-monorepo/issues/528

**Comment by kazaryan-t** [comment]
Verified 2 and 4.
Found ok
2. The email for the support opens when clicking on Contacts.
4. The button is disabled until the user enters data in all fields.
