### ISSUE TITLE
Web - landing page - the images are load very slow

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#502]
tested on http://35.208.173.116/

Steps to reproduce:
1. load the web site http://35.208.173.116/
2. pay attention to the loading images time

Actual results:
the images are load very slow, sometime it display

Expected results:
images must be load faster

**Comment by Jan-Blarky** [comment]
First of all, it’s a dev environment and here’s no CDN, so pictures downloading directly from the server, that’s of course a little bit slow. 
Second: there are some resources around 1mb or more(.otf file that weights 11.3 Mb O_O) that should be reduced.
![image](https://user-images.githubusercontent.com/69893042/119005561-3a58d580-b998-11eb-932c-4f1d04db6681.png)
