### ISSUE TITLE
Chat - New layout

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#510]
Design: https://zpl.io/bJXYmYK
Important notes:
- add + button for adding images
- other user's avatars should be 32px
- 8 px margin from the left side to user's avatar
- 8 px space between avatar and comment
<img width="376" alt="Screenshot 2021-05-23 at 09 30 57" src="https://user-images.githubusercontent.com/28015224/119250567-96467880-bba9-11eb-8418-7cf9a9f2b965.png">
- after 1000 chars the text is minimized and added "Read more". After clicking on it the full text is opened

**Please, pay attention to all margins and sizes**
More details:

- [Chat - My comments](https://miro.com/app/board/o9J_lXUPFyo=/?moveToWidget=3074457355198580885&cot=14)

- [Chat - Other user comments](https://miro.com/app/board/o9J_lXUPFyo=/?moveToWidget=3074457355198580887&cot=14)

**Comment by HannaMaklakova** [comment]
not relevant
