### ISSUE TITLE
Proposal - rejected proposal doesn't stop countdown

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#517]
Steps to reproduce:

1. created a request to join
2. reject that request to join

Expected result:
Countdown should stop

Actual result:
Countdown continues

**Comment by watchtower314** [comment]
pr: https://github.com/daostack/common/pull/1089

After the fix, the countdown will not be visible for rejected proposals (confirmed with Yaniv that this is the correct behaviour)

<img width="316" alt="Screen Shot 2021-05-23 at 19 23 28" src="https://user-images.githubusercontent.com/30501647/119268755-06cab500-bbfd-11eb-8c42-9a14b8a57799.png">
<img width="323" alt="Screen Shot 2021-05-23 at 19 23 21" src="https://user-images.githubusercontent.com/30501647/119268756-07634b80-bbfd-11eb-80a4-bb4b4eb1af40.png">

**Comment by kazaryan-t** [comment]
Checked.

**Comment by yanivi71** [comment]
tested on production
Found OK
