### ISSUE TITLE
conversionRate value is 0

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#519]
Conversion rate that is displayed is 0

<img width="215" alt="Screen Shot 2021-05-24 at 11 05 58" src="https://user-images.githubusercontent.com/30501647/119317236-89488880-bc80-11eb-8991-081e261d71c2.png">
<img width="326" alt="Screen Shot 2021-05-24 at 11 01 37" src="https://user-images.githubusercontent.com/30501647/119317244-8a79b580-bc80-11eb-94c6-14a01e8bbbcc.png">

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.7 (6591-285)
Tested on Staging Android version 1.9.7 (6591-246)

Found OK

**Comment by yanivi71** [comment]
Tested on production

Found OK
