### ISSUE TITLE
Create common - touches and review - wrong minimum contribution value

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#522]
Tested on Staging iOS version 1.9.7 (6591-283)
Tested on Staging Android version 1.9.7 (6591-244)

Steps to reproduce:
1. Create a new common
2. on funding screen choose one time contribution
3. mark the check box to allow minimum contribution $0
4. navigate to Final touches and review

Actual results:
Minimum contribution is $5 - see attached image

Expected results:
Minimum contribution should be $0
![image](https://user-images.githubusercontent.com/69141571/119346228-9eceaa00-bca2-11eb-8989-d1da77bd876f.png)

**Comment by watchtower314** [comment]
pr: https://github.com/daostack/common/pull/1092

screenshot of the fix:

<img width="354" alt="Screen Shot 2021-05-24 at 15 18 13" src="https://user-images.githubusercontent.com/30501647/119349006-47323d80-bca6-11eb-9dae-1ed099266746.png">
