### ISSUE TITLE
Web - Common - History - view proposal - wrong status appear in the proposal

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#525]
Steps to reproduce:
1. Go to a common with proposal in history e.g "Email Common abc"
2. go to history
3. Click on view proposal/read more 

Actual results:
the status on the top is  "time's up!"

Expected results:
The status should be the status of the proposal (Reject, approved. etc..). with the correct color background (green/ red)
![image](https://user-images.githubusercontent.com/69141571/119614533-0f8ed700-be07-11eb-844d-49b70ed27469.png)

**Comment by roienatan** [comment]
@Taikaish So in what situation we show “Time’s up”?
Since a proposal can be approved or rejected only looks like we'll never show “Time’s up”. 
Please correct me if I'm wrong.

**Comment by yanivi71** [comment]
Found OK
The status is the status of the proposal
