### ISSUE TITLE
Mobile Web - Add the Common logo and image for download button on opened menu

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#540]
Design - https://zpl.io/aBQd5RL

There are no Common logo and image for the download button on opened menu:

![Screenshot_20210601-111241_Chrome](https://user-images.githubusercontent.com/68247034/120297139-7ada1c80-c2d1-11eb-96e1-58826d386cd0.jpg)

![IMG_0157](https://user-images.githubusercontent.com/68247034/120297145-7c0b4980-c2d1-11eb-8c3a-2f4156b0ac1e.PNG)

**Comment by kazaryan-t** [comment]
Please, align the **Download Common app** text in the center.

![IMG_0191](https://user-images.githubusercontent.com/68247034/121788463-1fb00000-cbd6-11eb-808d-414edbe21a5d.PNG)

**Comment by yanivi71** [comment]
Tested on Web mobile
Common logo and image for the download button appears on opened menu
Download Common app text in the center
