### ISSUE TITLE
Web - There are some disabled links at the bottom of the page 

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#545]
At the bottom of the page, there are three disabled links: **About, Terms of use**, and **Privacy Policy**.

Expected:
All links should be clickable and lead to the correct content.

![Common - Google Chrome 2021-05-31 14 18 45](https://user-images.githubusercontent.com/68247034/120436813-129a4200-c388-11eb-8767-8833aacd4dfe.png)

**Comment by roienatan** [comment]
@Taikaish where the links should direct to?

**Comment by roienatan** [comment]
The "Terms of Use" and "Privacy Policy" links are now direct to a appropriate file.
According @Taikaish, the "About" links should redirect to the "What is Common" section in the landing page.

**Comment by kazaryan-t** [comment]
On Android, when clicking on Terms of Use or Privacy Policy links, the files should open and download automatically (as on iOS).

Current behavior:

https://user-images.githubusercontent.com/68247034/121157569-5a224180-c852-11eb-9242-49a589b9a3fa.mp4

**Comment by roienatan** [comment]
> On Android, when clicking on Terms of Use or Privacy Policy links, the files should open and download automatically (as on iOS).
> 
> Current behavior:
> 
>  Screen_Recording_20210608-115806_Chrome.mp4

@kazaryan-t  I think it's more about the device settings.
