### ISSUE TITLE
Add a link on My Profile: "About Common"

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#546]
1. Reorganize the order of links and add a link "About Common":

[<img width="189" alt="Screenshot 2021-06-02 at 10 59 32" src="https://user-images.githubusercontent.com/28015224/120445767-9efd3280-c391-11eb-9294-452ecd64add2.png">]
https://zpl.io/beqO1oY

2. When the "About Common" link is clicked, open the onboarding screens for new users:
https://zpl.io/aR5vqQE
<img width="189" src="https://user-images.githubusercontent.com/87295860/128874977-d1a8dedf-9c87-4119-9a97-4652ca328f7e.png">

**Comment by IlyaDylko** [comment]
Assigned to me

**Comment by IlyaDylko** [comment]
Everything is working like it should
