### ISSUE TITLE
Responsiveness - on wide screens, the cover photo changes its proportions - on 1440*900 pixel screens and more, the spaces should be the same as in the design, and only the margins need to grow.

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#550]
the grid grows to a maximum of 1440*900 pixels, and on wider screens, only the margins need to grow, and the design will always be centered.
Actual result: https://drive.google.com/file/d/1EJrTLuHZ2TXD9es4ASNwkNsDtUaQJ2vk/view
Expected result: https://zpl.io/be68NwD

**Comment by Taikaish** [comment]
Hey, 

See this:
![image](https://user-images.githubusercontent.com/5177733/122795312-dc384e80-d2c5-11eb-9b2e-42a88f5d36a1.png)

The gray background and the background of the menu (highlighted in the screenshot) should be stretched to fill the entire screen. Just like the footer and the header. The rest of the content should remain as is (fixed and centered).

@yanivi71 @gingervik

**Comment by yanivi71** [comment]
Tested on web site and found OK
The gray background and the background of the menu (highlighted in the screenshot) is stretched to fill the entire screen
The rest of the content  remain as is (fixed and centered).
