### ISSUE TITLE
Web - Long discussion title goes out of the background

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#551]
When the discussion title is very long, and the user hovers on this title with the cursor, the text of the discussion title goes out of the background.

![Безымянный](https://user-images.githubusercontent.com/68247034/120706999-73c63080-c4c2-11eb-8802-280b081785b3.png)

Need to discuss this issue with @Taikaish.
Maybe we can implement the same solution as in the mobile app - set a char limit for the discussion title in the Latest discussions tab, and put three dots at the end.

![Screenshot_20210603-232239_common-stg](https://user-images.githubusercontent.com/68247034/120707704-56de2d00-c4c3-11eb-938f-9d53bd626006.jpg)

**Comment by kazaryan-t** [comment]
Checked.

**Comment by kazaryan-t** [comment]
The bug reproduced.
Commons to check - http://35.208.173.116/commons/0644f463-4778-4233-8eac-22a1112b171f, http://35.208.173.116/commons/0c233ec1-c0a4-4776-8730-79777239a997

![Безымянный - Paint 2021-06-10 22 52 06](https://user-images.githubusercontent.com/68247034/121588401-8a2e3800-ca3e-11eb-9c7f-fb12659fe3b2.png)

**Comment by kazaryan-t** [comment]
The Discussion name is too close to the arrow when hovering the discussion with a long title.

![Безымянный - Paint 2021-06-12 23 00 38](https://user-images.githubusercontent.com/68247034/121787960-0dcc5e00-cbd2-11eb-9975-1a6a0bc72a5c.png)

**Comment by yanivi71** [comment]
tested on web site and found OK
