### ISSUE TITLE
Explore commons - Common bottom padding should be smaller

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#556]
Please, make common bottom padding according to design 
https://zpl.io/Vx4Wjkk

**Comment by roienatan** [comment]
I guess you meant the bottom padding should **larger**, since in the design there is more space between each common.

**Comment by kazaryan-t** [comment]
1. Please, increase the padding between common and footer to the size marked in the screenshot.

![Безымянный - Paint 2021-06-10 23 46 19](https://user-images.githubusercontent.com/68247034/121594700-1a23b000-ca46-11eb-8796-2cf5eff5b1a4.png)

**Comment by kazaryan-t** [comment]
Please, make smaller the bottom padding in common cards (should be 1.125rem). 

![Common - Google Chrome 2021-06-12 23 06 30](https://user-images.githubusercontent.com/68247034/121788061-f5a90e80-cbd2-11eb-9ca8-59e7f57f2c5a.png)

![Безымянный - Paint 2021-06-12 23 08 00](https://user-images.githubusercontent.com/68247034/121788068-0194d080-cbd3-11eb-8981-5b36b6d56b71.png)

**Comment by yanivi71** [comment]
tested on web and mobile sites
bottom padding is smaller
