### ISSUE TITLE
Subscriptions - Update card with new details 

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#559]
When the card expires, or the subscription could not be processed and the user is required to update her payment details 

- [x] brio design for `update details` screen @Taikaish
- [ ] spec the flow

https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/6033efdd7ece919b74135c21

**Comment by watchtower314** [comment]
@HannaMaklakova I think this is about one of the payment batch #2, which is a December feature, this is why I think we should close this, because we don't know what will be with our payments 

https://www.notion.so/daostack/Product-Roadmap-04ecd4b465a24041b80c94a300595c1c?p=24bed68dda1e4603a70f64da9957d923

**Comment by HannaMaklakova** [comment]
Okay! Thank you for the explanation!
