### ISSUE TITLE
Explore Commons - There is no hover state for commons' cards

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#560]
Please, fix according to design 
https://app.zeplin.io/project/603377c3d4da061120ed2961/screen/6033856688f05210f6ced424

Please, pay attention to the shadow
<img width="1265" alt="Screenshot 2021-06-07 at 12 04 33" src="https://user-images.githubusercontent.com/28015224/120989741-87a2b880-c788-11eb-90f3-4b0f61b68cf2.png">

**Comment by yanivi71** [comment]
Tested on the web site

hover state for commons' cards appears
