### ISSUE TITLE
Join effort - UI fixes

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#562]
Please, make the following fixes
- pop-up should be smaller
- header of the pop-up should be taller
- add hover state for AppStore button

Please, see design
https://zpl.io/V0XGYBQ

**Comment by kazaryan-t** [comment]
1. Please, increase the padding from the top. 

![Безымянный](https://user-images.githubusercontent.com/68247034/121643513-90ea9880-ca9a-11eb-9e09-8f2ddcf404e5.png)

![Безымянный - Paint 2021-06-11 09 49 10](https://user-images.githubusercontent.com/68247034/121643505-8f20d500-ca9a-11eb-8752-6dd042205975.png)

2. Seems that button AppStore is bigger than Google play (a bit taller and wider)

![Common - Google Chrome 2021-06-11 09 50 14](https://user-images.githubusercontent.com/68247034/121643718-d0b18000-ca9a-11eb-81fe-3d41b4b60d3b.png)

3. Add hover state for AppStore button, the same as for Google Play.

https://user-images.githubusercontent.com/68247034/121643998-271ebe80-ca9b-11eb-915d-2bc1eed742f1.mp4

**Comment by yanivi71** [comment]
@razoorka now when clicking on join affords the pop up does not display in full.
user must scroll down to see the whole pop up

![image](https://user-images.githubusercontent.com/69141571/121865759-fe9afc80-cd06-11eb-9d31-e80ff178db65.png)

**Comment by gingervik** [comment]
@yanivi71 please, add screen resolution for which this bug is reproduced. It will be very helpful for @razoorka 
1920x1080 is ok for me
<img width="890" alt="Screenshot 2021-06-14 at 12 29 03" src="https://user-images.githubusercontent.com/28015224/121870849-1de85880-cd0c-11eb-972d-1641914409ad.png">
1366x768 is also (almost) ok
<img width="714" alt="Screenshot 2021-06-14 at 12 30 07" src="https://user-images.githubusercontent.com/28015224/121870996-44a68f00-cd0c-11eb-8a56-3316b4b58cca.png">
1536х864
<img width="775" alt="Screenshot 2021-06-14 at 12 33 56" src="https://user-images.githubusercontent.com/28015224/121871443-cbf40280-cd0c-11eb-85aa-ca2f617fa763.png">

**Comment by yanivi71** [comment]
@gingervik thanks
@razoorka mine is 1920x1080.

**Comment by yanivi71** [comment]
tested on web site and found OK

**Comment by Taikaish** [comment]
Fix required: 
The background image at the top should be taller, so more of it will appear.
There should be a margin between where the text ends and where the background ends.

Production:
![image](https://user-images.githubusercontent.com/5177733/122968108-dc068480-d393-11eb-8feb-7eef6af3bf94.png)

Design:
![image](https://user-images.githubusercontent.com/5177733/122968163-e88add00-d393-11eb-963b-76f9dda37831.png)

**Comment by kazaryan-t** [comment]
Checked.
Fixed the background image, now it looks taller.
