### ISSUE TITLE
Common - Add 'About' title above agenda

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#563]
missing "about" title
https://zpl.io/VO6MoEP

**Comment by roienatan** [comment]
I'm pretty sure in one of past issues it was requested to remove the "About" word.
Please verify @Taikaish @kazaryan-t @yanivi71

**Comment by kazaryan-t** [comment]
It was the issue - https://github.com/daostack/common-monorepo/issues/488 to remove the word "About" for mobile web due to the design - https://zpl.io/ann6Y5v.

**Comment by roienatan** [comment]
> It was the issue - #488 to remove the word "About" for mobile web due to the design - https://zpl.io/ann6Y5v.

So it should appear in desktop but not in mobile?

**Comment by Taikaish** [comment]
Yes

**Comment by roienatan** [comment]
@Taikaish There is inconsistency in the design. Please see this issue https://github.com/daostack/common-monorepo/issues/578.

**Comment by Taikaish** [comment]
Commented on the other issue (578) - this should solve it.
Both screens (mobile & desktop) should have the "About" title, it just has a different design.

**Comment by yanivi71** [comment]
Tested on web and mobile "about" title is added
