### ISSUE TITLE
Common card - there is should be more space between content selector and description card

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#564]
Please, fix according to design
<img width="725" alt="Screenshot 2021-06-07 at 10 59 18" src="https://user-images.githubusercontent.com/28015224/120981937-d8161800-c780-11eb-81e8-13e818a5cdd1.png">
https://app.zeplin.io/project/603377c3d4da061120ed2961/screen/603e2514054da0b1a926e23a

**Comment by yanivi71** [comment]
Tested on web site

more space between content selector and description card is added
