### ISSUE TITLE
Increase the spaces between images and description for previous image

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#569]
"What is common" section needs bigger spaces. It is hard to understand which illustration matches each paragraph.
The exact space size you can see in the design.

Design:
![Безымянный](https://user-images.githubusercontent.com/68247034/121010128-b11a0f00-c79d-11eb-9993-0ceffefb49e4.png)

**Comment by kazaryan-t** [comment]
1. Divide the text into rows as in the design.

![02 00 01 - full screen - Common Web - Zeplin - Goodf](https://user-images.githubusercontent.com/68247034/121136800-b4b1a280-c83e-11eb-80f7-af61c1a8fe0f.png)
![zsxd](https://user-images.githubusercontent.com/68247034/121137031-f2163000-c83e-11eb-99be-776c1b855b74.png)
![02 00 01 - full screen - Common Web - Zeplin - Goodfx](https://user-images.githubusercontent.com/68247034/121136802-b54a3900-c83e-11eb-8f5d-0c7d8944ed2a.png)
![02 00 01 - full screen - Common Web - Zeplin - Goosdfgh](https://user-images.githubusercontent.com/68247034/121136803-b5e2cf80-c83e-11eb-9305-ac3d4213ffd6.png)

**Comment by roienatan** [comment]
> 1. Divide the text into rows as in the design.
> 
> ![02 00 01 - full screen - Common Web - Zeplin - Goodf](https://user-images.githubusercontent.com/68247034/121136800-b4b1a280-c83e-11eb-80f7-af61c1a8fe0f.png)
> ![zsxd](https://user-images.githubusercontent.com/68247034/121137031-f2163000-c83e-11eb-99be-776c1b855b74.png)
> ![02 00 01 - full screen - Common Web - Zeplin - Goodfx](https://user-images.githubusercontent.com/68247034/121136802-b54a3900-c83e-11eb-8f5d-0c7d8944ed2a.png)
> ![02 00 01 - full screen - Common Web - Zeplin - Goosdfgh](https://user-images.githubusercontent.com/68247034/121136803-b5e2cf80-c83e-11eb-9305-ac3d4213ffd6.png)

@kazaryan-t @Taikaish  In this case I really don't think it's matter - it can be just in the desktop version.

**Comment by Taikaish** [comment]
Not sure I got this.
The exact point of the linebreak is less important, but I think the text is too small.
If the font-size and paragraph width are similar to the design, I think it should also linebreak at around the same point, right?

**Comment by kazaryan-t** [comment]
Checked.
