### ISSUE TITLE
Countdown not updating in proposal screen

### ISSUE THREAD

**Issue by BigRomanov** [daostack/common-backend#57]
The countdown is not updating in the proposal screen

**Comment by kazaryan-t** [comment]
The countdown starts to update when we scroll down and then scroll up the proposal screen.

Steps to reproduce:
1. Go to a proposal screen
2. Pay attention to a countdown
3. Scroll down the page (the countdown hides)
4. Scroll up the page (the countdown appears)
5. Pay attention to a countdown

Please look at the video.

https://user-images.githubusercontent.com/68247034/112457136-83abf080-8d6c-11eb-93a9-aa02486a1b50.mp4

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-255)
Tested on Staging Android version 1.9.5 (4978-216)

Found OK
countdown is started when opening view proposal

**Comment by yanivi71** [comment]
Verified on production
