### ISSUE TITLE
Common - Discussion - "Read more" button - should appear only if the text is longer than the text-box

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#570]
Steps to reproduce:
1. Explore commons
2. Go to common with discussion
3. Choose discussion with short description

Actual results:
"Read more" Appears
![image](https://user-images.githubusercontent.com/69141571/121010385-06eeb700-c79e-11eb-82af-0a7f0c73f9c5.png)

Expected results:
"Read more" button - should appear only if the text is longer than the text-box

**Comment by roienatan** [comment]
@yanivi71 What do you mean by "longer than the text-box"?
Which text box? How should we verdict whether to show/not show?

**Comment by roienatan** [comment]
@Taikaish Please clarify here 🙏

**Comment by Taikaish** [comment]
The maximum height for each discussion block is 23.438rem.

![image](https://user-images.githubusercontent.com/5177733/121162509-a4a5bd00-c856-11eb-918d-15e8b4f3ad7f.png)

It means that -
If there are 6 lines of text or less - we can show it in full and the "Read more" button is not needed.
If there 7 lines of text or more - we need to show the first 5 lines and add a "Read more" button.

**Comment by yanivi71** [comment]
@razoorka still not fixed . i can see the "Read more" but actually its the whole text.
Also i think that the size of the text aria is not one size. it is growing when there is more text.
Common "Email Common abc"
![image](https://user-images.githubusercontent.com/69141571/121864838-fdb59b00-cd05-11eb-811c-d4d63bad9893.png)

Common "T-Shirt"
![image](https://user-images.githubusercontent.com/69141571/121864975-1de55a00-cd06-11eb-96b1-c07261c66f1a.png)

**Comment by yanivi71** [comment]
@Taikaish @gingervik @kazaryan-t 
Now we do not display "Read more" at all, We are waiting fixes for these issues related to Responsiveness
https://github.com/daostack/common-monorepo/issues/550
https://github.com/daostack/common-monorepo/issues/643

**Comment by yanivi71** [comment]
@razoorka 
Hi, Now we do not see "read more" at all. 

if there are 6 lines of text or less - we can show it in full and the "Read more" button is not needed.
If there 7 lines of text or more - we need to show the first 5 lines and add a "Read more" button.

**Comment by razoorka** [comment]
@yanivi71 Can you provide the common where it was happening and your resolution?

**Comment by yanivi71** [comment]
The text area should not expand. When the button is clicked, the post should open in full, just like when clicking on "View discussion".
Basically, the button is another way to signal that what users see is not the full post and they should open it in full to continue reading.

**Comment by kazaryan-t** [comment]
_If there 7 lines of text or more - we need to show the **first 5 lines** and add a "Read more" button._

1. Actually, there are 6 lines displayed and then the button Read more appears (should be 5 lines of the text).
2. If the text fits in 6 lines, the button Read more is not needed (for example in the screenshot, the text in Hebrew is shown fully in 6 lines, the button is not needed).

![Common - Google Chrome 2021-06-24 15 48 58](https://user-images.githubusercontent.com/68247034/123265414-b4cec500-d503-11eb-974a-b0fe8fe23826.png)

**Comment by razoorka** [comment]
@Taikaish @kazaryan-t I'm sorry, but it is not possible to show different counts of the lines in different cases. Each person has his own resolution, text which fits the criteria will be different on 1368 and 1920 resolutions. So, please, could we show the same amount of lines in both cases? Can we leave current behavior ( 6 lines ), cause I have no idea, how to implement different counts of lines for different cases.

**Comment by gingervik** [comment]
Discussed with @Taikaish 
Acc to him "...Anyways, I think it works ok the it is today - not super important if it's 5/6/7"

**Comment by gingervik** [comment]
@kazaryan-t @yanivi71 if there is everything ok with all other cases about read button please close this task as done. Number of lines depends on user's resolution and etc.

**Comment by kazaryan-t** [comment]
The functionality is checked. 
Found ok.
