### ISSUE TITLE
Change the spaces in common summary.

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#577]
Design - https://zpl.io/addRPq7

Please set bigger the padding between the Common tagline or title and numbers (too close to the title), and set smaller the space between numbers and their description (numbers are too far away from their description).

![Screenshot_20210607-153216_Chrome](https://user-images.githubusercontent.com/68247034/121017193-acf1ef80-c7a5-11eb-896d-69a549c1908d.jpg)

**Comment by roienatan** [comment]
Same reported here https://github.com/daostack/common-monorepo/issues/574

**Comment by kazaryan-t** [comment]
1. All numbers (marked in red) should be in bold.
2. The font size for the words Available, Raised, Members, Proposals should be 0.75rem.
3. Implement the space between numbers and words Available, Raised, Members, Proposals as in the design (0.313rem).

![02 02 02 - common page - mobile screen size - CommLJH](https://user-images.githubusercontent.com/68247034/121356663-bad87980-c939-11eb-8c6d-d4b8ca4677f2.png)

![Безымянный - Paint 2021-06-09 14 55 21LKJ](https://user-images.githubusercontent.com/68247034/121356667-bb711000-c939-11eb-86ef-10ce553f6ad3.png)

**Comment by kazaryan-t** [comment]
Please, fix the position of the common summary, it should start on the same line as Common name, tagline, agenda, about, etc.

![Screenshot_20210610-234023_Chrome](https://user-images.githubusercontent.com/68247034/121651597-7668ed00-caa3-11eb-989b-5a32c6d18789.jpg)

![121356667-bb711000-c939-11eb-86ef-10ce553f6ad3](https://user-images.githubusercontent.com/68247034/121651733-9e585080-caa3-11eb-9e1a-c74004b14957.png)

**Comment by yanivi71** [comment]
Tested on mobile web site
Found OK.
Text is align
