### ISSUE TITLE
Add "Our Mission" before common description on the Agenda screen

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#578]
Add "Our Mission" before the common description on the Agenda screen. The exact font, font size, color etc, you can find in the design - https://zpl.io/ann6Y5v.

![02 02 01 - common page - Common Web - Zeplin - Goo](https://user-images.githubusercontent.com/68247034/121017776-520cc800-c7a6-11eb-9bbd-ebe5977b5373.png)

**Comment by roienatan** [comment]
@Taikaish @kazaryan-t @yanivi71 There is something inconsistent here, I guess it should be or "About" or "Our Mission".
See related issue here: https://github.com/daostack/common-monorepo/issues/563

**Comment by Taikaish** [comment]
I agree. In the app we use "About", let's keep it in the web version.

It means that in the mobile web we need to change "Our Mission" to "About". Let's keep the designs for both mobile and web, and only change the text.

I will ask Brio to update this screen accordingly: 
https://app.zeplin.io/project/603377c3d4da061120ed2961/screen/604103a1682480aea747d773

**Comment by kazaryan-t** [comment]
Please, implement the correct font size.
1. The words Agenda, Discussions, Proposals and History 
![agenda](https://user-images.githubusercontent.com/68247034/121147338-72419300-c849-11eb-8de4-ed968774f034.png)

2. The word **About** 
![about](https://user-images.githubusercontent.com/68247034/121147394-81284580-c849-11eb-85f2-4de95b4f2181.png)

3. Common description (under the word About)
![description](https://user-images.githubusercontent.com/68247034/121147567-a61cb880-c849-11eb-8988-9e786df393a7.png)

**Comment by kazaryan-t** [comment]
All elements should start at the same distance from the screen edge (Common name, tagline, the word available, the button Join the effort, Agenda tab, About, common description, links, etc.)

Actual:
![Screenshot_20210609-122009_Chrome](https://user-images.githubusercontent.com/68247034/121328761-498acd80-c91d-11eb-8fc2-c0c1d733199c.jpg)


Design:
![Безымянный - Paint 2021-06-09 12 16 56](https://user-images.githubusercontent.com/68247034/121328436-fe70ba80-c91c-11eb-99fb-53d6cc46d7e2.png)

**Comment by kazaryan-t** [comment]
Please, align the button "Join the effort" with the common summary (should be aligned in the center).

![IMG_0187](https://user-images.githubusercontent.com/68247034/121787792-f0e35b00-cbd0-11eb-8f61-3d1459c36a61.PNG)

![02 02 01 - common page - Common Web - Zeplin - Goo](https://user-images.githubusercontent.com/68247034/121787810-140e0a80-cbd1-11eb-954a-5c667bc59b4e.png)

**Comment by yanivi71** [comment]
Tested on Web site and mobile 
Found OK. 
"About " is display
The test is align
