### ISSUE TITLE
Join common section - Align the background photo

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#581]
Please, align the background photo as in the design (now we see only the man, but should be visible the woman too) and make waves at the top of the background photo very close to the design.
Design - https://zpl.io/Vq7kEvJ

![02 00 01 - full screen - Common Web - Zeplin - Goo](https://user-images.githubusercontent.com/68247034/121048360-6610f380-c7bf-11eb-8745-813a65caa9ef.png)

**Comment by yanivi71** [comment]
@razoorka still the images are not resemble to the design
Attached images from android and iPhone
![Screenshot_2021-06-14-11-20-33-418_com android chrome](https://user-images.githubusercontent.com/69141571/121861816-d7dac700-cd02-11eb-8e54-2814c4fedc26.jpg)
![File (69)](https://user-images.githubusercontent.com/69141571/121861823-d9a48a80-cd02-11eb-839c-55ad1f30dc44.jpg)

**Comment by yanivi71** [comment]
@gingervik @kazaryan-t @razoorka 
Images on the mobile still not resemble to the design.
On 375px width layout seems exactly like it was provided in design, but if the width is more then 375px then the images not resemble.
We are waiting for brio answer
