### ISSUE TITLE
Share Common - Facebook - The Share common link to a Common on Facebook doesn't redirect to the common

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#583]
Reported by Arava - Reproduced on android device
On production Ver 1.9.8 (6671-59)

Steps to reproduce:
1. Go to a Common
2. Click on the Share icon
3. Choose Facebook
4. Go to the Facebook  shared content and click on it (use Facebook app that installed on your device)

Actual results:
user redirect to common web site , even if the app is installed on the device

**Note : Also reproduced on iOS device** 

Expected results:
Users must be redirect to the shared common within the app

**Comment by IlyaDylko** [comment]
That's an old facebook/firebase issue. https://github.com/firebase/firebase-android-sdk/issues/916.
There is a possible solution for android. https://medium.com/@milan.jovic86/we-have-experienced-the-same-issue-in-our-app-i-e-ca4bce0adcc8. But I can't test it atm. I guess it's better to move it to backlog till firebase or facebook will come up with the universal solution. If it's not in high priority.
