### ISSUE TITLE
Proposal - Create proposal - When Funding amount is 0 the balance message app

### ISSUE THREAD

**Issue by BigRomanov** [daostack/common-backend#59]
https://daostack1.atlassian.net/browse/CM-1593

Tested on Staging iOS version 1.9.5 (4978-210)
Tested on Staging Android version 1.9.5 (4978-171)

Steps to reproduce:
1. Go to a common that you are a member
2. Create a proposal with no funds ($0)

Actual results:
proposal is created but contain the message "Other proposals might be accepted and ...."
see attached image

Expected results:
this message should not appear when proposal is 0

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-216)
Tested on Staging Android version 1.9.5 (4978-177)

found ok
message does not appear when proposal is 0

**Comment by yanivi71** [comment]
Verified on Production
