### ISSUE TITLE
Web - UI issues on Landing page 

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#590]
Design - https://zpl.io/Vq7kEvJ

1. Please, place **"Available on"** in the center and make it **in bold**.

![02 00 01 - full screen - Common Web - Zeplin - Goo852](https://user-images.githubusercontent.com/68247034/121344268-3d5a3c80-c92c-11eb-86a2-64da8508d7a5.png)

![02 00 01 - full screen - Common Web - Zeplin - Goonbvc](https://user-images.githubusercontent.com/68247034/121344274-3e8b6980-c92c-11eb-937b-b5a041b0f826.png)

2. Cut the phone image as in the design (in the design the phone image does not have the word Common)

![02 00 01 - full screen - Common Web - Zeplin - Goofgb](https://user-images.githubusercontent.com/68247034/121344305-48ad6800-c92c-11eb-9a2e-cfbadfdffa78.png)

**Comment by roienatan** [comment]
1. @Taikaish @kazaryan-t according the design in mobile it's bold and in desktop it's not. Is it a mistake or really should be different between mobile and desktop?

**Comment by kazaryan-t** [comment]
Checked.
