### ISSUE TITLE
Common -history - Proposal with no votes - Empty voting bar 

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#591]
Steps to reproduce:
1. Go a common with proposals in history
2. Find a proposal with no votes

Actual results:
There is no grey bar for 0 votes - see image
![image](https://user-images.githubusercontent.com/69141571/121357218-481bce00-c93a-11eb-9ad7-3c9cca1a7c47.png)

Expected results:
There should be a grey bar, for o votes - see attached design

![image](https://user-images.githubusercontent.com/69141571/121357434-7dc0b700-c93a-11eb-9e06-500ec3ea2975.png)

**Comment by kazaryan-t** [comment]
Checked.
The grey bar with _No votes yet_ text appears.
