### ISSUE TITLE
Web mobile - Home page - Contact form - needs more space

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#593]
Steps to reproduce:
1. Open the mobile web
2. go to home page
3. scroll down to contact

Actual results:
needs more space in the "contact" form
![image](https://user-images.githubusercontent.com/69141571/121469906-fae53e00-c9c5-11eb-80f2-c15780f4e0a3.png)

Expected results:
see design
https://zpl.io/Vq7kEvJ

**Comment by kazaryan-t** [comment]
Please, reduce the padding between the envelope icon +**hi@common.io** email and **Your name** field.

![IMG_0194](https://user-images.githubusercontent.com/68247034/121788771-ad8cea80-cbd8-11eb-9d55-6f924c248f01.PNG)

![Безымянный - Paint 2021-06-12 23 46 58](https://user-images.githubusercontent.com/68247034/121788786-c4cbd800-cbd8-11eb-95c7-9b342e210be9.png)

**Comment by yanivi71** [comment]
Tested on web site 
Found OK
Contact form - appears with more space as the design
