### ISSUE TITLE
Web - Explore commons title

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#595]
Design - https://zpl.io/Vx4Wjkk
Change the font-weight of **Explore commons** title (should be 600, now it is 700).

![01 01 02 Explore commons - Common Web - Zeplin - G](https://user-images.githubusercontent.com/68247034/121478337-962fe080-c9d1-11eb-9062-4041aa2d458f.png)

**Comment by roienatan** [comment]
The styles in the side in Zeplin are not always necessary and I guess they are generated automatically. 
The most important thing here is the font family which as in the design. You can also see a screenshot of the app and the design - it looks identical. I'm closing the issue unless you still think it's a mistake and we can discuss about it. 

<img width="389" alt="Screen Shot 2021-06-10 at 15 54 55" src="https://user-images.githubusercontent.com/34843014/121547654-3b63ac80-ca04-11eb-85ab-52f347f46472.png">
