### ISSUE TITLE
Web - Explore commons - Common title in Hebrew 

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#596]
Design - https://zpl.io/Vx4Wjkk

Please, implement the correct font for the common titles in Hebrew, it should be Assistant Bold.

![01 01 02 Explore commons - Common Web - Zeplin - G](https://user-images.githubusercontent.com/68247034/121479067-55849700-c9d2-11eb-8ad5-e09251aa0e30.png)

**Comment by roienatan** [comment]
@Taikaish Is it correct to use a different font for different language? Sounds weird to me.

**Comment by Taikaish** [comment]
Usually better to use the same font but It's tricky with Hebrew, there are very few fonts that look good in both languages.

**Comment by yanivi71** [comment]
Tested on web site and found OK
font in Hebrew is changed
![image](https://user-images.githubusercontent.com/69141571/122808828-098cf880-d2d6-11eb-852a-117b97d6be3c.png)

**Comment by Taikaish** [comment]
Fix required:

In Hebrew:
The font used for the name of the common (title) is correct.
The font used for the tagline (sub title) is wrong.

![image](https://user-images.githubusercontent.com/5177733/122968872-ac0bb100-d394-11eb-9ac3-52c2ca1993ea.png)

The right font appears here:
https://app.zeplin.io/project/603377c3d4da061120ed2961/screen/6033856688f05210f6ced424

CSS from Zeplin:
  width: 15.25rem;
  height: 2.5rem;
  margin: 0.313rem 0 0;
  text-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
  font-family: Assistant;
  font-size: 0.75rem;
  font-weight: 300;
  font-stretch: normal;
  font-style: normal;
  line-height: 1.33;
  letter-spacing: normal;
  text-align: center;
  color: #ffffff;

**Comment by kazaryan-t** [comment]
Seems that the font family for the tagline in Hebrew is not fixed. 
Should be **Assistant-Light**.

![Безымянный](https://user-images.githubusercontent.com/68247034/123296975-c920bb00-d51f-11eb-8743-4f030487af32.png)

@Taikaish, clarify please if we should implement the same font family for common name and tagline in Hebrew on the common agenda page. Actually, the font family used for Hebrew on the common agenda page is the same as for Latin.

@roienatan, please, let me know if I am mistaken. 

![Common - Google Chrome 2021-06-24 18 53 05](https://user-images.githubusercontent.com/68247034/123296926-bf975300-d51f-11eb-9449-b777c45bf70c.png)

![Common - Google Chrome 2021-06-24 18 53 50](https://user-images.githubusercontent.com/68247034/123296929-c02fe980-d51f-11eb-8b05-0d66b0a1d8b1.png)

**Comment by yanivi71** [comment]
tested on the web site. and found Ok
font-family: Assistant-Light;
![image](https://user-images.githubusercontent.com/69141571/123757046-3b99ee00-d8c6-11eb-88a2-2d9defad68ca.png)
