### ISSUE TITLE
Web - Landing page - Increase the Leverage trust section

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#597]
Leverage trust section on the Landing page should be bigger.

Design - https://zpl.io/2GDR54J

**Comment by kazaryan-t** [comment]
Please, raise the half phone image as in the design.

![Безымянный - Paint 2021-06-21 13 22 21](https://user-images.githubusercontent.com/68247034/122747453-bdb95f80-d293-11eb-8751-96b9177a4d9e.png)

**Comment by kazaryan-t** [comment]
Сhecked.
Found OK.

**Comment by Taikaish** [comment]
Fix required:

Make the top & bottom padding 1.5-2X higher.
The section should be bigger, with more space above and below the text.

**Comment by kazaryan-t** [comment]
Remove the marked line above the section.

![Common - Google Chrome 2021-06-24 18 37 40](https://user-images.githubusercontent.com/68247034/123291790-1cdcd580-d51b-11eb-9f7d-0ddb7bf4706b.png)

**Comment by kazaryan-t** [comment]
Checked.
Found ok, the section is increased, the line is removed.
