### ISSUE TITLE
Web Mobile - Download common popup - size is  too small

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#598]
Steps to reproduce:
1. go to discussion
2. Click on read more/ view discussion
3. look at the download pop up

Actual results:
The download pop up  is too small
![image](https://user-images.githubusercontent.com/69141571/121487467-c9c33880-c9da-11eb-8df5-8c31b1d22565.png)

Expected results:
See design 
https://app.zeplin.io/project/603377c3d4da061120ed2961/screen/6041053dc7f90dad234961d7

**Comment by kazaryan-t** [comment]
When Download common popup opens there is a non-shaded part on the page appears.
Remove the non-shaded area of ​​the screen (look at the screenshots).
Look in the design https://zpl.io/be9zolW how it should be.

![IMG_0192](https://user-images.githubusercontent.com/68247034/121788656-97325f00-cbd7-11eb-834c-b17a660af69f.PNG)
![IMG_0193](https://user-images.githubusercontent.com/68247034/121788657-97caf580-cbd7-11eb-9a5e-936d57928b36.PNG)

**Comment by yanivi71** [comment]
Tested on Web site and found OK

**Comment by Taikaish** [comment]
Fix required:

The height of the popup is still too small.
See the design:
https://app.zeplin.io/project/603377c3d4da061120ed2961/screen/6041053dc7f90dad234961d7

Height should be 20.125rem

**Comment by kazaryan-t** [comment]
1. On iPhone a non-shaded part still appears.
2. Make smaller the purple part of the popup, should be more of a white part.

![02 02 05 - join common popup - Common Web - Zeplin](https://user-images.githubusercontent.com/68247034/123259801-94037100-d4fd-11eb-8a11-827982d5cf26.png)

![Screenshot_20210624-145427_Chrome](https://user-images.githubusercontent.com/68247034/123258955-a335ef00-d4fc-11eb-8cdb-2e5861d207cd.jpg)
![IMG_0198](https://user-images.githubusercontent.com/68247034/123258920-99ac8700-d4fc-11eb-9a8f-419dd9b9b825.PNG)

3. Need to discuss with @Taikaish.
I couldn't find the design for the popup that appears when clicking in **Join the effort** button.

Now it looks like this, is it ok or we should make it bigger like the previous popup?
![IMG_0197](https://user-images.githubusercontent.com/68247034/123259416-1ccddd00-d4fd-11eb-9535-459d877db8e5.PNG)

**Comment by roienatan** [comment]
1. Can't reproduce on my iPhone (XR).
2. DONE
3. This is the design - https://app.zeplin.io/project/603377c3d4da061120ed2961/screen/6041053dc7f90dad234961d7
I see no reason why the text itself should be changed from the desktop version. So either the correct text is of the mobile version or the desktop version.

**Comment by kazaryan-t** [comment]
№2 not fixed.
Still need to increase the white part of the popup.
