### ISSUE TITLE
Proposal - Create proposal - Funding amount is not limited and amount display incorrectly

### ISSUE THREAD

**Issue by BigRomanov** [daostack/common-backend#60]
https://daostack1.atlassian.net/browse/CM-1586

Tested on Staging iOS version 1.9.5 (4978-207)
Tested on Staging Android version 1.9.5 (4978-168)

Steps to reproduce:
1. Go to a common that you are a member
2. Create a new proposal
3. enter amount with many numbers

Actual results:
The amount and the conversion amount display incorrectly - see attached image

Expected results:
The amount should be limit to 4-5 digits

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-216)
Tested on Staging Android version 1.9.5 (4978-177)

Found OK
The amount is limited

**Comment by yanivi71** [comment]
Verified on Production
