### ISSUE TITLE
Web - Landing page - UI issues footer

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#600]
Design - https://zpl.io/2GDR54J

1. Change the size of the common logo and the word COMMON as in the design.
![Безымянный - Paint 2021-06-10 11 21 57](https://user-images.githubusercontent.com/68247034/121491126-591e1b00-c9de-11eb-9223-0b323c434a83.png)
![Безымянный - Paint 2021-06-10 11 22 40](https://user-images.githubusercontent.com/68247034/121491129-59b6b180-c9de-11eb-8603-ea44031f1346.png)

2. Fix the space between the common logo with the word COMMON and tab About (8.75 rem).
![Безымянный - Paint 2021-06-10 11 23 20](https://user-images.githubusercontent.com/68247034/121491304-7f43bb00-c9de-11eb-8914-6500279ef2c0.png)

3. Fix the space between the tabs (2.5 rem).
![Безымянный - Paint 2021-06-10 11 21 00](https://user-images.githubusercontent.com/68247034/121491465-a5695b00-c9de-11eb-9685-950740823cea.png)

**Comment by Taikaish** [comment]
Fix required: 

The footer links currently spread across most of the browser width.
The design is different:
https://zpl.io/VQJloRW

There should be a fixed margin of 2.5rem between each link, and the entire link section should be centered.

![image](https://user-images.githubusercontent.com/5177733/122969869-d6aa3980-d395-11eb-857e-a2ec42dd2c5a.png)

**Comment by kazaryan-t** [comment]
Checked.
The links are centered and the fixed margin between each link is 2.5rem.
