### ISSUE TITLE
Web - Explore commons - Common - Proposals - requested amount box is too wide

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#603]
Steps to reproduce:
1. Choose a common with proposals
2. Go to proposal / history
3. look at the requested amount box

Actual results:
requested amount box is too wide
![image](https://user-images.githubusercontent.com/69141571/121495418-473e7700-c9e2-11eb-98e6-67937e948b74.png)

Expected results:
See design
https://app.zeplin.io/project/603377c3d4da061120ed2961/screen/60365d92bbe907be4768b679

**Comment by kazaryan-t** [comment]
Checked.
