### ISSUE TITLE
Web - Agenda - Add Join the effort and Share button

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#604]
Design - https://zpl.io/VO6MoEP
Please, add the **Join the effort** and **Share** buttons on the Agenda page of the common.

![01 02 01 Common page - Agenda - Common Web - Zepli](https://user-images.githubusercontent.com/68247034/121494867-cbdcc580-c9e1-11eb-8100-717cb237b25d.png)

**Comment by yanivi71** [comment]
Testes on web site and found OK
Join the effort and Share button are added to the agenda
