### ISSUE TITLE
Web - UI fixes of Share menu

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#605]
Design - https://zpl.io/2jgmBx6

1. Please, increase the padding from the bottom of the Share menu.

![Безымянный - Paint 2021-06-10 12 35 24](https://user-images.githubusercontent.com/68247034/121501764-309b1e80-c9e8-11eb-91ed-44d93fe6cb17.png)

2. Move the Share menu to the right, it should end beyond the image line (look at the screenshot).

![01 02 03 Common page - Agenda - Share popup - Comm](https://user-images.githubusercontent.com/68247034/121502369-c9ca3500-c9e8-11eb-86a1-18ea0494f13c.png)

**Comment by roienatan** [comment]
2 - I think it's better to have the popup inside the content borders so in smaller screen it'll not be hidden. Note that the design shows you fixed screen size.

**Comment by kazaryan-t** [comment]
Marked paddings should be the same size (1.5 rem).
Now the side paddings are larger than the bottom paddings.

![Common - Google Chrome 2021-06-22 17 16 38](https://user-images.githubusercontent.com/68247034/122941825-68a64800-d37e-11eb-8247-22918bb0c361.png)

**Comment by roienatan** [comment]
The paddings are exactly the same, the difference is a 10px margin of the first and the last links. Will be fixed in the coming fix soon.

**Comment by kazaryan-t** [comment]
Checked.
