### ISSUE TITLE
Web - Common - Proposals - empty-  Spaces from the top should be bigger, text box is too wide

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#606]
Steps to reproduce:
1.Explore commons
2.  Go to a common with no proposal that has About (e.g T-Shirt)

Actual results:
Spaces from the top should be bigger, text box is too wide
![image](https://user-images.githubusercontent.com/69141571/121504828-fb440000-c9ea-11eb-80a2-db02c05653b3.png)

Expected results:
See design
https://app.zeplin.io/project/603377c3d4da061120ed2961/screen/60363650cd2b612dac9874d3

**Comment by kazaryan-t** [comment]
Checked.

**Comment by Taikaish** [comment]
Fix required:

The bottom margin should also be bigger, similar to the top margin (7.25rem)

**Comment by kazaryan-t** [comment]
Checked.
Added the paddings on the top and at the bottom
