### ISSUE TITLE
Web - Explore commons - Common - Discussion - gap from the top when scrolled

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#607]
Steps to reproduce:
1. Go to a common with discussion (E.G "Email Common abc")
2. Go to discussion with many chats
3. Click on view discussion
4. Scroll the chat window

Actual results:
There is a gap from the top when scrolled
![image](https://user-images.githubusercontent.com/69141571/121505686-b4a2d580-c9eb-11eb-9964-9b11650d3afc.png)

Expected results:
No gap should be display. See design
https://app.zeplin.io/project/603377c3d4da061120ed2961/screen/60365ed9f8f74429cc52d1eb

**Comment by kazaryan-t** [comment]
Please, add the scrolling bar for the chats with many comments.

![01 04 02 Common page - Proposals full view - 1st t](https://user-images.githubusercontent.com/68247034/121788870-c2b64900-cbd9-11eb-8a71-187dbb87934c.png)

**Comment by yanivi71** [comment]
Tested on website and found OK
