### ISSUE TITLE
Web - Chats - Align the time

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#609]
Design - https://zpl.io/2EnEwOM

1. Please, align the time in the comments, it should be aligned to the bottom of the content.
2. Add an additional space from the left (two columns).

![01 03 03 Common page - Discussions full view - 1st](https://user-images.githubusercontent.com/68247034/121520570-baa0b280-c9fb-11eb-8ac8-3174e9f4e0d4.png)
![Безымянный - Paint 2021-06-10 14 53 48](https://user-images.githubusercontent.com/68247034/121520573-bbd1df80-c9fb-11eb-9cc5-2c1548ef6b43.png)

**Comment by kazaryan-t** [comment]
№1 not fixed.
The time should be placed in the same line as the last row of the comment.

![Common - Google Chrome 2021-06-10 23 13 17](https://user-images.githubusercontent.com/68247034/121591258-ef375d00-ca41-11eb-9a5e-94992aab9b23.png)

![Безымянный - Paint 2021-06-10 14 53 48](https://user-images.githubusercontent.com/68247034/121591315-024a2d00-ca42-11eb-80f5-3080e7527fe9.png)

**Comment by yanivi71** [comment]
Tested on web site and found Ok
Time is align
