### ISSUE TITLE
Web - Fix the arrow padding 

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#612]
Design - https://zpl.io/VO6MoEP

Fix the arrow padding in the Latest Proposals and Latest Discussions tabs.

![Безымянный - Paint 2021-06-10 15 24 50](https://user-images.githubusercontent.com/68247034/121524301-d908ad00-c9ff-11eb-9e75-de6ab54df594.png)

**Comment by razoorka** [comment]
Right padding has been increased, Y coordinate stayed the same,on the center of the block
