### ISSUE TITLE
Web - Change the size of cards

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#618]
Need to fix **cards size** according to the design. 
The cards on the pages Agenda, Discussions, Proposals, and History are too wide.
Please, check the correct size of cards in the designs.

Agenda - https://zpl.io/VQ6LWL4
Discussion - https://zpl.io/bJM3G69\
Proposals - https://zpl.io/an5ZQGQ
History - https://zpl.io/VO6MW1L

1. Basically, all these cards end on the same line where the **Available Funds** section starts.

![01 04 01 Common page - Proposals - Common Web - Ze](https://user-images.githubusercontent.com/68247034/121642290-ffc6f200-ca98-11eb-8562-280fd5b866ec.png)
![01 05 01 Common page - History - Common Web - Zepl](https://user-images.githubusercontent.com/68247034/121642297-02294c00-ca99-11eb-8062-34da1c72420f.png)
![Common - Google Chrome 2021-06-11 09 22 07](https://user-images.githubusercontent.com/68247034/121642298-02294c00-ca99-11eb-92d2-ede326c3a57a.png)
![Common - Google Chrome 2021-06-11 09 32 52](https://user-images.githubusercontent.com/68247034/121642300-02c1e280-ca99-11eb-9db7-165b9b3ea415.png)

**Comment by razoorka** [comment]
The size of cards depends on the resolution, it is not a good idea to make it static.

**Comment by roienatan** [comment]
> The size of cards depends on the resolution, it is not a good idea to make it static. 

I agree, but we should have a max-width at least I think
