### ISSUE TITLE
Migration TODO - Move IEntity from Firebase to Graphql

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#634]
Entities that are in Firebase/EntityTypes, should be removed and redefined in Graphql directory
e.g. from `Firebase/EntityTypes/IUserEntity` to  `Graphql/User/UserType.ts`

By the end of this process, we should not have the Firebase directory at all.

**Comment by watchtower314** [comment]
@MeyerPV is this about migration, or about cleaning the code? can we do this on sprint 8 instead of sprint 7?

**Comment by MeyerPV** [comment]
> @MeyerPV is this about migration, or about cleaning the code? can we do this on sprint 8 instead of sprint 7?

Hi, it's done. I will create PR after merging my PR about moderation
