### ISSUE TITLE
Notification - Notification issues

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#64]
Link to Jira: https://daostack1.atlassian.net/browse/CM-1596?atlOrigin=eyJpIjoiYWFhZjU3NTQ4ZDMwNDE0ZTgzNzRiNTcxNDVmMmZkMjEiLCJwIjoiaiJ9

Tested on Staging iOS version 1.9.5 (4978-212)Tested on Staging Android version 1.9.5 (4978-173)

Steps to reproduce:1. Accept Membership of user who request to join your common2. Go to a common and create a new post3. Simlulate conversation with more the 5 notification for a member

Actual results:1. No Notification for "Your membership request was accepted"2. No notification for Create a new post3. There is no limitation foe messages

Expected results:1. Notification for accept membership2. Notification foe create a new post3. limitation of 5 messages to a member in the common

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-232)
Tested on Staging Android version 1.9.5 (4978-193)

Found OK
1. Notification for accept membership- OK
2. Notification for create a new post - OK
3. limitation of 5 messages to a member in the common - OK

**Comment by yanivi71** [comment]
Verified on production
