### ISSUE TITLE
Apple emails - Private Email Relay Service investigation

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#672]
We need to have ability to send emails to our users who logged via AppleID and hide their emails.
Please, see more info here https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/communicating_using_the_private_email_relay_service

**Comment by Jan-Blarky** [comment]
![image](https://user-images.githubusercontent.com/69893042/123608549-83a60b80-d807-11eb-9c65-93136795a3e5.png)
