### ISSUE TITLE
Web - Chat - on Windows, hide scroll bars when no scroll is needed

### ISSUE THREAD

**Issue by Taikaish** [daostack/common-backend#693]
1. When no scrolling possible, scroll bars should not appear.

![image](https://user-images.githubusercontent.com/5177733/123075803-37cb1f00-d421-11eb-8300-fb9400fee5d5.png)
![image](https://user-images.githubusercontent.com/5177733/123075612-0ce0cb00-d421-11eb-9f34-e4b4a25ab11a.png)

2. When scrolling is possible, we should use our scroller design and not the default one.

**Comment by razoorka** [comment]
@Taikaish  Custom scrollbars are not supported in Firefox and in Edge. Unnecessary scrolls were removed.

**Comment by yanivi71** [comment]
Tested on Chrome ,Firefox, edge browsers
scrollbars where removed.
@Taikaish what about the chat window? if there are many comments there is no indication for scroll bars. when user is scroll the mouse wheel he see the rest of the comments. is it OK?
