### ISSUE TITLE
Landing page - Inactive buttons for downloading the app

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#699]
Please, enable the buttons for downloading the app on the Landing page.

![Common - Google Chrome 2021-06-28 13 25 41](https://user-images.githubusercontent.com/68247034/123621776-3e3c0b00-d814-11eb-92d8-5f93b0300cce.png)

**Comment by yanivi71** [comment]
Tested on web site and found ok.
The buttons for downloading the app are enable
