### ISSUE TITLE
Change the name of the "Monthly Contributions" to "Billing".

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#713]
Change the name of 

1. the "Monthly Contributions" screen and 
2. link on "My Profile" 

to "Billing".

https://zpl.io/beqO1oY
<img width="250" src="https://user-images.githubusercontent.com/28015224/125902813-acab956a-9ccf-4e89-8255-017aaddc44eb.png">

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.7 (10-307)
Tested on Staging Android version v1.0 (391)
Found OK
"Monthly Contributions"  changed to "Billing"
