### ISSUE TITLE
Update/Change Payment method details behaviour [S11-03]

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#716]
* In the billing details screen - https://zpl.io/aBQWZzK

* The form for replacing card details: https://zpl.io/2jy80Lq

* Notification that payment method was updated: https://zpl.io/2yo7zYq

BE part: https://github.com/daostack/common-backend/issues/1226

**Comment by ariel-dao** [comment]
@HannaMaklakova 
`Notification to update payment methods for users who still have circle payment method: https://zpl.io/ag79LoR`

this should be a separate task

**Comment by HannaMaklakova** [comment]
> @HannaMaklakova `Notification to update payment methods for users who still have circle payment method: https://zpl.io/ag79LoR`
> 
> this should be a separate task

reopened it https://github.com/daostack/common-backend/issues/1158. I've created separate one but Moore said that we can combine them

**Comment by ariel-dao** [comment]
> > @HannaMaklakova `Notification to update payment methods for users who still have circle payment method: https://zpl.io/ag79LoR`
> > this should be a separate task
> 
> reopened it #1158. I've created separate one but Moore said that we can combine them

Specifically circle requires a different approach, thanks

**Comment by yanivi71** [comment]
@IlyaDylko @watchtower314 
1. The card aria is too big there is a big gap between the fields. user does not see the whole page and the scroll is damaged
2. first name, family name,  expiration card date are missing
![image](https://user-images.githubusercontent.com/69141571/162805661-226359c4-9225-455b-8d98-d4fc321bf301.png)
3. wrong route at the top
![image](https://user-images.githubusercontent.com/69141571/162805951-04e33b3e-ddbe-409d-b1cc-8ead7407f79e.png)
4. the card image always display as Mastercard even though i insert visa
5. pop up display "Ok" instead of "OK"

**Comment by watchtower314** [comment]
@HannaMaklakova can you please get Visa icon from brio?

**Comment by watchtower314** [comment]
@yanivi71 can you please provide more details, I cannot reproduce on my end

<img width="358" alt="Screen Shot 2022-04-12 at 18 33 45" src="https://user-images.githubusercontent.com/30501647/162999557-4c6d8003-0d86-4562-b891-bebbb12c695e.png">

**Comment by HannaMaklakova** [comment]
> @HannaMaklakova can you please get Visa icon from brio?

Okay!

**Comment by HannaMaklakova** [comment]
@watchtower314 please find the icon [here](https://www.figma.com/file/9tLpH4g7ac8HGaRX1Ej5WT/Library----Common-v1.0?node-id=790%3A2713)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.11.3 (17-317)
Tested on Staging Android version v1.0 (402)
found ok
@watchtower314 @IlyaDylko @MeyerPV the images contain now visa and Mastercard, but there are more cards like : American express , Diners etc. and there are no images for them. it display master card. please advice
