### ISSUE TITLE
Email notification to confirm that we added/replace the card 

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#719]
waiting for templates from @Taikaish

**Comment by Taikaish** [comment]
Thanks @gingervik !

We need two email templates:

1. After a method was saved (1st time):

"
Subject: Your payment method was saved

Hello {User first name},

Your payment method was successfully saved. You will be able to use it for future contributions without entering the details again. 

For more information you can contact us any time using our {support chat link}.

Common,
Collaborative Social Action.
"

2. After a method was changed:
"
Subject: Your payment method was updated

Hello {User first name},

Per your request, your payment method was updated successfully.

For more information you can contact us any time using our {support chat link}.

Common,
Collaborative Social Action.
"
