### ISSUE TITLE
Send notification on request to join

### ISSUE THREAD

**Issue by alexander2001i** [daostack/common-backend#72]
When a user creates a new join request send a new notification to all members of the common

**Comment by watchtower314** [comment]
I think @Taikaish wanted the notification to only be sent to the founder of the common

**Comment by Taikaish** [comment]
Right. Should be sent only to Moderators (currently the founder and soon maybe a couple more members we promote to moderator manually).

**Comment by kazaryan-t** [comment]
Checked.

The notifications New member are sent only to the moderator of the common as @Taikaish specified.
