### ISSUE TITLE
Let users delete commons

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#722]
- Let users delete commons if they are the only member. 
Only if there is 1 member (not more) -
As part of the moderation menu, **add: "Delete Common"**.
https://zpl.io/a3mAKYN
<img width="250" src="https://user-images.githubusercontent.com/87295860/126188591-a5024354-c014-4416-98cc-3f0006332d21.png">

- If clicked, show a message:
"Are you sure?
If you delete this Common the data will be erased. You can not restore your Common once you delete it."
And two buttons: [ Cancel ] [ Delete Common ]
https://zpl.io/VQPR9Jm
<img width="250" src="https://user-images.githubusercontent.com/87295860/126283917-7606a877-b3c3-477e-825d-aa601b30ee43.png">

- If deleted, show a confirmation message:
"Common deleted successfully" with a button: "Ok"
https://zpl.io/bzQ61dG
<img width="250" src="https://user-images.githubusercontent.com/87295860/126284597-aafa3e6c-12ba-48ca-954d-393cfcf4562a.png">

**Comment by IlyaDylko** [comment]
**Waiting for the design update**

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.7 (10-307)
Tested on Staging Android version v1.0 (391)
found ok.
common with 1 member only is deleted
