### ISSUE TITLE
Voting - Allow users to see what they voted for

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#726]
Allow users to see what they voted for:
https://zpl.io/2ZRnDeL

1. If you click 'approve' -> Can see "Vote to approve" and "Cancel"
https://zpl.io/VKOJ43P

2. Loading: https://zpl.io/YYdqXyM

3. Your vote is approved
https://zpl.io/VQ6zoJP

4. If you click 'reject' -> Can see "Vote to reject" and "Cancel"
https://zpl.io/V4gjPXQ

5. Loading: https://zpl.io/ew83Wdm

5. Your vote is rejected
https://zpl.io/1ykxpMm

**Comment by IlyaDylko** [comment]
assigned to me

**Comment by IlyaDylko** [comment]
**Waiting for the loading screen improvement from the designers.**

**Comment by IlyaDylko** [comment]
This is a duplicate task. Me and Pavel have already done that.
