### ISSUE TITLE
Members - History tab - add a card "Created this Common

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#732]
Please, add a card to the history tab of the Members section.
Instead of "Approved", it should say "Created this Common".
The amount should be displayed as well, but there wouldn't be any voting indications.
There should be a lighter version of the proposal screen, without voting indications or intro text.
**Pay attention to monthly contribution**
<img width="287" alt="Screenshot 2021-07-21 at 17 39 20" src="https://user-images.githubusercontent.com/28015224/126507558-66e70b75-08d6-4e5c-aea8-0ca28b39aaa6.png">
https://zpl.io/VY6Nk4L

**Comment by HannaMaklakova** [comment]
not relevant
