### ISSUE TITLE
Notification - when user open notification App is stuck and user see a white screen.

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#74]
Tested on Staging iOS version 1.9.5 (4978-212)
Tested on Staging Android version 1.9.5 (4978-173)

Steps to reproduce:
1. Get notification
2. In ios - Slide to right and click open - see attached video
3. in android just click on the notification

Actual results:
App is stuck and user see a white screen.

Expected results:
User should navigate to the notification location within the app

https://user-images.githubusercontent.com/69141571/107661919-6a565580-6c92-11eb-91c1-db14b70a5364.mp4

**Comment by watchtower314** [comment]
This is the error that is showing; the discussion/comment/proposal was created in the database, but we are not subscribed to their changes
<img width="555" alt="Screen Shot 2021-02-28 at 12 35 30" src="https://user-images.githubusercontent.com/30501647/109427673-76941f80-79c1-11eb-84dd-005184a430ad.png">

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-233)
Tested on Staging Android version 1.9.5 (4978-194)

1. When clicking on Push notification for a new proposal, the user sees a white screen (iOS and Android).
2.  When clicking on notification for a new proposal from the Notification tab the app on Android crashes.

**Comment by watchtower314** [comment]
This is caused due to `navigationRef.current` that is undefined, hence cannot dispatch navigation

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-236)
Tested on Staging Android version 1.9.5 (4978-197)

@lpetkov-sw 
1. The notification on android always redirect to common list (when app is closed or open)
2. the notification on ios  when app is closed it redirect to common list . when app is open it redirect to the correct position

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-239)
Tested on Staging Android version 1.9.5 (4978-200)

Found ok
User is navigate to the notification location within the app.
Note that in android when the app is closed the user will be redirect to common list. This is the behaviour in android

**Comment by yanivi71** [comment]
Verified on Production
