### ISSUE TITLE
Back-end: Synchronize Back-end "ReportFor" with Front-end/Mobile Report Reasons

### ISSUE THREAD

**Issue by MeyerPV** [daostack/common-backend#787]
Also fix the typo in back-end - `ViolAnce` to `ViolEnce`

Front-end:
<img width="298" alt="Screenshot 2021-08-31 at 11 48 25" src="https://user-images.githubusercontent.com/35873164/131472390-2a457701-4697-45fe-93a0-b7d7de708872.png">

Back-end:
<img width="279" alt="Screenshot 2021-08-31 at 11 48 38" src="https://user-images.githubusercontent.com/35873164/131472427-573735bb-c065-44d6-9210-596bf1db114e.png">

**Comment by SobolevYuri** [comment]
no more relevant
