### ISSUE TITLE
Missing information on web after migration

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#797]
Tested on https://web1staging.common.io/

**1. The attached links are not displayed in the commons**
Common to check - https://web1staging.common.io/commons/c188816a-7b2a-4a55-b1a0-54d0dd9d400a

![Common - Google Chrome 2021-09-09 18 23 00](https://user-images.githubusercontent.com/68247034/132714384-e526cb5d-e5d2-4760-82c3-45b3f730e2e2.png)
![Common page - Agenda · Issue #412 · daostack_commo](https://user-images.githubusercontent.com/68247034/132714393-1084c8d2-c82e-49e6-8f88-876475360d87.png)

**2. On the discussions screen:**

**- the date of creation is displayed incorrect (NaN days ago);**

**- the member's avatar is not displayed.**

![Common - Google Chrome 2021-09-09 15 29 08](https://user-images.githubusercontent.com/68247034/132714696-4bfc48c6-11fc-4027-8802-4814ede6db87.png)

**3. On the History screen the amount of rejected proposals is incorrect (in the screenshot there are at least 2 rejected proposals but the number is 0)**

![Common - Google Chrome 2021-09-09 15 28 33](https://user-images.githubusercontent.com/68247034/132715598-913cbb9a-1f1a-47d4-bb7e-6e58cf67eab2.png)

**4. On the Explore commons page, common's taglines are not displayed.**

![Common - Google Chrome 2021-09-09 18 29 37](https://user-images.githubusercontent.com/68247034/132715485-bbc97254-4d05-4fe7-9076-207f0fc35779.png)

**Comment by Jan-Blarky** [comment]
**1) attached links:**
I inspected PgSQL database and didn't find any object that have not empty field "links". 
On the screenshot you can see common with name "Andromeda", but every 332 common object doesn't have any links attached.
![image](https://user-images.githubusercontent.com/69893042/135760874-eef670a3-86b4-4592-b235-40094316c43a.png)

**2) date of creation:**
Everithing is on place and working
![image](https://user-images.githubusercontent.com/69893042/135760990-ef66eb95-9669-4d97-b092-d4cda8522435.png)

**3) avatar problem**
 i'll continue researching. It seems that there are problems in connecting to the firestore there this pictures are storing.
 
**4) Proposals** 
history is also absolutely on place and working correctly
![image](https://user-images.githubusercontent.com/69893042/135761379-b76ec480-4fc8-48e6-878e-2423a492793e.png)

**5) tags** 
i didn't found any info there they must be stored, in the db they are not traceble.

*P.S. there were a little bit adds from Yaniv:*

**6) discussions and commons**
Database contains 332 records of commons objects and 64 records of discussions. and all of them are created after 2021-06-15.
![image](https://user-images.githubusercontent.com/69893042/135761796-9b8d19ca-17e5-4e95-814f-edbd50ff0120.png)
example of common objects (!look at the creation date!)
![image](https://user-images.githubusercontent.com/69893042/135761876-84f12c37-8c7c-41fb-a9eb-c06b594f97c6.png)
example of discussion objects (!look at the creation date!)
![image](https://user-images.githubusercontent.com/69893042/135761889-080835df-1f50-4035-8c16-745aa763a6b7.png)

**7) images of commons**
like at number 3 - avatar problem, i think it's problem of accessing to firestore, will check it.

**Comment by Jan-Blarky** [comment]
to the number (3) and (7) I checked, connections with firestore is working correctly.
