### ISSUE TITLE
Common - View request - Click on the link - user does not redirect with android device

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#80]
Tested on production

Steps to reproduce:
1. Go to production to "common X"
2. click on members 
3. click on history
4. view request from "Tal Yaron"
5. Click on the link from ios device
6. Click on the link from android device

Actual results:
Ios - redirect to the link - see attached video
Android - Does not and display error message on the screen - see attached video

Expected results:
User should be redirect to the attached link

https://user-images.githubusercontent.com/69141571/107942725-52354d80-6f94-11eb-844b-e861e115bba1.mp4

https://user-images.githubusercontent.com/69141571/107942863-83158280-6f94-11eb-8596-f5456081126e.mp4

**Comment by watchtower314** [comment]
Note: this is a screenshot of the device browser after I entered that url from the membership request, so the error seems to be an android thing, and not necessarily something with our app.
<img width="350" alt="Screen Shot 2021-03-07 at 7 51 09" src="https://user-images.githubusercontent.com/30501647/110240489-20236580-7f1a-11eb-96cb-c1abd698877c.png">

**Comment by IvanSantiagoUk** [comment]
Can you please confirm this still a Bug I just tested and everything fine on my end


https://user-images.githubusercontent.com/20967640/112323513-23f10f00-8cb2-11eb-9896-e89b124cbb8b.mov

**Comment by kazaryan-t** [comment]
Tested on Staging Android version 1.9.5 (4978-211)

When the link http://www.talyaron.com is pasted in the link field, it still displays an error message on the screen - see attached video.

https://user-images.githubusercontent.com/68247034/113030614-793b8d80-9196-11eb-8741-c8b945e4cadc.mp4

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-262)
Tested on Staging Android version 1.9.5 (4978-223)

@IvanSantiagoUk @MeyerPV this issue still not fixed

**Comment by kazaryan-t** [comment]
Tested on Staging Android version 1.9.5 (4978-224)

When the link http://www.talyaron.com is pasted in the **link field**, it still displays an error message on the screen - see attached video. 

But if the link is pasted in the Description, Message or About fields it opens and works fine.


https://user-images.githubusercontent.com/68247034/114007993-7f063280-986a-11eb-9d36-51426f41458f.mp4


https://user-images.githubusercontent.com/68247034/114007999-80375f80-986a-11eb-9927-a165ab44082c.mp4

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.6 (6433)
Tested on Staging Android version 1.9.6 (6433-230)

Found ok!
Link opens on iOS and Android, from link fields and other text fields like Description, Message, or About.

**Comment by yanivi71** [comment]
Tested on Production

Found OK
