### ISSUE TITLE
iOS - user cannot login

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#827]
Steps to reproduce:
1. Install and open the app
2. perform login with apple/google user

Actual results:
user gets loading image see attached image, and stays on this screen .
![File (72)](https://user-images.githubusercontent.com/69141571/138591007-726060d9-4797-4f03-828b-e6f60ab70877.jpg)

Expected results:
User is logged in to the app

**Comment by watchtower314** [comment]
@yanivi71 this was fixed with the release of this morning, no?

**Comment by yanivi71** [comment]
Yes 
This issue if fixed
