### ISSUE TITLE
Some UI elements don't fit on screen.

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#829]
Tested on staging version.
Device iPhone 7: resolution - 750x1334 pixels.

Buttons and text in some cases do not fit the screen.

![IMG_0311](https://user-images.githubusercontent.com/68247034/138660686-1d2b7667-305a-4bec-b9cc-92c159ada52e.PNG)
![IMG_0312](https://user-images.githubusercontent.com/68247034/138660689-d6e05161-b883-440b-ad92-cb9516c1f7ed.PNG)
![IMG_0313](https://user-images.githubusercontent.com/68247034/138660691-d2917be0-c8fa-4cb3-9b9e-a9b7b7462b65.PNG)
![IMG_0315](https://user-images.githubusercontent.com/68247034/138660693-07b73bcc-a245-414e-aa58-6b60c63c5bab.PNG)
![IMG_0318](https://user-images.githubusercontent.com/68247034/138660696-c199101f-f4de-4143-b5ab-6a5aa0845296.PNG)
![IMG_0320](https://user-images.githubusercontent.com/68247034/138668967-484d789f-1385-48e9-a352-4297cc27c70d.PNG)

**Comment by watchtower314** [comment]
@kazaryan-t  I'm using iPhone 7 and it seems fine, is this maybe related to larger text size, or zoomed displayed that was changed in the phone setting?

![IMG_D9C84106C77C-1](https://user-images.githubusercontent.com/30501647/138724240-438ea26e-e34d-4938-a649-17f507482161.jpeg)

https://user-images.githubusercontent.com/30501647/138724328-c7fe9211-9fdb-48df-832e-ee47475ca021.mov

**Comment by kazaryan-t** [comment]
It seems to be nice, you are right!
Checked.
