### ISSUE TITLE
Add permissions to users

### ISSUE THREAD

**Issue by lpetkov-sw** [daostack/common-backend#83]
https://daostack1.atlassian.net/browse/CM-1513

Currently, founders can edit their Commons. We want to extend this to other users as well, so we add a simple sort of permission system. 

What we can do is add to the user doc a `permissions` property, that is a list of objects of the form

```
IRole: 'founder'| 'moderator' | 'otherrolestobedefinedlater'

IPermission: {  role: IRole,  data?: {   commonId?: string  }

IPermissionList = IPermission[]

IUser: {
 ...
  roles?: IPermissionList

}
```

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-216)
Tested on Staging Android version 1.9.5 (4978-177)

Found OK
role was added to the user when he created a new common
![image (15)](https://user-images.githubusercontent.com/69141571/108095149-3c08b980-7088-11eb-9780-398d9f531b7e.png)
