### ISSUE TITLE
Error when adding rules to commons without rules

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#835]
Tested on iOS.
Staging version - 1.10.0 (4) 

If common was created without rules (or rules were deleted by a moderator) and then the moderator clicks on Edit rules, the error appears.

https://user-images.githubusercontent.com/68247034/139214826-fea02511-e329-425c-8b69-80099144cdd2.MP4

![IMG_0324](https://user-images.githubusercontent.com/68247034/139214817-1f7421a2-7c03-49e8-8d35-1390fce92d53.PNG)

**Comment by watchtower314** [comment]
Fix in: https://github.com/daostack/common/pull/1142

https://user-images.githubusercontent.com/30501647/141677745-a77044c8-92ad-436a-8ff6-aa4e792a6f8d.mov

**Comment by kazaryan-t** [comment]
Checked
