### ISSUE TITLE
Incorrect behavior of Proposal chat

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#839]
Tested on iOS.
Staging version - 1.10.0 (4)

1. Weird behavior of proposal chat when trying to scroll to the proposal general info. 

https://user-images.githubusercontent.com/68247034/139446269-acfbb103-c5fa-46fd-9b97-e7ac899ecc1c.MP4

2. Fix the background of the proposal chat. There is a section at the top of the page that is not painted in the background color.

![IMG_0335](https://user-images.githubusercontent.com/68247034/139446502-edb8504e-1913-4c5b-8d33-0b262c72160a.PNG)

**Comment by watchtower314** [comment]
Fix: https://github.com/daostack/common/pull/1143

https://user-images.githubusercontent.com/30501647/141679849-9253b312-d0da-46a2-84a2-9afedbd4d1b8.mov

**Comment by kazaryan-t** [comment]
Tested on iOS Staging version - 1.10.1 (5)
Tested on Android Staging version - 1.0 (291)

**1. On iOS the same weird behavior, on Android it looks better.**

**iOS:**

https://user-images.githubusercontent.com/68247034/143561433-3d89550f-1bb9-4706-b4bc-01c543f02221.MP4


**Android:**

https://user-images.githubusercontent.com/68247034/143561274-b47e6b6c-7414-4ea7-95cc-61bdf15467af.mp4


**2. Fix the background of the proposal chat. There is a section at the top of the page that is not painted in the background color.**

![IMG_0342](https://user-images.githubusercontent.com/68247034/143560464-29feb0be-94d4-46a7-9dd4-070116aab7af.PNG)
![Screenshot_20211126-122359_common-stg](https://user-images.githubusercontent.com/68247034/143560471-84981370-42a3-4ed6-8bbb-fa2a606757bd.jpg)

**3. On Android fix the Common name at the top of the page, it should be in the center.**

![Screenshot_20211126-122359_common-stg](https://user-images.githubusercontent.com/68247034/143560675-b4a0a66f-af50-48e2-acef-cc661cfd473c.jpg)
