### ISSUE TITLE
Proposals - How hidden proposals is shown to users

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#841]
Please show hidden proposals to users in the following way:

- https://zpl.io/25XXYJJ
<img width="250" src="https://user-images.githubusercontent.com/87295860/139638656-64efee88-0234-4912-a096-369262f19f05.jpg">

- After clicking on the hidden proposal user will see the following (when the user chooses option that **not required** to add note)  
https://zpl.io/bAee97q 
<img width="250" src="https://user-images.githubusercontent.com/87295860/139638926-6498c400-9905-4ce3-8560-115ddcd60891.png">

- After clicking on the hidden proposal user will see the following (when the user chooses option that **required** to add note) 
https://zpl.io/2jAAE5Q
<img width="250" src="https://user-images.githubusercontent.com/87295860/139639196-dd4360d6-755d-4599-9908-3e3cb7e8044f.png">

**Comment by watchtower314** [comment]
Make `reported` visible  available to all app app users, not just moderators
