### ISSUE TITLE
Proposals - Report proposals for hiding

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#842]
When user want to report proposal they follow the next steps:

- after clicking on the **...** (three drops in the right bottom corner) user open proposals' options
https://zpl.io/VQllLv9
<img width="250" src="https://user-images.githubusercontent.com/87295860/139640855-6923c02f-f9cf-4a2f-8d1e-2480a8834ad3.jpg">

- then click **report** option
https://zpl.io/VQllLv9
<img width="250" src="https://user-images.githubusercontent.com/87295860/139642163-2e35c7d2-15af-4cd6-be31-fb9bd56401f9.jpg">

- after clicking **report** button user will see the next menu:
https://zpl.io/adllDz1
<img width="250" src="https://user-images.githubusercontent.com/87295860/139657590-e612dc56-7732-4699-bcdc-82e4bb2a0b0a.png">

- users can choose one of the options:
https://zpl.io/2pppmvM
<img width="250" src="https://user-images.githubusercontent.com/87295860/139660261-b02f3eb4-cc99-48ad-93c2-9e36dc31686c.png">

**!!!** Only after choosing one of the option button 'Hide' will become highlighted and proposal will be hidden
<img width="250" src="https://user-images.githubusercontent.com/87295860/139660739-38c20339-b2f2-40d2-b31b-da8f7ddb871c.jpg">

- after clicking 'Hide' please show next:
https://zpl.io/VDXXvAW
<img width="250" src="https://user-images.githubusercontent.com/87295860/139661262-38f35c1f-2116-4a57-812d-57db761e8893.png">

- **in the case** , when user chose 'Something Else' option => they need to add note of reporting (**It's required for this option**).
https://zpl.io/aglloQN
<img width="250" src="https://user-images.githubusercontent.com/87295860/139662810-9139a228-11ab-4d5f-bee0-44779618a6a8.jpg">

- after adding note user can click 'Hide' (as it's highlighted after entering text) and hide proposal:
https://zpl.io/2GXX4G9
<img width="250" src="https://user-images.githubusercontent.com/87295860/139663225-47d12199-6a42-4bc1-8683-628a8e150168.jpg">

- after clicking 'Hide' please show next:
https://zpl.io/VDXXvAW
<img width="250" src="https://user-images.githubusercontent.com/87295860/139661262-38f35c1f-2116-4a57-812d-57db761e8893.png">

**Comment by watchtower314** [comment]
Make report available to all app users (not just common members)
