### ISSUE TITLE
Discussion - How Hidden Discussion is shown to users

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#845]
- User will see the Hidden Discussion in the application in the following way:
https://zpl.io/2ppz13l
<img width="250" src="https://user-images.githubusercontent.com/87295860/139819296-5f489221-47d4-4ca6-b593-e9f39a2deb2c.jpg">

- After clicking on the Hidden Discussion user see the following details about hiding the Discussion (when the user chooses option that **not required** to add note):
https://zpl.io/25QRKL3
<img width="250" src="https://user-images.githubusercontent.com/87295860/139821461-586ce4b9-4218-49c4-947a-f51060a81e90.png">

- After clicking on the Hidden Discussion user see the following details about hiding the Discussion (when the user chooses option that **required** to add note):
https://zpl.io/bL6zRyd
 <img width="250" src="https://user-images.githubusercontent.com/87295860/139821619-6a36278c-2caf-4ed5-9afe-e005b968060a.png">

**Comment by watchtower314** [comment]
Make hidden discussions visible to all app users (not just common members)
