### ISSUE TITLE
App crashes when creating commons

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#857]
Tested on Android version 11
Device - Samsung s10e
App version - Common-stg v1.0 (280)

When creating a common user returns from Final touches and review screen to the General info screen and adds a link, the app crashes.

Steps to reproduce:
1. Create a common
2. Go to the Final touches and review screen
3. Click the back button until the General info screen
4. Add a link and go to the Final touches and review screen

https://user-images.githubusercontent.com/68247034/140334354-5f36a7c9-6987-4137-881a-1c80c1603563.mp4

**Comment by watchtower314** [comment]
Fix in here -> https://github.com/daostack/common/pull/1146


Demo
https://user-images.githubusercontent.com/30501647/142428483-d2e320ec-037c-41b4-924b-f72825b39452.mov

**Comment by kazaryan-t** [comment]
Checked.
