### ISSUE TITLE
Notifications fixes 

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#858]
**1. Change the notification name from "Proposal Accepted" to "Proposal Approved".**
Design:
![14 01 04 Notification Screen - all read - Common MSD](https://user-images.githubusercontent.com/68247034/140529989-5f83f238-703e-4161-853a-3ae1631a9bfe.png)
Current:
![IMG_0336 PNG ‎- Фотографии 2021-11-05 17 53 48](https://user-images.githubusercontent.com/68247034/140529990-d3b1c1bf-2319-4b83-aeec-99b10e6be41b.png)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.8 (11-308)
Tested on Staging Android version v1.0 (392)
found ok
"Proposal approved" appears when proposal is accepted
