### ISSUE TITLE
Implement change vote - API endpoints 

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#866]
Add an endpoint on the backend to change a vote

**Comment by noamso1** [comment]
Do you want to "flip" the vote? or just "discard" the vote?
(discard is better because maybe you don't want to vote at all...)
currently i'm doing "discard" - remove the vote and recalculate proposal state.

**Comment by HannaMaklakova** [comment]
Here we need to have an opportunity to change our chose then discard and change another variant or don't vote at all
