### ISSUE TITLE
My profile - Change currency

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#881]
- Change currency to shekels on the the my profile page while scrolling and showing Commons and proposals of the user
https://zpl.io/aBxdjzp
<img width="250" src="https://user-images.githubusercontent.com/87295860/144050764-ba49a5ec-e6b2-4bbe-adb4-619cbcdd77a5.jpeg">

- Change currency to shekels on the page that shows user’s proposal on the page ‘My proposals’:
https://zpl.io/VYv1Wqe
<img width="250" src="https://user-images.githubusercontent.com/87295860/144051329-c174cdaf-675f-4978-a5fe-a11f9cb86616.jpeg">

- Change currency to shekels on the page that shows ‘My Commons’
https://zpl.io/brBq6nr
<img width="250" src="https://user-images.githubusercontent.com/87295860/144055859-385ca208-fd4b-4473-a324-22774e4143e0.jpeg">

- Change currency to shekels on the page that shows ‘membership requests’ (pending, approved):
https://zpl.io/bzg94yA https://zpl.io/2GKBR3d
<img width="250" src="https://user-images.githubusercontent.com/87295860/144056775-46b6cbf4-f45c-4e6e-b0b0-915b000ea708.jpeg"> <img width="250" src="https://user-images.githubusercontent.com/87295860/144057386-ba7d7561-97a8-4455-9d3d-da28d1bd5eb9.jpeg">

- Change currency to shekels on the page that shows ‘membership requests’ (rejected):
https://zpl.io/25Rdol8
<img width="250" src="https://user-images.githubusercontent.com/87295860/144057880-62b0a3bb-b1dc-453c-a9e4-0c8114a58941.jpeg">

**Comment by watchtower314** [comment]
@HannaMaklakova  The visual changes can be done in a few hours, but the conversion rate needs to be addressed also (we need to decide the rate we want to use)
