### ISSUE TITLE
Change contribution page - Change the currency

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#886]
- change the currency to shekels on the Change contribution page:
https://zpl.io/VYqRBed https://zpl.io/2y3ymrp
<img width="250" src="https://user-images.githubusercontent.com/87295860/144231204-613af1ce-d159-4437-ba70-eb37c4ced0e1.jpeg"> <img width="250" src="https://user-images.githubusercontent.com/87295860/144231525-160cf61d-bb1f-4376-8a00-609cea4310f9.jpeg">

**Comment by IlyaDylko** [comment]
Done here https://github.com/daostack/common/pull/1156
