### ISSUE TITLE
User profile - Change currency

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#889]
- Change currency to shekels on the Member profile popup:
https://zpl.io/V4m9PyQ
<img width="250" src="https://user-images.githubusercontent.com/87295860/144790950-d4d68094-4787-4385-b78a-640e51d8961b.jpeg">

- Change currency to shekels on the User profile page:
https://zpl.io/agYO9K0
<img width="250" src="https://user-images.githubusercontent.com/87295860/144791266-6314a34a-6369-467a-8793-35b5631ab443.jpeg">

- Change currency to shekels on the Other user profile (unverified):
https://zpl.io/2jKgLlm
<img width="250" src="https://user-images.githubusercontent.com/87295860/144791604-a42c55b0-328a-4b8a-a67e-54d81edebef1.jpeg">

**Comment by IlyaDylko** [comment]
Done by Moore in https://github.com/daostack/common/pull/1156
