### ISSUE TITLE
Notifications - Change currency

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#890]
- Change currency on the Commons page where all notifications were read:
https://zpl.io/agR6ylA
<img width="250" src="https://user-images.githubusercontent.com/87295860/144791972-6391cc72-46f7-4a5f-af90-160bb4e1f8cd.jpeg">

- Change currency to shekels on the Commons page where user has norifications:
https://zpl.io/bP6d74p
<img width="250" src="https://user-images.githubusercontent.com/87295860/144792283-bfb39787-919c-49ca-8d51-568a29079db6.jpeg">

**Comment by IlyaDylko** [comment]
Done https://github.com/daostack/common/pull/1156
