### ISSUE TITLE
Create common - Change currency

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#891]
- Change currency on the Funding page while creating Common (One-time contribution type):
https://zpl.io/VxzyAqm
<img width="250" src="https://user-images.githubusercontent.com/87295860/144792694-338f8715-7edb-4883-b8c1-c9764e62f2c2.jpeg">

- Change currency on the Funding page while creating Common (without personal contribution):
https://zpl.io/2p8d45Q
<img width="250" src="https://user-images.githubusercontent.com/87295860/144793052-5d69395c-e1d6-42dd-8623-80e1dccb1e11.jpeg">

- Change currency to shekels on the Funding page while creating Common (error):
https://zpl.io/bPKg8eA
<img width="250" src="https://user-images.githubusercontent.com/87295860/144793364-7a705f1e-4e71-4ade-9ab2-069f367469c8.jpeg">

- Change currency to shekels on the Funding page (Monthly contribution):
https://zpl.io/bAMOB96
<img width="250" src="https://user-images.githubusercontent.com/87295860/144793604-73cf4c12-db79-4380-9fd9-900d63cdf01e.jpeg">

**Comment by kazaryan-t** [comment]
Checked
