### ISSUE TITLE
Create Common - Change currency [2]

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#892]
- Change currency on the stylize and review common page:
https://zpl.io/a7AvZG8
<img width="250" src="https://user-images.githubusercontent.com/87295860/144794198-6ac59a83-bcac-472e-9071-3526a51967b5.jpeg">

- Change currency on the stylize and review common page with logo:
https://zpl.io/aMAj4LJ
<img width="250" src="https://user-images.githubusercontent.com/87295860/144796191-b1de333a-f9ef-4bcc-975d-15f35df5c31b.jpeg">

- Change currency to shekels on the stylize and review common page with logo with message of making changes:
https://zpl.io/awEGj5J
<img width="250" src="https://user-images.githubusercontent.com/87295860/144796743-793021c9-376c-4bcc-a826-09f5726d98c2.jpeg">

- Change currency to shekels on the Create Common page (Common without tagline):
https://zpl.io/V4wAXOQ
<img width="250" src="https://user-images.githubusercontent.com/87295860/144797150-3b1d0435-06d2-458f-9003-ae2be0adc263.jpeg">

- Change currency to shekels on the Create Common page with min contribution:
https://zpl.io/V1EWgBm
<img width="250" src="https://user-images.githubusercontent.com/87295860/144797478-55dd733d-1fe5-4c68-a46d-b70bffe42b93.jpeg">

**Comment by kazaryan-t** [comment]
on iOS remove extra ISL currency on the Final touches and review screen.
Design - https://zpl.io/aMAj4LJ

![IMG_0366](https://user-images.githubusercontent.com/68247034/148767813-7912e2f5-065b-4816-91d0-e563b1005036.PNG)
![IMG_0367](https://user-images.githubusercontent.com/68247034/148767815-aedb0ede-c3c0-494d-a049-82df67590aab.PNG)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.5 (8-300)
Tested on Staging Android version v1.0 (358)
currency is changed
