### ISSUE TITLE
Create Common - Personal Contribution

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#893]
- Change currency to shekels on the Personal Contribution page (One-time contribution):
https://zpl.io/VxAw4vm
<img width="250" src="https://user-images.githubusercontent.com/87295860/144798425-9ffa8c28-3585-4b30-a54c-2eb738e2aa8c.jpeg">

- Change currency to shekels on the Personal Contribution page (Monthly contribution):
<img width="250" src="https://zpl.io/b653jQR
https://user-images.githubusercontent.com/87295860/144798649-d7359b9e-0c90-41f5-a8a6-f3539e4e1661.jpeg">

- Change currency to shekels on the Billing monthly details:
https://zpl.io/2jyv4rq
<img width="250" src="https://user-images.githubusercontent.com/87295860/144798933-35ded110-f9ed-4f06-a4dc-d4d8d4b6fe5c.jpeg">

- Change currency to shekels on the Payment details page (Monthly):
https://zpl.io/bAKZq6e
<img width="250" src="https://user-images.githubusercontent.com/87295860/144800333-e2105dd0-d646-4baf-9539-07d5dbad755e.jpeg ">

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.3(6-295)
Tested on Staging Android version v1.0 (324)
Found OK
currency was change to ILS
