### ISSUE TITLE
Personal Contribution - Payment Method - Change currency

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#894]
Change currency to shekels for the next pages in the Personal Contribution area with Payment Method:

- One-time contribution https://zpl.io/aRwWYDe
<img width="250" src="https://user-images.githubusercontent.com/87295860/144801496-eea3010a-5c29-4262-9065-70acd29b8e4b.jpeg">

- One-time contribution payment method
https://zpl.io/VqQlBRN
<img width="250" src="https://user-images.githubusercontent.com/87295860/144804328-4f6d7ecf-6f0d-4394-ac34-836ee61a60ac.jpeg">

- Monthly contribution
https://zpl.io/2Z3jJ4X
<img width="250" src="https://user-images.githubusercontent.com/87295860/144801795-211eea22-e6f8-4f65-8437-047a5f8ff274.jpeg">

- monthly contribution payment method
https://zpl.io/VOymP8l
<img width="250" src="https://user-images.githubusercontent.com/87295860/144804596-d72b9152-6bf9-46e4-ad8a-a297b2cc1929.jpeg">

**Comment by IlyaDylko** [comment]
These are new screens, they are not yet in the application.

**Comment by HannaMaklakova** [comment]
not relevant for now
