### ISSUE TITLE
Common page (Member view) - Change currency

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#896]
Change currency to shekels for the following pages:

- Common page (Member view, funding stage) - discussions: https://zpl.io/adeNP6K
- Common page (Member view, operating stage) - proposals:
https://zpl.io/V4mzvgy
- Common page - Moderator view: https://zpl.io/a3mAKYN
- Common page - regular user menu: https://zpl.io/29myZwA
- Commons page - Common was deleted: https://zpl.io/bzQ61dG

**Comment by IlyaDylko** [comment]
Done https://github.com/daostack/common/pull/1156
