### ISSUE TITLE
Common page - Proposals tab - Change currency

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#899]
Change currency to shekels for the following pages:

- Common page - Empty proposals - safety period: https://zpl.io/Vkq3g08
- Common page - after clicking on the message about safety period: https://zpl.io/a8gBXME
- Common page - Empty proposals - after safety period: https://zpl.io/awR9z0d
- Common page - Empty proposals - NON member - funding stage: https://zpl.io/VOQ9lLY

**Comment by kazaryan-t** [comment]
Checked
