### ISSUE TITLE
Hide Proposal - Moderator view

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#901]
Change currency to shekels for the following pages:
- Hide proposal - Moderator view: https://zpl.io/2pw0L0r
- Hide proposal - Moderator view - after copy link: https://zpl.io/bzQ614X

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.5 (8-300)
Tested on Staging Android version v1.0 (358)
Currency is changed
