### ISSUE TITLE
Common Finance - Change Currency

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#908]
Change currency to shekels for the following pages:

- Finance page what were paid: https://zpl.io/ag3NGOR
- Finance page what was paid in April: https://zpl.io/VQNEWdP
- Finance page what were raised: https://zpl.io/2GjOzRj
- Finance page - raised scrolled page: https://zpl.io/ad3kMqE
- Finance page - what were raised in April - monthly charge: https://zpl.io/254rgoj
- Finance page - what were raised in April - one-time charge: https://zpl.io/2j3wl7q
- Finance page - April raised scrolled page: https://zpl.io/2p3Bo7N

**Comment by watchtower314** [comment]
@HannaMaklakova we don't have that screen yet

**Comment by HannaMaklakova** [comment]
not relevant for now
