### ISSUE TITLE
Funding page - Change functionality for Monthly contribution

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#911]
re #891 
Change functionality of the checkbox https://zpl.io/2p8d45Q
When user is choosing 'Let user join the Common without a personal contribution' for the One-time contribution type we will allow to choose sum in the field for Monthly contribution:
https://zpl.io/2p8d45Q  https://zpl.io/bAMOB96
<img width="250" src="https://user-images.githubusercontent.com/87295860/144993635-cc25b4fb-be56-44bf-8191-636b74b686ee.jpg"> <img width="250" src="https://user-images.githubusercontent.com/87295860/144994217-528145fd-44bb-4993-96a3-912ffcbe32aa.jpg">

**Comment by kazaryan-t** [comment]
Checked.
