### ISSUE TITLE
Hidden Membership request - Change currency

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#922]
Change currency to shekels for the following pages:

- hidden membership request - regular user view-hidden: https://zpl.io/a7XXqlR
- hidden membership request - moderator view-hidden: https://zpl.io/VDXX5oJ

**Comment by MeyerPV** [comment]
I think it was done in https://github.com/daostack/common-monorepo/issues/903

**Comment by HannaMaklakova** [comment]
> I think it was done in #903

not really. these are with the hidden content

**Comment by watchtower314** [comment]
@HannaMaklakova @MeyerPV 
Pavel is right, it is done, there's no difference with or without hidden content
