### ISSUE TITLE
Funding proposal - Add bank account - Add functionality

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#923]
re #914 
Create proposal and bank account:
- Add to the account page of registered user (empty page) 'Receive funds' link: https://zpl.io/beqO1oY
- Add to the account page of registered user 'Receive funds' link: https://zpl.io/awRgnzd
- Add to the account page of registered user (scrolled proposal) 'Receive funds' link: https://zpl.io/a7AvKPW
- After clicking 'Receive funds' please show the next page: https://zpl.io/awlGG9j
- After added bank information: https://zpl.io/bzzppvl
- After clicking 'edit details': https://zpl.io/agE77yD
- Add detail about 'Bank Name': https://zpl.io/bex7qNm (**bank nane** in the screen. will ask to fix)

**Comment by HannaMaklakova** [comment]
@IlyaDylko  task will be updated as soon as I have info

**Comment by IlyaDylko** [comment]
Task is same as https://github.com/daostack/common-monorepo/issues/938. I've done some screens and modal which were reused in 938 and finished.

**Comment by yanivi71** [comment]
@IlyaDylko @watchtower314 @HannaMaklakova this issue is not ready. 
Receive funds does not display in user profile page

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.6 (9-306)
Tested on Staging Android version v1.0 (389)
found ok
Receive funds display in user profile page
