### ISSUE TITLE
Remove Circle logo

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#924]
please remove Circle logo from the following pages:

- https://zpl.io/2jy80Lq
- https://zpl.io/bAKZq6e
- https://zpl.io/VqQlBRN
- https://zpl.io/VOymP8l
- https://zpl.io/am34nM6
- https://zpl.io/2EQeAgD

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.5 (8-300)
Tested on Staging Android version v1.0 (358)
circle logo removed
