### ISSUE TITLE
Common profile - Non Member - Add pending balance

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#925]
Add pending balance (money in process) for the Common profile page for the Non-Member:
https://zpl.io/2pqmd3J
<img width="250" src="https://user-images.githubusercontent.com/87295860/145173805-99d5b579-94a5-4a6d-9310-06fded589518.jpeg">

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.6 (9-306)
Tested on Staging Android version v1.0 (389)
in process amount is added
