### ISSUE TITLE
Invoice submission - Add pages for Trustees Invoices

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#929]
After clicking the link in the email (user should be received the email after payment process done) user will see the next pages with functionality of adding invoice:

- Page where user can choose ‘add invoice’: https://zpl.io/VQzWPgm
- After choosing ‘add invoice’ there are three options to add it: https://zpl.io/2GMzDeE
- During uploading invoice: https://zpl.io/VD8DjYO
- Popup notified - uploaded successfully: https://zpl.io/VD8DjYO
- User upload the file or do another option and see their file on the page with possibilities to add more invoices or finish (done) with uploading: https://zpl.io/29957Yy
- In the case user need to look at the invoice - view the file and add invoice amount: https://zpl.io/ag7Gx7Z
- For choosing ‘add invoice amount’: https://zpl.io/VxjBA5R
- When user tap delete please show the pop-up: https://zpl.io/bAPGgP8
- Popup verified - filled mount: https://zpl.io/255gP3e
- All info filled: https://zpl.io/2pWo8Zo
- All invoices uploaded - full page: https://zpl.io/2jOlNBp (already without dates)

**Comment by watchtower314** [comment]
@IvanSantiagoUk there is no need for the date on top of the invoice screenshot
