### ISSUE TITLE
Common - proposal - Create proposal - Error message appears when user insert a valid amount

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#93]
Tested on Staging iOS version 1.9.5 (4978-216)
Tested on Staging Android version 1.9.5 (4978-177)

Steps to reproduce:
1. Create a new proposal
2. In funding amount insert non integer number e.g. 0.5
3. Fill all the required field and click on create proposal

Actual results:
Error message appear "The amount must be at least $0 and at most $3000

Expected results:
No error should be display Since it is a valid number

![Screenshot_20210216-174548_common (1)](https://user-images.githubusercontent.com/69141571/108200642-678eb100-7127-11eb-8526-1ae76969718e.jpg)

**Comment by kazaryan-t** [comment]
Tested on Staging Android version 1.9.5 (4978-225)

On Android when typing a non-integral number, the second dot appears automatically. 

https://user-images.githubusercontent.com/68247034/114017895-4586f480-9875-11eb-9ea3-9b62dab8081b.mp4

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-266)
Tested on Staging Android version 1.9.5 (4978-227)

Found OK!
Users are able to create proposals with a non-integral number of the funding amount.

**Comment by kazaryan-t** [comment]
Verified on Production.
