### ISSUE TITLE
Funding proposal - create funding proposal - add bank account

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#938]
For creating proposal and add bank account use next: 

- After clicking 'create proposal' - https://zpl.io/29388xB
- When user doesn't fill in the info - highlighted button 'add bank account': https://zpl.io/bo7yyqo
- Add Bank Account popup: https://zpl.io/aN3AAg4
- Add Bank Account popup with selected 'Add Photo ID' button: https://zpl.io/2vXzzJn
- After choosing 'Add Photo ID' button with option of adding: https://zpl.io/V4X44mJ
- Reviewing ID photo: https://zpl.io/2E3ZZNy
- popup with uploaded files (photo ID and letter): https://zpl.io/VxWggzm

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.5 (8-300)
Tested on Staging Android version v1.0 (358)
add bank account created with the correct design
