### ISSUE TITLE
Show loading animation on opening app for first time and on notification click

### ISSUE THREAD

**Issue by lpetkov-sw** [daostack/common-backend#94]
We need to show a loader screen when the app is already opened but we are not ready to show the data. Also it should be shown when the app is opened from a notification.

The loader should have the following behaviour:
- The loader should not be dismissible.
- After 100 seconds we should show a dismissible error message (use the usual error message format): **Oops...** We couldn't load the app. [ Reload].
Clicking on the button should reload the app.

Here is the design for the loader. https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/60104e13fb74240f58acc7aa/

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-227)
Tested on Staging Android version 1.9.5 (4978-188)

1. The loading animation does not appear when opening the notifications screen.

https://user-images.githubusercontent.com/68247034/109638738-6c0f8c80-7b5f-11eb-89f8-33ff8148993c.mp4

2. On iOS (checked on iPhone 7) the loading animation does not correspond to the design - https://zpl.io/ad6AmN1.

https://user-images.githubusercontent.com/68247034/109638945-a711c000-7b5f-11eb-9c3f-30d5ab8a044f.MOV

**Comment by yanivi71** [comment]
@lpetkov-sw this one is already deployed to production
