### ISSUE TITLE
Common - user profile - monthly contribution - Cancel monthly contribution does not execute

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#95]
Tested on Staging iOS version 1.9.5 (4978-216)
Tested on Staging Android version 1.9.5 (4978-177)

Steps to reproduce:
1. Go to user profile
2. Click on monthly contribution
3. Choose a subscription that is on going
4. Cancel the subscription

Actual results:
Subscription is canceled but user is still a member in the common - See attached stuff
E.g. Common "Miluiim"
These are the card id's
627a517e-4b23-487b-aef2-79ea3385e987
e8a2c186-b1b2-44dd-b36d-2af457125347
25533db6-4fd5-4606-b477-90e885f1a7e5

Expected results:
Subscription must be canceled and user is no longer a member in the common

![Screenshot_2021-02-17-15-12-55-808_com daostack common staging](https://user-images.githubusercontent.com/69141571/108211132-05d54380-7135-11eb-94d7-08ce5f493fa6.jpg)
![Screenshot_2021-02-17-15-14-44-921_com daostack common staging](https://user-images.githubusercontent.com/69141571/108211141-079f0700-7135-11eb-8a4e-937933f92218.jpg)
![image](https://user-images.githubusercontent.com/69141571/108211529-71b7ac00-7135-11eb-8b10-befed47ace6e.png)
![image](https://user-images.githubusercontent.com/69141571/108211653-9dd32d00-7135-11eb-996d-b6d5eae05508.png)

**Comment by alexander2001i** [comment]
@yanivi71 do not check before #171 is merged and deployed as well

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-232)
Tested on Staging Android version 1.9.5 (4978-193)

Found OK
Subscription is canceled
