### ISSUE TITLE
Notification - clicking on Back from push notification user navigates to main common list screen

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#97]
Tested on Staging iOS version 1.9.5 (4978-216)
Tested on Staging Android version 1.9.5 (4978-177)

Steps to reproduce:
1. Get push notification
2. Click on the push notification - user redirect to the notification  position screen
3. Click on Back

Actual results:
Clicking on Back from push notification user navigates to main common list screen

Expected results:
user should redirect to the current common

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-246)
Tested on Staging Android version 1.9.5 (4978-207)

Works fine.
Tested with push notifications for:
- Request to join
- A new funding proposal in your Common
- A funding proposal was approved
- New post
- A new comment in a post you created
- A new comment in a post you commented
- Content is reported

**Comment by yanivi71** [comment]
Verified on production
