### ISSUE TITLE
*Invoices uploaded* flow [ Email ]

### ISSUE THREAD

**Issue by SobolevYuri** [daostack/common-backend#987]
event name: **_FUNDING_REQUEST_INVOICES_UPLOADED_**

Send a corresponding email (by its template) to:
- trustee (containing relevant details + link to the interface for verifying an invoices)
- common support

**Comment by ariel-dao** [comment]
no need to send email when wallet is created to anyone, this is inner BE logic
@SobolevYuri I think this task can be closed unless I'm missing something
