### ISSUE TITLE
Cannot upload image to proposal

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#990]

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.3(6-295)
Tested on Staging Android version v1.0 (324)
found ok
user can upload images on proposal

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.4 (7)
@watchtower314 this issue happens again.
when i tried to load image the app crashes

**Comment by kazaryan-t** [comment]
Tested
