### ISSUE TITLE
Request to join - 2 continue buttons appear instead of one

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#999]
Tested on Staging iOS version 1.10.3(6-295)
Tested on Staging Android version v1.0 (324)

Steps to reproduce:
1. Request to join a common
2. fill the values and navigate to credit card detail screen

Actual results:
There are 2 continue  button instead of 1 and it very confusing the user
see attached images
![image](https://user-images.githubusercontent.com/69141571/148691668-be0f8b5e-25d2-4c6b-a94c-372b471889d9.png)
![image](https://user-images.githubusercontent.com/69141571/148691714-14962613-0329-4ee5-bcdf-6759250a0930.png)

Expected results:
Should be only one "Continue button"

**Comment by watchtower314** [comment]
There is no different design for that, so we decided by ourselves

**Comment by watchtower314** [comment]
@yanivi71 the button is disabled before payment was processed, where is the confusion?

<img width="332" alt="Screen Shot 2022-01-10 at 11 39 12" src="https://user-images.githubusercontent.com/30501647/148744904-64fba92a-2ac5-4deb-b8ab-20482fe0ea81.png">

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.4 (7-298)
Tested on Staging Android version v1.0 (330)
Found ok. only one button is presented
